// Liste des joueurs et des questions
const questions = [
    "Cite 3 fruits rouges.",
    "Fais 3 pompes.",
    "Cite 3 capitales européennes.",
    "Donne 3 animaux marins.",
    "Cite 3 marques de voitures.",
    "Cite 3 choses que tu emmènerais sur une île déserte.",
    "Donne 3 instruments de musique.",
    "Fais 3 sauts sur place.",
    "Cite 3 pays d'Afrique.",
    "Nommes 3 couleurs primaires.",
    "Donne 3 films célèbres.",
    "Cite 3 oiseaux qui volent.",
    "Fais 3 grimaces différentes.",
    "Nommes 3 langues parlées en Europe.",
    "Donne 3 légumes verts.",
    "Cite 3 sports de ballon.",
    "Fais 3 pas en arrière.",
    "Nommes 3 planètes du système solaire.",
    "Donne 3 métiers que tu admires.",
    "Cite 3 pays d’Amérique du Sud.",
    "Fais 3 clins d’œil.",
    "Nommes 3 océans.",
    "Donne 3 personnages de contes.",
    "Cite 3 instruments à cordes.",
    "Fais 3 tours sur toi-même.",
    "Nommes 3 fromages français.",
    "Donne 3 marques de vêtements.",
    "Cite 3 fêtes célébrées dans le monde.",
    "Fais 3 étirements simples.",
    "Nommes 3 villes italiennes.",
    "Donne 3 animaux de la ferme.",
    "Cite 3 aliments sucrés.",
    "Fais 3 mouvements de bras.",
    "Nommes 3 types de fleurs.",
    "Donne 3 langues étrangères.",
    "Cite 3 continents.",
    "Fais 3 sauts de grenouille.",
    "Nommes 3 insectes.",
    "Donne 3 jeux de société.",
    "Cite 3 personnages historiques.",
    "Fais 3 respirations profondes.",
    "Nommes 3 moyens de transport.",
    "Donne 3 objets de la cuisine.",
    "Cite 3 métiers artistiques.",
    "Fais 3 pas de danse.",
    "Nommes 3 capitales asiatiques.",
    "Donne 3 boissons froides.",
    "Cite 3 animaux de la savane.",
    "Fais 3 tours sur toi-même en sautant.",
    "Nommes 3 éléments naturels.",
    "Donne 3 objets que tu trouves dans une chambre.",
    "Cite 3 desserts au chocolat.",
    "Fais 3 grimaces rigolotes.",
    "Nommes 3 types de roches.",
    "Donne 3 sports aquatiques.",
    "Cite 3 chansons populaires.",
    "Fais 3 mouvements de tête.",
    "Nommes 3 pays nordiques.",
    "Donne 3 objets du bureau.",
    "Cite 3 films d’animation.",
    "Fais 3 pas chassés.",
    "Nommes 3 rivières célèbres.",
    "Donne 3 types de chapeaux.",
    "Cite 3 animaux nocturnes.",
    "Fais 3 étirements de bras.",
    "Nommes 3 monuments célèbres.",
    "Donne 3 types de nuages.",
    "Cite 3 livres pour enfants.",
    "Fais 3 mouvements de jambes.",
    "Nommes 3 oiseaux marins.",
    "Donne 3 instruments de percussion.",
    "Cite 3 pays d’Asie.",
    "Fais 3 roulades au sol.",
    "Nommes 3 types de poissons.",
    "Donne 3 objets que l’on trouve dans une cuisine.",
    "Cite 3 animaux de la forêt.",
    "Fais 3 mimiques différentes.",
    "Nommes 3 capitales africaines.",
    "Donne 3 moyens de communication.",
    "Cite 3 sports d’hiver.",
    "Fais 3 pas de côté.",
    "Nommes 3 types de fruits exotiques.",
    "Donne 3 objets que l’on trouve dans un sac à dos.",
    "Cite 3 films comiques.",
    "Fais 3 mouvements de bras et jambes en même temps.",
    "Nommes 3 types d’arbres.",
    "Donne 3 marques de téléphones.",
    "Cite 3 animaux du désert.",
    "Fais 3 sauts sur un pied.",
    "Nommes 3 capitales américaines.",
    "Donne 3 types de boissons chaudes.",
    "Cite 3 instruments de musique à vent.",
    "Fais 3 mouvements de tête en rythme.",
    "Nommes 3 types de biscuits.",
    "Donne 3 métiers liés à l’art.",
    "Cite 3 pays d’Océanie.",
    "Fais 3 pas en avant rapidement.",
    "Nommes 3 animaux polaires.",
    "Donne 3 plats typiques français.",
    "Cite 3 personnages de Disney.",
    "Fais 3 mouvements de bras circulaires.",
    "Nommes 3 capitales du Moyen-Orient.",
    "Donne 3 moyens de transport en commun.",
    "Cite 3 sports collectifs.",
    "Fais 3 pas de côté rapides.",
    "Nommes 3 types de pains.",
    "Donne 3 animaux aquatiques.",
    "Cite 3 boissons gazeuses.",
    "Fais 3 grimaces différentes en un instant.",
    "Nommes 3 types de chocolat.",
    "Donne 3 personnages célèbres de livres.",
    "Cite 3 animaux domestiques.",
    "Fais 3 étirements de jambes.",
    "Nommes 3 capitales européennes moins connues.",
    "Donne 3 instruments de musique classiques.",
    "Cite 3 sports de raquette.",
    "Fais 3 tours sur toi-même rapidement.",
    "Nommes 3 types de fromage italien.",
    "Donne 3 aliments à cuisiner au four.",
    "Cite 3 animaux d’Amérique du Nord.",
    "Fais 3 pas chassés en avant.",
    "Nommes 3 monuments historiques en France.",
    "Donne 3 objets de salle de bain.",
    "Cite 3 types de danse.",
    "Fais 3 mouvements de bras croisés.",
    "Nommes 3 animaux sauvages d’Afrique.",
    "Donne 3 films d’aventure.",
    "Cite 3 capitales d’Europe de l’Est.",
    "Fais 3 sauts de grenouille en avant.",
    "Nommes 3 types de fromages à pâte molle.",
    "Donne 3 aliments à base de lait.",
    "Cite 3 personnages de dessins animés.",
    "Fais 3 mouvements d’épaules.",
    "Nommes 3 types de fleurs rouges.",
    "Donne 3 moyens de locomotion.",
    "Cite 3 animaux de la jungle.",
    "Fais 3 pas rapides sur place.",
    "Nommes 3 villes côtières célèbres.",
    "Donne 3 types de boissons alcoolisées.",
    "Cite 3 sports de combat.",
    "Fais 3 roulades avant.",
    "Nommes 3 capitales du monde.",
    "Donne 3 plats typiques asiatiques.",
    "Cite 3 animaux préhistoriques.",
    "Fais 3 mouvements de tête et mains.",
    "Nommes 3 types de nuages en ciel.",
    "Donne 3 objets que l’on trouve dans une école.",
    "Cite 3 chansons pour enfants.",
    "Fais 3 pas de danse improvisés.",
    "Nommes 3 capitales d’Amérique du Sud.",
    "Donne 3 objets pour dessiner.",
    "Cite 3 animaux dangereux.",
    "Fais 3 étirements du dos.",
    "Nommes 3 types de légumes racines.",
    "Donne 3 films d’action.",
    "Cite 3 pays d’Europe de l’Ouest.",
    "Fais 3 mouvements circulaires avec tes bras.",
    "Nommes 3 types de fruits jaunes.",
    "Donne 3 instruments de musique électroniques.",
    "Cite 3 animaux de montagne.",
    "Fais 3 tours sur toi-même lentement.",
    "Nommes 3 types de poissons rouges.",
    "Donne 3 objets de la salle de classe.",
    "Cite 3 sports extrêmes.",
    "Fais 3 pas en arrière rapidement.",
    "Nommes 3 capitales asiatiques peu connues.",
    "Donne 3 aliments à grignoter.",
    "Cite 3 animaux marins rares.",
    "Fais 3 sauts groupés.",
    "Nommes 3 types de pain complet.",
    "Donne 3 types de chocolats.",
    "Cite 3 métiers scientifiques.",
    "Fais 3 mouvements de jambes rapides.",
    "Nommes 3 capitales africaines peu connues.",
    "Donne 3 plats végétariens.",
    "Cite 3 oiseaux de proie.",
    "Fais 3 tours sur toi-même en sautant.",
    "Nommes 3 animaux domestiques exotiques.",
    "Donne 3 instruments de musique traditionnels.",
    "Cite 3 sports de glisse.",
    "Fais 3 étirements du cou.",
    "Nommes 3 capitales d’Océanie.",
    "Donne 3 types de jus de fruits.",
    "Cite 3 animaux de compagnie.",
    "Fais 3 mouvements d’épaules en rythme.",
    "Nommes 3 types de fromages à pâte dure.",
    "Donne 3 films d’horreur célèbres.",
    "Cite 3 fruits exotiques.",
    "Fais 3 pas chassés sur place.",
    "Nommes 3 capitales nordiques.",
    "Donne 3 objets que tu trouves dans un salon.",
    "Cite 3 sports nautiques.",
    "Fais 3 roulades arrière.",
    "Nommes 3 types de légumes verts.",
    "Donne 3 films romantiques.",
    "Cite 3 animaux aquatiques dangereux.",
    "Fais 3 mouvements de bras en cercle.",
    "Nommes 3 capitales d’Europe centrale.",
    "Donne 3 aliments sucrés.",
    "Cite 3 types de fromage français.",
    "Fais 3 sauts de grenouille sur place.",
    "Nommes 3 types de fleurs blanches.",
    "Donne 3 instruments de percussion rares.",
    "Cite 3 animaux de la savane africaine.",
    "Fais 3 pas rapides sur le côté.",
    "Nommes 3 capitales sud-américaines.",
    "Donne 3 plats italiens célèbres.",
    "Cite 3 animaux de compagnie exotiques.",
    "Fais 3 mouvements d’épaules et de bras.",
    "Nommes 3 types de pain français.",
    "Donne 3 films d’animation récents.",
    "Cite 3 sports collectifs d’intérieur.",
    "Fais 3 étirements du torse.",
    "Nommes 3 capitales européennes peu connues.",
    "Donne 3 objets de décoration.",
    "Cite 3 animaux de la forêt tropicale.",
    "Fais 3 pas chassés rapides.",
    "Nommes 3 types de chocolat noir.",
    "Donne 3 boissons énergétiques.",
    "Cite 3 personnages de films célèbres.",
    "Fais 3 mouvements de bras et jambes synchronisés.",
    "Nommes 3 capitales asiatiques célèbres.",
    "Donne 3 aliments pour petit-déjeuner.",
    "Cite 3 animaux nocturnes dangereux.",
    "Fais 3 tours sur toi-même lentement.",
    "Nommes 3 types de fruits rouges.",
    "Donne 3 plats typiques mexicains.",
    "Cite 3 instruments de musique anciens.",
    "Fais 3 sauts sur place et bras levés.",
    "Nommes 3 capitales européennes célèbres.",
    "Donne 3 films dramatiques.",
    "Cite 3 animaux marins géants.",
    "Fais 3 pas en arrière en rythme.",
    "Nommes 3 types de légumes racines colorés.",
    "Donne 3 boissons chaudes populaires.",
    "Cite 3 sports olympiques.",
    "Fais 3 mouvements de hanches.",
    "Nommes 3 capitales africaines célèbres.",
    "Donne 3 plats typiques asiatiques.",
    "Cite 3 animaux domestiques originaux.",
    "Fais 3 pas chassés avec les bras en l’air.",
    "Nommes 3 types de chocolat au lait.",
    "Donne 3 films d’aventure récents.",
    "Cite 3 oiseaux migrateurs.",
    "Fais 3 roulades avant et arrière.",
    "Nommes 3 capitales américaines célèbres.",
    "Donne 3 aliments riches en protéines.",
    "Cite 3 animaux de montagne rares.",
    "Fais 3 mouvements de bras circulaires et lents.",
    "Nommes 3 types de fromage suisse.",
    "Donne 3 plats végétariens populaires.",
    "Cite 3 animaux dangereux de la jungle.",
    "Fais 3 tours sur toi-même rapidement et lentement.",
    "Nommes 3 capitales d’Europe occidentale.",
    "Donne 3 instruments de musique à cordes.",
    "Cite 3 sports extrêmes d’été.",
    "Fais 3 étirements des jambes et bras.",
    "Nommes 3 types de fleurs jaunes.",
    "Donne 3 boissons non alcoolisées.",
    "Cite 3 animaux polaires rares.",
    "Fais 3 pas de danse improvisés sur place.",
    "Nommes 3 capitales asiatiques lointaines.",
    "Donne 3 types de jus de fruits exotiques.",
    "Cite 3 animaux domestiques rares.",
    "Fais 3 mouvements de bras et mains en rythme.",
    "Nommes 3 types de chocolat blanc.",
    "Donne 3 films fantastiques célèbres.",
    "Cite 3 fruits rouges rares.",
    "Fais 3 sauts groupés avec les bras levés.",
    "Nommes 3 capitales européennes anciennes.",
    "Donne 3 plats typiques indiens.",
    "Cite 3 instruments de musique modernes.",
    "Fais 3 pas chassés rapides et lents.",
    "Nommes 3 types de légumes verts foncés.",
    "Donne 3 boissons gazeuses internationales.",
    "Cite 3 animaux marins colorés.",
    "Fais 3 mouvements d’épaules synchronisés.",
    "Nommes 3 capitales nordiques célèbres.",
    "Donne 3 aliments pour dessert.",
    "Cite 3 sports collectifs d’extérieur.",
    "Fais 3 roulades rapides sur le sol.",
    "Nommes 3 types de fleurs bleues.",
    "Donne 3 plats typiques japonais.",
    "Cite 3 animaux nocturnes rares.",
    "Fais 3 tours sur toi-même en sautant.",
    "Nommes 3 capitales sud-américaines célèbres.",
    "Donne 3 instruments de musique électroniques célèbres.",
    "Cite 3 animaux sauvages d’Afrique célèbres.",
    "Fais 3 mouvements de bras et jambes rapides.",
    "Nommes 3 types de pain du monde.",
    "Donne 3 films comiques récents.",
    "Cite 3 oiseaux rares.",
    "Fais 3 pas rapides avec les bras levés.",
    "Nommes 3 capitales européennes lointaines.",
    "Donne 3 types de chocolat rares.",
    "Cite 3 animaux marins rares et exotiques.",
    "Fais 3 étirements rapides des bras et jambes.",
    "Nommes 3 types de fromage hollandais.",
    "Donne 3 plats typiques espagnols.",
    "Cite 3 animaux domestiques exotiques rares.",
    "Fais 3 pas chassés rapides en cercle.",
    "Nommes 3 capitales asiatiques historiques.",
    "Donne 3 boissons alcoolisées internationales.",
    "Cite 3 sports de glisse d’hiver.",
    "Fais 3 roulades avant rapides et lentes.",
    "Nommes 3 types de légumes colorés.",
    "Donne 3 films dramatiques récents.",
    "Cite 3 animaux polaires célèbres.",
    "Fais 3 mouvements circulaires rapides des bras et mains.",
    "Nommes 3 capitales africaines historiques.",
    "Donne 3 plats typiques français célèbres.",
    "Cite 3 instruments de musique anciens célèbres.",
    "Fais 3 tours sur toi-même rapidement.",
    "Nommes 3 types de fleurs exotiques.",
    "Donne 3 boissons chaudes internationales.",
    "Cite 3 animaux dangereux de la savane.",
    "Fais 3 pas chassés avec rythme et style.",
    "Nommes 3 capitales européennes modernes.",
    "Donne 3 films d’animation récents et populaires.",
    "Cite 3 fruits tropicaux.",
    "Fais 3 sauts de grenouille sur place.",
    "Nommes 3 types de pain typiques.",
    "Donne 3 plats végétariens célèbres.",
    "Cite 3 animaux de la jungle exotiques.",
    "Fais 3 mouvements de bras en rythme rapide.",
    "Nommes 3 capitales asiatiques modernes.",
    "Donne 3 instruments de musique classiques célèbres.",
    "Cite 3 sports nautiques dangereux.",
    "Fais 3 étirements des bras et jambes en même temps.",
    "Nommes 3 types de fleurs rares et exotiques.",
    "Donne 3 boissons gazeuses internationales célèbres.",
    "Cite 3 animaux polaires dangereux.",
    "Fais 3 tours sur toi-même lentement avec les bras levés.",
    "Nommes 3 capitales nordiques modernes.",
    "Donne 3 plats typiques italiens célèbres.",
    "Cite 3 instruments de musique électroniques célèbres.",
    "Fais 3 pas chassés rapides et sautillés.",
    "Nommes 3 types de chocolat rares et précieux.",
    "Donne 3 films fantastiques récents et célèbres.",
    "Cite 3 animaux domestiques rares et originaux.",
    "Fais 3 mouvements circulaires rapides des bras et jambes.",
    "Nommes 3 capitales sud-américaines modernes.",
    "Donne 3 plats typiques mexicains célèbres.",
    "Cite 3 oiseaux rares et exotiques.",
    "Fais 3 roulades avant et arrière rapides.",
    "Nommes 3 types de pain internationaux.",
    "Donne 3 boissons chaudes internationales célèbres.",
    "Cite 3 animaux marins géants et rares.",
    "Fais 3 sauts groupés rapides et coordonnés.",
    "Nommes 3 capitales européennes anciennes célèbres.",
    "Donne 3 plats typiques indiens célèbres.",
    "Cite 3 instruments de musique modernes célèbres.",
    "Fais 3 pas chassés rapides et tournants.",
    "Nommes 3 types de légumes verts rares.",
    "Donne 3 boissons gazeuses internationales populaires.",
    "Cite 3 fruits jaunes.",
    "Fais 3 sauts de kangourou.",
    "Cite 3 capitales nord-américaines.",
    "Donne 3 animaux de la forêt.",
    "Cite 3 marques de chaussures.",
    "Cite 3 objets que tu prendrais en vacances.",
    "Donne 3 instruments de musique à vent.",
    "Fais 3 grimaces différentes.",
    "Cite 3 pays d’Océanie.",
    "Nommes 3 couleurs secondaires.",
    "Donne 3 films d’aventure.",
    "Cite 3 oiseaux chanteurs.",
    "Fais 3 mouvements de bras en cercle.",
    "Nommes 3 langues africaines.",
    "Donne 3 légumes rouges.",
    "Cite 3 sports individuels.",
    "Fais 3 pas de côté.",
    "Nommes 3 planètes gazeuses.",
    "Donne 3 métiers liés à la nature.",
    "Cite 3 pays d’Amérique du Nord.",
    "Fais 3 clins d’œil rapides.",
    "Nommes 3 océans de la planète.",
    "Donne 3 personnages de légendes.",
    "Cite 3 instruments de percussion.",
    "Fais 3 tours sur toi-même lentement.",
    "Nommes 3 fromages européens.",
    "Donne 3 marques de vêtements sportives.",
    "Cite 3 fêtes religieuses.",
    "Fais 3 étirements des bras.",
    "Nommes 3 villes allemandes.",
    "Donne 3 animaux de compagnie.",
    "Cite 3 aliments salés.",
    "Fais 3 mouvements de jambes.",
    "Nommes 3 fleurs comestibles.",
    "Donne 3 langues parlées en Afrique.",
    "Cite 3 continents peu connus.",
    "Fais 3 sauts sur un pied.",
    "Nommes 3 insectes de jardin.",
    "Donne 3 jeux de cartes.",
    "Cite 3 personnages mythologiques.",
    "Fais 3 respirations profondes.",
    "Nommes 3 moyens de transport insolites.",
    "Donne 3 objets du salon.",
    "Cite 3 métiers scientifiques.",
    "Fais 3 pas de danse différents.",
    "Nommes 3 capitales d’Europe du Nord.",
    "Donne 3 boissons alcoolisées.",
    "Cite 3 animaux de la mer profonde.",
    "Fais 3 tours sur toi-même avec les bras levés.",
    "Nommes 3 types de pierres précieuses.",
    "Donne 3 objets qu’on trouve dans une chambre.",
    "Cite 3 desserts glacés.",
    "Fais 3 grimaces marrantes.",
    "Nommes 3 types de roches.",
    "Donne 3 sports de glisse.",
    "Cite 3 chansons françaises populaires.",
    "Fais 3 mouvements de tête rapides.",
    "Nommes 3 pays nordiques.",
    "Donne 3 objets d’écriture.",
    "Cite 3 films comiques récents.",
    "Fais 3 pas de côté en rythme.",
    "Nommes 3 rivières européennes.",
    "Donne 3 types de chapeaux.",
    "Cite 3 animaux nocturnes du jardin.",
    "Fais 3 étirements des jambes.",
    "Nommes 3 monuments célèbres dans le monde.",
    "Donne 3 types de nuages.",
    "Cite 3 livres d’aventure.",
    "Fais 3 mouvements de bras.",
    "Nommes 3 oiseaux migrateurs.",
    "Donne 3 instruments de musique rares.",
    "Cite 3 pays asiatiques.",
    "Fais 3 roulades sur le sol.",
    "Nommes 3 types de poissons d’aquarium.",
    "Donne 3 objets qu’on trouve dans une cuisine.",
    "Cite 3 animaux d’Afrique.",
    "Fais 3 mimiques différentes rapidement.",
    "Nommes 3 capitales africaines.",
    "Donne 3 moyens de communication modernes.",
    "Cite 3 sports d’hiver.",
    "Fais 3 pas rapides sur place.",
    "Nommes 3 fruits exotiques rouges.",
    "Donne 3 objets dans un sac d’école.",
    "Cite 3 films d’animation Disney.",
    "Fais 3 mouvements de bras croisés.",
    "Nommes 3 rivières célèbres du monde.",
    "Donne 3 types de pain.",
    "Cite 3 animaux domestiques.",
    "Fais 3 étirements du cou.",
    "Nommes 3 capitales européennes peu connues.",
    "Donne 3 instruments de musique à cordes.",
    "Cite 3 sports de raquette.",
    "Fais 3 tours sur toi-même.",
    "Nommes 3 fromages à pâte molle.",
    "Donne 3 aliments cuisinés au four.",
    "Cite 3 animaux d’Amérique du Sud.",
    "Fais 3 pas chassés.",
    "Nommes 3 monuments historiques français.",
    "Donne 3 objets de salle de bain.",
    "Cite 3 types de danse.",
    "Fais 3 mouvements de bras circulaires.",
    "Nommes 3 animaux sauvages d’Amérique.",
    "Donne 3 films d’aventure récents.",
    "Cite 3 capitales européennes de l’Est.",
    "Fais 3 sauts en avant.",
    "Nommes 3 fromages à pâte dure.",
    "Donne 3 plats végétariens.",
    "Cite 3 personnages de dessins animés célèbres.",
    "Fais 3 mouvements d’épaules.",
    "Nommes 3 fleurs rouges.",
    "Donne 3 moyens de transport différents.",
    "Cite 3 animaux de la jungle.",
    "Fais 3 pas rapides sur place.",
    "Nommes 3 villes portuaires.",
    "Donne 3 boissons fraîches.",
    "Cite 3 sports de combat.",
    "Fais 3 roulades avant.",
    "Nommes 3 capitales mondiales.",
    "Donne 3 plats typiques japonais.",
    "Cite 3 animaux préhistoriques.",
    "Fais 3 mouvements de bras et mains.",
    "Nommes 3 types de nuages visibles.",
    "Donne 3 objets scolaires.",
    "Cite 3 chansons célèbres.",
    "Fais 3 pas de danse improvisés.",
    "Nommes 3 capitales sud-américaines.",
    "Donne 3 objets pour dessiner.",
    "Cite 3 animaux dangereux de la savane.",
    "Fais 3 étirements du dos.",
    "Nommes 3 légumes racines.",
    "Donne 3 films d’action.",
    "Cite 3 pays d’Europe de l’Ouest.",
    "Fais 3 mouvements de bras circulaires.",
    "Nommes 3 fruits jaunes.",
    "Donne 3 instruments de musique électroniques.",
    "Cite 3 animaux de montagne.",
    "Fais 3 tours sur toi-même lentement.",
    "Nommes 3 poissons exotiques.",
    "Donne 3 objets de bureau.",
    "Cite 3 sports extrêmes.",
    "Fais 3 pas en arrière rapidement.",
    "Nommes 3 capitales asiatiques peu connues.",
    "Donne 3 snacks sucrés.",
    "Cite 3 animaux marins colorés.",
    "Fais 3 sauts groupés.",
    "Nommes 3 pains du monde.",
    "Donne 3 chocolats différents.",
    "Cite 3 métiers scientifiques.",
    "Fais 3 mouvements de jambes rapides.",
    "Nommes 3 capitales africaines peu connues.",
    "Donne 3 plats végétariens célèbres.",
    "Cite 3 oiseaux de proie.",
    "Fais 3 tours sur toi-même en sautant.",
    "Nommes 3 animaux domestiques exotiques.",
    "Donne 3 instruments traditionnels.",
    "Cite 3 sports de glisse.",
    "Fais 3 étirements du cou.",
    "Nommes 3 capitales océaniques.",
    "Donne 3 jus de fruits différents.",
    "Cite 3 animaux de compagnie.",
    "Fais 3 mouvements de bras en rythme.",
    "Nommes 3 fromages à pâte dure.",
    "Donne 3 films d’horreur célèbres.",
    "Cite 3 fruits exotiques.",
    "Fais 3 pas chassés.",
    "Nommes 3 capitales nordiques.",
    "Donne 3 objets dans le salon.",
    "Cite 3 sports nautiques.",
    "Fais 3 roulades arrière.",
    "Nommes 3 légumes verts.",
    "Donne 3 films romantiques.",
    "Cite 3 animaux aquatiques dangereux.",
    "Fais 3 mouvements de bras en cercle.",
    "Nommes 3 capitales d’Europe centrale.",
    "Donne 3 sucreries.",
    "Cite 3 fromages français.",
    "Fais 3 sauts de grenouille sur place.",
    "Nommes 3 fleurs blanches.",
    "Donne 3 instruments rares.",
    "Cite 3 animaux d’Afrique célèbres.",
    "Fais 3 pas de côté rapides.",
    "Nommes 3 capitales sud-américaines célèbres.",
    "Donne 3 plats italiens célèbres.",
    "Cite 3 animaux exotiques domestiques.",
    "Fais 3 mouvements de bras et épaules.",
    "Nommes 3 pains français.",
    "Donne 3 films d’animation récents.",
    "Cite 3 sports collectifs en salle.",
    "Fais 3 étirements du torse.",
    "Nommes 3 capitales européennes modernes.",
    "Donne 3 objets décoratifs.",
    "Cite 3 animaux de forêt tropicale.",
    "Fais 3 pas chassés rapides.",
    "Nommes 3 chocolats noirs.",
    "Donne 3 boissons énergétiques.",
    "Cite 3 personnages célèbres.",
    "Fais 3 mouvements synchronisés de bras et jambes.",
    "Nommes 3 capitales asiatiques célèbres.",
    "Donne 3 plats pour le petit-déjeuner.",
    "Cite 3 animaux nocturnes dangereux.",
    "Fais 3 tours sur toi-même avec les bras levés.",
    "Nommes 3 fleurs rouges.",
    "Donne 3 plats mexicains célèbres.",
    "Cite 3 instruments anciens célèbres.",
    "Fais 3 sauts sur place avec bras levés.",
    "Nommes 3 capitales européennes célèbres.",
    "Donne 3 films dramatiques.",
    "Cite 3 animaux marins géants.",
    "Fais 3 pas en arrière en rythme.",
    "Nommes 3 légumes racines colorés.",
    "Donne 3 boissons chaudes populaires.",
    "Cite 3 sports olympiques.",
    "Fais 3 mouvements de hanches.",
    "Nommes 3 capitales africaines célèbres.",
    "Donne 3 plats asiatiques typiques.",
    "Cite 3 animaux domestiques originaux.",
    "Fais 3 pas chassés avec bras levés.",
    "Nommes 3 chocolats au lait.",
    "Donne 3 films d’aventure récents.",
    "Cite 3 oiseaux rares.",
    "Fais 3 roulades avant et arrière.",
    "Nommes 3 capitales américaines célèbres.",
    "Donne 3 aliments riches en protéines.",
    "Cite 3 animaux de montagne rares.",
    "Fais 3 mouvements circulaires des bras.",
    "Nommes 3 fromages suisses.",
    "Donne 3 plats végétariens populaires.",
    "Cite 3 animaux dangereux de la jungle.",
    "Fais 3 tours sur toi-même rapidement.",
    "Nommes 3 capitales d’Europe occidentale.",
    "Donne 3 instruments à cordes célèbres.",
    "Cite 3 sports extrêmes d’été.",
    "Fais 3 étirements bras et jambes simultanés.",
    "Nommes 3 fleurs jaunes.",
    "Donne 3 boissons non alcoolisées.",
    "Cite 3 animaux polaires rares.",
    "Fais 3 pas de danse improvisés.",
    "Nommes 3 capitales asiatiques lointaines.",
    "Donne 3 jus de fruits exotiques.",
    "Cite 3 animaux domestiques rares.",
    "Fais 3 mouvements rapides de bras et mains.",
    "Nommes 3 chocolats blancs.",
    "Donne 3 films fantastiques célèbres.",
    "Cite 3 fruits rouges rares.",
    "Fais 3 sauts groupés avec bras levés.",
    "Nommes 3 capitales européennes anciennes.",
    "Donne 3 plats indiens célèbres.",
    "Cite 3 instruments modernes célèbres.",
    "Fais 3 pas chassés rapides.",
    "Nommes 3 légumes verts rares.",
    "Donne 3 boissons gazeuses populaires.",
    "Quel est le plat préféré de {joueur} ?",
    "Quelle est la couleur préférée de {joueur} ?",
    "Quel animal {joueur} aimerait avoir comme compagnon ?",
    "Quelle est la pire habitude de {joueur} selon toi ?",
    "Quel est le film préféré de {joueur} ?",
    "Quelle est la boisson favorite de {joueur} ?",
    "Quel est le pays que {joueur} rêve de visiter ?",
    "Quel est le pire défaut de {joueur} selon toi ?",
    "Quel est le meilleur souvenir de {joueur} ?",
    "Quel est le sport préféré de {joueur} ?",
    "Quelle est la chanson préférée de {joueur} ?",
    "Quel est le talent caché de {joueur} ?",
    "Quelle est la peur secrète de {joueur} ?",
    "Quel est le dessert préféré de {joueur} ?",
    "Quel est le jeu préféré de {joueur} ?",
    "Quelle est la couleur que {joueur} déteste ?",
    "Quel est le personnage préféré de {joueur} dans un film ?",
    "Quelle est l'activité relaxante préférée de {joueur} ?",
    "Quel est le meilleur ami de {joueur} ?",
    "Quel est le lieu préféré de {joueur} pour se détendre ?",
    "Quelle est la chose que {joueur} ferait pour rire ?",
    "Quel est le plat que {joueur} ne mangerait jamais ?",
    "Quel est le rêve le plus fou de {joueur} ?",
    "Quelle est l'émotion que {joueur} ressent le plus souvent ?",
    "Quel est le style de musique préféré de {joueur} ?",
    "Quelle est la série préférée de {joueur} ?",
    "Quelle est la chose que {joueur} ne partagerait jamais ?",
    "Quel est le passe-temps préféré de {joueur} ?",
    "Quelle est la pire peur de {joueur} ?",
    "Quel est le cadeau idéal pour {joueur} ?",
    "Quel est le meilleur conseil que {joueur} ait reçu ?",
    "Quelle est la personne qui inspire {joueur} le plus ?",
    "Quelle est la couleur que {joueur} porte le plus souvent ?",
    "Quel est le meilleur endroit où {joueur} ait voyagé ?",
    "Quelle est la plus grande réussite de {joueur} ?",
    "Quel est le pire repas que {joueur} ait mangé ?",
    "Quel est le plat que {joueur} cuisine le mieux ?",
    "Quel est le mot que {joueur} utilise le plus souvent ?",
    "Quel est le film que {joueur} regarde en boucle ?",
    "Quelle est la chose que {joueur} aime faire quand il pleut ?",
    "Quel est l'animal que {joueur} déteste le plus ?",
    "Quel est le livre préféré de {joueur} ?",
    "Quel est le sport que {joueur} n’aime pas ?",
    "Quel est le lieu où {joueur} se sent le plus heureux ?",
    "Quel est le rêve d’enfance de {joueur} ?",
    "Quelle est la chanson que {joueur} chante sous la douche ?",
    "Quelle est la pire blague que {joueur} ait faite ?",
    "Quel est le plat que {joueur} trouve dégoûtant ?",
    "Quel est l’objet que {joueur} perd le plus souvent ?",
    "Quel est le film que {joueur} a honte d’aimer ?",
    "Quel est le talent secret de {joueur} ?",
    "Quel est le super-héros préféré de {joueur} ?",
    "Quel est le meilleur conseil que {joueur} donnerait ?",
    "Quel est le pire film que {joueur} ait vu ?",
    "Quelle est l’activité que {joueur} ferait tous les jours ?",
    "Quel est le dessert que {joueur} pourrait manger tous les jours ?",
    "Quelle est la chose la plus embarrassante que {joueur} ait faite ?",
    "Quel est le pire cadeau reçu par {joueur} ?",
    "Quelle est la chose que {joueur} collectionne ?",
    "Quel est le style vestimentaire de {joueur} ?",
    "Quel est le meilleur endroit pour sortir selon {joueur} ?",
    "Quel est le pire mensonge que {joueur} ait dit ?",
    "Quel est le plat que {joueur} déteste cuisiner ?",
    "Quel est le jeu de société préféré de {joueur} ?",
    "Quel est le sport que {joueur} aimerait apprendre ?",
    "Quelle est la chose la plus courageuse que {joueur} ait faite ?",
    "Quel est le film d’horreur que {joueur} ne regarderait jamais ?",
    "Quel est le loisir préféré de {joueur} ?",
    "Quel est le vêtement que {joueur} ne porterait jamais ?",
    "Quel est l’endroit que {joueur} veut visiter cette année ?",
    "Quel est l’aliment que {joueur} mange en cachette ?",
    "Quelle est la plus grande peur de {joueur} ?",
    "Quel est le personnage de série préféré de {joueur} ?",
    "Quel est l’endroit où {joueur} se sent le plus stressé ?",
    "Quel est le moment préféré de la journée pour {joueur} ?",
    "Quel est le pire cauchemar de {joueur} ?",
    "Quel est le plat que {joueur} pourrait manger sans se lasser ?",
    "Quel est le lieu que {joueur} aime pour se promener ?",
    "Quel est l’ami avec qui {joueur} rit le plus ?",
    "Quel est le sport que {joueur} regarde à la télévision ?",
    "Quel est le meilleur souvenir d’école de {joueur} ?",
    "Quel est l’animal que {joueur} trouve le plus mignon ?",
    "Quel est le pire bruit selon {joueur} ?",
    "Quelle est la chose que {joueur} ferait pour gagner un pari ?",
    "Quel est le personnage de dessin animé préféré de {joueur} ?",
    "Quel est le plat que {joueur} a essayé et détesté ?",
    "Quel est le loisir que {joueur} n’a jamais essayé ?",
    "Quelle est la chose que {joueur} a toujours voulu apprendre ?",
    "Quel est l’outil ou objet préféré de {joueur} ?",
    "Quel est le lieu où {joueur} se sent le plus relaxé ?",
    "Quelle est la musique qui fait danser {joueur} ?",
    "Quel est le dessert préféré de {joueur} à la fête ?",
    "Quel est le jeu vidéo que {joueur} adore ?",
    "Quel est le film que {joueur} pourrait regarder mille fois ?",
    "Quel est le rêve impossible de {joueur} ?",
    "Quel est l’animal que {joueur} n’a jamais vu mais aimerait voir ?",
    "Quel est l’objet que {joueur} utilise tous les jours ?",
    "Quel est le lieu où {joueur} a passé ses meilleures vacances ?",
    "Quel est le pire aliment que {joueur} ait goûté ?",
    "Quelle est la chose la plus drôle que {joueur} ait faite ?",
    "Quel est le personnage de livre préféré de {joueur} ?",
    "Quel est le sport que {joueur} n’aime vraiment pas ?",
    "Quel est le plat le plus étrange que {joueur} ait mangé ?",
    "Quel est le loisir créatif préféré de {joueur} ?",
    "Quel est le cadeau que {joueur} a adoré recevoir ?",
    "Quelle est la chose la plus courageuse que {joueur} a faite ?",
    "Quel est le vêtement préféré de {joueur} ?",
    "Quelle est la saison préférée de {joueur} ?",
    "Quel est le jeu que {joueur} préfère jouer avec ses amis ?",
    "Quel est le fruit que {joueur} déteste le plus ?",
    "Quel est le lieu où {joueur} aime aller se balader ?",
    "Quel est l’aliment que {joueur} pourrait manger tous les jours ?",
    "Quel est le pays que {joueur} a visité et adoré ?",
    "Quelle est la série que {joueur} recommande toujours ?",
    "Quel est le sport que {joueur} pratique le plus souvent ?",
    "Quel est le plat que {joueur} adore cuisiner ?",
    "Quelle est la couleur que {joueur} porte le plus souvent ?",
    "Quel est le film que {joueur} déteste ?",
    "Quel est l’animal que {joueur} trouve effrayant ?",
    "Quelle est la chanson que {joueur} chante toujours ?",
    "Quel est l’endroit préféré de {joueur} pour passer un week-end ?",
    "Quelle est l’émotion que {joueur} ressent le plus souvent ?",
    "Quel est le personnage de fiction que {joueur} admire le plus ?",
    "Quel est le plat que {joueur} commande toujours au restaurant ?",
    "Quel est le loisir que {joueur} ferait tous les jours si possible ?",
    "Quel est le pire bruit qui énerve {joueur} ?",
    "Donne 3 choses que {joueur} fait toujours le matin.",
    "Donne 3 choses que {joueur} oublie souvent.",
    "Donne 3 plats que {joueur} adore.",
    "Donne 3 films que {joueur} n’a jamais vus.",
    "Donne 3 chansons que {joueur} écoute en boucle.",
    "Donne 3 endroits où {joueur} aimerait voyager.",
    "Donne 3 animaux que {joueur} adore.",
    "Donne 3 sports que {joueur} pratique.",
    "Donne 3 jeux que {joueur} aime.",
    "Donne 3 objets que {joueur} emmène partout.",
    "Donne 3 habitudes que {joueur} a.",
    "Donne 3 choses que {joueur} déteste.",
    "Donne 3 cadeaux que {joueur} aimerait recevoir.",
    "Donne 3 boissons que {joueur} boit le plus.",
    "Donne 3 desserts que {joueur} préfère.",
    "Donne 3 personnes que {joueur} admire.",
    "Donne 3 secrets que {joueur} garde.",
    "Donne 3 endroits où {joueur} se sent bien.",
    "Donne 3 activités que {joueur} fait le week-end.",
    "Donne 3 moments que {joueur} n’oubliera jamais.",
    "Donne 3 langues que {joueur} aimerait apprendre.",
    "Donne 3 choses que {joueur} collectionne.",
    "Donne 3 objets que {joueur} utilise tous les jours.",
    "Donne 3 choses qui font rire {joueur}.",
    "Donne 3 plats que {joueur} ne mangerait jamais.",
    "Donne 3 films que {joueur} déteste.",
    "Donne 3 animaux que {joueur} a peur de voir.",
    "Donne 3 livres que {joueur} adore.",
    "Donne 3 souvenirs d’enfance de {joueur}.",
    "Donne 3 chansons qui font pleurer {joueur}.",
    "Donne 3 sports que {joueur} regarde à la télé.",
    "Donne 3 endroits que {joueur} veut visiter cette année.",
    "Donne 3 choses que {joueur} a apprises cette semaine.",
    "Donne 3 moments embarrassants de {joueur}.",
    "Donne 3 habitudes bizarres de {joueur}.",
    "Donne 3 fêtes préférées de {joueur}.",
    "Donne 3 choses qui énervent {joueur}.",
    "Donne 3 plats que {joueur} cuisine le mieux.",
    "Donne 3 films que {joueur} recommande toujours.",
    "Donne 3 personnes qui inspirent {joueur}.",
    "Donne 3 endroits où {joueur} aime se promener.",
    "Donne 3 choses que {joueur} ferait pour gagner un pari.",
    "Donne 3 moments où {joueur} a eu peur.",
    "Donne 3 choses que {joueur} a cassées par accident.",
    "Donne 3 habitudes matinales de {joueur}.",
    "Donne 3 souvenirs d’école de {joueur}.",
    "Donne 3 aliments que {joueur} mange en cachette.",
    "Donne 3 moments où {joueur} a beaucoup ri.",
    "Donne 3 objets que {joueur} a perdus récemment.",
    "Donne 3 films que {joueur} regarde quand il est triste.",
    "Donne 3 choses que {joueur} fait pour se détendre.",
    "Donne 3 animaux que {joueur} aimerait adopter.",
    "Donne 3 séries que {joueur} regarde en ce moment.",
    "Donne 3 habits préférés de {joueur}.",
    "Donne 3 desserts que {joueur} n’aime pas.",
    "Donne 3 choses que {joueur} trouve effrayantes.",
    "Donne 3 musiques que {joueur} chante sous la douche.",
    "Donne 3 endroits où {joueur} s’endort facilement.",
    "Donne 3 moments que {joueur} voudrait revivre.",
    "Donne 3 plats que {joueur} a goûtés pour la première fois récemment.",
    "Donne 3 choses que {joueur} a apprises récemment.",
    "Donne 3 objets que {joueur} garde précieusement.",
    "Donne 3 endroits préférés de vacances de {joueur}.",
    "Donne 3 moments tristes que {joueur} se rappelle.",
    "Donne 3 choses que {joueur} a offertes comme cadeau.",
    "Donne 3 jeux que {joueur} a gagnés.",
    "Donne 3 livres que {joueur} a lus cette année.",
    "Donne 3 plats que {joueur} a cuisinés récemment.",
    "Donne 3 endroits où {joueur} aime sortir.",
    "Donne 3 choses que {joueur} aime faire sous la pluie.",
    "Donne 3 moments où {joueur} s’est senti fier.",
    "Donne 3 animaux que {joueur} aimerait voir dans la nature.",
    "Donne 3 choses que {joueur} a apprises à l’école.",
    "Donne 3 sports que {joueur} n’a jamais pratiqués.",
    "Donne 3 plats que {joueur} aimerait apprendre à cuisiner.",
    "Donne 3 souvenirs de voyage de {joueur}.",
    "Donne 3 objets que {joueur} aime toucher.",
    "Donne 3 musiques qui font danser {joueur}.",
    "Donne 3 films que {joueur} a vus plusieurs fois.",
    "Donne 3 moments où {joueur} a été courageux.",
    "Donne 3 choses que {joueur} a cachées à ses amis.",
    "Donne 3 endroits que {joueur} aimerait visiter en secret.",
    "Donne 3 choses que {joueur} fait pour aider les autres.",
    "Donne 3 activités préférées de {joueur} en été.",
    "Donne 3 plats que {joueur} n’a jamais aimés.",
    "Donne 3 choses que {joueur} a oubliées récemment.",
    "Donne 3 souvenirs d’anniversaire de {joueur}.",
    "Donne 3 cadeaux que {joueur} a reçus cette année.",
    "Donne 3 moments où {joueur} a été surpris.",
    "Donne 3 objets que {joueur} utilise pour travailler.",
    "Donne 3 choses que {joueur} n’ose jamais dire.",
    "Donne 3 animaux que {joueur} trouve mignons.",
    "Donne 3 plats que {joueur} partage avec plaisir.",
    "Donne 3 choses que {joueur} fait avant de dormir.",
    "Donne 3 moments où {joueur} a ri aux larmes.",
    "Donne 3 habitudes alimentaires de {joueur}.",
    "Donne 3 endroits où {joueur} aime se promener en hiver.",
    "Donne 3 chansons qui rappellent des souvenirs à {joueur}.",
    "Donne 3 choses que {joueur} ne fait jamais le matin.",
    "Donne 3 moments où {joueur} a été embarrassé.",
    "Donne 3 films que {joueur} aime regarder en famille.",
    "Donne 3 activités que {joueur} fait avec ses amis.",
    "Donne 3 objets qui sont dans la chambre de {joueur}.",
    "Donne 3 moments que {joueur} voudrait oublier.",
    "Donne 3 plats que {joueur} a mangés lors d’un voyage.",
    "Donne 3 choses que {joueur} collectionne depuis longtemps.",
    "Donne 3 moments où {joueur} a été en colère.",
    "Donne 3 choses que {joueur} fait pour se motiver.",
    "Donne 3 souvenirs d’école primaire de {joueur}.",
    "Donne 3 chansons que {joueur} a apprises par cœur.",
    "Donne 3 moments où {joueur} a été triste.",
    "Donne 3 endroits où {joueur} aimerait vivre.",
    "Donne 3 choses que {joueur} a apprises en voyage.",
    "Donne 3 activités que {joueur} aime faire seul.",
    "Donne 3 objets que {joueur} a perdus récemment.",
    "Donne 3 plats que {joueur} aimerait goûter.",
    "Donne 3 moments heureux de {joueur}.",
    "Donne 3 choses que {joueur} fait pour se détendre après l’école.",
    "Donne 3 habitudes du matin de {joueur}.",
    "Donne 3 films que {joueur} regarde avant de dormir.",
    "Donne 3 moments où {joueur} a été surpris agréablement.",
    "Donne 3 choses que {joueur} a apprises en famille.",
    "Donne 3 objets que {joueur} utilise pour ses loisirs.",
    "Donne 3 plats que {joueur} préfère commander au restaurant.",
    "Donne 3 activités que {joueur} n’a jamais essayées.",
    "Donne 3 moments où {joueur} a été fier de lui.",
    "Donne 3 choses que {joueur} fait quand il est heureux.",
    "Donne 3 endroits où {joueur} se sent libre.",
    "Donne 3 objets que {joueur} a fabriqués lui-même.",
    "Donne 3 habitudes que {joueur} voudrait changer.",
    "Donne 3 plats que {joueur} aime partager.",
    "Donne 3 choses que {joueur} a apprises cette année.",
    "Donne 3 moments drôles de {joueur}.",
    "Donne 3 activités que {joueur} fait en famille.",
    "Donne 3 souvenirs de vacances de {joueur}.",
    "Donne 3 chansons que {joueur} aime chanter.",
    "Donne 3 endroits où {joueur} aime aller se promener.",
    "Donne 3 objets que {joueur} aimerait recevoir.",
    "Donne 3 moments où {joueur} a été courageux.",
    "Donne 3 plats que {joueur} n’oserait jamais goûter.",
    "Donne 3 choses que {joueur} aime faire seul.",
    "Donne 3 souvenirs d’enfance drôles de {joueur}.",
    "Donne 3 activités préférées de {joueur} au printemps.",
    "Donne 3 films que {joueur} regarde avec plaisir.",
    "Donne 3 moments où {joueur} a été surpris par un ami.",
    "Donne 3 choses que {joueur} a apprises récemment.",
    "Donne 3 endroits que {joueur} rêve de visiter.",
    "Donne 3 objets que {joueur} aimerait acheter.",
    "Donne 3 choses que {joueur} adore partager.",
    "Donne 3 moments où {joueur} a été ému.",
    "Donne 3 plats que {joueur} cuisine pour ses amis.",
    "Donne 3 choses que {joueur} fait quand il est triste.",
    "Donne 3 souvenirs scolaires de {joueur}.",
    "Donne 3 habitudes de {joueur} qui font rire.",
    "Donne 3 chansons que {joueur} fredonne souvent.",
    "Donne 3 moments où {joueur} a eu peur mais a surmonté.",
    "Donne 3 objets que {joueur} utilise tous les jours.",
    "Donne 3 activités que {joueur} aimerait apprendre.",
    "Donne 3 plats que {joueur} prépare quand il est motivé.",
    "Donne 3 moments drôles que {joueur} a partagés.",
    "Donne 3 choses que {joueur} fait le soir.",
    "Donne 3 endroits où {joueur} se sent heureux.",
    "Donne 3 objets que {joueur} n’aime pas.",
    "Donne 3 plats que {joueur} ne peut pas digérer.",
    "Donne 3 moments où {joueur} s’est senti embarrassé.",
    "Donne 3 habitudes de {joueur} que tu aimerais copier.",
    "Donne 3 choses que {joueur} fait pour impressionner les autres.",
    "Donne 3 choses que {joueur} trouve sexy chez quelqu’un.",
    "Donne 3 endroits où {joueur} aimerait être embrassé.",
    "Donne 3 fantasmes que {joueur} n’a jamais racontés.",
    "Donne 3 gestes qui font rougir {joueur}.",
    "Donne 3 parties du corps de {joueur} qu’il/elle préfère montrer.",
    "Donne 3 situations où {joueur} se sent irrésistible.",
    "Donne 3 choses que {joueur} adore recevoir pendant un baiser.",
    "Donne 3 vêtements que {joueur} trouve sexy.",
    "Donne 3 moments où {joueur} a flirté récemment.",
    "Donne 3 compliments que {joueur} aime entendre.",
    "Donne 3 positions préférées de {joueur} dans un câlin.",
    "Donne 3 choses que {joueur} aimerait essayer avec quelqu’un.",
    "Donne 3 actions qui font craquer {joueur}.",
    "Donne 3 endroits insolites où {joueur} aimerait être embrassé.",
    "Donne 3 façons dont {joueur} aime séduire.",
    "Donne 3 moments où {joueur} a eu chaud.",
    "Donne 3 qualités physiques que {joueur} trouve attirantes.",
    "Donne 3 types de baisers que {joueur} préfère.",
    "Donne 3 situations coquines que {joueur} fantasme.",
    "Donne 3 choses que {joueur} aime sentir sur lui/elle.",
    "Donne 3 gestes de séduction que {joueur} fait souvent.",
    "Donne 3 endroits où {joueur} se sentirait le plus attirant(e).",
    "Donne 3 types de massages que {joueur} adore.",
    "Donne 3 moments où {joueur} se sent vulnérable mais sexy.",
    "Donne 3 accessoires que {joueur} trouve sensuels.",
    "Donne 3 façons de toucher {joueur} qui le/la font craquer.",
    "Donne 3 situations où {joueur} rougit instantanément.",
    "Donne 3 choses que {joueur} aime faire avec quelqu’un de spécial.",
    "Donne 3 fantasmes romantiques de {joueur}.",
    "Donne 3 parties du corps que {joueur} aime faire admirer.",
    "Donne 3 situations où {joueur} se sent irrésistible pour quelqu’un.",
    "Donne 3 choses qui font sourire {joueur} de manière coquine.",
    "Donne 3 gestes tendres que {joueur} adore recevoir.",
    "Donne 3 actions audacieuses que {joueur} a faites pour séduire.",
    "Donne 3 types de caresses que {joueur} adore.",
    "Donne 3 moments où {joueur} a flirté sans honte.",
    "Donne 3 compliments sexy que {joueur} a déjà reçus.",
    "Donne 3 choses que {joueur} aimerait entendre au lit.",
    "Donne 3 façons dont {joueur} aime qu’on le/la touche.",
    "Donne 3 situations coquines que {joueur} a imaginées récemment.",
    "Donne 3 types de baisers que {joueur} préfère donner.",
    "Donne 3 endroits où {joueur} aimerait être caressé.",
    "Donne 3 gestes séduisants de {joueur} que tu as remarqués.",
    "Donne 3 choses que {joueur} ferait pour séduire quelqu’un.",
    "Donne 3 situations où {joueur} se sent charmant(e).",
    "Donne 3 choses que {joueur} aime voir chez quelqu’un de sexy.",
    "Donne 3 façons dont {joueur} montre son attirance.",
    "Donne 3 actions coquines que {joueur} a déjà faites en privé.",
    "Donne 3 moments où {joueur} s’est senti(e) irrésistible.",
    "Donne 3 choses que {joueur} aime dans les jeux de séduction.",
    "Donne 3 endroits où {joueur} fantasme secrètement.",
    "Donne 3 gestes de flirt que {joueur} fait inconsciemment.",
    "Donne 3 types de vêtements sexy que {joueur} possède.",
    "Donne 3 moments où {joueur} a été intimement proche de quelqu’un.",
    "Donne 3 situations où {joueur} a été audacieux(se) en séduction.",
    "Donne 3 choses que {joueur} aimerait essayer lors d’un rendez-vous.",
    "Donne 3 types de baisers que {joueur} adore recevoir.",
    "Donne 3 gestes coquets de {joueur} que tu as remarqués.",
    "Donne 3 moments où {joueur} a été charmeur(se).",
    "Donne 3 actions sensuelles que {joueur} aimerait tester.",
    "Donne 3 compliments que {joueur} voudrait entendre.",
    "Donne 3 façons dont {joueur} séduit quelqu’un de manière subtile.",
    "Donne 3 parties du corps que {joueur} trouve les plus sexy.",
    "Donne 3 situations où {joueur} s’est senti(e) désiré(e).",
    "Donne 3 choses coquines que {joueur} ferait en privé.",
    "Donne 3 moments où {joueur} a ressenti une forte attraction.",
    "Donne 3 gestes sexy que {joueur} fait naturellement.",
    "Donne 3 choses que {joueur} aimerait qu’on fasse pour lui/elle.",
    "Donne 3 endroits romantiques où {joueur} aimerait être avec quelqu’un.",
    "Donne 3 situations de flirt où {joueur} a été osé(e).",
    "Donne 3 choses que {joueur} aime dans les contacts physiques.",
    "Donne 3 gestes tendres mais coquins que {joueur} adore.",
    "Donne 3 moments où {joueur} a ressenti du désir pour quelqu’un.",
    "Donne 3 actions sexy que {joueur} aimerait essayer en couple.",
    "Donne 3 façons dont {joueur} flirte sans que tu t’en rendes compte.",
    "Donne 3 choses que {joueur} trouve irrésistibles chez l’autre.",
    "Donne 3 moments où {joueur} s’est senti(e) sexy en public.",
    "Donne 3 façons dont {joueur} tease quelqu’un.",
    "Donne 3 gestes coquins que {joueur} fait avec humour.",
    "Donne 3 situations où {joueur} a été charmé(e).",
    "Donne 3 moments où {joueur} a ressenti une tension romantique.",
    "Donne 3 choses que {joueur} aimerait que l’autre remarque sur lui/elle.",
    "Donne 3 gestes que {joueur} trouve irrésistibles chez quelqu’un.",
    "Donne 3 situations sexy que {joueur} imagine souvent.",
    "Donne 3 types de caresses que {joueur} adore recevoir.",
    "Donne 3 actions que {joueur} fait pour attirer l’attention d’un crush.",
    "Donne 3 moments où {joueur} a été audacieux(se) dans un flirt.",
    "Donne 3 choses que {joueur} trouve excitantes mais secrètes.",
    "Donne 3 gestes tendres que {joueur} utilise pour séduire.",
    "Donne 3 moments où {joueur} a été irrésistible selon toi.",
    "Donne 3 choses que {joueur} aime murmurer à l’oreille de quelqu’un.",
    "Donne 3 situations où {joueur} se sent très désirable.",
    "Donne 3 choses coquines que {joueur} n’a jamais racontées.",
    "Donne 3 gestes que {joueur} fait pour faire craquer quelqu’un."
];