 const hotWords = [
    "Je n'ai jamais couché avec le/la partenaire d’un(e) ami(e)",
    "Je n'ai jamais fait l’amour dans un lieu public",
    "Je n'ai jamais eu un plan cul en soirée sans connaître le prénom",
    "Je n'ai jamais trompé mon/ma partenaire",
    "Je n'ai jamais été surpris(e) en train de me masturber",
    "Je n'ai jamais regardé du porno au travail",
    "Je n'ai jamais eu un coup d’un soir qui a mal tourné",
    "Je n'ai jamais fantasmé sur un(e) collègue",
    "Je n'ai jamais utilisé un jouet sexuel",
    "Je n'ai jamais fait l’amour avec plus d’une personne en même temps",
    "Je n'ai jamais envoyé de nudes",
    "Je n'ai jamais reçu de dickpic non sollicité",
    "Je n'ai jamais pratiqué le sexe anal",
    "Je n'ai jamais simulé un orgasme",
    "Je n'ai jamais eu un orgasme en public sans que personne ne s’en rende compte",
    "Je n'ai jamais eu des relations sexuelles dans les toilettes d’un bar",
    "Je n'ai jamais embrassé quelqu’un du même sexe",
    "Je n'ai jamais participé à une partouze",
    "Je n'ai jamais payé pour du sexe",
    "Je n'ai jamais été payé(e) pour du sexe",
    "Je n'ai jamais fait l’amour dans la voiture de mes parents",
    "Je n'ai jamais eu un(e) sex friend",
    "Je n'ai jamais regardé du porno en couple pour pimenter les choses",
    "Je n'ai jamais essayé le bondage",
    "Je n'ai jamais utilisé des menottes au lit",
    "Je n'ai jamais fait l’amour sur une plage",
    "Je n'ai jamais eu un rapport sans protection avec un inconnu",
    "Je n'ai jamais fantasmé sur un professeur",
    "Je n'ai jamais eu des relations dans un ascenseur",
    "Je n'ai jamais pratiqué le rôle play coquin",
    "Je n'ai jamais été infidèle en voyage",
    "Je n'ai jamais eu un threesome",
    "Je n'ai jamais filmé mes ébats sexuels",
    "Je n'ai jamais regardé une vidéo de moi en train de faire l’amour",
    "Je n'ai jamais eu du sexe au bureau",
    "Je n'ai jamais fait l’amour dans un cimetière",
    "Je n'ai jamais eu un orgasme bruyant en présence d’autres personnes",
    "Je n'ai jamais pratiqué le BDSM",
    "Je n'ai jamais porté de lingerie pour exciter quelqu’un",
    "Je n'ai jamais eu du sexe dans une cabine d’essayage",
    "Je n'ai jamais embrassé plus de 5 personnes en une soirée",
    "Je n'ai jamais eu des relations sexuelles avec un(e) ex après une rupture",
    "Je n'ai jamais menti sur mon nombre de partenaires",
    "Je n'ai jamais eu du sexe en plein air sous la pluie",
    "Je n'ai jamais utilisé de la nourriture pendant l’acte",
    "Je n'ai jamais fait l’amour avec la lumière allumée en étant gêné(e)",
    "Je n'ai jamais eu un crush sur le/la partenaire d’un(e) ami(e)",
    "Je n'ai jamais dragué en étant en couple",
    "Je n'ai jamais eu du sexe dans un train",
    "Je n'ai jamais pratiqué le quickie dans un lieu risqué",
    "Je n'ai jamais eu des relations avec une différence d’âge de plus de 15 ans",
    "Je n'ai jamais fantasmé sur un membre de la famille d’un(e) ami(e)",
    "Je n'ai jamais eu du sexe torride après une dispute",
    "Je n'ai jamais utilisé un vibromasseur en présence de quelqu’un",
    "Je n'ai jamais eu un orgasme juste en embrassant",
    "Je n'ai jamais fait l’amour dans une piscine",
    "Je n'ai jamais eu des relations avec quelqu’un que je venais de rencontrer sur Tinder",
    "Je n'ai jamais pratiqué le dirty talk",
    "Je n'ai jamais eu du sexe dans un hôtel avec un inconnu",
    "Je n'ai jamais simulé être malade pour avoir du sexe",
    "Je n'ai jamais eu des relations dans la maison parentale en cachette",
    "Je n'ai jamais regardé du porno hentai",
    "Je n'ai jamais eu un fétichisme bizarre",
    "Je n'ai jamais fait l’amour avec les fenêtres ouvertes",
    "Je n'ai jamais eu du sexe en regardant un miroir",
    "Je n'ai jamais pratiqué le edging",
    "Je n'ai jamais eu des relations avec quelqu’un en uniforme",
    "Je n'ai jamais envoyé des messages coquins au travail",
    "Je n'ai jamais eu du sexe dans un avion",
    "Je n'ai jamais participé à un strip-poker qui a dégénéré",
    "Je n'ai jamais eu un orgasme en dormant",
    "Je n'ai jamais fait l’amour sur un balcon",
    "Je n'ai jamais eu des relations avec un(e) collègue",
    "Je n'ai jamais pratiqué le sexe tantrique",
    "Je n'ai jamais eu du sexe en état d’ébriété regretté",
    "Je n'ai jamais utilisé des glaçons pendant l’acte",
    "Je n'ai jamais eu des relations dans une église",
    "Je n'ai jamais fantasmé sur un personnage fictif de façon intense",
    "Je n'ai jamais eu du sexe avec la musique à fond pour couvrir les bruits",
    "Je n'ai jamais pratiqué le facesitting",
    "Je n'ai jamais eu un rapport qui a duré plus de 2 heures",
    "Je n'ai jamais menti pour coucher avec quelqu’un",
    "Je n'ai jamais eu des relations dans un parking souterrain",
    "Je n'ai jamais utilisé du lubrifiant aromatisé",
    "Je n'ai jamais eu du sexe en camping sauvage",
    "Je n'ai jamais pratiqué le dogging",
    "Je n'ai jamais eu un orgasme en faisant du sport",
    "Je n'ai jamais fantasmé sur un inconnu dans les transports",
    "Je n'ai jamais eu des relations avec quelqu’un marié(e)",
    "Je n'ai jamais regardé du porno en public discrètement",
    "Je n'ai jamais eu du sexe dans une bibliothèque",
    "Je n'ai jamais pratiqué le spanking",
    "Je n'ai jamais eu un coup de foudre sexuel immédiat",
    "Je n'ai jamais utilisé un plug anal",
    "Je n'ai jamais eu des relations dans un sauna",
    "Je n'ai jamais simulé un accent pour exciter",
    "Je n'ai jamais eu du sexe sur une table de cuisine",
    "Je n'ai jamais pratiqué le sexe oral dans une voiture en mouvement",
    "Je n'ai jamais eu un partenaire qui m’a surpris(e) sexuellement",
    "Je n'ai jamais regardé du porno lesbien en étant hétéro",
    "Je n'ai jamais eu des relations avec quelqu’un que je détestais",
    "Je n'ai jamais pratiqué le jeu de rôle maître/esclave",
    "Je n'ai jamais eu du sexe en regardant le lever du soleil",
    "Je n'ai jamais utilisé des huiles de massage coquines",
    "Je n'ai jamais eu un orgasme sans contact physique",
    "Je n'ai jamais fantasmé sur un(e) inconnu(e) croisé(e) dans la rue",
    "Je n'ai jamais eu des relations dans un festival",
    "Je n'ai jamais pratiqué le sexting avec photos",
    "Je n'ai jamais eu du sexe dans l’eau salée",
    "Je n'ai jamais simulé une panne pour coucher",
    "Je n'ai jamais eu des relations avec un(e) voisin(e)",
    "Je n'ai jamais pratiqué le sexe en talons aiguilles",
    "Je n'ai jamais eu un rapport bruyant qui a réveillé quelqu’un",
    "Je n'ai jamais utilisé un foulard pour bander les yeux",
    "Je n'ai jamais eu du sexe dans un cinéma",
    "Je n'ai jamais fantasmé sur un boss",
    "Je n'ai jamais eu des relations après un enterrement",
    "Je n'ai jamais pratiqué le 69",
    "Je n'ai jamais eu du sexe avec un(e) inconnu(e) rencontré(e) en ligne le jour même",
    "Je n'ai jamais utilisé de la chantilly sur le corps",
    "Je n'ai jamais eu un orgasme en dansant collé-serré",
    "Je n'ai jamais pratiqué le sexe debout contre un mur",
    "Je n'ai jamais eu des relations dans un vestiaire",
    "Je n'ai jamais simulé être vierge pour exciter",
    "Je n'ai jamais eu du sexe en écoutant de la musique classique",
    "Je n'ai jamais pratiqué le slow sex",
    "Je n'ai jamais eu un partenaire qui pleurait après l’acte",
    "Je n'ai jamais utilisé des bougies pour l’ambiance (et plus)",
    "Je n'ai jamais eu des relations dans un musée",
    "Je n'ai jamais fantasmé sur un(e) célébrité de façon obsessionnelle",
    "Je n'ai jamais pratiqué le sexe avec des miroirs partout",
    "Je n'ai jamais eu du sexe après avoir fumé",
    "Je n'ai jamais utilisé des plumes pour titiller",
    "Je n'ai jamais eu un rapport qui a cassé un meuble",
    "Je n'ai jamais pratiqué le sexe en costume",
    "Je n'ai jamais eu des relations avec quelqu’un parlant une autre langue",
    "Je n'ai jamais simulé un gémissement exagéré",
    "Je n'ai jamais eu du sexe dans un hamac",
    "Je n'ai jamais pratiqué le sexe virtuel par webcam",
    "Je n'ai jamais eu un orgasme en roulant en voiture",
    "Je n'ai jamais utilisé du chocolat fondu",
    "Je n'ai jamais eu des relations dans un arbre",
    "Je n'ai jamais fantasmé sur un(e) inconnu(e) en uniforme",
    "Je n'ai jamais pratiqué le sexe avec des jouets connectés",
    "Je n'ai jamais eu du sexe en pleurant de plaisir",
    "Je n'ai jamais utilisé des menottes en fourrure",
    "Je n'ai jamais eu des relations dans un château",
    "Je n'ai jamais pratiqué le sexe après un concert",
    "Je n'ai jamais eu un partenaire qui m’a mordue jusqu’au sang",
    "Je n'ai jamais simulé être dominant(e) alors que je ne le suis pas",
    "Je n'ai jamais eu du sexe dans la neige",
    "Je n'ai jamais pratiqué le sexe avec des lumières noires",
    "Je n'ai jamais eu des relations orales sous la douche",
    "Je n'ai jamais utilisé un oreiller pour étouffer les cris",
    "Je n'ai jamais eu du sexe en regardant un film porno ensemble",
    "Je n'ai jamais pratiqué le sexe avec des gants en latex",
    "Je n'ai jamais eu un orgasme si fort que j’ai tremblé pendant longtemps",
    "Je n'ai jamais fantasmé sur un viol (consenti en roleplay)",
    "Je n'ai jamais eu des relations dans un bateau",
    "Je n'ai jamais menti sur mon CV",
"Je n'ai jamais triché à un examen",
"Je n'ai jamais volé quelque chose dans un magasin",
"Je n'ai jamais conduit sans permis",
"Je n'ai jamais pris un tramway",
"Je n'ai jamais fait de bateau",
"Je n'ai jamais dénoncé quelqu’un anonymement",
"Je n'ai jamais diffusé une rumeur sur quelqu’un",
"Je n'ai jamais ghosté un ami proche",
"Je n'ai jamais trahi la confiance de quelqu’un",
"Je n'ai jamais menti à mes parents sur quelque chose de grave",
"Je n'ai jamais falsifié une signature",
"Je n'ai jamais copié sur un collègue au travail",
"Je n'ai jamais pris l’argent dans le portefeuille de quelqu’un",
"Je n'ai jamais accusé quelqu’un à tort",
"Je n'ai jamais harcelé quelqu’un en ligne",
"Je n'ai jamais partagé une photo privée sans permission",
"Je n'ai jamais piraté un compte",
"Je n'ai jamais vendu des informations confidentielles",
"Je n'ai jamais menti pour obtenir un avantage financier",
"Je n'ai jamais fraudé les impôts",
"Je n'ai jamais déclaré quelque chose de faux aux assurances",
"Je n'ai jamais profité d’une personne vulnérable",
"Je n'ai jamais discriminé quelqu’un ouvertement",
"Je n'ai jamais tenu des propos racistes",
"Je n'ai jamais tenu des propos homophobes",
"Je n'ai jamais moqué le handicap de quelqu’un",
"Je n'ai jamais ignoré une personne en détresse",
"Je n'ai jamais laissé quelqu’un prendre la faute à ma place",
"Je n'ai jamais menti lors d’un entretien d’embauche",
"Je n'ai jamais saboté le travail d’un collègue",
"Je n'ai jamais volé des idées à quelqu’un",
"Je n'ai jamais plagié un travail",
"Je n'ai jamais répandu des fake news sciemment",
"Je n'ai jamais manipulé quelqu’un pour obtenir quelque chose",
"Je n'ai jamais menacé quelqu’un",
"Je n'ai jamais participé à du cyberharcèlement",
"Je n'ai jamais doxxé quelqu’un",
"Je n'ai jamais créé un faux profil pour espionner",
"Je n'ai jamais menti sur ma situation familiale",
"Je n'ai jamais caché une maladie grave à mon entourage",
"Je n'ai jamais abandonné un animal",
"Je n'ai jamais maltraité un animal",
"Je n'ai jamais participé à une bagarre physique",
"Je n'ai jamais porté une arme",
"Je n'ai jamais conduit en état d’ivresse",
"Je n'ai jamais consommé des substances interdites",
"Je n'ai jamais vendu des produits illégaux",
"Je n'ai jamais été arrêté par la police",
"Je n'ai jamais fui un contrôle policier",
"Je n'ai jamais menti à la police",
"Je n'ai jamais témoigné à charge contre quelqu’un à tort",
"Je n'ai jamais corrompu quelqu’un",
"Je n'ai jamais accepté un pot-de-vin",
"Je n'ai jamais détourné de l’argent",
"Je n'ai jamais blanchi de l’argent",
"Je n'ai jamais participé à une escroquerie",
"Je n'ai jamais arnaqué une personne âgée",
"Je n'ai jamais usurpé l’identité de quelqu’un",
"Je n'ai jamais falsifié un document officiel",
"Je n'ai jamais voté plusieurs fois",
"Je n'ai jamais truqué une élection",
"Je n'ai jamais profité d’une catastrophe pour voler",
"Je n'ai jamais ignoré un accident sans porter secours",
"Je n'ai jamais causé un accident et fui",
"Je n'ai jamais menti sur mes diplômes",
"Je n'ai jamais inventé une maladie pour obtenir des avantages",
"Je n'ai jamais simulé un handicap",
"Je n'ai jamais profité du RSA en travaillant au noir",
"Je n'ai jamais déclaré un faux sinistre",
"Je n'ai jamais incendié volontairement quelque chose",
"Je n'ai jamais vandalisé un lieu public",
"Je n'ai jamais tagué sans autorisation",
"Je n'ai jamais participé à une manifestation violente",
"Je n'ai jamais jeté un objet sur la police",
"Je n'ai jamais agressé verbalement un inconnu",
"Je n'ai jamais tenu des propos antisémites",
"Je n'ai jamais nié un génocide",
"Je n'ai jamais soutenu une idéologie extrémiste",
"Je n'ai jamais adhéré à une secte",
"Je n'ai jamais recruté pour une secte",
"Je n'ai jamais forcé quelqu’un à croire en quelque chose",
"Je n'ai jamais coupé les ponts avec ma famille sans raison grave",
"Je n'ai jamais abandonné un proche en difficulté",
"Je n'ai jamais refusé d’aider financièrement un proche dans le besoin",
"Je n'ai jamais menti sur la mort de quelqu’un",
"Je n'ai jamais profité d’un deuil pour gagner quelque chose",
"Je n'ai jamais volé dans une église ou un lieu de culte",
"Je n'ai jamais blasphémé intentionnellement pour choquer",
"Je n'ai jamais saccagé une tombe",
"Je n'ai jamais menti lors d’un procès",
"Je n'ai jamais été juré et menti",
"Je n'ai jamais caché une preuve",
"Je n'ai jamais détruit des preuves",
"Je n'ai jamais accusé un innocent de viol",
"Je n'ai jamais couvert un crime grave",
"Je n'ai jamais été complice d’un délit",
"Je n'ai jamais participé à du trafic",
"Je n'ai jamais acheté des biens volés sciemment",
"Je n'ai jamais revendu des objets volés",
"Je n'ai jamais menti pour protéger un criminel",
"Je n'ai jamais menacé un témoin",
"Je n'ai jamais intimidé quelqu’un pour qu’il se taise",
"Je n'ai jamais participé à une vengeance",
"Je n'ai jamais diffamé publiquement quelqu’un",
"Je n'ai jamais ruiné la réputation de quelqu’un intentionnellement",
"Je n'ai jamais monté un dossier contre quelqu’un",
"Je n'ai jamais espionné les conversations privées de quelqu’un",
"Je n'ai jamais enregistré quelqu’un sans consentement",
"Je n'ai jamais diffusé un enregistrement privé",
"Je n'ai jamais menti sur mes origines",
"Je n'ai jamais discriminé à l’embauche",
"Je n'ai jamais refusé un poste à quelqu’un pour son apparence",
"Je n'ai jamais harcelé moralement au travail",
"Je n'ai jamais forcé quelqu’un à démissionner",
"Je n'ai jamais volé du matériel au travail",
"Je n'ai jamais utilisé les ressources de l’entreprise à des fins personnelles graves",
"Je n'ai jamais menti sur un arrêt maladie",
"Je n'ai jamais simulé une blessure",
"Je n'ai jamais profité d’un drame pour attirer l’attention",
"Je n'ai jamais inventé une agression",
"Je n'ai jamais accusé faussement quelqu’un de harcèlement",
"Je n'ai jamais utilisé la victimisation pour manipuler",
"Je n'ai jamais menti sur une agression subie",
"Je n'ai jamais minimisé les souffrances de quelqu’un",
"Je n'ai jamais ri d’une tragédie",
"Je n'ai jamais profité d’une guerre ou d’une crise",
"Je n'ai jamais vendu des faux médicaments",
"Je n'ai jamais participé à de la désinformation médicale",
"Je n'ai jamais refusé le vaccin par conviction forte (et imposé ça aux autres)",
"Je n'ai jamais imposé mes croyances politiques violemment",
"Je n'ai jamais coupé contact avec quelqu’un pour ses opinions",
"Je n'ai jamais annulé quelqu’un publiquement",
"Je n'ai jamais participé à une cancel culture excessive",
"Je n'ai jamais dénoncé quelqu’un pour ses anciennes opinions",
"Je n'ai jamais jugé quelqu’un sur son passé sans contexte",
"Je n'ai jamais refusé de pardonner une erreur",
"Je n'ai jamais tenu rancune pendant des années",
"Je n'ai jamais souhaité du mal à quelqu’un ouvertement",
"Je n'ai jamais célébré la mort de quelqu’un",
"Je n'ai jamais ri d’un suicide",
"Je n'ai jamais poussé quelqu’un au bord du gouffre",
"Je n'ai jamais ignoré les signes de détresse d’un proche",
"Je n'ai jamais abandonné quelqu’un en dépression",
"Je n'ai jamais moqué une tentative de suicide",
"Je n'ai jamais partagé une histoire tragique pour faire le buzz",
"Je n'ai jamais exploité la souffrance des autres",
"Je n'ai jamais menti sur mon passé militaire",
"Je n'ai jamais prétendu avoir vécu une guerre",
"Je n'ai jamais volé la valorisation d’un vétéran",
"Je n'ai jamais porté une médaille non méritée",
"Je n'ai jamais menti sur une maladie grave",
"Je n'ai jamais prétendu avoir un cancer",
"Je n'ai jamais organisé une fausse collecte de dons",
"Je n'ai jamais détourné des dons caritatifs",
"Je n'ai jamais profité d’une association humanitaire",
"Je n'ai jamais menti sur mon engagement écologique tout en polluant",
"Je n'ai jamais jeté des déchets dans la nature",
"Je n'ai jamais participé à du braconnage",
"Je n'ai jamais acheté de l’ivoire ou des produits illégaux d’animaux",
"Je n'ai jamais soutenu la corrida",
"Je n'ai jamais participé à des combats d’animaux",
"Je n'ai jamais abandonné un enfant",
"Je n'ai jamais renié mon enfant",
"Je n'ai jamais forcé un enfant à travailler",
"Je n'ai jamais privé un enfant d’éducation",
"Je n'ai jamais imposé une religion par la force",
"Je n'ai jamais pratiqué l’excision ou la mutilation",
"Je n'ai jamais arrangé un mariage forcé",
"Je n'ai jamais participé à un crime d’honneur"
  ]
  // Liste des mots (à personnaliser)
  const words = [
    "Je n'ai jamais voyagé en avion",
    "Je n'ai jamais mangé de sushi",
    "Je n'ai jamais fait du ski",
    "Je n'ai jamais raté un réveil",
    "Je n'ai jamais chanté sous la douche",
    "Je n'ai jamais dormi plus de 12 heures",
    "Je n'ai jamais pris le métro à minuit",
    "Je n'ai jamais lu un roman entier en une journée",
    "Je n'ai jamais fait de camping",
    "Je n'ai jamais vu un film d'horreur seul",
    "Je n'ai jamais mangé de chocolat blanc",
    "Je n'ai jamais cassé un téléphone",
    "Je n'ai jamais fait de karaoké",
    "Je n'ai jamais sauté à l'élastique",
    "Je n'ai jamais fait de vélo sans les mains",
    "Je n'ai jamais mangé de bonbon au piment",
    "Je n'ai jamais fait un marathon",
    "Je n'ai jamais pris de bain moussant",
    "Je n'ai jamais oublié un anniversaire",
    "Je n'ai jamais essayé un sport extrême",
    "Je n'ai jamais planté d'arbre",
    "Je n'ai jamais fait de pâtisserie",
    "Je n'ai jamais fait de peinture",
    "Je n'ai jamais dormi dans une tente",
    "Je n'ai jamais vu un arc-en-ciel complet",
    "Je n'ai jamais chanté en public",
    "Je n'ai jamais pris de photos de nuit",
    "Je n'ai jamais parlé à un inconnu dans la rue",
    "Je n'ai jamais eu un animal de compagnie",
    "Je n'ai jamais essayé le yoga",
    "Je n'ai jamais fait de snowboard",
    "Je n'ai jamais perdu mes clés",
    "Je n'ai jamais bu de café glacé",
    "Je n'ai jamais regardé un lever de soleil",
    "Je n'ai jamais cuisiné un plat compliqué",
    "Je n'ai jamais joué à un jeu vidéo toute une nuit",
    "Je n'ai jamais pris un selfie",
    "Je n'ai jamais été au cinéma seul",
    "Je n'ai jamais fait de course à pied",
    "Je n'ai jamais pris le train de nuit",
    "Je n'ai jamais fait de jardinage",
    "Je n'ai jamais lu un livre en anglais",
    "Je n'ai jamais pris un taxi",
    "Je n'ai jamais eu le vertige",
    "Je n'ai jamais nagé dans la mer",
    "Je n'ai jamais mangé de nourriture exotique",
    "Je n'ai jamais fait un puzzle",
    "Je n'ai jamais dormi dehors",
    "Je n'ai jamais pris un vol international",
    "Je n'ai jamais fait du roller",
    "Je n'ai jamais fait de vélo en ville",
    "Je n'ai jamais dessiné un portrait",
    "Je n'ai jamais pris un bus de nuit",
    "Je n'ai jamais visité un musée",
    "Je n'ai jamais vu un feu d'artifice",
    "Je n'ai jamais pris un bain de minuit",
    "Je n'ai jamais écrit une lettre à la main",
    "Je n'ai jamais fait de karaoké en groupe",
    "Je n'ai jamais pris de photo polaroid",
    "Je n'ai jamais goûté des fruits exotiques",
    "Je n'ai jamais dormi plus de 10 heures",
    "Je n'ai jamais fait un pique-nique",
    "Je n'ai jamais assisté à un concert",
    "Je n'ai jamais pris un train local",
    "Je n'ai jamais fait de méditation",
    "Je n'ai jamais regardé une série entière en une journée",
    "Je n'ai jamais fait de randonnée",
    "Je n'ai jamais pris le bus pour aller loin",
    "Je n'ai jamais mangé des insectes",
    "Je n'ai jamais fait du patin à glace",
    "Je n'ai jamais mangé un plat végétarien",
    "Je n'ai jamais fait de courses dans un supermarché seul",
    "Je n'ai jamais fait de trampoline",
    "Je n'ai jamais appris une langue étrangère",
    "Je n'ai jamais vu un animal sauvage de près",
    "Je n'ai jamais fait du canoë",
    "Je n'ai jamais essayé un instrument de musique",
    "Je n'ai jamais porté un costume",
    "Je n'ai jamais fait du shopping seul",
    "Je n'ai jamais bu de thé glacé",
    "Je n'ai jamais pris un cours de danse",
    "Je n'ai jamais vu la neige",
    "Je n'ai jamais fait de camping sauvage",
    "Je n'ai jamais lu un manga",
    "Je n'ai jamais mangé de fromage bizarre",
    "Je n'ai jamais conduit une voiture",
    "Je n'ai jamais fait du roller en ville",
    "Je n'ai jamais regardé un match de sport en direct",
    "Je n'ai jamais fait du trampoline",
    "Je n'ai jamais pris le métro aux heures de pointe",
    "Je n'ai jamais mangé un dessert maison",
    "Je n'ai jamais pris une photo avec un animal",
    "Je n'ai jamais participé à une course",
    "Je n'ai jamais vu une aurore",
    "Je n'ai jamais fait de bénévolat",
    "Je n'ai jamais mangé des sushis",
    "Je n'ai jamais été à la mer",
    "Je n'ai jamais visité une capitale",
    "Je n'ai jamais bu de soda",
    "Je n'ai jamais fait de shopping en ligne",
    "Je n'ai jamais fait de barbecue",
    "Je n'ai jamais pris le train pour une longue distance",
    "Je n'ai jamais visité un parc d'attractions",
    "Je n'ai jamais vu un match de football",
    "Je n'ai jamais fait de karaoké avec des amis",
    "Je n'ai jamais mangé une glace seule",
    "Je n'ai jamais pris un cours de sport",
    "Je n'ai jamais fait un road trip",
    "Je n'ai jamais regardé un film en noir et blanc",
    "Je n'ai jamais fait du roller en montagne",
    "Je n'ai jamais pris un cours de dessin",
    "Je n'ai jamais assisté à un spectacle de magie",
    "Je n'ai jamais pris un avion en urgence",
    "Je n'ai jamais fait du yoga en plein air",
    "Je n'ai jamais mangé un plat épicé",
    "Je n'ai jamais vu un ballet",
    "Je n'ai jamais nagé dans une rivière",
    "Je n'ai jamais fait de kayak",
    "Je n'ai jamais pris un selfie avec un ami",
    "Je n'ai jamais joué à un instrument en public",
    "Je n'ai jamais fait un concours de chant",
    "Je n'ai jamais assisté à une exposition d'art",
    "Je n'ai jamais fait un pique-nique en forêt",
    "Je n'ai jamais pris un bain de soleil",
    "Je n'ai jamais fait de bateau",
    "Je n'ai jamais pris un tramway",
    "Je n'ai jamais visité un château",
    "Je n'ai jamais fait de ski nautique",
    "Je n'ai jamais mangé de pizza entière seul",
    "Je n'ai jamais pris un train à grande vitesse",
    "Je n'ai jamais fait de trottinette électrique",
    "Je n'ai jamais pris un cours de cuisine",
    "Je n'ai jamais participé à une fête foraine",
    "Je n'ai jamais regardé un match de basket",
    "Je n'ai jamais fait un dessin animé",
    "Je n'ai jamais pris un selfie devant un monument",
    "Je n'ai jamais goûté un plat japonais",
    "Je n'ai jamais fait de roller en parc",
    "Je n'ai jamais pris un bus touristique",
    "Je n'ai jamais mangé un dessert italien",
    "Je n'ai jamais fait de peinture à l'aquarelle",
    "Je n'ai jamais fait un escape game",
    "Je n'ai jamais pris un cours de photographie",
    "Je n'ai jamais fait du patin à roulettes",
    "Je n'ai jamais visité une bibliothèque",
    "Je n'ai jamais pris un cours de chant",
    "Je n'ai jamais mangé un plat chinois",
    "Je n'ai jamais fait un footing",
    "Je n'ai jamais pris un selfie au coucher du soleil",
    "Je n'ai jamais fait de camping en montagne",
    "Je n'ai jamais pris un train local long trajet",
    "Je n'ai jamais fait de méditation guidée",
    "Je n'ai jamais visité un zoo",
    "Je n'ai jamais fait un pique-nique au bord de l'eau",
    "Je n'ai jamais pris un bain dans un lac",
    "Je n'ai jamais fait de roller en groupe",
    "Je n'ai jamais pris un cours de sport collectif",
    "Je n'ai jamais mangé un plat végétalien",
    "Je n'ai jamais fait un tour de manège",
    "Je n'ai jamais pris un taxi de nuit",
    "Je n'ai jamais assisté à un feu d'artifice",
    "Je n'ai jamais fait un selfie avec un animal sauvage",
    "Je n'ai jamais pris un café au lait",
    "Je n'ai jamais fait un marathon de films",
    "Je n'ai jamais visité un aquarium",
    "Je n'ai jamais fait de randonnée en montagne",
    "Je n'ai jamais pris un bain dans la mer",
    "Je n'ai jamais joué à un jeu de société",
    "Je n'ai jamais fait de roller nocturne",
    "Je n'ai jamais pris un selfie devant un monument célèbre",
    "Je n'ai jamais mangé un fruit de mer",
    "Je n'ai jamais assisté à un festival",
    "Je n'ai jamais fait de yoga à la plage",
    "Je n'ai jamais pris un cours de danse moderne",
    "Je n'ai jamais fait un puzzle compliqué",
    "Je n'ai jamais pris un bain de minuit",
    "Je n'ai jamais participé à un escape game en groupe",
    "Je n’ai jamais embrassé quelqu’un du même sexe",
    "Je n’ai jamais eu un orgasme en public",
    "Je n’ai jamais envoyé de photo sexy",
    "Je n’ai jamais fait l’amour dans un lieu public",
    "Je n’ai jamais bu plus de 10 shots d’alcool en une soirée",
    "Je n’ai jamais essayé un cocktail bizarre",
    "Je n’ai jamais vomi à cause de l’alcool",
    "Je n’ai jamais eu de relation d’un soir",
    "Je n’ai jamais été dans un club échangiste",
    "Je n’ai jamais utilisé un sextoy",
    "Je n’ai jamais couché avec quelqu’un de plus âgé",
    "Je n’ai jamais fantasmé sur le meilleur ami de mon partenaire",
    "Je n’ai jamais fait l’amour en pleine journée",
    "Je n’ai jamais été nu devant quelqu’un pour plaisanter",
    "Je n’ai jamais eu un coup de foudre sexuel",
    "Je n’ai jamais été surpris en train de se masturber",
    "Je n’ai jamais fait un strip-tease",
    "Je n’ai jamais bu un verre en cachette de mes parents",
    "Je n’ai jamais goûté un aliment bizarre en soirée",
    "Je n’ai jamais dansé sur une table",
    "Je n’ai jamais fait un baiser volé",
    "Je n’ai jamais touché quelqu’un sous la table",
    "Je n’ai jamais couché avec quelqu’un sur un coup de tête",
    "Je n’ai jamais menti pour draguer quelqu’un",
    "Je n’ai jamais essayé de draguer un professeur",
    "Je n’ai jamais été dans un sauna nudiste",
    "Je n’ai jamais eu une relation avec quelqu’un que je connaissais peu",
    "Je n’ai jamais fait l’amour dans une voiture",
    "Je n’ai jamais été ivre mort",
    "Je n’ai jamais fait un jeu de vérité ou conséquence coquin",
    "Je n’ai jamais embrassé deux personnes le même soir",
    "Je n’ai jamais joué à boire pour perdre",
    "Je n’ai jamais eu un rendez-vous Tinder qui a mal tourné",
    "Je n’ai jamais pris une douche avec quelqu’un d’autre que moi",
    "Je n’ai jamais essayé le cunnilingus",
    "Je n’ai jamais été surpris en train de regarder du porno",
    "Je n’ai jamais envoyé de message coquin par erreur",
    "Je n’ai jamais fait de danse sexy pour quelqu’un",
    "Je n’ai jamais eu de flashback embarrassant après l’alcool",
    "Je n’ai jamais embrassé quelqu’un que je n’aimais pas",
    "Je n’ai jamais fait semblant d’être ivre",
    "Je n’ai jamais fait un baiser français",
    "Je n’ai jamais embrassé un inconnu",
    "Je n’ai jamais dragué quelqu’un en soirée",
    "Je n’ai jamais été à une soirée à thème sexy",
    "Je n’ai jamais essayé le bondage",
    "Je n’ai jamais fait un pari osé avec des amis",
    "Je n’ai jamais embrassé quelqu’un pour me venger",
    "Je n’ai jamais été collé à quelqu’un sur un canapé",
    "Je n’ai jamais bu un verre cul-sec",
    "Je n’ai jamais couché avec quelqu’un que je venais de rencontrer",
    "Je n’ai jamais été dans un jacuzzi avec plusieurs personnes",
    "Je n’ai jamais touché le sexe de quelqu’un",
    "Je n’ai jamais reçu un message sexy inattendu",
    "Je n’ai jamais eu un fantasme étrange",
    "Je n’ai jamais essayé de séduire quelqu’un en ligne",
    "Je n’ai jamais eu une aventure d’un soir en vacances",
    "Je n’ai jamais été surpris à me masturber",
    "Je n’ai jamais embrassé quelqu’un en public",
    "Je n’ai jamais pris une photo coquine de moi",
    "Je n’ai jamais participé à un strip-poker",
    "Je n’ai jamais bu un verre en cachette",
    "Je n’ai jamais eu un rendez-vous arrangé par un ami",
    "Je n’ai jamais fait l’amour dans un endroit interdit",
    "Je n’ai jamais essayé le body shot",
    "Je n’ai jamais couché avec quelqu’un de célébrité",
    "Je n’ai jamais été dans un bar pour célibataires",
    "Je n’ai jamais embrassé quelqu’un sous la pluie",
    "Je n’ai jamais touché quelqu’un que je devais ignorer",
    "Je n’ai jamais menti sur mon âge pour séduire",
    "Je n’ai jamais été saoul au point d’oublier mon nom",
    "Je n’ai jamais fait l’amour debout",
    "Je n’ai jamais été surpris en train de faire des choses bêtes en soirée",
    "Je n’ai jamais bu un mélange étrange d’alcool",
    "Je n’ai jamais embrassé quelqu’un de plus vieux",
    "Je n’ai jamais été dans un bar gay/lesbien sans être de la communauté",
    "Je n’ai jamais essayé le sexe oral sur quelqu’un",
    "Je n’ai jamais fait un pari coquin",
    "Je n’ai jamais eu de rencard arrangé par un ami",
    "Je n’ai jamais dansé de façon suggestive pour attirer quelqu’un",
    "Je n’ai jamais eu un orgasme seul après une soirée",
    "Je n’ai jamais flirté avec quelqu’un marié",
    "Je n’ai jamais fait semblant de connaître quelqu’un pour séduire",
    "Je n’ai jamais bu un shot que je regrettais",
    "Je n’ai jamais été accro à un jeu coquin en ligne",
    "Je n’ai jamais embrassé un ami proche",
    "Je n’ai jamais eu une relation interdite",
    "Je n’ai jamais été dans une situation embarrassante avec de l’alcool",
    "Je n’ai jamais eu des pensées sexuelles dans un lieu public",
    "Je n’ai jamais fait l’amour en plein air",
    "Je n’ai jamais embrassé quelqu’un pour de l’argent",
    "Je n’ai jamais essayé de séduire un collègue",
    "Je n’ai jamais pris une photo embarrassante en soirée",
    "Je n’ai jamais été à un enterrement de vie de jeune fille/garçon coquin",
    "Je n’ai jamais menti sur ma vie sexuelle",
    "Je n’ai jamais couché avec quelqu’un dans une piscine",
    "Je n’ai jamais bu un cocktail bizarre pour impressionner",
    "Je n’ai jamais été dans un club privé sexy",
    "Je n’ai jamais eu une aventure avec un ami d’un ami",
    "Je n’ai jamais eu de fantasme sur un prof",
    "Je n’ai jamais flirté avec plusieurs personnes en même temps",
    "Je n’ai jamais embrassé quelqu’un sur un coup de tête",
    "Je n’ai jamais fait l’amour sur un canapé",
    "Je n’ai jamais été surpris en train de danser sexy",
    "Je n’ai jamais touché les seins de quelqu’un",
    "Je n’ai jamais eu un pari stupide en soirée",
    "Je n’ai jamais été dans un sauna mixte",
    "Je n’ai jamais bu pour oublier un moment gênant",
    "Je n’ai jamais fait un strip devant quelqu’un",
    "Je n’ai jamais fait semblant d’aimer quelqu’un pour obtenir quelque chose",
    "Je n’ai jamais été attiré par quelqu’un de l’autre côté de la barrière",
    "Je n’ai jamais embrassé quelqu’un en boîte",
    "Je n’ai jamais fait un pari osé avec un inconnu",
    "Je n’ai jamais flirté avec un inconnu en soirée",
    "Je n’ai jamais essayé de séduire quelqu’un d’impossible",
    "Je n’ai jamais eu un plan à trois",
    "Je n’ai jamais fait une blague sexuelle qui a mal tourné",
    "Je n’ai jamais bu un verre que je ne pouvais pas finir",
    "Je n’ai jamais été pris en flagrant délit de drague",
    "Je n’ai jamais embrassé quelqu’un pour impressionner",
    "Je n’ai jamais fait un pari embarrassant avec des amis",
    "Je n’ai jamais été tenté de coucher avec un ami",
    "Je n’ai jamais été dans un endroit sexy par hasard",
    "Je n’ai jamais tenté d’embrasser quelqu’un pour s’amuser",
    "Je n’ai jamais eu un rendez-vous bizarre après l’alcool",
    "Je n’ai jamais été dans un bar étrange",
    "Je n’ai jamais touché quelqu’un pour rire",
    "Je n’ai jamais eu des pensées bizarres en soirée",
    "Je n’ai jamais fait un pari fou en soirée",
    "Je n’ai jamais été embarrassé par mes actions après l’alcool",
    "Je n’ai jamais flirté en ligne avec un inconnu",
    "Je n’ai jamais envoyé un message coquin par erreur",
    "Je n’ai jamais tenté de séduire quelqu’un en public",
    "Je n’ai jamais eu des pensées coquines dans un lieu public",
    "Je n’ai jamais embrassé quelqu’un de manière inappropriée",
    "Je n’ai jamais été surpris en train de faire l’idiot avec de l’alcool",
    "Je n’ai jamais bu un verre trop fort pour mon âge",
    "Je n’ai jamais tenté une approche risquée pour séduire",
    "Je n’ai jamais été à un événement coquin",
    "Je n’ai jamais mangé un insecte entier",
    "Je n’ai jamais dormi dehors sous la pluie",
    "Je n’ai jamais fait du yoga dans un ascenseur",
    "Je n’ai jamais sauté dans une fontaine publique",
    "Je n’ai jamais parlé à un inconnu pendant une panne d’ascenseur",
    "Je n’ai jamais goûté une glace au wasabi",
    "Je n’ai jamais essayé de chanter sous la douche avec un micro imaginaire",
    "Je n’ai jamais marché pieds nus sur des cailloux",
    "Je n’ai jamais fait semblant de connaître quelqu’un pour impressionner",
    "Je n’ai jamais pris un selfie avec un animal sauvage",
    "Je n’ai jamais confondu du sel et du sucre en cuisinant",
    "Je n’ai jamais parlé à mon animal comme à une personne",
    "Je n’ai jamais eu peur d’un objet inanimé",
    "Je n’ai jamais inventé une excuse complètement bidon pour sécher un cours",
    "Je n’ai jamais essayé de jongler avec des fruits",
    "Je n’ai jamais fait semblant de téléphoner pour éviter quelqu’un",
    "Je n’ai jamais mangé quelque chose directement tombé par terre",
    "Je n’ai jamais couru sous la pluie juste pour le fun",
    "Je n’ai jamais pris un objet pour un autre par erreur",
    "Je n’ai jamais chanté dans un lieu public en pensant être seul",
    "Je n’ai jamais imité un animal pour faire rire",
    "Je n’ai jamais utilisé une brosse à dents pour autre chose que les dents",
    "Je n’ai jamais parlé à une plante",
    "Je n’ai jamais dansé dans un supermarché",
    "Je n’ai jamais regardé un film d’horreur seul dans le noir",
    "Je n’ai jamais goûté une boisson bizarre juste pour le défi",
    "Je n’ai jamais essayé de toucher un nuage",
    "Je n’ai jamais marché dans une flaque et éclaboussé quelqu’un",
    "Je n’ai jamais pris une photo ridicule pour Snapchat/Instagram",
    "Je n’ai jamais fait semblant d’être malade pour rester au lit",
    "Je n’ai jamais fait un dessin ridicule sur le visage de quelqu’un qui dort",
    "Je n’ai jamais fait du roller dans un lieu interdit",
    "Je n’ai jamais dormi dans un lieu insolite",
    "Je n’ai jamais fait du karaoké seul chez moi",
    "Je n’ai jamais parlé dans une langue inventée en public",
    "Je n’ai jamais mangé un aliment étrange juste pour parier",
    "Je n’ai jamais fait semblant de comprendre quelque chose que je ne comprenais pas",
    "Je n’ai jamais essayé de voler quelque chose de ridicule",
    "Je n’ai jamais sauté sur un trampoline en public",
    "Je n’ai jamais fait semblant d’être un fantôme",
    "Je n’ai jamais pris une photo en sautant pour faire genre je vole",
    "Je n’ai jamais imité un professeur en cours",
    "Je n’ai jamais joué avec un distributeur automatique",
    "Je n’ai jamais mis des chaussettes dépareillées exprès",
    "Je n’ai jamais fait un concours de grimaces devant un miroir",
    "Je n’ai jamais inventé une danse ridicule",
    "Je n’ai jamais parlé à un inconnu en prétendant que je le connaissais",
    "Je n’ai jamais pris un animal pour un autre",
    "Je n’ai jamais essayé de respirer sous l’eau dans une piscine",
    "Je n’ai jamais dessiné sur un trottoir avec de la craie",
    "Je n’ai jamais essayé de faire du surf sur autre chose qu’une planche",
    "Je n’ai jamais imité un bruit d’animal pour embêter quelqu’un",
    "Je n’ai jamais tenté de marcher en équilibre sur un muret",
    "Je n’ai jamais fait semblant de téléporter quelque chose",
    "Je n’ai jamais testé un gadget inutile mais marrant",
    "Je n’ai jamais fait un concours de celui qui mange le plus vite",
    "Je n’ai jamais tenté de grimper un arbre trop haut",
    "Je n’ai jamais fait semblant d’être un robot",
    "Je n’ai jamais mis un objet dans un frigo par erreur",
    "Je n’ai jamais joué avec une fontaine publique",
    "Je n’ai jamais porté des vêtements à l’envers toute la journée",
    "Je n’ai jamais essayé de deviner ce que quelqu’un pense juste en le regardant",
    "Je n’ai jamais mis de glaçons dans un bol de céréales",
    "Je n’ai jamais imité le son d’un instrument avec ma bouche",
    "Je n’ai jamais couru dans un escalier en pensant que c’était drôle",
    "Je n’ai jamais fait un concours de grimaces dans un ascenseur",
    "Je n’ai jamais mangé un aliment expiré pour le fun",
    "Je n’ai jamais fait semblant d’être un super-héros",
    "Je n’ai jamais joué avec une ombre pour créer des formes bizarres",
    "Je n’ai jamais mis des lunettes de soleil la nuit pour rigoler",
    "Je n’ai jamais pris un objet pour un autre en public",
    "Je n’ai jamais essayé de marcher comme un pingouin",
    "Je n’ai jamais fait semblant d’être un chat",
    "Je n’ai jamais fait un château avec des objets insolites",
    "Je n’ai jamais pris une photo dans une position ridicule",
    "Je n’ai jamais parlé avec un accent bizarre juste pour rigoler",
    "Je n’ai jamais mis mes vêtements à l’envers pour voir la réaction des autres",
    "Je n’ai jamais fait un parcours d’obstacles avec des meubles",
    "Je n’ai jamais fait un selfie avec une statue",
    "Je n’ai jamais essayé de grimper une clôture juste pour le défi",
    "Je n’ai jamais joué avec un ballon dans un lieu public interdit",
    "Je n’ai jamais imité une célébrité dans un lieu public",
    "Je n’ai jamais essayé de marcher sur un mur (par jeu, évidemment)",
    "Je n’ai jamais fait semblant de tomber pour rigoler",
    "Je n’ai jamais mis un objet ridicule dans un sac d’école/courses",
    "Je n’ai jamais fait semblant de lire un livre pour paraître intelligent",
    "Je n’ai jamais chanté dans un bus ou un métro",
    "Je n’ai jamais mis mes chaussures à l’envers pour voir si quelqu’un le remarque",
    "Je n’ai jamais fait semblant de me perdre pour embêter quelqu’un",
    "Je n’ai jamais marché en arrière dans un lieu public",
    "Je n’ai jamais essayé de faire un tour sur un fauteuil roulant",
    "Je n’ai jamais inventé une expression pour faire rire",
    "Je n’ai jamais essayé de faire du skate sur un objet improvisé",
    "Je n’ai jamais mis du sel dans le café de quelqu’un (gentiment, hein)",
    "Je n’ai jamais tenté de faire un saut depuis un meuble",
    "Je n’ai jamais crié pour surprendre quelqu’un",
    "Je n’ai jamais pris un selfie avec un masque bizarre",
    "Je n’ai jamais essayé de parler comme un robot",
    "Je n’ai jamais mis un objet étrange dans une poche d’un ami",
    "Je n’ai jamais joué à un jeu ridicule en public",
    "Je n’ai jamais inventé un surnom ridicule pour quelqu’un",
    "Je n’ai jamais fait semblant de chasser quelque chose invisible",
    "Je n’ai jamais mis du ketchup ou autre sur un aliment insolite",
    "Je n’ai jamais fait semblant de savoir danser un style que je ne connais pas",
    "Je n’ai jamais imité le bruit d’un moteur ou d’une machine en public",
    "Je n’ai jamais fait un lancer d’objet ridicule pour le fun",
    "Je n’ai jamais essayé de marcher comme un mannequin",
    "Je n’ai jamais fait semblant de connaître une chanson que je ne connais pas",
    "Je n’ai jamais essayé de manger un aliment sans les mains",
    "Je n’ai jamais inventé un mot juste pour rigoler",
    "Je n’ai jamais couru dans un lieu public en faisant semblant d’être poursuivi",
    "Je n’ai jamais fait un selfie avec un reflet bizarre",
    "Je n’ai jamais essayé de grimper sur une structure en public juste pour tester",
    "Je n’ai jamais chanté à tue-tête en voiture",
    "Je n’ai jamais joué avec des bulles de savon en public",
    "Je n’ai jamais fait semblant de parler à un fantôme",
    "Je n’ai jamais essayé de marcher sur les mains",
    "Je n’ai jamais fait une blague visuelle pour surprendre quelqu’un",
    "Je n’ai jamais mis un objet insolite dans le frigo d’un ami",
    "Je n’ai jamais dansé sur une table (mini scène, évidemment)",
    "Je n’ai jamais fait un selfie en faisant une grimace extrême",
    "Je n’ai jamais mis mes lunettes sur le front par erreur",
    "Je n’ai jamais imité un bruit d’animal dans un lieu public",
    "Je n’ai jamais essayé de faire un tour sur un skate improvisé",
    "Je n’ai jamais parlé dans une langue inventée pour embêter quelqu’un",
    "Je n’ai jamais mis mes vêtements de façon absurde pour rigoler",
    "Je n’ai jamais fait semblant de tomber dans un lieu public",
    "Je n’ai jamais tenté de grimper un arbre pour le fun",
    "Je n’ai jamais fait semblant d’être un personnage de dessin animé",
    "Je n’ai jamais mis un objet dans un endroit improbable pour surprendre",
    "Je n’ai jamais fait une danse ridicule juste pour le fun",
    "Je n’ai jamais joué à un jeu absurde en public",
    "Je n’ai jamais inventé une excuse folle pour partir en avance",
    "Je n’ai jamais essayé de marcher comme une marionnette",
    "Je n’ai jamais fait un selfie dans une position insolite",
    "Je n’ai jamais fait semblant de parler à un animal en public",
    "Je n’ai jamais mis mes chaussures à l’envers pour rigoler",
    "Je n’ai jamais fait un mini spectacle ridicule pour impressionner quelqu’un",
    "Je n’ai jamais chanté une chanson inventée en public",
    "Je n’ai jamais fait un parcours du combattant avec des objets du quotidien",
    "Je n’ai jamais mis un aliment étrange sur ma tête pour une photo",
    "Je n’ai jamais imité un bruit de machine ou de moteur pour rigoler",
    "Je n’ai jamais essayé de marcher comme un ninja dans la rue",
    "Je n’ai jamais mis des accessoires ridicules pour faire rire",
    "Je n’ai jamais fait un selfie en sautant le plus haut possible",
    "Je n’ai jamais mis un objet insolite dans une chaussure",
    "Je n’ai jamais dansé avec un objet improbable comme partenaire",
    "Je n’ai jamais fait semblant de jouer d’un instrument invisible",
    "Je n’ai jamais crié pour surprendre un ami juste pour rire",
    "Je n’ai jamais tenté de faire un saut depuis un petit muret",
    "Je n’ai jamais fait semblant d’être un super-héros dans la rue",
    "Je n’ai jamais mis un objet ridicule sur la tête juste pour rire",
    "Je n’ai jamais parlé dans un micro invisible pour un show improvisé",
    "Je n’ai jamais imité un bruit de nourriture en public",
    "Je n’ai jamais pris une pose ridicule pour une photo",
    "Je n’ai jamais marché comme un robot dans un lieu public",
    "Je n’ai jamais mis des vêtements dépareillés pour faire rire",
    "Je n’ai jamais mangé un plat en entier sans le goûter avant.",
    "Je n’ai jamais dansé tout seul dans ma chambre en pensant que personne ne me voyait.",
    "Je n’ai jamais oublié le nom de quelqu’un immédiatement après l’avoir rencontré.",
    "Je n’ai jamais ri au mauvais moment et tout le monde m’a regardé bizarrement.",
    "Je n’ai jamais fait semblant de comprendre un film alors que je ne comprenais rien.",
    "Je n’ai jamais envoyé un message à la mauvaise personne et regretté instantanément.",
    "Je n’ai jamais chanté sous la douche comme si j’étais une rockstar.",
    "Je n’ai jamais pris une photo embarrassante que je voulais supprimer mais que j’ai gardée.",
    "Je n’ai jamais essayé de parler une langue étrangère et fait n’importe quoi.",
    "Je n’ai jamais oublié un anniversaire important et paniqué après.",
    "Je n’ai jamais essayé de cuisiner quelque chose et totalement raté.",
    "Je n’ai jamais dansé en public et regretté juste après.",
    "Je n’ai jamais imité quelqu’un pour faire rire et que ça se retourne contre moi.",
    "Je n’ai jamais dit 'je vais bien' alors que j’étais clairement pas bien.",
    "Je n’ai jamais confondu quelqu’un avec quelqu’un d’autre et dit son nom par erreur.",
    "Je n’ai jamais ri tellement fort que j’ai pleuré.",
    "Je n’ai jamais fait semblant d’être occupé pour éviter quelqu’un.",
    "Je n’ai jamais pris un selfie ridicule juste pour m’amuser.",
    "Je n’ai jamais oublié mes clés et paniqué comme si c’était la fin du monde.",
    "Je n’ai jamais fait une blague qui a mal tourné.",
    "Je n’ai jamais marché dans un poteau en regardant mon téléphone.",
    "Je n’ai jamais envoyé un message embarrassant à mon crush.",
    "Je n’ai jamais oublié où j’avais mis mon téléphone juste devant moi.",
    "Je n’ai jamais mis mes vêtements à l’envers sans m’en rendre compte.",
    "Je n’ai jamais chanté une chanson entière en public sans m’en rendre compte.",
    "Je n’ai jamais essayé de prendre une pose cool et échoué complètement.",
    "Je n’ai jamais confondu le sel avec le sucre en cuisinant.",
    "Je n’ai jamais éclaté de rire dans un moment sérieux.",
    "Je n’ai jamais fait une imitation ridicule juste pour rire.",
    "Je n’ai jamais oublié d’éteindre un appareil électrique avant de partir.",
    "Je n’ai jamais mis mes chaussures à l’envers.",
    "Je n’ai jamais parlé à mon animal comme s’il comprenait tout.",
    "Je n’ai jamais oublié le nom de ma propre rue en la cherchant.",
    "Je n’ai jamais mis du dentifrice au mauvais endroit par erreur.",
    "Je n’ai jamais essayé de frimer avec un truc que je ne maîtrisais pas.",
    "Je n’ai jamais confondu des mots et créé des phrases absurdes.",
    "Je n’ai jamais essayé de chanter mais totalement faux.",
    "Je n’ai jamais porté des vêtements dépareillés par accident.",
    "Je n’ai jamais tenté un pas de danse ridicule juste pour rigoler.",
    "Je n’ai jamais dit quelque chose de très sérieux par erreur.",
    "Je n’ai jamais essayé de prendre un selfie parfait et échoué.",
    "Je n’ai jamais fait tomber quelque chose et essayé de faire comme si rien ne s’était passé.",
    "Je n’ai jamais imité un accent complètement faux.",
    "Je n’ai jamais ri d’une blague avant de la comprendre.",
    "Je n’ai jamais fait semblant d’être occupé pour éviter une corvée.",
    "Je n’ai jamais eu un fou rire au mauvais endroit.",
    "Je n’ai jamais fait un gâteau raté mais l’ai mangé quand même.",
    "Je n’ai jamais pris un objet pour quelque chose d’autre par erreur.",
    "Je n’ai jamais oublié de mettre du sel dans un plat.",
    "Je n’ai jamais dansé comme un fou en écoutant de la musique.",
    "Je n’ai jamais fait une grimace drôle et vu quelqu’un la prendre au sérieux.",
    "Je n’ai jamais rigolé dans une réunion sérieuse.",
    "Je n’ai jamais porté un vêtement à l’envers toute la journée.",
    "Je n’ai jamais fait tomber mon téléphone dans un endroit improbable.",
    "Je n’ai jamais fait une blague trop obscure que personne n’a comprise.",
    "Je n’ai jamais chanté faux en public mais fait comme si de rien n’était.",
    "Je n’ai jamais essayé de faire un tour de magie et raté complètement.",
    "Je n’ai jamais confondu gauche et droite en public.",
    "Je n’ai jamais parlé à un objet comme à une personne.",
    "Je n’ai jamais mis une chaussette différente de l’autre exprès ou pas.",
    "Je n’ai jamais fait semblant de comprendre un cours en hochant la tête.",
    "Je n’ai jamais rigolé d’un jeu de mots nul mais drôle.",
    "Je n’ai jamais oublié mon mot de passe et paniqué.",
    "Je n’ai jamais essayé un filtre ridicule sur une photo.",
    "Je n’ai jamais confondu une boisson avec une autre.",
    "Je n’ai jamais dansé en pyjama devant tout le monde.",
    "Je n’ai jamais dit quelque chose et regretté immédiatement.",
    "Je n’ai jamais mis trop de sel et ruiné un plat.",
    "Je n’ai jamais tenté de jongler et tout fait tomber.",
    "Je n’ai jamais fait un selfie avec une grimace improbable.",
    "Je n’ai jamais pris une photo compromettante par accident.",
    "Je n’ai jamais confondu le sel et le sucre dans une recette.",
    "Je n’ai jamais imité un animal pour faire rire quelqu’un.",
    "Je n’ai jamais essayé de chanter et craché par accident.",
    "Je n’ai jamais mis mon vêtement à l’envers toute la journée sans m’en rendre compte.",
    "Je n’ai jamais envoyé un message à la mauvaise personne par erreur.",
    "Je n’ai jamais essayé de faire un saut ridicule et tombé.",
    "Je n’ai jamais pris quelque chose de travers et paniqué.",
    "Je n’ai jamais éclaté de rire en regardant un film triste.",
    "Je n’ai jamais fait un compliment maladroit.",
    "Je n’ai jamais oublié le nom de quelqu’un dans une conversation.",
    "Je n’ai jamais confondu un ami avec un inconnu.",
    "Je n’ai jamais imité une célébrité de manière ridicule.",
    "Je n’ai jamais fait semblant de savoir quelque chose que je ne savais pas.",
    "Je n’ai jamais chanté faux et continué comme si de rien n’était.",
    "Je n’ai jamais dansé bêtement pour faire rire quelqu’un.",
    "Je n’ai jamais essayé de faire du sport et échoué complètement.",
    "Je n’ai jamais rigolé tellement fort que j’ai fait tomber quelque chose.",
    "Je n’ai jamais pris une mauvaise direction et paniqué.",
    "Je n’ai jamais fait semblant de travailler alors que je procrastinais.",
    "Je n’ai jamais fait une blague nulle mais drôle quand même.",
    "Je n’ai jamais porté un vêtement démodé par erreur.",
    "Je n’ai jamais oublié un rendez-vous important.",
    "Je n’ai jamais tenté un jeu vidéo et perdu lamentablement.",
    "Je n’ai jamais confondu deux plats et mangé quelque chose de bizarre.",
    "Je n’ai jamais essayé un filtre ridicule et ri toute la journée.",
    "Je n’ai jamais parlé tout seul comme un fou.",
    "Je n’ai jamais oublié de répondre à un message important.",
    "Je n’ai jamais fait semblant de comprendre un film compliqué.",
    "Je n’ai jamais essayé de chanter une chanson compliquée et échoué.",
    "Je n’ai jamais ri à une blague que je ne comprenais pas.",
    "Je n’ai jamais pris une photo drôle et partagé sans réfléchir.",
    "Je n’ai jamais confondu quelqu’un avec un personnage de film.",
    "Je n’ai jamais mis mes chaussures à l’envers en public.",
    "Je n’ai jamais essayé un tour de magie et échoué complètement.",
    "Je n’ai jamais dansé sur un rythme qui n’existait pas.",
    "Je n’ai jamais fait tomber quelque chose et prétendu que c’était rien.",
    "Je n’ai jamais parlé à un animal comme s’il me répondait.",
    "Je n’ai jamais confondu un objet avec un autre et paniqué.",
    "Je n’ai jamais fait une grimace ridicule pour amuser quelqu’un.",
    "Je n’ai jamais chanté sous la douche avec trop de conviction.",
    "Je n’ai jamais rigolé au mauvais moment devant tout le monde.",
    "Je n’ai jamais oublié où j’avais posé quelque chose d’important.",
    "Je n’ai jamais fait une blague qui a échoué complètement.",
    "Je n’ai jamais pris un selfie bizarre juste pour rigoler.",
    "Je n’ai jamais tenté de danser comme un pro et échoué.",
    "Je n’ai jamais confondu des mots et raconté une histoire absurde.",
    "Je n’ai jamais rigolé de manière incontrôlable dans un endroit sérieux.",
    "Je n’ai jamais fait tomber mon téléphone dans un endroit improbable.",
    "Je n’ai jamais fait semblant de savoir quelque chose alors que non.",
    "Je n’ai jamais chanté une chanson que je ne connaissais pas en public.",
    "Je n’ai jamais porté des chaussettes différentes volontairement.",
    "Je n’ai jamais fait une blague trop subtile que personne n’a comprise.",
    "Je n’ai jamais confondu un plat avec un autre et mangé n’importe quoi.",
    "Je n’ai jamais ri tellement fort que j’ai fait tomber un objet.",
    "Je n’ai jamais envoyé un message à la mauvaise personne et réalisé trop tard.",
    "Je n’ai jamais appelé quelqu’un par le mauvais prénom devant tout le monde.",
    "Je n’ai jamais rigolé au mauvais moment en réunion.",
    "Je n’ai jamais oublié de mettre du déodorant et senti mauvais toute la journée.",
    "Je n’ai jamais renversé ma boisson sur quelqu’un par accident.",
    "Je n’ai jamais marché dans une flaque en pensant qu’elle était sèche.",
    "Je n’ai jamais chanté faux en public en croyant être parfait.",
    "Je n’ai jamais dit quelque chose de très intime devant des inconnus.",
    "Je n’ai jamais envoyé un texto compromettant à mon crush par erreur.",
    "Je n’ai jamais oublié un mot important dans un discours et paniqué.",
    "Je n’ai jamais éternué en pleine réunion silencieuse.",
    "Je n’ai jamais oublié de mettre un pantalon complet avant de sortir.",
    "Je n’ai jamais glissé dans un lieu public et essayé de faire semblant.",
    "Je n’ai jamais parlé à mon prof comme si c’était mon ami et regretté.",
    "Je n’ai jamais confondu quelqu’un avec un autre et commencé une conversation bizarre.",
    "Je n’ai jamais ronflé devant quelqu’un par accident.",
    "Je n’ai jamais oublié d’enlever quelque chose de ridicule de mes cheveux.",
    "Je n’ai jamais fait tomber un objet bruyant dans un endroit silencieux.",
    "Je n’ai jamais raconté un secret à la mauvaise personne.",
    "Je n’ai jamais confondu un moment sérieux avec un moment fun.",
    "Je n’ai jamais envoyé un message embarrassant au groupe entier.",
    "Je n’ai jamais pris un appel embarrassant en public.",
    "Je n’ai jamais oublié de fermer un pantalon ou une fermeture éclair.",
    "Je n’ai jamais éternué sur quelqu’un par accident.",
    "Je n’ai jamais glissé sur une peau de banane imaginaire (ou presque).",
    "Je n’ai jamais fait tomber mon téléphone dans les toilettes.",
    "Je n’ai jamais rigolé en entendant quelque chose de triste et paniqué.",
    "Je n’ai jamais oublié de retirer quelque chose de mes dents avant de parler.",
    "Je n’ai jamais chanté avec la bouche pleine.",
    "Je n’ai jamais fait tomber un plat entier devant des invités.",
    "Je n’ai jamais confondu un mot et dit quelque chose de totalement bizarre.",
    "Je n’ai jamais porté une tenue ridicule en pensant que ça allait passer.",
    "Je n’ai jamais crié sur quelqu’un par erreur et paniqué.",
    "Je n’ai jamais fait un bruit gênant en public sans pouvoir l’arrêter.",
    "Je n’ai jamais dit ‘je t’aime’ par erreur à la mauvaise personne.",
    "Je n’ai jamais oublié de couper son micro en visioconférence et dit n’importe quoi.",
    "Je n’ai jamais marché sur quelqu’un par accident en public.",
    "Je n’ai jamais rigolé pendant un enterrement ou un moment triste.",
    "Je n’ai jamais confondu une porte avec une autre et paniqué.",
    "Je n’ai jamais raconté une histoire embarrassante sur moi-même par erreur.",
    "Je n’ai jamais oublié d’enlever un autocollant ridicule sur un vêtement.",
    "Je n’ai jamais envoyé un GIF compromettant au mauvais destinataire.",
    "Je n’ai jamais confondu les touches du clavier et envoyé un mot bizarre à quelqu’un.",
    "Je n’ai jamais dit quelque chose de trop intime en réunion Zoom.",
    "Je n’ai jamais essayé de faire une blague et tout le monde m’a regardé bizarrement.",
    "Je n’ai jamais rigolé tellement fort que j’ai renversé ma boisson.",
    "Je n’ai jamais oublié de fermer un tiroir et cogné quelqu’un.",
    "Je n’ai jamais mis deux chaussettes différentes et fait semblant que c’était volontaire.",
    "Je n’ai jamais crié ‘oui’ ou ‘non’ au mauvais moment.",
    "Je n’ai jamais confondu une date et paniqué en arrivant en retard.",
    "Je n’ai jamais renversé de la nourriture sur quelqu’un par accident.",
    "Je n’ai jamais oublié de verrouiller la porte et quelqu’un est entré.",
    "Je n’ai jamais éternué en pleine photo de groupe.",
    "Je n’ai jamais raconté un secret en public sans m’en rendre compte.",
    "Je n’ai jamais marché dans un endroit interdit et paniqué.",
    "Je n’ai jamais glissé sur une marche en pensant que c’était plat.",
    "Je n’ai jamais dit quelque chose d’intime devant un groupe de personnes.",
    "Je n’ai jamais confondu une rue et marché dans le mauvais quartier.",
    "Je n’ai jamais fait tomber un objet très bruyant dans une bibliothèque.",
    "Je n’ai jamais oublié d’enlever un sticker sur mes lunettes ou mon téléphone.",
    "Je n’ai jamais essayé d’ouvrir une porte et réalisé que c’était la mauvaise.",
    "Je n’ai jamais dit un mot embarrassant devant mon crush.",
    "Je n’ai jamais rigolé à une blague que je n’ai pas comprise et paniqué.",
    "Je n’ai jamais confondu un mot de politesse et dit quelque chose de ridicule.",
    "Je n’ai jamais crié accidentellement en public.",
    "Je n’ai jamais renversé de l’eau sur moi en essayant de boire discrètement.",
    "Je n’ai jamais oublié d’éteindre mon micro et dit quelque chose de gênant.",
    "Je n’ai jamais envoyé un message à mon ex par erreur.",
    "Je n’ai jamais marché sur une pelouse interdite et été grondé.",
    "Je n’ai jamais rigolé au mauvais moment en classe ou réunion.",
    "Je n’ai jamais oublié un objet important chez quelqu’un et paniqué.",
    "Je n’ai jamais confondu un cadeau et donné quelque chose de ridicule.",
    "Je n’ai jamais chanté une chanson embarrassante dans la rue.",
    "Je n’ai jamais fait tomber un objet sur quelqu’un sans le vouloir.",
    "Je n’ai jamais confondu deux personnes et commencé à parler de manière bizarre.",
    "Je n’ai jamais oublié un mot important dans une présentation.",
    "Je n’ai jamais mis une chaussette sale sans m’en rendre compte.",
    "Je n’ai jamais parlé trop fort dans un lieu silencieux.",
    "Je n’ai jamais oublié d’éteindre la caméra et fait un geste ridicule.",
    "Je n’ai jamais renversé du café sur un document important.",
    "Je n’ai jamais dit un mot embarrassant en réunion Zoom.",
    "Je n’ai jamais marché dans un endroit glissant et paniqué.",
    "Je n’ai jamais gloussé au mauvais moment devant tout le monde.",
    "Je n’ai jamais confondu un nom et appelé quelqu’un par erreur.",
    "Je n’ai jamais fait tomber quelque chose et essayé de prétendre que c’était normal.",
    "Je n’ai jamais mis un vêtement troué sans m’en rendre compte.",
    "Je n’ai jamais oublié de répondre à un message urgent et paniqué.",
    "Je n’ai jamais chanté une chanson ridicule devant des amis.",
    "Je n’ai jamais parlé à un inconnu comme si je le connaissais.",
    "Je n’ai jamais renversé de nourriture sur mes vêtements et paniqué.",
    "Je n’ai jamais fait une blague qui a mal tourné en public.",
    "Je n’ai jamais glissé sur un sol mouillé et essayé de paraître cool.",
    "Je n’ai jamais confondu un objet avec un autre en public.",
    "Je n’ai jamais oublié de fermer un tiroir et cogné quelqu’un.",
    "Je n’ai jamais dit quelque chose d’intime devant des inconnus.",
    "Je n’ai jamais rigolé à une blague trop tard et paniqué.",
    "Je n’ai jamais confondu les touches du clavier et envoyé un message bizarre.",
    "Je n’ai jamais chanté faux en public et prétendu que c’était normal.",
    "Je n’ai jamais renversé un verre sur quelqu’un sans faire exprès.",
    "Je n’ai jamais marché dans une flaque en pensant que c’était sec."
  ];
