// data.js
const db = {
    normal: [
    "C'est une 10, mais elle vole tes frites alors qu'elle a dit qu'elle n'avait pas faim.",
    "C'est une 3 mais elle est super riche.",
    "C'est un 8 mais il a un super chien.",
    "C'est un 6 mais elle fait du bénévolat le week-end.",
    "C'est un 9 mais il cuisine comme un chef.",
    "C'est une 4 mais elle a une collection impressionnante de timbres.",
    "C'est un 7 mais il joue du piano comme un virtuose.",
    "C'est une 5 mais elle parle cinq langues couramment.",
    "C'est un 10 mais il ronfle comme un tracteur.",
    "C'est une 2 mais elle possède une île privée.",
    "C'est un 6 mais il sait réparer tout ce qui est cassé.",
    "C'est une 9 mais elle déteste les fleurs.",
    "C'est un 4 mais il est champion d'échecs.",
    "C'est une 8 mais elle mange des céréales au dîner.",
    "C'est un 3 mais il a un jet privé.",
    "C'est une 7 mais elle court le marathon en moins de trois heures.",
    "C'est un 10 mais il a peur des araignées.",
    "C'est une 5 mais elle chante comme une professionnelle.",
    "C'est un 8 mais il pleure devant les films Disney.",
    "C'est une 4 mais elle est ceinture noire de judo.",
    "C'est un 9 mais il oublie toujours les anniversaires.",
    "C'est une 6 mais elle fait les meilleurs gâteaux du monde.",
    "C'est un 2 mais il est ami avec des célébrités.",
    "C'est une 10 mais elle parle toute seule.",
    "C'est un 7 mais il danse comme un pro.",
    "C'est une 3 mais elle a gagné trois fois au loto.",
    "C'est un 5 mais il dessine hyper bien.",
    "C'est une 9 mais elle déteste le chocolat.",
    "C'est un 10 mais il ne sait pas nager.",
    "C'est une 4 mais elle connaît toutes les capitales du monde.",
    "C'est un 8 mais il collectionne les figurines Pokémon.",
    "C'est une 6 mais elle sait faire du surf.",
    "C'est un 9 mais il regarde des séries pour ados.",
    "C'est une 5 mais elle est ultra gentille avec tout le monde.",
    "C'est un 7 mais il a escaladé le Mont Blanc.",
    "C'est une 10 mais elle est accro aux réseaux sociaux.",
    "C'est un 3 mais il possède une collection de voitures de luxe.",
    "C'est une 8 mais elle rit trop fort au cinéma.",
    "C'est un 6 mais il joue de la guitare comme un dieu.",
    "C'est une 4 mais elle a un doctorat en astrophysique.",
    "C'est un 10 mais il mange des chips au petit-déjeuner.",
    "C'est une 2 mais elle est héritière d’une grande fortune.",
    "C'est un 9 mais il a peur des hauteurs.",
    "C'est une 7 mais elle fait du bénévolat dans un refuge animal.",
    "C'est un 5 mais il parle aux plantes.",
    "C'est une 10 mais elle ne supporte pas le silence.",
    "C'est un 8 mais il dort avec une veilleuse.",
    "C'est une 6 mais elle sait programmer en dix langages.",
    "C'est un 4 mais il est champion de bowling.",
    "C'est une 9 mais elle déteste voyager.",
    "C'est un 10 mais il est nul en orientation.",
    "C'est une 3 mais elle dirige une multinationale.",
    "C'est un 7 mais il fait des blagues nulles mais attachantes.",
    "C'est une 5 mais elle a sauvé trois personnes d’un incendie.",
    "C'est un 9 mais il chante faux sous la douche.",
    "C'est une 8 mais elle vole toujours la couette.",
    "C'est un 6 mais il connaît tous les films par cœur.",
    "C'est une 10 mais elle est toujours en retard.",
    "C'est un 2 mais il a inventé une appli à succès.",
    "C'est une 4 mais elle parle aux animaux et ils l’écoutent.",
    "C'est un 8 mais il a une collection de mugs ridicule.",
    "C'est une 7 mais elle sait faire du feu sans allumettes.",
    "C'est un 10 mais il déteste les câlins.",
    "C'est une 5 mais elle est ultra douée en maths.",
    "C'est un 9 mais il regarde des téléréalités toute la journée.",
    "C'est une 6 mais elle a adopté cinq chats.",
    "C'est un 3 mais il possède un château.",
    "C'est une 10 mais elle mange avec les mains.",
    "C'est un 7 mais il sait imiter n’importe quelle voix.",
    "C'est une 4 mais elle a couru l’ultra-trail du Mont-Blanc.",
    "C'est un 8 mais il a peur des clowns.",
    "C'est une 9 mais elle ne boit jamais de café.",
    "C'est un 5 mais il fait les meilleures pizzas maison.",
    "C'est une 10 mais elle parle pendant les films.",
    "C'est un 6 mais il est champion de jeux vidéo.",
    "C'est une 3 mais elle est pilote de Formule 1.",
    "C'est un 9 mais il collectionne les pierres.",
    "C'est une 7 mais elle sait tricoter des pulls magnifiques.",
    "C'est un 10 mais il est allergique aux chiens.",
    "C'est une 5 mais elle a un rire contagieux.",
    "C'est un 8 mais il dort 12 heures par nuit.",
    "C'est une 4 mais elle parle japonais couramment.",
    "C'est un 9 mais il déteste les épices.",
    "C'est une 6 mais elle fait du parapente tous les week-ends.",
    "C'est un 10 mais il ne sait pas cuisiner un œuf.",
    "C'est une 2 mais elle est la PDG d’une startup valorisée à un milliard.",
    "C'est un 7 mais il chante des chansons des années 80 tout le temps.",
    "C'est une 8 mais elle oublie les noms de tout le monde.",
    "C'est un 5 mais il a écrit un roman à succès.",
    "C'est une 10 mais elle déteste les chaussures.",
    "C'est un 9 mais il a peur des ascenseurs.",
    "C'est une 6 mais elle sait réparer un moteur.",
    "C'est un 4 mais il joue aux échecs au niveau grand maître.",
    "C'est une 3 mais elle a une fondation caritative.",
    "C'est un 8 mais il regarde des dessins animés le matin.",
    "C'est une 7 mais elle fait du yoga à 5h du matin.",
    "C'est un 10 mais il est nul en danse.",
    "C'est une 5 mais elle connaît toutes les constellations.",
    "C'est un 9 mais il mange toujours les mêmes plats.",
    "C'est une 4 mais elle a sauvé un refuge entier d’animaux.",
    "C'est un 6 mais il joue de trois instruments.",
    "C'est une 10 mais elle est accro au karaoké.",
    "C'est un 8 mais il collectionne les vieux journaux.",
    "C'est une 9 mais elle ne sait pas faire de vélo.",
    "C'est un 7 mais il fait des massages professionnels.",
    "C'est une 5 mais elle a un sens de l'humour incroyable.",
    "C'est un 3 mais il est propriétaire d'une équipe de foot.",
    "C'est une 10 mais elle déteste la plage.",
    "C'est un 6 mais il parle couramment le langage des signes.",
    "C'est une 8 mais elle est toujours en pyjama à la maison.",
    "C'est un 4 mais il a breveté une invention révolutionnaire.",
    "C'est une 9 mais elle a peur des chiens.",
    "C'est un 10 mais il ne supporte pas les légumes.",
    "C'est une 2 mais elle est championne olympique.",
    "C'est un 7 mais il sait faire des origamis complexes.",
    "C'est une 6 mais elle organise les meilleures soirées.",
    "C'est un 5 mais il a une mémoire photographique.",
    "C'est une 10 mais elle ronfle doucement.",
    "C'est un 8 mais il collectionne les vinyles rares.",
    "C'est une 4 mais elle est professeure à Harvard.",
    "C'est un 9 mais il déteste les fêtes.",
    "C'est une 3 mais elle possède une flotte de yachts.",
    "C'est un 10 mais il est accro aux bonbons.",
    "C'est une 7 mais elle sait hypnotiser les gens.",
    "C'est un 6 mais il fait du stand-up hilarant.",
    "C'est une 5 mais elle a escaladé l'Everest.",
    "C'est un 8 mais il pleure aux mariages.",
    "C'est une 9 mais elle mange des glaces en hiver.",
    "C'est un 4 mais il est multimillionnaire.",
    "C'est une 10 mais elle est nulle en cuisine.",
    "C'est un 7 mais il sait jongler avec cinq balles.",
    "C'est une 6 mais elle a un rire ultra communicatif.",
    "C'est un 5 mais il parle aux oiseaux.",
    "C'est une 8 mais elle déteste les selfies.",
    "C'est un 9 mais il a peur des orages.",
    "C'est une 3 mais elle est astronaute.",
    "C'est un 10 mais il ne sait pas whistle.",
    "C'est une 4 mais elle a composé une symphonie.",
    "C'est un 6 mais il fait les meilleurs cocktails.",
    "C'est une 7 mais elle collectionne les plantes rares.",
    "C'est un 8 mais il regarde des comédies romantiques.",
    "C'est une 5 mais elle sait faire de la magie.",
    "C'est un 9 mais il est allergique au pollen.",
    "C'est une 10 mais elle parle trop vite.",
    "C'est un 2 mais il est prince d'un petit pays.",
    "C'est une 6 mais elle sait piloter un hélicoptère.",
    "C'est un 7 mais il fait des imitations parfaites.",
    "C'est une 4 mais elle a découvert une nouvelle espèce.",
    "C'est un 10 mais il déteste le sport.",
    "C'est une 8 mais elle est accro aux séries coréennes.",
    "C'est un 5 mais il a une voix radio FM.",
    "C'est une 9 mais elle ne boit pas d'alcool.",
    "C'est un 3 mais il possède une mine d'or.",
    "C'est une 10 mais elle est toujours en chaussettes dépareillées.",
    "C'est un 6 mais il sait réparer les ordinateurs les yeux fermés.",
    "C'est une 7 mais elle fait du bénévolat à l'étranger.",
    "C'est un 8 mais il collectionne les timbres anciens.",
    "C'est une 5 mais elle est championne de trivia.",
    "C'est un 9 mais il a peur des piscines.",
    "C'est une 4 mais elle est auteure à succès.",
    "C'est un 10 mais il mange la croûte du fromage.",
    "C'est une 2 mais elle est mannequin internationale.",
    "C'est un 7 mais il sait faire des sculptures sur glace.",
    "C'est une 6 mais elle a un jardin potager incroyable.",
    "C'est un 8 mais il dort avec un doudou.",
    "C'est une 9 mais elle déteste les restaurants étoilés.",
    "C'est un 5 mais il parle latin couramment.",
    "C'est une 10 mais elle est nulle en géographie.",
    "C'est un 4 mais il est hacker éthique célèbre.",
    "C'est une 3 mais elle possède une chaîne de restaurants.",
    "C'est un 9 mais il regarde des vidéos de chats toute la journée.",
    "C'est une 7 mais elle sait faire du skate comme une pro.",
    "C'est un 6 mais il a une collection de comics rare.",
    "C'est une 8 mais elle chante dans la voiture à tue-tête.",
    "C'est un 10 mais il est allergique aux chats.",
    "C'est une 5 mais elle fait des dons anonymes énormes.",
    "C'est un 9 mais il ne sait pas faire de café.",
    "C'est une 4 mais elle est championne de poker.",
    "C'est un 7 mais il sait raconter des histoires captivantes.",
    "C'est une 10 mais elle déteste les surprises.",
    "C'est un 8 mais il a peur des montagnes russes.",
    "C'est une 6 mais elle parle mandarin couramment.",
    "C'est un 3 mais il est propriétaire d'une équipe esport.",
    "C'est une 9 mais elle mange des bonbons au petit-déjeuner.",
    "C'est un 5 mais il sait faire des tours de cartes incroyables.",
    "C'est une 10 mais elle est accro aux puzzles.",
    "C'est un 4 mais il a fondé une ONG.",
    "C'est une 7 mais elle sait jouer aux échecs en aveugle.",
    "C'est un 6 mais il fait des barbecues légendaires.",
    "C'est une 8 mais elle oublie toujours où elle a garé sa voiture.",
    "C'est un 9 mais il déteste les musées.",
    "C'est une 5 mais elle a un sourire qui illumine tout.",
    "C'est un 10 mais il ne supporte pas le froid.",
    "C'est une 2 mais elle est reine d'un petit royaume.",
    "C'est un 7 mais il sait faire des cocktails sans recette.",
    "C'est une 6 mais elle collectionne les livres anciens.",
    "C'est un 8 mais il pleure aux happy ends.",
    "C'est une 4 mais elle est neurochirurgienne.",
    "C'est un 9 mais il est nul en bricolage.",
    "C'est une 10 mais elle déteste les photos.",
    "C'est un 5 mais il a une patience infinie.",
    "C'est une 3 mais elle possède une marque de luxe.",
    "C'est un 6 mais il sait danser le tango.",
    "C'est une 7 mais elle fait des rêves prémonitoires.",
    "C'est un 10 mais il mange toujours trop salé.",
    "C'est une 8 mais elle est accro aux escape games.",
    "C'est un 9 mais il a peur des profondeurs.",
    "C'est une 5 mais elle sait tout réparer avec du duct tape.",
    "C'est un 4 mais il est sommelier renommé.",
    "C'est une 10 mais elle parle aux séries TV.",
    "C'est un 7 mais il collectionne les pièces de monnaie.",
    "C'est une 6 mais elle a un talent pour la négociation.",
    "C'est un 8 mais il déteste les légumes verts.",
    "C'est une 9 mais elle ne sait pas conduire.",
    "C'est un 3 mais il est investisseur dans les licornes.",
    "C'est une 10 mais elle est toujours pieds nus.",
    "C'est un 5 mais il sait faire des blagues en plusieurs langues.",
    "C'est une 4 mais elle est exploratrice polaire.",
    "C'est un 6 mais il fait des photos magnifiques.",
    "C'est une 7 mais elle sait cultiver ses propres légumes.",
    "C'est un 9 mais il regarde des tutos YouTube toute la journée.",
    "C'est une 8 mais elle a peur des insectes.",
    "C'est un 10 mais il ne sait pas lacer ses chaussures vite.",
    "C'est une 2 mais elle est actrice oscarisée.",
    "C'est un 7 mais il sait faire des nœuds marins.",
    "C'est une 6 mais elle a une voix apaisante.",
    "C'est un 5 mais il collectionne les souvenirs de voyages.",
    "C'est une 9 mais elle déteste les concerts.",
    "C'est un 8 mais il dort avec les chaussettes.",
    "C'est une 10 mais elle est nulle en technologie.",
    "C'est un 4 mais il est maître sushi.",
    "C'est une 3 mais elle possède une galerie d'art.",
    "C'est un 9 mais il a peur des avions.",
    "C'est une 7 mais elle sait faire des macarons parfaits.",
    "C'est un 6 mais il est expert en vins.",
    "C'est une 5 mais elle a un talent pour écouter.",
    "C'est un 10 mais il déteste les épinards.",
    "C'est une 8 mais elle collectionne les carnets.",
    "C'est un 7 mais il sait réparer les vélos.",
    "C'est une 4 mais elle est championne de natation.",
    "C'est un 9 mais il est accro aux mots croisés.",
    "C'est une 10 mais elle mange la pâte à crêpes crue.",
    "C'est un 5 mais il a une imagination débordante.",
    "C'est une 6 mais elle sait faire du pain maison.",
    "C'est un 8 mais il pleure aux pubs émotionnelles.",
    "C'est une 3 mais elle est fondatrice d'une fondation.",
    "C'est un 10 mais il ne sait pas siffler.",
    "C'est une 7 mais elle collectionne les pierres précieuses.",
    "C'est un 9 mais il déteste les ascenseurs bondés.",
    "C'est une 5 mais elle fait des câlins parfaits.",
    "C'est un 4 mais il est astrophysicien.",
    "C'est une 10 mais elle est toujours en retard aux rendez-vous.",
    "C'est un 6 mais il sait jouer du saxophone.",
    "C'est une 8 mais elle a peur des fantômes.",
    "C'est un 7 mais il fait des playlists légendaires.",
    "C'est une 9 mais elle ne boit que de l'eau.",
    "C'est un 2 mais il est héritier d'un empire.",
    "C'est une 10 mais elle déteste les talons hauts.",
    "C'est un 5 mais il sait tout sur l'histoire.",
    "C'est une 4 mais elle est pilote de chasse.",
    "C'est un 8 mais il collectionne les bouteilles vides.",
    "C'est une 6 mais elle a un don pour les langues.",
    "C'est un 9 mais il regarde des documentaires animaliers.",
    "C'est une 7 mais elle sait faire des bijoux.",
    "C'est un 10 mais il est nul en chant.",
    "C'est une 3 mais elle possède une écurie de chevaux.",
    "C'est un 6 mais il fait des omelettes parfaites.",
    "C'est une 5 mais elle a une énergie contagieuse.",
    "C'est un 8 mais il a peur des serpents.",
    "C'est une 9 mais elle mange des frites avec de la mayo.",
    "C'est un 4 mais il est développeur de jeux vidéo à succès.",
    "C'est une 10 mais elle oublie les paroles des chansons.",
    "C'est un 7 mais il sait faire des lanternes volantes.",
    "C'est une 6 mais elle collectionne les cartes postales.",
    "C'est un 5 mais il est super doué pour les câlins.",
    "C'est une 8 mais elle déteste les matinées.",
    "C'est un 9 mais il ne sait pas faire de sport.",
    "C'est une 10 mais elle est accro aux émissions culinaires.",
    "C'est un 3 mais il est magnat du pétrole.",
    "C'est une 7 mais elle sait faire des confitures maison.",
    "C'est un 6 mais il a une barbe parfaite.",
    "C'est une 4 mais elle est mathématicienne génie.",
    "C'est un 10 mais il déteste les odeurs fortes.",
    "C'est une 5 mais elle sait tout sur les étoiles.",
    "C'est un 8 mais il collectionne les magnets de voyage.",
    "C'est une 9 mais elle a peur des hauteurs.",
    "C'est un 7 mais il fait des gaufres incroyables.",
    "C'est une 6 mais elle est toujours positive.",
    "C'est un 10 mais il mange trop vite.",
    "C'est une 2 mais elle est influenceuse milliardaire.",
    "C'est un 4 mais il est photographe animalier primé.",
    "C'est une 8 mais elle parle dans son sommeil.",
    "C'est un 9 mais il déteste les foules.",
    "C'est une 5 mais elle a un talent pour la décoration.",
    "C'est un 6 mais il sait faire des barbes à papa.",
    "C'est une 10 mais elle est nulle en sport.",
    "C'est un 7 mais il collectionne les bandes dessinées.",
    "C'est une 3 mais elle possède une vineyard célèbre.",
    "C'est un 8 mais il a peur des abeilles.",
    "C'est une 9 mais elle ne mange pas de viande.",
    "C'est un 5 mais il sait faire des avions en papier parfaits.",
    "C'est une 10 mais elle déteste les miroirs.",
    "C'est un 6 mais il est expert en survie.",
    "C'est une 7 mais elle fait des dessins réalistes.",
    "C'est un 4 mais il est chef pâtissier étoilé.",
    "C'est une 8 mais elle collectionne les bougies.",
    "C'est un 9 mais il regarde des films muets.",
    "C'est une 10 mais elle est accro aux mots fléchés.",
    "C'est un 2 mais il est roi d'un pays exotique.",
    "C'est une 5 mais elle sait faire des compliments sincères.",
    "C'est un 7 mais il a une voix grave sexy.",
    "C'est une 6 mais elle collectionne les souvenirs kitsch.",
    "C'est un 8 mais il pleure aux opéras.",
    "C'est une 9 mais elle déteste les bijoux.",
    "C'est un 10 mais il ne sait pas faire de nœuds.",
    "C'est une 4 mais elle est archéologue célèbre.",
    "C'est un 3 mais il possède une île aux Caraïbes.",
    "C'est une 7 mais elle sait faire des glaces maison.",
    "C'est un 6 mais il est super calin.",
    "C'est une 5 mais elle a un sens de l'orientation infaillible.",
    "C'est un 9 mais il déteste les chats.",
    "C'est une 10 mais elle mange les cornichons directement du pot.",
    "C'est un 8 mais il collectionne les tickets de concert.",
    "C'est une 6 mais elle sait tout sur les vins."
],

    hot: ["C'est une 10, mais elle aime les jeux de rôle un peu trop intenses.",
"C'est un 8 mais il fume de l'herbe tous les soirs pour se détendre.",
"C'est une 6 mais elle fait des blagues racistes en pensant que c'est drôle.",
"C'est un 9 mais il a un faible pour les soirées cocaïne.",
"C'est une 4 mais elle est experte en positions yoga... au lit.",
"C'est un 7 mais il déteste les immigrés sans raison.",
"C'est une 5 mais elle collectionne les jouets pour adultes.",
"C'est un 10 mais il sniffe des lignes avant les rencards.",
"C'est une 3 mais elle est ouvertement homophobe en famille.",
"C'est un 6 mais il aime les partouzes surprises.",
"C'est une 9 mais elle roule des joints comme une pro.",
"C'est un 4 mais il fait des commentaires xénophobes sur les voisins.",
"C'est une 8 mais elle a un tatouage antisémite caché.",
"C'est un 7 mais il préfère le BDSM soft.",
"C'est une 5 mais elle vend de la weed à ses amis.",
"C'est un 10 mais il blague sur les Juifs tout le temps.",
"C'est une 6 mais elle adore les trips à l'acide.",
"C'est un 9 mais il est raciste envers les Asiatiques.",
"C'est une 4 mais elle aime les films pornos vintage.",
"C'est un 8 mais il consomme des champignons hallucinogènes.",
"C'est une 3 mais elle est homophobe et fière de l'être.",
"C'est un 7 mais il a un donjon personnel.",
"C'est une 5 mais elle deale de l'ecstasy en club.",
"C'est un 10 mais il fait des blagues xénophobes sur les Mexicains.",
"C'est une 6 mais elle préfère les orgies masquées.",
"C'est un 9 mais il fume du crack en secret.",
"C'est une 4 mais elle est antisémite et lit des théories du complot.",
"C'est un 8 mais il aime le sexe en public.",
"C'est une 3 mais elle vend de la meth à ses potes.",
"C'est un 7 mais il déteste les gays ouvertement.",
"C'est une 5 mais elle collectionne les vibromasseurs.",
"C'est un 10 mais il sniffe de la colle pour rigoler.",
"C'est une 6 mais elle fait des remarques racistes sur les Noirs.",
"C'est un 9 mais il adore les soirées LSD.",
"C'est une 4 mais elle est xénophobe envers les Européens de l'Est.",
"C'est un 8 mais il pratique le swinging.",
"C'est une 3 mais elle est homophobe et vote en conséquence.",
"C'est un 7 mais il consomme des opioïdes pour le fun.",
"C'est une 5 mais elle a un piercing intime.",
"C'est un 10 mais il blague sur l'Holocauste.",
"C'est une 6 mais elle deale de la MDMA.",
"C'est un 9 mais il est raciste envers les Latinos.",
"C'est une 4 mais elle aime le fétichisme des pieds.",
"C'est un 8 mais il fume de l'héroïne occasionnellement.",
"C'est une 3 mais elle est antisémite et porte des symboles.",
"C'est un 7 mais il préfère le sexe anal.",
"C'est une 5 mais elle cultive du cannabis chez elle.",
"C'est un 10 mais il déteste les étrangers bruyants.",
"C'est une 6 mais elle prend des amphétamines pour étudier.",
"C'est un 9 mais il fait des blagues homophobes.",
"C'est une 4 mais elle adore les clubs échangistes.",
"C'est un 8 mais il sniffe du ketamine en soirée.",
"C'est une 3 mais elle est raciste envers les Arabes.",
"C'est un 7 mais il a un faible pour le sadomasochisme.",
"C'est une 5 mais elle vend des pilules bleues illégales.",
"C'est un 10 mais il est xénophobe envers les Africains.",
"C'est une 6 mais elle fait des trips au DMT.",
"C'est un 9 mais il est antisémite en privé.",
"C'est une 4 mais elle aime le sexe en groupe.",
"C'est un 8 mais il consomme du GHB.",
"C'est une 3 mais elle déteste les lesbiennes.",
"C'est un 7 mais il collectionne les menottes.",
"C'est une 5 mais elle roule des blunts parfaits.",
"C'est un 10 mais il blague sur les camps de concentration.",
"C'est une 6 mais elle deale de la coke pure.",
"C'est un 9 mais il est raciste envers les Indiens.",
"C'est une 4 mais elle pratique le tantrisme extrême.",
"C'est un 8 mais il fume du PCP.",
"C'est une 3 mais elle est homophobe et le dit haut et fort.",
"C'est un 7 mais il aime le roleplay nazi.",
"C'est une 5 mais elle cultive des champignons magiques.",
"C'est un 10 mais il déteste les musulmans.",
"C'est une 6 mais elle prend des barbituriques.",
"C'est un 9 mais il fait des blagues sur les trans.",
"C'est une 4 mais elle adore les donjons BDSM.",
"C'est un 8 mais il sniffe de l'éther.",
"C'est une 3 mais elle est xénophobe envers les Chinois.",
"C'est un 7 mais il préfère le sexe violent.",
"C'est une 5 mais elle vend de l'héroïne coupée.",
"C'est un 10 mais il est antisémite et collectionne des artefacts.",
"C'est une 6 mais elle fait des soirées ayahuasca.",
"C'est un 9 mais il est raciste envers les Blancs.",
"C'est une 4 mais elle aime les fessées publiques.",
"C'est un 8 mais il consomme du fentanyl.",
"C'est une 3 mais elle déteste les bi.",
"C'est un 7 mais il a un harnais en cuir.",
"C'est une 5 mais elle roule des joints géants.",
"C'est un 10 mais il blague sur les génocides.",
"C'est une 6 mais elle deale du speed.",
"C'est un 9 mais il est homophobe envers les gays.",
"C'est une 4 mais elle pratique le polyamour extrême.",
"C'est un 8 mais il fume du salvia.",
"C'est une 3 mais elle est raciste envers les Roumains.",
"C'est un 7 mais il aime le choking.",
"C'est une 5 mais elle cultive de la opium.",
"C'est un 10 mais il déteste les Juifs.",
"C'est une 6 mais elle prend des benzos.",
"C'est un 9 mais il fait des blagues xénophobes sur les Russes.",
"C'est une 4 mais elle adore les orgies thématiques.",
"C'est un 8 mais il sniffe du poppers.",
"C'est une 3 mais elle est antisémite et lit Mein Kampf.",
"C'est un 7 mais il préfère le sexe avec des inconnus.",
"C'est une 5 mais elle vend du cannabis synthétique.",
"C'est un 10 mais il est homophobe et évite les bars gays.",
"C'est une 6 mais elle fait des trips au mescaline.",
"C'est un 9 mais il est raciste envers les Turcs.",
"C'est une 4 mais elle collectionne les plugs.",
"C'est un 8 mais il consomme du crystal meth.",
"C'est une 3 mais elle déteste les immigrants illégaux.",
"C'est un 7 mais il a un fouet préféré.",
"C'est une 5 mais elle roule des pétards aromatisés.",
"C'est un 10 mais il blague sur les attentats.",
"C'est une 6 mais elle deale de l'herbe médicale illégale.",
"C'est un 9 mais il est xénophobe envers les Polonais.",
"C'est une 4 mais elle pratique le edging extrême.",
"C'est un 8 mais il fume du hasch.",
"C'est une 3 mais elle est homophobe et prie contre ça.",
"C'est un 7 mais il aime le bondage.",
"C'est une 5 mais elle cultive des plantes psychoactives.",
"C'est un 10 mais il déteste les Noirs.",
"C'est une 6 mais elle prend des hallucinogènes.",
"C'est un 9 mais il fait des blagues antisémite.",
"C'est une 4 mais elle adore les glory holes.",
"C'est un 8 mais il sniffe du gaz hilarant.",
"C'est une 3 mais elle est raciste envers les Hispaniques.",
"C'est un 7 mais il préfère le sexe en latex.",
"C'est une 5 mais elle vend des edibles maison.",
"C'est un 10 mais il est xénophobe envers les Anglais.",
"C'est une 6 mais elle fait des soirées PCP.",
"C'est un 9 mais il est homophobe envers les lesbiennes.",
"C'est une 4 mais elle collectionne les dildos.",
"C'est un 8 mais il consomme du LSD en microdoses.",
"C'est une 3 mais elle déteste les Juifs riches.",
"C'est un 7 mais il a un masque en cuir.",
"C'est une 5 mais elle roule des spliffs.",
"C'est un 10 mais il blague sur les migrants.",
"C'est une 6 mais elle deale du fentanyl.",
"C'est un 9 mais il est raciste envers les Coréens.",
"C'est une 4 mais elle pratique le pegging.",
"C'est un 8 mais il fume de la DMT.",
"C'est une 3 mais elle est antisémite et conspirationniste.",
"C'est un 7 mais il aime le roleplay maître/esclave.",
"C'est une 5 mais elle cultive du peyotl.",
"C'est un 10 mais il déteste les gays mariés.",
"C'est une 6 mais elle prend des stéroïdes anabolisants.",
"C'est un 9 mais il fait des blagues sur les handicapés raciaux.",
"C'est une 4 mais elle adore les bukkake.",
"C'est un 8 mais il sniffe de la MDMA pure.",
"C'est une 3 mais elle est xénophobe envers les Italiens.",
"C'est un 7 mais il préfère le sexe avec des costumes.",
"C'est une 5 mais elle vend du GHB.",
"C'est un 10 mais il est homophobe et boycotte les pride.",
"C'est une 6 mais elle fait des trips au salvia.",
"C'est un 9 mais il est raciste envers les Japonais.",
"C'est une 4 mais elle collectionne les lubrifiants.",
"C'est un 8 mais il consomme du kratom.",
"C'est une 3 mais elle déteste les transgenres.",
"C'est un 7 mais il a un collier de soumission.",
"C'est une 5 mais elle roule des bangs.",
"C'est un 10 mais il blague sur les pogroms.",
"C'est une 6 mais elle deale des benzos.",
"C'est un 9 mais il est xénophobe envers les Grecs.",
"C'est une 4 mais elle pratique le fisting.",
"C'est un 8 mais il fume du k2.",
"C'est une 3 mais elle est antisémite et admire Hitler.",
"C'est un 7 mais il aime le sexe en plein air.",
"C'est une 5 mais elle cultive des iboga.",
"C'est un 10 mais il déteste les bisexuels.",
"C'est une 6 mais elle prend des nootropiques illégaux.",
"C'est un 9 mais il fait des blagues racistes sur les Blancs.",
"C'est une 4 mais elle adore les gangbangs.",
"C'est un 8 mais il sniffe du nitrous.",
"C'est une 3 mais elle est homophobe et anti-mariage gay.",
"C'est un 7 mais il préfère le sexe avec des jouets.",
"C'est une 5 mais elle vend du spice.",
"C'est un 10 mais il est raciste envers les Autochtones.",
"C'est une 6 mais elle fait des soirées mescaline.",
"C'est un 9 mais il est xénophobe envers les Espagnols.",
"C'est une 4 mais elle collectionne les condoms aromatisés.",
"C'est un 8 mais il consomme du bath salts.",
"C'est une 3 mais elle déteste les Juifs orthodoxes.",
"C'est un 7 mais il a un kit BDSM complet.",
"C'est une 5 mais elle roule des doobies.",
"C'est un 10 mais il blague sur les lynchages.",
"C'est une 6 mais elle deale du krokodil.",
"C'est un 9 mais il est homophobe envers les queers."]};