// data.js
const wordList = [
    "chat", "chien", "maison", "voiture", "arbre", "soleil", "lune", "étoile", "porte", "fenêtre",
    "table", "chaise", "lit", "lampe", "livre", "stylo", "crayon", "papier", "sac", "clé",
    "ballon", "pomme", "banane", "orange", "raisin", "fraise", "cerise", "tomate", "carotte", "pain",
    "fromage", "eau", "lait", "café", "thé", "jus", "gâteau", "pizza", "riz", "pâtes",
    "poisson", "poule", "vache", "cheval", "mouton", "canard", "oiseau", "abeille", "fourmi", "papillon",
    "abat-jour", "acrobate", "agenda", "agrafeuse", "aimant", "album", "algue", "alligator", "amande", "ambassadeur",
    "anchois", "antilope", "apéro", "ara", "arbitre", "archipel", "ardoise", "armure", "artichaut", "aspirateur",
    "astéroïde", "atelier", "aubergine", "autruche", "babouin", "baignoire", "balançoire", "bambou", "banjo", "barrage",
    "basilic", "bassine", "bazar", "beignet", "belette", "bélier", "berceau", "betterave", "biceps", "bière",
    "bifteck", "bikini", "billard", "binocle", "bison", "blaireau", "blouse", "bobine", "boomerang", "bosse",
    "botte", "bouc", "bouclier", "bouée", "boulanger", "bourdon", "boussole", "boxeur", "bracelet", "brancard",
    "branche", "brassard", "brebis", "brioche", "broche", "brosse à dents", "brouette", "buffle", "bulletin", "bunker",
    "buste", "câble", "cacao", "cadre", "cafétéria", "caille", "caissier", "calculatrice", "calepin", "caméscope",
    "camisole", "canal", "caneton", "caniche", "canoë", "cantine", "cape", "capsule", "capuchon", "carie",
    "carnaval", "carpe", "carreau", "carrefour", "cartouche", "cascade", "casier", "casserole", "cassette", "castor",
    "catapulte", "cathédrale", "cauchemar", "caviar", "cellule", "cendrier", "cerceau", "céréale", "cerveau", "chaîne",
    "chaise longue", "chalet", "chameau", "champagne", "chandelier", "chantier", "charbon", "charpentier", "châtaigne", "chaudron",
    "chauve-souris", "chèque", "chercheur", "chevalet", "cheville", "chevreuil", "chicorée", "chimpanzé", "chirurgien", "chœur",
    "chouette", "cigale", "cigare", "cil", "cintre", "circuit", "cirque", "citadelle", "citron", "civière",
    "clairon", "clarinette", "classeur", "clé à molette", "climatiseur", "clinique", "club", "cobra", "cocotier", "comédien",
    "mouche", "araignée", "serpent", "lion", "tigre", "singe", "éléphant", "girafe", "zèbre", "ours",
    "cochon", "lapin", "souris", "chèvre", "âne", "dauphin", "requin", "baleine", "crabe", "tortue",
    "grenouille", "lézard", "panda", "kangourou", "perroquet", "hibou", "aigle", "pigeon", "corbeau", "ciel",
    "nuage", "pluie", "neige", "vent", "feuille", "fleur", "herbe", "forêt", "montagne", "rivière",
    "lac", "mer", "océan", "plage", "sable", "île", "rocher", "volcan", "vallée", "route",
    "commandant", "commode", "compresse", "comte", "concerto", "concierge", "concombre", "condor", "confetti", "congélateur",
    "constellation", "conte", "continent", "contour", "contrat", "coquelicot", "corbeille", "cordon", "cornemuse", "cornichon",
    "corsaire", "corset", "cortège", "costume", "côte", "coucou", "coude", "couguar", "couloir", "coupole",
    "courage", "courge", "courgette", "couronne", "courrier", "couscous", "couvercle", "couvert", "couverture", "crachat",
    "craie", "crampon", "crâne", "crapaud", "cratère", "cravate", "crèche", "crème", "crêpe", "crépuscule",
    "cresson", "crevasse", "crevette", "crible", "cric", "crime", "crinière", "cristal", "crochet", "crocodile",
    "croisière", "croquis", "croûte", "cruche", "cuir", "cuirasse", "cuisinier", "cuisse", "cuivre", "culotte",
    "cumin", "cuvette", "cyclone", "cylindre", "dague", "dalle", "dalmatien", "danois", "dard", "datte",
    "débat", "débarras", "débris", "décennie", "déclic", "décor", "défaut", "défense", "défi", "dégât",
    "dégel", "degré", "déluge", "demeure", "dentelle", "dentiste", "dépanneuse", "dépêche", "dépense", "dépôt",
    "dérive", "désastre", "désordre", "destin", "détail", "détective", "détresse", "détroit", "dette", "deuil",
    "diadème", "diamant", "diapason", "dictaphone", "digue", "diligence", "dîner", "diplomate", "directeur", "dirigeable",
    "discours", "discussion", "disque", "divan", "divertissement", "documentaire", "dodo", "dogue", "dollar", "dôme",
    "domaine", "dompteur", "don", "donjon", "dorade", "dortoir", "dossier", "douane", "doublure", "douche",
    "douceur", "douleur", "doute", "douve", "doyen", "dragée", "drap", "draperie", "droguerie", "drone",
    "duché", "duel", "dune", "duo", "duplicata", "durée", "duvet", "dynamite", "dynastie", "eau-de-vie",
    "ébène", "écart", "échalote", "échafaudage", "échalas", "échantillon", "échasse", "échec", "échine", "écho",
    "pont", "train", "bus", "avion", "bateau", "vélo", "moto", "camion", "feu", "police",
    "pompier", "docteur", "infirmière", "professeur", "élève", "ami", "famille", "bébé", "maman", "papa",
    "frère", "sœur", "oncle", "tante", "cousin", "grand-mère", "grand-père", "roi", "reine", "prince",
    "princesse", "chevalier", "soldat", "château", "tour", "mur", "escalier", "montre", "ordinateur", "téléphone",
    "télévision", "radio", "caméra", "photo", "film", "musique", "chanson", "danse", "dessin", "peinture",
    "couleur", "rouge", "bleu", "vert", "jaune", "noir", "blanc", "gris", "marron", "rose",
    "violet", "or", "argent", "cercle", "carré", "triangle", "cœur", "main", "pied", "tête",
    "bras", "jambe", "doigt", "œil", "nez", "bouche", "oreille", "dent", "cheveu", "barbe",
    "moustache", "visage", "dos", "cou", "ventre", "amour", "joie", "colère", "peur", "tristesse",
    "rire", "sourire", "larme", "fête", "cadeau", "jeu", "jouet", "poupée", "voisin", "travail",
    "bureau", "argent", "magasin", "marché", "école", "hôpital", "jardin", "parc", "musée", "cinéma",
    "théâtre", "restaurant", "hôtel", "ville", "village", "pays", "monde", "terre", "planète", "espace",
    "fusée", "astronaute", "robot", "internet", "logiciel", "jeu vidéo", "électricité", "ampoule", "prise", "pile",
    "chaud", "froid", "jour", "nuit", "matin", "midi", "soir", "heure", "minute", "seconde",
    "printemps", "été", "automne", "hiver", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi",
    "dimanche", "année", "mois", "semaine", "vacances", "voyage", "aventure", "sport", "football", "basket",
    "tennis", "natation", "course", "ski", "patin", "boxe", "karaté", "yoga", "guitare", "piano",
    "batterie", "violon", "flûte", "trompette", "tambour", "micro", "voix", "scène", "rideau", "lumière",
    "ombre", "étoffe", "tissu", "couture", "aiguille", "fil", "bouton", "chaussure", "pantalon", "chemise",
    "robe", "jupe", "manteau", "chapeau", "gant", "écharpe", "ceinture", "sac à dos", "abeille", "abricot",
    "accordéon", "affiche", "aiguille", "ail", "allumette", "ambulance", "amitié", "ananas", "anneau", "appareil",
    "arbre de Noël", "arc", "arc-en-ciel", "armoire", "aventure", "balai", "balle", "banc", "barque", "bateau à voile",
    "biberon", "biscuit", "bijou", "billet", "blé", "bloc", "boîte", "bonbon", "bouteille", "brique", "brocoli", "brosse", "brouillard", "bulle", "cabane", "cadenas", "cadeau", "cactus", "cafard", "cahier",
    "calendrier", "camionnette", "canapé", "canne", "capuche", "caravane", "carte", "carrousel", "casque", "cave",
    "céleri", "cerf", "cerf-volant", "chandelle", "chanson", "chapeau de paille", "chariot", "chaussette", "cheminée", "chenille",
    "chocolat", "cigogne", "ciseau", "citrouille", "clavier", "cloche", "clown", "coccinelle", "coffre", "colle",
    "colline", "compagnon", "comète", "compte", "confiture", "coquillage", "corde", "corne", "couteau", "coussin",
    "crayon de couleur", "croix", "cuisinière", "cure-dent", "danseur", "dé", "désert", "dictionnaire", "dinosaure", "drapeau",
    "dromadaire", "échelle", "écureuil", "éléphant rose", "enveloppe", "épée", "épingle", "escalier roulant", "escargot", "essence",
    "étoile filante", "fauteuil", "fenouil", "ferme", "feuille de papier", "figue", "filet", "flamme", "flèche", "fleuve",
    "fontaine", "formule", "fougère", "fourchette", "fourneau", "fraise tagada", "framboise", "fusil", "galet", "gants de boxe",
    "garage", "gâteau au chocolat", "gazelle", "géant", "girouette", "glace", "gomme", "goudron", "grenier", "griffe",
    "grille", "grue", "guirlande", "haricot", "harmonica", "hélicoptère", "hermine", "horloge", "hublot", "igloo",
    "immeuble", "instrument", "jambon", "jardinier", "jeton", "joie", "joueur", "judo", "kayak", "ketchup",
    "kiwi", "lampe torche", "lanterne", "lapin de Pâques", "lavabo", "léopard", "lettre", "linge", "lionceau", "livre de poche",
    "loup", "loup-garou", "loupe", "lunettes", "machine", "magie", "maillot", "mangue", "manivelle", "marteau",
    "masque", "médaille", "méduse", "melon", "miel", "miroir", "mobile", "moineau", "monstre", "montre-bracelet",
    "mouchette", "muguet", "muscle", "navire", "nénuphar", "nid", "nuage noir", "numéro", "océan Pacifique", "œuf",
    "oiseau de nuit", "olive", "ombrage", "orchestre", "ordinateur portable", "ours polaire", "outil", "paille", "paquet", "parapluie",
    "parfum", "parterre", "pastèque", "pavé", "peigne", "pelle", "pendule", "perle", "persil", "petit pois",
    "phare", "photo de famille", "piano à queue", "piège", "pigeon voyageur", "pile électrique", "pingouin", "piscine", "planche", "planète Mars",
    "pluie d’été", "plume", "poêle", "poire", "poisson-chat", "poivron", "pomme de pin", "portefeuille", "poubelle", "poupée russe",
    "poussette", "poussin", "prison", "prix", "produit", "professeur de sport", "propulseur", "puzzle", "quille", "quincaillerie",
    "râteau", "raquette", "ravin", "rayon", "réacteur", "réfrigérateur", "rideau rouge", "rivière glacée", "robot chien", "rochers",
    "rondin", "roue", "rouge-gorge", "roulotte", "sac de couchage", "sachet", "salade", "savon", "scie", "scorpion",
    "seau", "serrure", "serveur", "sifflet", "sirène", "ski nautique", "soldat de plomb", "sorcière", "sourire", "spectacle",
    "statue", "stylo plume", "sucre", "tableau", "tablier", "tapis", "tapis volant", "tas", "tente", "terrasse",
    "tigre blanc", "toile", "toit", "tonneau", "tortue de mer", "tournevis", "tracteur", "train électrique", "triangle musical", "tronc",
    "trousse", "valise", "vélo de course", "verre", "verre d’eau", "veste", "vitrine", "vitre", "voeu", "voile",
    "wagon", "xylophone", "zèbre rayé", "abricotier", "aéroport", "aigle royal", "alouette", "ampoule électrique", "ancre", "âne gris",
    "appartement", "arrosoir", "asperge", "assiette", "avocat", "baguette", "bague", "balcon", "ballet", "banc public",
    "banquise", "barbe à papa", "barbecue", "barque de pêche", "barrette", "bateau pirate", "batterie solaire", "bave", "béret", "biberon vide",
    "biscuit sec", "bocal", "bois", "boisson", "boîte à musique", "bol", "bonnet", "bouteille d’eau", "bretzel", "briquet",
    "brochette", "bruit", "bureau d’école", "cabinet", "cadenas rouillé", "cadran", "café crème", "caillou", "caleçon", "caméléon",
    "campagne", "canari", "canne à pêche", "canon", "capitaine", "caravelle", "carotte râpée", "cartable", "carton", "casquette",
    "caverne", "cendres", "cerise noire", "chaleur", "champignon", "champ de blé", "chapiteau", "charrette", "chausson", "chef",
    "chemin", "cheval de bois", "chiffon", "chou", "ciel étoilé", "cigarette", "clapier", "clémentine", "clé anglaise", "cloche d’église",
    "clou", "cochon d’Inde", "cœur rouge", "colibri", "colline verte", "compagnie", "compas", "compote", "coq", "corde à sauter",
    "coriandre", "cornet de glace", "corps", "coton", "couteau suisse", "crabe géant", "crayons", "croissant", "cube", "cuisine",
    "cuillère", "cymbale", "cygne", "dauphin bleu", "dé à coudre", "débardeur", "dentifrice", "dents", "départ", "désert chaud",
    "dessert", "dindon", "diplôme", "doigt de pied", "domino", "doudou ours", "dragon", "drôle", "écaille", "écharpe rouge",
    "échelle en bois", "éclaire", "école primaire", "écran", "écrou", "église", "élastique", "électrophone", "éléphant d’Afrique", "embouteillage",
    "empreinte", "enceinte", "encre", "enfant", "engin", "entrée", "épaule", "épouvantail", "équilibre", "espace-temps",
    "escargot géant", "esquisse", "étagère", "été indien", "étincelle", "étui", "examen", "expérience", "fable", "facteur",
    "falaise", "famille heureuse", "fantôme", "farine", "fenêtre ouverte", "fer à repasser", "feuille d’arbre", "feu d’artifice", "feu de camp", "ficelle",
    "figure", "filet de pêche", "film ancien", "fleur rouge", "fleuriste", "flocon", "flûte traversière", "foire", "fond marin", "fontaine magique",
    "forgeron", "formule magique", "four", "fraise des bois", "framboisier", "frigo", "froid", "fromager", "fuseau", "fusée spatiale",
    "galaxie", "galette", "garde", "gare", "gâteau aux pommes", "gaz", "gazon", "géographie", "girafe bébé", "glace vanille",
    "goudron noir", "graine", "grenade", "griffe de lion", "grill", "grimoire", "groseille", "grotte", "guépard", "guitare électrique",
    "gymnase", "habitation", "hachoir", "hamac", "hamster", "harpe", "héros", "hibiscus", "histoire", "houx",
    "hublot d’avion", "huître", "humour", "hymne", "idée", "image", "immeuble haut", "indien", "insecte", "île déserte",
    "instrument de musique", "invitation", "jardin secret", "jasmin", "jet", "joaillerie", "jouet en bois", "journal", "kangourou roux", "kayak gonflable",
    "kiwi fruit", "lampe à huile", "lampe de chevet", "langue", "lave-linge", "légume", "lentille", "lettre d’amour", "libellule", "lien",
    "linge propre", "lionceau blanc", "liquide", "liste", "livraison", "locomotive", "loup noir", "lune brillante", "lutin", "machine à écrire",
    "magicien", "magnétophone", "maison de poupée", "maïs", "mallette", "mammouth", "mandarine", "manège", "mante religieuse", "marchand",
    "marin", "marmotte", "masse", "matelas", "médecin", "melon vert", "méridien", "micro-ondes", "minibus", "minuteur",
    "miroir rond", "mobile musical", "mode", "moisson", "monnaie", "montagne enneigée", "monument", "morceau", "moto-cross", "moule",
    "moulin", "moustiquaire", "muguet blanc", "musée d’art", "navet", "navire ancien", "nectarine", "neige fondue", "nid d’oiseau", "niveau",
    "noisette", "nuit claire", "objet", "obus", "océan Indien", "œil bleu", "oiseau blanc", "olive noire", "ongle", "opéra",
    "orange sanguine", "orchidée", "outil de jardin", "page", "pain d’épice", "palais", "palme", "panda roux", "panier", "panthère",
    "papiers", "parapente", "parfum sucré", "parking", "parquet", "partie", "passage", "pastel", "patate", "patinoire",
    "paume", "paysage", "peau", "pelle de sable", "pendule ancienne", "personne", "phoque", "photo souvenir", "pichet", "pièce",
    "pied nu", "pigeon blanc", "pilule", "pince", "pinguin empereur", "pirogue", "piscine vide", "planche à voile", "planisphère", "plateau",
    "pluie fine", "plumeau", "poids", "poignée", "poireau", "poisson d’avril", "policier", "pompe", "pont-levis", "porte d’entrée",
    "portique", "portrait", "poubelle verte", "poussette jaune", "prairie", "premier", "présent", "prisme", "prune", "puit",
    "quartz", "quartier", "question", "quille de bowling", "racine", "radis", "rail", "rameau", "râteau de plage", "rayon de soleil",
    "recette", "reine des neiges", "repas", "ressort", "rhinocéros", "rideau bleu", "rivage", "robe de soirée", "robot ménager", "rochers blancs",
    "rond", "rouage", "rouge vif", "route de campagne", "ruban", "ruche", "sac en papier", "sage", "sanglier", "sapin",
    "savane", "seau d’eau", "seconde main", "serpent vert", "siège", "silex", "sirène de mer", "ski alpin", "soie", "soldat romain",
    "sommeil", "sorbet", "souris grise", "souvenir", "spectre", "spirale", "statue grecque", "stylo bille", "sucre glace", "sujet",
    "talisman", "tambourin", "tapis rouge", "télécommande", "téléphérique", "tempête", "terrarium", "théière", "tigre jaune", "tonnerre",
    "tortue terrestre", "tour de magie", "tracteur rouge", "train rapide", "trampoline", "tremplin", "triangle rectangle", "trilogie", "tronc d’arbre", "trombone",
    "tuyau", "uniforme", "urne", "usine", "valet", "vallee verte", "valeur", "vanille", "vélo électrique", "vent fort",
    "verger", "vernis", "verre cassé", "veste bleue", "village ancien", "violoncelle", "vitamine", "voiture rouge", "wagon bleu", "wagon-lit",
    "xylophone en bois", "yacht", "yaourt", "zèbre blanc", "zéro", "zoo", "zodiaque", "zombi"
];

const hotWordList = [
    "String", "Menottes", "Fouet", "Massage coquin", "Huile de massage", "Jeu de rôle",
    "Infirmière", "Policier", "Pompière", "Professeur", "Élève", "Patron",
    "Secrétaire", "Fantasme", "Lingerie", "Bas résille", "Talons aiguilles",
    "Caleçon", "Soutien-gorge", "Nue", "Strip-tease", "Effeuillage", "Danse sensuelle",
    "Baiser volé", "French kiss", "Dans le cou", "Morsure", "Griffer", "Caresser",
    "Fesser", "Dominant", "Soumis", "Bondage", "Yeux bandés", "Plume",
    "Glaçon", "Chocolat fondu", "Chantilly", "Fraise", "Langue", "Lécher",
    "Sucer", "Mordre la lèvre", "Soupir", "Gémissement", "Câlin torride",
    "Pelotage", "Main baladeuse", "Sous la douche", "Dans la voiture", "Ascenseur",
    "Sur la table", "Contre le mur", "Par derrière", "69", "Missionnaire",
    "Cowgirl", "Reverse cowgirl", "Levrette", "Cuillères", "Sur le canapé",
    "Dans la cuisine", "Sur le bureau", "Dans les toilettes", "Sur la plage",
    "Dans la forêt", "Sous la tente", "Dans la piscine", "Jacuzzi", "Bulle de bain",
    "Mousse", "Savon", "Éponge", "Serviette", "Peignoir ouvert", "Nudiste",
    "Plage naturiste", "Bronzage intégral", "Huile solaire", "Crème solaire",
    "Massage dos", "Massage pieds", "Massage cuisses", "Zone érogène", "Point G",
    "Prostate", "Clitoris", "Érection", "Excitée", "Mouillée", "Dur comme du bois",
    "Tremblement", "Orgasme", "Jouir", "Multiple", "Fontaine", "Éjaculation",
    "Fellation", "Cunnilingus", "Anulingus", "Doigter", "Pénétration", "Vibromasseur",
    "Godemiché", "Plug anal", "Perles anales", "Cock ring", "Boules de geisha",
    "Menottes en fourrure", "Masque", "Collier", "Laisse", "Jeu de domination",
    "Maîtresse", "Esclave", "Châtiment", "Récompense", "Carotte et bâton",
    "Faire l'amour", "Baiser passionné", "Nuit torride", "Marathon sexuel",
    "Quickie", "Sexe matinal", "Sexe avant le boulot", "Sexe dans le noir",
    "Chuchotements", "Mots crus", "Parler sale", "Gros mots", "Insultes coquines",
    "Salaud", "Salope", "Chérie", "Mon amour", "Mon chéri", "Ma puce",
    "Mon trésor", "Mon corps", "Tes seins", "Tes fesses", "Ton paquet",
    "Ta chatte", "Ta bite", "Ton cul", "Tes lèvres", "Ta bouche", "Tes mains",
    "Tes doigts", "Ta langue", "Ton souffle", "Ton odeur", "Ton goût",
    "Transpiration", "Corps à corps", "Peau contre peau", "Chaleur", "Fièvre",
    "Désir", "Envie", "Pulsion", "Addiction", "Dépendance", "Obsession",
    "Jalousie", "Adultère", "Infidélité", "Aventure d'un soir", "Plan cul",
    "Sex friend", "Amants", "Maîtresse", "Amant", "Trio", "Partouze",
    "Échangisme", "Club libertin", "Soirée privée", "Masques vénitiens",
    "Costumes sexy", "Latex", "Cuir", "Vinyle", "Corset", "Porte-jarretelles",
    "Guêpière", "Body", "Nuisette", "Kimono en satin", "Peignoir transparent",
    "Tanga", "String ficelle", "Boxer moulant", "Slip kangourou", "Érotique",
    "Porno", "Film X", "Hard", "Soft", "Amateur", "Camgirl", "Webcam coquine",
    "Sexting", "Photo coquine", "Nudes", "Dickpic", "Selfie torride",
    "Mirror nude", "Pose suggestive", "Regard de braise", "Sourire coquin",
    "Langue tirée", "Moue boudeuse", "Doigt sur la bouche", "Shhh",
    "Interdit", "Tabou", "Défendu", "Péché", "Tentateur", "Démon",
    "Ange déchu", "Diablesse", "Séducteur", "Dragueur", "Allumeur",
    "Tease", "Provocation", "Sous-entendu", "Double sens", "Clin d'œil",
    "Sourire en coin", "Mains sur les hanches", "Déhanchement", "Frottement",
    "Collé-serré", "Danse lascive", "Twerk", "Grind", "Lap dance",
    "Pole dance", "Barre de pole", "Effeuillage burlesque", "Plumes", "Éventail",
    "Gants longs", "Chapeau", "Cigarette factice", "Regard fumé",
    "Rouge à lèvres", "Trace de rouge", "Marque de rouge sur le col",
    "Parfum enivrant", "Phéromones", "Attirance animale", "Chaleur animale",
    "Rut", "Chasse", "Proie", "Prédateur", "Dompter", "Apprivoiser",
    "Céder", "Se laisser aller", "Abandon", "Extase", "Plaisir intense",
    "Frisson", "Chair de poule", "Électricité", "Étincelle", "Flamme",
    "Brûler de désir", "Consumer", "Fondre", "Exploser", "Déflagration",
    "Feu d'artifice", "Big bang", "Cosmique", "Transcendant", "Divin",
    "Sacrilège", "Hérésie", "Orgasme cosmique", "Petite mort", "Jouissance",
    "Bière", "Vin rouge", "Vin blanc", "Champagne", "Vodka", "Whisky", "Rhum", "Tequila",
    "Shot", "Shooter", "Cul sec", "Pinte", "Demi", "Chope", "Verre ballon", "Flûte",
    "Cocktail", "Mojito", "Piña colada", "Margarita", "Bloody Mary", "Sex on the beach",
    "Tequila sunrise", "Long island", "Cuba libre", "Gin tonic", "Martini", "Dry martini",
    "Cosmopolitan", "Caïpirinha", "Spritz", "Pastis", "Ricard", "Absinthe", "Jägerbomb",
    "Bière pression", "Craft beer", "IPA", "Stout", "Porter", "Lager", "Triple", "Double",
    "Bar", "Pub", "Boîte de nuit", "After", "Soirée arrosée", "Cuite", "Gueule de bois",
    "Hair of the dog", "Défoncé", "Bourré", "Pété", "Torché", "Ivrogne", "Alcoolique",
    "Tournée générale", "Verre de trop", "Blackout", "Blanc", "Film déchiré", "Vomir",
    "Toilettes du bar", "Kébab de fin de soirée", "Tacos après la teuf", "Frite mayo",
    "Joint", "Pétard", "Beuh", "Herbe", "Weed", "Marie-Jeanne", "Ganjas", "Shit",
    "Hash", "Résine", "Marocain", "Afghan", "Skunk", "Haze", "Amnesia", "OG Kush",
    "Grinder", "Feuille à rouler", "OCB", "Filter tips", "Bang", "Pipe", "Chillum",
    "Vaporisateur", "Dab", "Wax", "Shatter", "Crumble", "Rosin", "Live resin",
    "Edibles", "Space cake", "Brownie au cannabis", "Gummies THC", "Bonbon stupéfiant",
    "High", "Défonce", "Planant", "Stone", "Parano", "Munchies", "Fringale", "Oeil rouge",
    "Cocaïne", "Coke", "Neige", "Ligne", "Rail", "Sniffer", "Paille", "Carte de crédit",
    "MDMA", "Ecstasy", "Molly", "XTC", "Pilule", "Cachet", "Roll", "K-hole",
    "Kétamine", "Special K", "Horse tranquilizer", "Dissociatif", "LSD", "Acide",
    "Trip", "Buvard", "Microdose", "Champis", "Champignons magiques", "Psilocybine",
    "Mescaline", "Peyotl", "Cactus", "Ayahuasca", "DMT", "Changa", "Machine elf",
    "Speed", "Amphétamines", "Crystal meth", "Ice", "Tina", "Pervitin", "Poppers",
    "Nitrite d'amyle", "Rush", "Sniff", "GHB", "Droque du viol", "Liquide ecstasy",
    "Héroïne", "H", "Brown sugar", "Seringue", "Fix", "Overdose", "Naloxone",
    "Subutex", "Méthadone", "Sevrage", "Détox", "Fumer du crack", "Pipe à crack",
    "Base", "Freebase", "Fumeur de cailloux", "Clopes", "Cigarette", "Paquet",
    "Tabac à rouler", "Nicotine", "Vape", "Puff", "E-cigarette", "Pod", "Juul",
    "Bar à chicha", "Narguilé", "Shisha", "Goût pomme", "Charbon", "Foil",
    "Snus", "Poche sous la lèvre", "Chiquer", "Tabac à chiquer", "Café clope",
    "Apéro", "Before", "Pré-soirée", "Dégustation vin", "Cave à vin", "Sommelier",
    "Tireuse à bière", "Fût", "Keg", "Pompe à bière", "Afterwork", "Happy hour",
    "Open bar", "All you can drink", "Beuverie", "Binge drinking", "Alcootest",
    "Éthylotest", "Contrôle routier", "Permis suspendu", "Alcool au volant",
    "Fumer dans la voiture", "Cendrier plein", "Odeur de weed", "Parfum d'alcool",
    "Lunettes de soleil gueule de bois", "Cachet d'aspirine", "Alka-Seltzer",
    "Eau pétillante", "Citron pressé", "Déshydratation", "Lit qui tourne",
    "Hallucinations", "Bad trip", "Good trip", "Flashback", "Tolerance",
    "Dépendance", "Accoutumance", "Craving", "Manque", "Syndrome de sevrage",
    "Dealer", "Revendeur", "Trafiquant", "Stupéfiants", "Douane", "Chien renifleur",
    "Planque", "Cachette", "Ballon dans l'estomac", "Mule", "Go fast",
    "Laboratoire clandestin", "Cuisine de meth", "Chimiste amateur", "Précurseurs",
    "Coffee shop", "Amsterdam", "Cannabis social club", "Grow shop", "Culture indoor",
    "Lampe HPS", "Engrais", "Tente de culture", "Trim", "Manucure", "Buds",
    "Terpènes", "Arôme", "Flush", "Séchage", "Curing", "Jarre en verre",
    "Festival techno", "Rave", "Free party", "Tekos", "Sound system", "MD en festival",
    "Tente qui pue la weed", "Bière chaude", "File aux toilettes chimiques",
    "Wagon", "Combi Volkswagen", "Road trip défoncé", "Camping sauvage",
    "Bière autour du feu", "Guitare et chansons", "Chanter faux", "Karaoké bourré",
    "Strip poker ivre", "Jeu à boire", "Caps", "Beer pong", "Flip cup", "Kings cup",
    "Never have I ever", "Action ou vérité", "Gage débile", "Perdre aux cartes",
    "Casino", "Machine à sous", "Jackpot", "Poker bluff", "Royal flush",
    "Paris sportifs bourré", "Perdre son salaire", "Dette de jeu", "Prêt sur gages",
    "Tatouage impulsif", "Percing de soirée", "Regret du lendemain", "Photo compromettante",
    "Selfie défoncé", "Story Instagram", "Filtre gueule de bois", "Bloquer ses ex",
    "Appel à 3h du mat", "Message regretté", "Drague en boîte", "Numéro sur un ticket",
    "Danse collé-serré", "Grind bourré", "Perdre ses potes en soirée", "Rentrer à pied",
    "Uber à 50€", "Taxi qui pue", "Métro fermé", "Attendre le premier bus",
    "Dormir dans le canapé", "Réveil en sueur", "Perdu son téléphone", "Batterie à 1%",
    "Chercher ses clés", "Portefeuille vide", "Ticket de caisse 200€", "Note de bar",
    "Addition salée", "Pourboire généreux", "Serveur sympa", "Barman qui arrose",
    "Verre gratuit", "Shooter offert", "Flirt avec le barman", "Dernier verre",
    "Une dernière pour la route", "Promesse non tenue", "Recommencer le lendemain",
    "Avortement", "Euthanasie", "Suicide assisté", "Peine de mort", "Exécution", "Chambre à gaz",
    "Pendu", "Guillotine", "Peloton d'exécution", "Torture", "Waterboarding", "Électrochocs",
    "Prison à vie", "Solitaire", "Trou disciplinaire", "Viol en prison", "Corruption policière",
    "Bavure", "Violence policière", "Matraque", "Taser", "Flashball", "Dictature", "Coup d'État",
    "Génocide", "Nettoyage ethnique", "Camp de concentration", "Holocauste", "Négationnisme",
    "Révisionnisme", "Propagande", "Fake news", "Complotisme", "Terre plate", "Antivax",
    "Vaccin obligatoire", "Puce électronique", "Great reset", "Nouvel ordre mondial",
    "Illuminati", "Franc-maçonnerie", "Secte", "Suicide collectif", "Jonestown", "Waco",
    "Possession démoniaque", "Exorcisme", "Satanisme", "Messe noire", "Sacrifice humain",
    "Cannibalisme", "Nécrophilie", "Taxidermie humaine", "Trophée de chasse humaine",
    "Trafic d'organes", "Marché noir", "Esclavage moderne", "Travail forcé", "Enfant soldat",
    "Mariage forcé", "Excision", "Lapidation", "Crime d'honneur", "Féminicide", "Infanticide",
    "Corruption politique", "Pots-de-vin", "Népotisme", "Clientélisme", "Détournement de fonds",
    "Évasion fiscale", "Paradis fiscal", "Offshore", "Blanchiment d'argent", "Mafia",
    "Cartel", "Narco-trafic", "Assassinat politique", "Attentat", "Terrorisme", "Kamikaze",
    "Bombe humaine", "Décapitation", "Otage", "Rançon", "Piraterie", "Trafic d'êtres humains",
    "Prostitution forcée", "Réseau pédophile", "Pédophilie", "Inceste", "Maltraitance animale",
    "Corrida", "Chasse à courre", "Combats de coqs", "Expérimentation animale", "Vivisection",
    "Clonage humain", "Expérience sur humains", "MK Ultra", "Expériences nazies",
    "Stérilisation forcée", "Eugénisme", "Supériorité raciale", "Racisme", "Discrimination",
    "Antisémitisme", "Islamophobie", "Homophobie", "Transphobie", "Cancel culture",
    "Woke", "Virtue signaling", "Safe space", "Trigger warning", "Micro-agression",
    "Privilège blanc", "Appropriation culturelle", "Colonialisme", "Esclavagisme historique",
    "Réparations", "Statues déboulonnées", "Réécriture de l'histoire", "Censure", "Autocensure",
    "Délation", "Police de la pensée", "Totalitarisme", "Orwell", "Big Brother", "Caméra de surveillance",
    "Reconnaissance faciale", "Dossier médical partagé", "Fichage ADN", "Bracelet électronique",
    "Liberté conditionnelle", "Fichage policier", "Fiché S", "Internement psychiatrique forcé",
    "Lobotomie", "Électrochocs thérapeutiques", "Hôpital psychiatrique", "Camisole de force",
    "Contention", "Isolement", "Médicamentation forcée", "Schizophrénie", "Paranoïa",
    "Délire de persécution", "Hallucinations", "Trouble bipolaire", "Dépression sévère",
    "Automutilation", "Scarification", "Anorexie", "Boulimie", "Obésité morbide",
    "Chirurgie esthétique extrême", "Body modification", "Implant sous-cutané", "Langue fendue",
    "Corne implantée", "Modification génétique", "Bébé sur mesure", "CRISPR", "Designer baby",
    "Intelligence artificielle consciente", "Singularité technologique", "Transhumanisme",
    "Téléchargement de conscience", "Immortalité", "Cryogénie", "Tête congelée", "Corps sans tête",
    "Greffe de tête", "Arme biologique", "Virus fabriqué", "Pandémie planifiée", "Confinement éternel",
    "Pass sanitaire", "QR code obligatoire", "Société de contrôle", "Crédit social chinois",
    "Note citoyenne", "Interdiction de voyager", "Camp de rééducation", "Goulag", "Laogai",
    "Travail forcé idéologique", "Rééducation politique", "Autocritique publique", "Humiliation publique",
    "Pilori", "Carcan", "Flagellation", "Fouet public", "Amputation judiciaire", "Main coupée",
    "Œil pour œil", "Vengeance", "Justice privée", "Lynchage", "Meute", "Chasse à l'homme",
    "Prime sur tête", "Contrat sur quelqu'un", "Tueur à gages", "Serial killer", "Tueur en série",
    "Cannibale célèbre", "Nécrophile célèbre", "Cadavre", "Autopsie", "Thanatopracteur",
    "Embaumement", "Momie", "Catacombe", "Ossuaire", "Crématorium", "Four crématoire",
    "Cendres dispersées", "Urne funéraire", "Testament", "Héritage contesté", "Famille qui se déchire",
    "Enterrement de vie de garçon raté", "Secret de famille", "Enfant caché", "Adultère découvert",
    "Divorce sanglant", "Garde d'enfants", "Pension alimentaire", "Faillite personnelle",
    "Saisie sur salaire", "Expulsion locative", "SDF", "Bidonville", "Camp de migrants",
    "Expulsion de migrants", "Frontière fermée", "Mur anti-migrants", "Barbelés", "Camp de rétention",
    "No man's land", "Mine antipersonnel", "Guerre", "Bombardement", "Drone tueur",
    "Soldat enfant", "Mercenaire", "Conflit oublié", "Génocide oublié", "Famine organisée",
    "Blocus humanitaire", "Sanctions économiques", "Embargo", "Pauvreté extrême", "Enfant des rues",
    "Mendicité organisée", "Exploitation des mineurs", "Usine clandestine", "Esclave salarié",
    "Burn-out", "Harcèlement au travail", "Licenciement abusif", "Chômage de longue durée",
    "RSA", "Allocations", "Fraude sociale", "Contrôleur", "Perquisition", "Saisie",
    "Prison pour dettes", "Huissier", "Vente aux enchères", "Squat", "Expulsion par la force",
    "Manif violente", "Black bloc", "Casseur", "Gaz lacrymogène", "Canon à eau", "Charge policière",
    "Émeute", "Insurrection", "Révolution", "Guillotine moderne", "Tribunal populaire",
    "Procès médiatique", "Lynchage médiatique", "Harcèlement en ligne", "Cyberharcèlement",
    "Doxxing", "Deepfake", "Usurpation d'identité", "Chantage en ligne", "Secte sur internet",
    "Forum extrémiste", "Site complotiste", "Dark web", "Marché noir en ligne", "Bitcoin anonyme",
    "Cryptomonnaie sale", "Rançongiciel", "Pirate informatique", "Virus destructeur",
    "Apocalypse numérique", "Panne mondiale", "Blackout électrique", "Effondrement sociétal",
    "Survivalisme", "Bunker", "Stock de nourriture", "Fin du monde", "Astéroïde", "Supervolcan",
    "Éruption Yellowstone", "Tsunami géant", "Séisme destructeur", "Pandémie mortelle",
    "Zombie", "Apocalypse zombie", "Dernier survivant", "Cannibalisme post-apo", "Tribus hostiles"
];