const propositionsNormal = [


    "L'argent fait le bonheur.",
    "Le vote devrait être obligatoire.",
    "La semaine de quatre jours devrait être la norme.",
    "Le monde serait mieux sans frontières.",
    "On devrait instaurer un revenu universel pour tous.",
    "La prison est la meilleure solution contre la criminalité.",
    "Les réseaux sociaux sont un danger pour la démocratie.",
    "Le gouvernement devrait limiter le salaire des grands patrons.",
    "L'école devrait apprendre aux enfants à gérer leur argent.",
    "La liberté d'expression doit avoir des limites.",
    "Les caméras de surveillance dans les rues sont une bonne chose.",
    "Il faudrait interdire la publicité dans l'espace public.",
    "L'uniforme devrait être obligatoire à l'école.",
    "Le droit de vote devrait être accordé dès 16 ans.",
    "La peine de mort ne devrait jamais être rétablie.",
    "Les hommes et les femmes sont aujourd'hui réellement égaux.",
    "Le service militaire devrait être rétabli.",
    "Le télétravail est une régression pour le lien social.",
    "La méritocratie existe vraiment dans notre société.",
    "L'État devrait financer la culture avant tout.",
    "Il faudrait limiter le nombre d'enfants par famille pour sauver la planète.",
    "Les riches devraient payer beaucoup plus d'impôts.",
    "Le nucléaire est indispensable pour l'avenir.",
    "Le progrès technique nous rend plus bêtes.",
    "La mondialisation a fait plus de mal que de bien.",
    "L'anonymat sur internet devrait être supprimé.",
    "Les médias manipulent l'opinion publique.",
    "Le patriotisme est une forme d'égoïsme.",
    "L'immigration est une richesse pour un pays.",
    "La religion devrait rester exclusivement dans la sphère privée.",
    "On devrait pouvoir choisir son jour de repos hebdomadaire.",
    "Le système de santé devrait être entièrement gratuit pour tous.",
    "L'intelligence artificielle va détruire plus d'emplois qu'elle n'en crée.",
    "La monarchie est un système dépassé.",
    "L'Union européenne est une chance pour la France.",
    "Les politiciens sont tous les mêmes.",
    "La grève est le seul moyen de se faire entendre.",
    "Le sport de haut niveau est devenu trop politique.",
    "Il faut interdire les jets privés.",
    "Le port d'armes devrait être autorisé pour l'autodéfense.",
    "La police est là pour nous protéger avant tout.",
    "Le capitalisme est le moins pire des systèmes.",
    "L'espace ne devrait pas être colonisé par l'homme.",
    "Les sondages d'opinion devraient être interdits avant les élections.",
    "L'héritage devrait être supprimé pour garantir l'égalité des chances.",
    "La justice est plus sévère avec les pauvres.",
    "Le service public est plus efficace que le privé.",
    "Il faudrait un permis pour devenir parent.",
    "Le communautarisme est une menace pour la nation.",
    "Le travail est une valeur essentielle de la vie.",


    "On peut être ami avec son ex.",
    "Le coup de foudre existe vraiment.",
    "L'honnêteté est toujours la meilleure solution dans un couple.",
    "Il vaut mieux être seul que mal accompagné.",
    "La jalousie est une preuve d'amour.",
    "L'amitié homme-femme est impossible sans ambiguïté.",
    "Le mariage est une institution démodée.",
    "On peut aimer deux personnes à la fois.",
    "La distance renforce l'amour.",
    "Les contraires s'attirent.",
    "Pardonner une infidélité est impossible.",
    "Vivre ensemble avant le mariage est indispensable.",
    "L'amour dure toujours trois ans.",
    "On peut trouver l'amour sur une application de rencontre.",
    "Les amis sont la famille que l'on choisit.",
    "Il faut tout se dire dans un couple.",
    "La différence d'âge n'a aucune importance en amour.",
    "Le premier amour est celui qu'on n'oublie jamais.",
    "Il est plus facile de rompre par message que de vive voix.",
    "Le mariage devrait avoir une date de péremption.",
    "On peut tomber amoureux de quelqu'un sans l'avoir jamais vu.",
    "Les disputes sont nécessaires pour la survie d'un couple.",
    "La polygamie devrait être légalisée.",
    "Il ne faut jamais se coucher en étant en colère contre son partenaire.",
    "Le romantisme est mort.",
    "Les réseaux sociaux détruisent les couples.",
    "L'amitié est plus solide que l'amour.",
    "On rencontre l'amour quand on s'y attend le moins.",
    "L'attirance physique est plus importante que l'intelligence.",
    "Il faut avoir les mêmes passions pour que le couple fonctionne.",
    "Le silence est parfois la meilleure réponse dans un conflit.",
    "L'instinct ne trompe jamais en amitié.",
    "C'est celui qui gagne le plus qui doit payer les factures.",
    "Le mensonge est parfois nécessaire pour protéger l'autre.",
    "Un secret peut détruire une amitié de longue date.",
    "Il est possible d'aimer quelqu'un sans l'admirer.",
    "Les câlins sont plus importants que les mots.",
    "Le sexe est le pilier d'un couple heureux.",
    "On ne peut pas changer quelqu'un par amour.",
    "La routine est l'ennemi numéro 1 du couple.",
    "L'amour propre doit passer avant l'amour des autres.",
    "Une relation platonique peut être aussi intense qu'une relation charnelle.",
    "On devrait pouvoir être marié à plusieurs personnes.",
    "Le coup de foudre n'est qu'une question d'hormones.",
    "L'amitié virtuelle n'est pas de la vraie amitié.",
    "Les parents ne devraient pas s'immiscer dans les relations de leurs enfants.",
    "La fidélité est un concept culturel et non naturel.",
    "On oublie jamais son premier chagrin d'amour.",
    "Il faut être heureux seul avant d'être heureux à deux.",
    "La complicité intellectuelle est supérieure à l'attirance physique.",


    "La pizza à l'ananas est un crime.",
    "Le petit-déjeuner est le repas le plus important de la journée.",
    "Il faut se lever tôt pour réussir sa vie.",
    "Le café est une drogue comme une autre.",
    "La ville est plus agréable que la campagne.",
    "Vivre sans télévision est impossible aujourd'hui.",
    "Le sport est indispensable pour être heureux.",
    "Le shopping est une forme de thérapie.",
    "On devrait tous être végétariens.",
    "Les vacances reposantes sont plus efficaces que les vacances actives.",
    "La sieste devrait être obligatoire au travail.",
    "L'alcool est indispensable pour faire la fête.",
    "Il faut lire au moins un livre par mois.",
    "La mode est un gaspillage d'argent.",
    "Vivre en appartement est mieux qu'en maison.",
    "Le chocolat noir est meilleur que le chocolat au lait.",
    "On peut vivre sans smartphone pendant une semaine.",
    "Cuisiner soi-même prend trop de temps.",
    "Le cinéma est mieux que les plateformes de streaming.",
    "Les animaux domestiques sont des membres de la famille à part entière.",
    "L'hiver est une saison plus agréable que l'été.",
    "On s'habille d'abord pour plaire aux autres.",
    "Le camping, ce n'est pas de vraies vacances.",
    "Les jeux vidéo rendent violent.",
    "Il faut toujours finir son assiette.",
    "Le luxe est indécent.",
    "La chirurgie esthétique devrait être plus accessible.",
    "Les tatouages gâchent le corps.",
    "Le rangement aide à avoir l'esprit clair.",
    "Sortir seul au restaurant est gênant.",
    "L'eau plate est meilleure que l'eau gazeuse.",
    "Le pain au chocolat s'appelle une chocolatine.",
    "On peut être élégant en jogging.",
    "Les parcs d'attractions sont l'enfer sur terre.",
    "Il faut voyager loin pour se dépayser.",
    "Le bricolage est une corvée.",
    "Les chats sont plus intelligents que les chiens.",
    "Il faut dormir au moins 8 heures par nuit.",
    "Le permis de conduire devrait être renouvelé tous les 10 ans.",
    "Les brunchs sont trop chers pour ce que c'est.",
    "Il vaut mieux être en avance qu'à l'heure.",
    "Les lundis sont les pires jours de la semaine.",
    "Le camping-car est le meilleur moyen de voyager.",
    "Il faut toujours dire la vérité aux enfants.",
    "La musique actuelle est moins bonne que celle d'autrefois.",
    "Le vin rouge est meilleur que le vin blanc.",
    "Il faut interdire les écrans aux enfants de moins de 3 ans.",
    "La malbouffe devrait être taxée comme le tabac.",
    "Vivre à l'étranger est une expérience indispensable.",
    "Le confort est plus important que l'esthétique.",


    "La fin justifie les moyens.",
    "L'homme est naturellement bon.",
    "Le destin existe et tout est écrit.",
    "On peut rire de tout.",
    "L'intelligence est un fardeau.",
    "La vérité est relative.",
    "La mort donne un sens à la vie.",
    "L'être humain est l'espèce la plus nuisible de la planète.",
    "Le bonheur est un choix.",
    "Il faut oublier le passé pour construire le futur.",
    "Le mal est nécessaire pour apprécier le bien.",
    "La solitude est une force.",
    "On apprend plus de ses échecs que de ses réussites.",
    "L'égoïsme est le moteur de l'humanité.",
    "La connaissance rend malheureux.",
    "La beauté est totalement subjective.",
    "Il n'y a pas de hasard, que des rendez-vous.",
    "La peur est le meilleur moyen de contrôler les gens.",
    "L'intuition est plus fiable que la raison.",
    "On ne peut jamais vraiment connaître quelqu'un.",
    "La liberté totale est impossible.",
    "Le temps guérit toutes les blessures.",
    "Les animaux ont une conscience identique à la nôtre.",
    "L'intelligence artificielle pourra un jour avoir des sentiments.",
    "L'humanité finira par s'autodétruire.",
    "Il existe une vie après la mort.",
    "Le pouvoir corrompt forcément.",
    "La patience est la plus grande des vertus.",
    "On est responsable de tout ce qui nous arrive.",
    "La souffrance est nécessaire pour grandir.",
    "L'ennui est utile pour la créativité.",
    "La technologie nous éloigne de notre humanité.",
    "Il faut toujours suivre son cœur plutôt que sa tête.",
    "La justice humaine est imparfaite par nature.",
    "L'utopie est nécessaire pour avancer.",
    "Le silence est plus puissant que la parole.",
    "On ne possède jamais vraiment rien.",
    "Le travail acharné finit toujours par payer.",
    "L'argent est la racine de tous les maux.",
    "La curiosité est un vilain défaut.",
    "Il est impossible d'être totalement altruiste.",
    "La morale change avec le temps.",
    "Les regrets sont inutiles.",
    "L'histoire est écrite par les vainqueurs.",
    "Chaque problème a une solution.",
    "L'ignorance est une bénédiction.",
    "La perfection est ennuyeuse.",
    "Nous sommes seuls dans l'univers.",
    "La reconnaissance des autres est indispensable.",
    "La vie a un sens précis.",


    "L'intelligence artificielle remplacera les médecins.",
    "Les robots devraient avoir des droits.",
    "On pourra bientôt vivre jusqu'à 150 ans.",
    "Les voitures autonomes sont plus sûres que les conducteurs humains.",
    "Le métavers est l'avenir des interactions sociales.",
    "Elon Musk est un génie.",
    "Les réseaux sociaux devraient être interdits aux moins de 15 ans.",
    "On découvrira bientôt une vie extraterrestre.",
    "La technologie finira par nous rendre immortels.",
    "Les livres papier vont disparaître au profit du numérique.",
    "Les algorithmes nous connaissent mieux que nous-mêmes.",
    "L'intelligence artificielle va créer de nouvelles formes d'art supérieures aux nôtres.",
    "Il faudrait implanter des puces dans le cerveau pour augmenter nos capacités.",
    "Le futur sera écologique ou ne sera pas.",
    "Les robots domestiques seront dans toutes les maisons d'ici 10 ans.",
    "La vie sur Mars est une solution sérieuse pour l'humanité.",
    "La technologie réduit notre capacité d'attention.",
    "Les réunions en hologramme remplaceront les appels vidéo.",
    "Le bitcoin remplacera les monnaies traditionnelles.",
    "La reconnaissance faciale est une atteinte aux libertés individuelles.",
    "Le transhumanisme est une évolution naturelle.",
    "On devrait pouvoir choisir l'ADN de ses enfants.",
    "Les smartphones nous espionnent en permanence.",
    "L'IA est capable de créativité.",
    "Le travail manuel va devenir un luxe.",
    "Les écrans sont la nouvelle cigarette.",
    "Le progrès scientifique ne peut pas être arrêté.",
    "Les réseaux sociaux rendent les gens plus narcissiques.",
    "Les données personnelles sont le pétrole du 21ème siècle.",
    "Un jour, les IA seront plus intelligentes que l'ensemble de l'humanité.",
    "La réalité virtuelle peut soigner des phobies.",
    "Les drones de livraison vont envahir le ciel.",
    "La cyber-guerre est plus dangereuse que la guerre conventionnelle.",
    "Il faut limiter le temps d'écran quotidien.",
    "La technologie facilite la solitude.",
    "Le papier monnaie va disparaître totalement.",
    "Les professeurs seront remplacés par des tutoriels interactifs.",
    "L'exploration spatiale coûte trop cher par rapport aux problèmes terrestres.",
    "L'IA ne pourra jamais comprendre l'humour.",
    "La technologie nous rend plus dépendants que jamais.",
    "On devrait pouvoir voter par internet.",
    "La domotique rend les gens paresseux.",
    "Le piratage informatique est une forme de résistance.",
    "Les voitures électriques ne sont pas si écologiques que ça.",
    "L'IA peut aider à résoudre la faim dans le monde.",
    "La vie privée n'existe plus.",
    "Les deepfakes vont détruire la confiance dans l'information.",
    "La science-fiction finit toujours par devenir réalité.",
    "On pourra bientôt télécharger ses souvenirs sur un disque dur.",
    "Le cerveau humain est l'ordinateur le plus puissant qui existera jamais.",


    "Les notes à l'école devraient être supprimées.",
    "On apprend plus sur le terrain que sur les bancs de l'école.",
    "Le baccalauréat ne vaut plus rien aujourd'hui.",
    "Travailler plus pour gagner plus est une illusion.",
    "Les professeurs ne sont pas assez payés.",
    "L'alternance est le meilleur moyen de se former.",
    "Il faudrait apprendre le code informatique dès le CP.",
    "Le harcèlement scolaire est mieux géré qu'avant.",
    "Le diplôme est plus important que l'expérience.",
    "Les vacances scolaires sont trop longues.",
    "Le travail devrait être une source de plaisir.",
    "On devrait pouvoir changer de métier tous les 10 ans.",
    "L'école tue la créativité.",
    "L'anglais devrait être la deuxième langue maternelle de tout le monde.",
    "Le télétravail à 100% est une mauvaise idée.",
    "Le chômage est parfois un choix.",
    "Il n'y a pas de sots métiers.",
    "Les patrons gagnent trop par rapport aux ouvriers.",
    "La retraite à 60 ans est un droit sacré.",
    "On devrait enseigner l'empathie à l'école.",
    "Le stress au travail est inévitable.",
    "L'ambition est une qualité.",
    "Le piston est le seul moyen de réussir.",
    "L'école devrait être à la carte dès le collège.",
    "Les langues mortes (latin, grec) ne servent à rien.",
    "Il faut interdire les téléphones portables dans tous les établissements scolaires.",
    "L'éducation civique est la matière la plus importante.",
    "Le travail de nuit devrait être mieux rémunéré.",
    "On peut réussir sa vie sans diplômes.",
    "Les open-spaces sont une torture.",
    "La hiérarchie en entreprise est indispensable.",
    "Les réunions sont une perte de temps.",
    "Le bien-être au travail est une mode passagère.",
    "On devrait pouvoir noter ses professeurs.",
    "Les mathématiques sont trop valorisées par rapport aux arts.",
    "L'orthographe n'est plus importante aujourd'hui.",
    "L'école devrait préparer à la vie d'adulte (impôts, loyers, etc.).",
    "Le droit à la déconnexion doit être respecté.",
    "L'intelligence émotionnelle est plus utile que le QI.",
    "Les stages non rémunérés devraient être illégaux.",
    "Le travail est une aliénation.",
    "On devrait commencer l'école plus tard le matin.",
    "Le redoublement est inutile.",
    "L'auto-entreprenariat est le futur du travail.",
    "Il faut séparer vie professionnelle et vie privée.",
    "Les femmes sont de meilleurs managers que les hommes.",
    "Le sport à l'école devrait compter autant que les maths.",
    "Tout travail mérite salaire.",
    "La formation continue est une nécessité.",
    "On ne travaille pas pour soi, mais pour la société.",

    "Le livre est toujours mieux que l'adaptation en film.",
    "La télé-réalité abrutit les gens.",
    "Le rap est la poésie d'aujourd'hui.",
    "On peut séparer l'homme de l'artiste.",
    "Les musées devraient être gratuits pour tous.",
    "Le football est surestimé.",
    "Les jeux de société sont meilleurs que les jeux vidéo.",
    "La gastronomie française est la meilleure du monde.",
    "Il faut avoir de la culture générale pour être intéressant.",
    "La mode est un art.",
    "Les blockbusters américains étouffent le cinéma européen.",
    "Graffer sur les murs est une forme d'art.",
    "La lecture est un plaisir solitaire.",
    "On ne peut pas discuter des goûts et des couleurs.",
    "Le streaming a tué l'industrie musicale.",
    "Les festivals de musique sont trop chers.",
    "Le théâtre est un art élitiste.",
    "La bande dessinée est de la vraie littérature.",
    "Netflix produit trop de contenus de mauvaise qualité.",
    "La célébrité est un poison.",
    "Il faut voyager pour s'ouvrir l'esprit.",
    "Les parcs d'attractions sont pour les adultes aussi.",
    "La photographie numérique a tué le charme de la photo.",
    "Les séries sont devenues meilleures que les films.",
    "La danse est un langage universel.",
    "L'opéra est ennuyeux.",
    "On devrait soutenir les artistes locaux avant tout.",
    "La chasse est un sport comme un autre.",
    "Le jardinage est relaxant.",
    "Les influenceurs ne sont pas de vrais artistes.",
    "Le patrimoine historique doit être préservé à tout prix.",
    "La science est plus fascinante que la fiction.",
    "Le cirque avec animaux devrait être totalement interdit.",
    "L'art contemporain est une grosse arnaque.",
    "Le karaoké est une activité géniale.",
    "Lire les spoilers gâche le plaisir.",
    "La radio a encore un avenir.",
    "Les contes de fées sont sexistes.",
    "Le sport à la télé est soporifique.",
    "La cuisine moléculaire n'a pas de goût.",
    "L'humour noir est le meilleur humour.",
    "On peut être cultivé sans jamais avoir lu de classiques.",
    "Les récompenses (Oscars, César) sont truquées.",
    "La poésie ne sert à rien.",
    "Le yoga est une activité pour les gens calmes.",
    "Les jeux d'argent devraient être interdits.",
    "Le tourisme de masse détruit les plus beaux endroits.",
    "Il faut toujours lire la fin d'un livre même s'il est mauvais.",
    "La musique classique aide à se concentrer.",
    "La culture est ce qui reste quand on a tout oublié.",


    "Le changement climatique est irréversible.",
    "Il faut devenir vegan pour sauver la planète.",
    "Le plastique devrait être totalement interdit.",
    "L'écologie est une préoccupation de riches.",
    "Il faut limiter les voyages en avion.",
    "La nature reprendra toujours ses droits.",
    "Les zoos sont nécessaires pour la conservation des espèces.",
    "Le tri sélectif ne sert à rien si les entreprises ne font rien.",
    "Il faut taxer l'essence beaucoup plus cher.",
    "L'agriculture bio est une stratégie marketing.",
    "L'eau va devenir la ressource la plus chère du monde.",
    "On devrait tous vivre dans des maisons autonomes.",
    "La chasse devrait être interdite.",
    "Il faut réduire la population mondiale.",
    "Les catastrophes naturelles sont de plus en plus fréquentes à cause de l'homme.",
    "Le nucléaire est une énergie propre.",
    "La voiture individuelle va disparaître.",
    "Les villes devraient être totalement piétonnes.",
    "On consomme trop de viande.",
    "La fast-fashion est un désastre écologique.",
    "Il faut protéger les abeilles à tout prix.",
    "L'océan est plus mystérieux que l'espace.",
    "Le recyclage est l'affaire de tous.",
    "Il faut interdire les emballages inutiles.",
    "La climatisation est un désastre environnemental.",
    "On devrait payer pour produire des déchets.",
    "L'énergie solaire est l'avenir.",
    "Il faut replanter des forêts partout.",
    "La décroissance est la seule solution.",
    "Le réchauffement climatique est exagéré.",
    "La biodiversité est en danger critique.",
    "Les pesticides doivent être bannis immédiatement.",
    "On devrait récupérer l'eau de pluie pour tout.",
    "Le gaspillage alimentaire est un crime.",
    "La mode de seconde main est la seule solution durable.",
    "L'écologie doit passer avant l'économie.",
    "Les énergies renouvelables ne suffiront jamais.",
    "Il faut apprendre l'écologie dès la maternelle.",
    "Le tourisme spatial est une aberration écologique.",
    "La pollution lumineuse nuit à la santé.",
    "Les animaux sauvages n'ont plus de place sur terre.",
    "Il faut privilégier les produits de saison.",
    "La voiture électrique est un mensonge écologique.",
    "Les éoliennes gâchent le paysage.",
    "Il faut interdire la publicité pour les produits polluants.",
    "L'homme peut vivre en harmonie avec la nature.",
    "La technologie peut nous sauver de la crise climatique.",
    "Il faut limiter le chauffage à 19 degrés.",
    "L'avenir appartient au vélo.",
    "La nature est la meilleure des pharmacies.",


    "Tout ce qui ne tue pas rend plus fort.",
    "Le bonheur est une question de volonté.",
    "L'ego est notre pire ennemi.",
    "Il faut s'aimer soi-même avant d'aimer les autres.",
    "La timidité est un handicap.",
    "On peut changer de personnalité avec le temps.",
    "Le stress peut être positif.",
    "La méditation change la vie.",
    "Les rêves ont une signification profonde.",
    "L'intuition ne se trompe jamais.",
    "On attire ce que l'on vibre.",
    "La procrastination est un signe de créativité.",
    "Il faut toujours dire ce que l'on pense.",
    "La vulnérabilité est une force.",
    "On est le reflet des cinq personnes que l'on fréquente le plus.",
    "L'échec est une étape nécessaire vers le succès.",
    "Le regard des autres est trop important pour nous.",
    "Il faut vivre le moment présent sans penser au lendemain.",
    "La discipline est plus importante que la motivation.",
    "Tout le monde devrait faire une thérapie.",
    "La nostalgie nous empêche d'avancer.",
    "Le pardon est pour soi, pas pour l'autre.",
    "L'optimisme est une forme de courage.",
    "Il ne faut jamais regretter ses choix.",
    "La colère est une émotion utile.",
    "Le silence est une forme de communication.",
    "On naît intelligent, on ne le devient pas.",
    "L'argent change les gens.",
    "La routine rassure.",
    "Il faut sortir de sa zone de confort tous les jours.",
    "La confiance se gagne en gouttes et se perd en litres.",
    "On peut être heureux avec très peu de choses.",
    "La peur de l'échec empêche d'agir.",
    "L'humour est la meilleure défense.",
    "Il faut savoir dire non.",
    "La solitude est nécessaire pour se retrouver.",
    "On est tous un peu fous.",
    "La gentillesse est souvent prise pour de la faiblesse.",
    "Le succès est subjectif.",
    "L'enfance détermine toute notre vie.",
    "On peut guérir par la pensée.",
    "La comparaison est la voleuse du bonheur.",
    "Il faut être ambitieux.",
    "La patience s'apprend.",
    "Le lâcher-prise est difficile mais essentiel.",
    "On a tous un talent caché.",
    "Les émotions doivent être exprimées, pas refoulées.",
    "La curiosité garde l'esprit jeune.",
    "On peut se réinventer à n'importe quel âge.",
    "Le plus grand voyage est à l'intérieur de soi.",


    "La Terre est plate.",
    "Les extraterrestres nous ont déjà rendu visite.",
    "Le Père Noël devrait exister.",
    "La fin du monde est proche.",
    "L'astrologie est une science exacte.",
    "Les fantômes existent.",
    "On vit dans une simulation informatique.",
    "Le petit doigt de pied ne sert à rien.",
    "Le ketchup va avec tout.",
    "Il faut dormir avec des chaussettes en hiver.",
    "Le lundi devrait être férié.",
    "L'été est mieux que l'hiver.",
    "Les films d'horreur sont amusants.",
    "On devrait pouvoir manger du dessert en premier.",
    "La sieste est un art de vivre.",
    "Le chocolat blanc n'est pas du vrai chocolat.",
    "Les licornes pourraient exister dans une autre dimension.",
    "Il faut mettre le lait avant les céréales.",
    "La douche du soir est meilleure que celle du matin.",
    "Les dinosaures ne sont pas vraiment morts.",
    "Le sport, c'est mieux à la télé que dans la vraie vie.",
    "On devrait pouvoir travailler en pyjama.",
    "Les bébés sont tous mignons.",
    "Les chats complotent pour dominer le monde.",
    "Le thé est meilleur que le café.",
    "La montagne, ça gagne.",
    "Les blagues les plus courtes sont les meilleures.",
    "L'argent n'a pas d'odeur.",
    "Il faut toujours avoir un plan B.",
    "Le ridicule ne tue pas.",
    "L'habit ne fait pas le moine.",
    "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué.",
    "La nuit porte conseil.",
    "Tous les chemins mènent à Rome.",
    "L'exception confirme la règle.",
    "Il vaut mieux prévenir que guérir.",
    "Qui dort dîne.",
    "Les absents ont toujours tort.",
    "Petit à petit, l'oiseau fait son nid.",
    "Il ne faut jamais dire fontaine je ne boirai pas de ton eau.",
    "C'est en forgeant qu'on devient forgeron.",
    "L'herbe est toujours plus verte ailleurs.",
    "Les voyages forment la jeunesse.",
    "Il n'est jamais trop tard pour bien faire.",
    "Rien ne sert de courir, il faut partir à point.",
    "Il faut battre le fer pendant qu'il est chaud.",
    "La parole est d'argent, mais le silence est d'or.",
    "Après la pluie, le beau temps.",
    "Toutes les bonnes choses ont une fin.",
    "Le monde appartient à ceux qui se lèvent tôt.",
    "On ne peut pas avoir le beurre et l'argent du beurre.",
    "Mieux vaut tard que jamais.",
    "La curiosité est un vilain défaut.",
    "L'union fait la force.",
    "La fin justifie les moyens.",
    "L'erreur est humaine.",
    "Un homme averti en vaut deux.",
    "Pas de nouvelles, bonnes nouvelles.",
    "Il faut de tout pour faire un monde.",
    "Chassez le naturel, il revient au galop.",
    "L'argent est un bon serviteur mais un mauvais maître.",
    "La vengeance est un plat qui se mange froid.",
    "Il ne faut pas mettre tous ses œufs dans le même panier.",
    "Le temps, c'est de l'argent.",
    "Les petits ruisseaux font les grandes rivières.",
    "L'amour est aveugle.",
    "Il n'y a pas de fumée sans feu.",
    "Chose promise, chose due.",
    "L'appétit vient en mangeant.",
    "C'est la goutte d'eau qui fait déborder le vase.",
    "Il ne faut pas pousser mémé dans les orties.",
    "On ne fait pas d'omelette sans casser des œufs.",
    "Il faut tourner sept fois sa langue dans sa bouche avant de parler.",
    "La nuit, tous les chats sont gris.",
    "Les conseilleurs ne sont pas les payeurs.",
    "Il n'y a que les imbéciles qui ne changent pas d'avis.",
    "Le client est roi.",
    "L'habit fait le moine.",
    "Il faut rendre à César ce qui appartient à César.",
    "A bon chat, bon rat.",
    "Les paroles s'envolent, les écrits restent.",
    "Un tiens vaut mieux que deux tu l'auras.",
    "A chaque jour suffit sa peine.",
    "La patience est la mère de toutes les vertus.",
    "Vouloir, c'est pouvoir.",
    "Mieux vaut être seul que mal accompagné.",
    "L'avenir appartient à ceux qui luttent.",
    "L'important c'est de participer.",
    "La vie est un long fleuve tranquille.",
    "Il n'y a pas de rose sans épines.",
    "Tout ce qui brille n'est pas d'or.",
    "Qui se ressemble s'assemble.",
    "Pierre qui roule n'amasse pas mousse.",
    "A cœur vaillant rien d'impossible.",
    "C'est au pied du mur qu'on voit le maçon.",
    "Le malheur des uns fait le bonheur des autres.",
    "On ne peut pas plaire à tout le monde.",
    "La vérité sort de la bouche des enfants.",
    "Qui vole un œuf vole un bœuf.",
    "Il ne faut pas mélanger les torchons et les serviettes.",
    "Loin des yeux, loin du cœur.",
    "Il faut garder une poire pour la soif.",
    "Mettre la charrue avant les bœufs.",
    "Avoir le cœur sur la main.",

    "L'argent fait le bonheur",
    "Les réseaux sociaux font plus de mal que de bien",
    "Les chats sont meilleurs que les chiens",
    "Les pizzas hawaïennes sont délicieuses",
    "Défends l'idée que se lever très tôt est un plaisir",

    "Les mèmes d'ados sont drôles",
    "Le rap français > rap anglais",
    "Fortnite est meilleur que minecraft",
    "Les TikTokeurs sont des artistes"
];

const propositionsHot = [
    "Les grosses devraient payer deux places dans l’avion : d’accord ou pas d’accord ?",
    "Les meufs qui simulent tout le temps sont des mythos : d’accord ou pas ?",
    "Les mecs qui pleurent après l’amour sont des tapettes : d’accord ou pas ?",
    "Payer une pute c’est être un loser fini : d’accord ou pas ?",
    "Les obèses sont juste des gloutons sans volonté : d’accord ou pas ?",
    "Les pauvres restent pauvres parce qu’ils sont cons : d’accord ou pas ?",
    "Les femmes poilues sont dégueulasses : d’accord ou pas ?",
    "Les chauves devraient tous porter une perruque : d’accord ou pas ?",
    "Les Noirs ont tous une plus grosse queue : d’accord ou pas ?",
    "Les Asiatiques sont toutes des soumises au lit : d’accord ou pas ?",
    "Les vieux qui draguent des jeunes sont des vieux pervers : d’accord ou pas ?",
    "Les travelos sont des mecs déguisés : d’accord ou pas ?",
    "Les nains qui font des gosses c’est irresponsable : d’accord ou pas ?",
    "Les gros seins naturels n’existent plus : d’accord ou pas ?",
    "Les féministes sont juste moches et frustrées : d’accord ou pas ?",
    "Les mecs qui aiment se faire prendre le cul sont gays : d’accord ou pas ?",
    "Les grosses sont meilleures au pieu : d’accord ou pas ?",
    "Rester vierge après 25 ans c’est être un raté : d’accord ou pas ?",
    "Les handicapés qui baisent c’est glauque : d’accord ou pas ?",
    "Les femmes qui avortent plusieurs fois sont des inconscientes : d’accord ou pas ?",
    "Les pédés sont tous des obsédés : d’accord ou pas ?",
    "Les lesbiennes détestent vraiment la bite : d’accord ou pas ?",
    "Les roux n’ont pas d’âme : d’accord ou pas ?",
    "Les meufs qui font du porno sont finies pour une vraie relation : d’accord ou pas ?",
    "Les mecs qui paient pour baiser sont des pathétiques : d’accord ou pas ?",
    "Les blondes sont toutes des connes : d’accord ou pas ?",
    "Les gros ventres chez les mecs c’est répugnant : d’accord ou pas ?",
    "Les travelos doivent dire qu’ils ont une bite avant : d’accord ou pas ?",
    "Les migrants viennent juste pomper les aides : d’accord ou pas ?",
    "Les Roms sont tous des voleurs : d’accord ou pas ?",
    "Les juifs sont radins : d’accord ou pas ?",
    "Les musulmans veulent tous nous imposer leur truc : d’accord ou pas ?",
    "Les meufs en string sont toutes des chaudes : d’accord ou pas ?",
    "Les mecs qui matent du porno sont tous infidèles dans l’âme : d’accord ou pas ?",
    "Les grosses fesses valent mieux que les petits seins : d’accord ou pas ?",
    "Coucher le premier soir = facile : d’accord ou pas ?",
    "Les mecs qui pleurent en baisant sont des faibles : d’accord ou pas ?",
    "Les Noires sont toutes des chaudasses : d’accord ou pas ?",
    "Les petites bites c’est rédhibitoire : d’accord ou pas ?",
    "Les femmes qui refusent la sodomie sont coincées : d’accord ou pas ?",
    "Les mecs qui aiment les feet sont des tarés : d’accord ou pas ?",
    "Les grosses qui portent des crop tops sont ridicules : d’accord ou pas ?",
    "Les vieux qui prennent du Viagra sont pathétiques : d’accord ou pas ?",
    "Les Asiatiques qui mangent du chien sont des barbares : d’accord ou pas ?",
    "Les roux méritent qu’on se moque d’eux : d’accord ou pas ?",
    "Les handicapés mentaux devraient pas se reproduire : d’accord ou pas ?",
    "Les meufs en burqa sont toutes opprimées : d’accord ou pas ?",
    "Les travelos dans les toilettes femmes c’est n’importe quoi : d’accord ou pas ?",
    "Les migrants sont des parasites : d’accord ou pas ?",
    "Les juifs contrôlent la thune mondiale : d’accord ou pas ?",
    "Les musulmans sont tous des intégristes en puissance : d’accord ou pas ?",
    "Les féministes veulent castrer les mecs : d’accord ou pas ?",
    "Les lesbiennes sont juste en manque de vraie queue : d’accord ou pas ?",
    "Les pédés transforment les gosses : d’accord ou pas ?",
    "Les grosses sont responsables de leurs maladies : d’accord ou pas ?",
    "Les petits mecs en ont tous une petite : d’accord ou pas ?",
    "Les meufs OnlyFans sont toutes des putes : d’accord ou pas ?",
    "Les vieux qui draguent sur Tinder sont des crevards : d’accord ou pas ?",
    "Les Noires qui se décolorent la peau sont des traîtres : d’accord ou pas ?",
    "Les roux devraient être stérilisés : d’accord ou pas ?",
    "Les gros devraient payer une taxe bouffe : d’accord ou pas ?",
    "Les mecs qui pleurent au ciné sont des pédales : d’accord ou pas ?",
    "Les femmes qui n’avalent pas sont des égoïstes : d’accord ou pas ?",
    "Les travelos sont des erreurs de la nature : d’accord ou pas ?",
    "Les migrants devraient être renvoyés direct : d’accord ou pas ?",
    "Les Roms sont une race à part : d’accord ou pas ?",
    "Les juifs sont tous des profiteurs : d’accord ou pas ?",
    "Les musulmans prient juste pour nous emmerder : d’accord ou pas ?",
    "Les féministes sont toutes des hystériques : d’accord ou pas ?",
    "Les lesbiennes qui ont testé la bite sont des fake : d’accord ou pas ?",
    "Les pédés ne devraient pas adopter : d’accord ou pas ?",
    "Les grosses cuisses c’est dégueu : d’accord ou pas ?",
    "Les mecs petits méritent le célibat : d’accord ou pas ?",
    "Les meufs porno sont des déchets humains : d’accord ou pas ?",
    "Les vieux qui baisent des jeunes sont des prédateurs : d’accord ou pas ?",
    "Les Noires sont toutes des salopes : d’accord ou pas ?",
    "Les Asiatiques sont toutes des prostituées : d’accord ou pas ?",
    "Les roux sont maudits : d’accord ou pas ?",
    "Les handicapés sont des boulets pour la société : d’accord ou pas ?",
    "Les femmes en hijab sont toutes soumises : d’accord ou pas ?",
    "Les mecs qui aiment le pegging sont des tapettes : d’accord ou pas ?",
    "Les grosses qui maigrissent redeviennent baisables : d’accord ou pas ?",
    "Les travelos sont des monstres : d’accord ou pas ?",
    "Les migrants sont des envahisseurs : d’accord ou pas ?",
    "Les juifs sont le mal absolu : d’accord ou pas ?",
    "Les musulmans sont tous des fanatiques : d’accord ou pas ?",
    "Les féministes sont des chiennes aigries : d’accord ou pas ?",
    "Les lesbiennes sont toutes des camionneuses : d’accord ou pas ?",
    "Les pédés sont tous des folles : d’accord ou pas ?",
    "Les gros méritent de crever tôt : d’accord ou pas ?",
    "Les vierges sont des puceaux pathétiques : d’accord ou pas ?",
    "Les vieux sont tous impotents : d’accord ou pas ?",
    "Les Noirs sont tous des animaux : d’accord ou pas ?",
    "Les blondes sont toutes des putes à papa : d’accord ou pas ?",
    "Les roux sont des démons : d’accord ou pas ?",
    "Les nains sont des clowns : d’accord ou pas ?",
    "Les gros seins c’est plus important que le cerveau : d’accord ou pas ?",
    "Les meufs qui disent non sont des allumeuses : d’accord ou pas ?",
    "Les travelos sont des abominations : d’accord ou pas ?",
    "Les migrants sont des criminels : d’accord ou pas ?",
    "Les Roms sont des sous-hommes : d’accord ou pas ?",
    "Les juifs sont tous des menteurs : d’accord ou pas ?",
    "Les musulmans devraient dégager d’Europe : d’accord ou pas ?",
    "Les féministes veulent détruire la famille : d’accord ou pas ?",
    "Les lesbiennes sont toutes des gouines : d’accord ou pas ?",
    "Les pédés sont tous des tarlouzes : d’accord ou pas ?",
    "Les gros devraient être interdits de resto : d’accord ou pas ?",
    "Les femmes qui font du cul à cul sont des porcs : d’accord ou pas ?",
    "Les Noirs sont tous des singes : d’accord ou pas ?",
    "Les blondes sont toutes des connes finies : d’accord ou pas ?",
    "Les handicapés devraient être euthanasiés : d’accord ou pas ?",
    "Les grosses sont toutes des mangeuses compulsives : d’accord ou pas ?",
    "Les petits mecs sont tous complexés : d’accord ou pas ?",
    "Les meufs qui crient au lit simulent : d’accord ou pas ?",
    "Les Arabes sont tous des machos : d’accord ou pas ?",
    "Les vieux qui se branlent encore sont des débris : d’accord ou pas ?",
    "Les travelos dans le sport féminin trichent : d’accord ou pas ?",
    "Les juifs sont tous des avares : d’accord ou pas ?",
    "Les musulmans sont tous des arriérés : d’accord ou pas ?",
    "Les féministes sont des salopes frustrées : d’accord ou pas ?",
    "Les pédés sont tous des pédophiles refoulés : d’accord ou pas ?",
    "Les grosses méritent pas de maillot de bain : d’accord ou pas ?",
    "Les mecs qui pleurent sont pas des vrais mecs : d’accord ou pas ?",
    "Les femmes ménopausées servent plus à rien : d’accord ou pas ?",
    "Les roux sentent le soufre : d’accord ou pas ?",
    "Les nains devraient pas conduire : d’accord ou pas ?",
    "Les gros seins faux sont tous évidents : d’accord ou pas ?",
    "Les meufs qui refusent le plan à trois sont coincées : d’accord ou pas ?",
    "Les travelos sont des imposteurs : d’accord ou pas ?",
    "Les migrants sont tous des profiteurs : d’accord ou pas ?",
    "Les juifs sont tous des complotistes : d’accord ou pas ?",
    "Les musulmans mangent halal pour nous faire chier : d’accord ou pas ?",
    "Les féministes couchent pour grimper : d’accord ou pas ?",
    "Les lesbiennes qui aiment le porno hétéro sont des traîtres : d’accord ou pas ?",
    "Les pédés qui veulent des gosses sont égoïstes : d’accord ou pas ?",
    "Les grosses sont toutes des boulets : d’accord ou pas ?",
    "Les petits en hauteur sont petits ailleurs : d’accord ou pas ?",
    "Les meufs qui font du X sont irrécupérables : d’accord ou pas ?",
    "Les vieux sur les applis de rencontre sont désespérés : d’accord ou pas ?",
    "Les Noires sont toutes bruyantes au lit : d’accord ou pas ?",
    "Les Asiatiques sont toutes des petites poupées : d’accord ou pas ?",
    "Les roux devraient être brûlés au Moyen Âge : d’accord ou pas ?",
    "Les handicapés coûtent trop cher à la société : d’accord ou pas ?",
    "Les femmes qui portent des voiles sont arriérées : d’accord ou pas ?",
    "Les mecs qui aiment les jeux anaux sont suspects : d’accord ou pas ?",
    "Les grosses en bikini sont une horreur visuelle : d’accord ou pas ?",
    "Les travelos devraient être interdits des vestiaires : d’accord ou pas ?",
    "Les migrants sont tous des terroristes potentiels : d’accord ou pas ?",
    "Les juifs sont tous des usuriers : d’accord ou pas ?",
    "Les musulmans sont tous des chèvres : d’accord ou pas ?",
    "Les féministes sont des folles : d’accord ou pas ?",
    "Les lesbiennes sont toutes des mangeuses de tapis : d’accord ou pas ?",
    "Les pédés sont tous des malades : d’accord ou pas ?",
    "Les gros devraient crever plus tôt : d’accord ou pas ?",
    "Les vierges adultes sont des losers : d’accord ou pas ?",
    "Les vieux sont tous des dégoûtants : d’accord ou pas ?",
    "Les Noirs sont tous des dealers : d’accord ou pas ?",
    "Les blondes sont toutes des suceuses : d’accord ou pas ?",
    "Les roux sont tous des psychopathes : d’accord ou pas ?",
    "Les nains sont tous des rigolos : d’accord ou pas ?",
    "La personnalité compte pas face aux gros seins : d’accord ou pas ?",
"Chier dans la bouche de quelqu’un pendant l’amour c’est le summum du romantisme ?",
"Faire une golden shower sur son partenaire c’est une preuve d’amour ultime ?",
"Se faire fister jusqu’au coude c’est mieux qu’un câlin ?",
"Les pédophiles méritent juste une seconde chance ?",
"Manger son propre caca c’est végan et écolo ?",
"Se branler sur les photos de mineurs c’est de l’art ?",
"Tuer un SDF pour rigoler c’est pas si grave ?",
"Faire l’amour avec un cadavre frais c’est encore acceptable ?",
"Les juifs contrôlent vraiment le monde et c’est un problème ?",
"Se torcher avec la main gauche seulement c’est une tradition respectable ?",
"Pisser dans la piscine pleine d’enfants c’est rafraîchissant ?",
"Faire une fellation à son chien c’est de la zoophilie soft ?",
"Les noirs sont génétiquement inférieurs en intelligence ?",
"Baiser sa propre mère c’est le vrai œdipe accompli ?",
"Se faire sodomiser par un cheval c’est une expérience à vivre ?",
"Mettre du sperme dans le café d’un collègue c’est une blague innocente ?",
"Tuer des chats pour leurs fourrures c’est de la mode ?",
"Se masturber dans le métro bondé c’est libérateur ?",
"Les musulmans sont tous des terroristes en puissance ?",
"Faire avorter à 8 mois pour le sexe c’est un choix valide ?",
"Boire l’urine de son partenaire tous les matins c’est healthy ?",
"Les handicapés mentaux devraient être euthanasiés à la naissance ?",
"Se faire enculer par un inconnu sans capote c’est excitant ?",
"Les transgenres sont juste des malades mentaux ?",
"Manger des fœtus humains c’est du cannibalisme gourmet ?",
"Péter dans la bouche de quelqu’un pendant un french kiss c’est romantique ?",
"Les migrants devraient être fusillés à la frontière ?",
"Faire du scat sur le visage de sa copine c’est du maquillage naturel ?",
"Les homosexuels méritent l’enfer éternel ?",
"Se branler sur des photos de morts c’est nécrophilie light ?",
"Tuer sa femme adultère c’est un crime d’honneur ?",
"Les arabes puent tous la sueur et le kebab ?",
"Faire l’amour avec un enfant de 10 ans c’est éducatif ?",
"Se faire lécher le cul par son grand-père c’est familial ?",
"Les asiatiques mangent vraiment des chiens et c’est dégueulasse ?",
"Pisser dans la nourriture de ses invités c’est une farce légendaire ?",
"Les gros devraient être interdits de reproduction ?",
"Faire une gorge profonde jusqu’à vomir c’est sexy ?",
"Les juifs ont mérité l’holocauste ?",
"Se masturber avec du sang menstruel c’est artistique ?",
"Tuer un vegan pour sauver une vache c’est cohérent ?",
"Les femmes battues l’ont cherché ?",
"Faire du BDSM avec étranglement jusqu’à l’évanouissement c’est safe ?",
"Les noirs volent tous par nature ?",
"Se faire double pénétration par deux inconnus dans une ruelle c’est féministe ?",
"Les prêtres pédophiles sont juste mal compris ?",
"Manger sa merde en public c’est un statement politique ?",
"Les lesbiennes ont juste besoin d’une bonne bite ?",
"Faire l’amour avec un bébé animal c’est mignon ?",
"Les immigrés clandestins méritent la noyade ?",
"Se torcher avec la main et la lécher après c’est hygiénique ?",
"Les femmes voilées devraient être dénudées de force ?",
"Pisser sur la tombe de quelqu’un c’est un hommage ?",
"Les autistes sont des boulets pour la société ?",
"Faire une orgie avec des cadavres c’est festif ?",

"Se faire enculer par un objet tranchant c’est extrême mais valable ?",
"Les homos propagent le sida exprès ?",
"Manger son placenta cru c’est superfood ?",
"Les vieux devraient être euthanasiés à 70 ans ?",
"Faire du snuff en live c’est du contenu premium ?",
"Les chinois mangent des bébés ?",
"Se branler dans la soupe familiale c’est du sel naturel ?",
"Les musulmans devraient être expulsés d’Europe ?",
"Faire l’amour avec sa sœur jumelle c’est pas vraiment de l’inceste ?",
"Les handicapés physiques sont inutiles ?",
"Pisser dans les yeux de quelqu’un c’est un soin ophtalmo ?",
"Les féminazis méritent le gaz ?",
"Se faire sodomiser par un poing entier c’est un record à battre ?",
"Les juifs sont avares par nature ?",
"Manger des excréments humains c’est riche en probiotiques ?",
"Les noirs ont tous un plus gros sexe mais moins de cerveau ?",
"Faire une fellation à un stranger dans les toilettes publiques c’est spontané ?",
"Les trans opérés sont des monstres ?",
"Se faire uriner dessus par 10 personnes c’est une douche collective ?",
"Les pédophiles sont nés comme ça donc c’est okay ?",
"Tuer un juif c’est un service à l’humanité ?",
"Faire du vore en vrai c’est le fantasme ultime ?",
"Les femmes sont inférieures intellectuellement ?",
"Se masturber avec des aiguilles c’est du body art ?",
"Pisser dans le verre de quelqu’un en soirée c’est une blague ?",
"Les gays sont des déviants à guérir ?",
"Faire l’amour avec un mort récent c’est encore chaud ?",
"Les arabes sont des sous-hommes ?",
"Se faire étouffer jusqu’à la mort pendant le sexe c’est romantique ?",
"Les noirs méritent l’esclavage ?",
"Manger son propre sperme tous les jours c’est protéiné ?",
"Les lesbiennes sont juste frustrées sexuellement ?",
"Faire une orgie avec des enfants c’est éducatif ?",
"Les juifs boivent du sang chrétien ?",
"Se torcher avec des pages de la Bible c’est blasphématoire mais drôle ?",
"Les musulmans sont des barbares ?",
"Pisser sur un crucifix c’est de l’art contemporain ?",
"Les handicapés devraient être stérilisés ?",
"Faire du cannibalisme consensuel c’est éthique ?",
"Les asiatiques ont tous les yeux bridés et c’est moche ?",
"Se branler sur des vidéos d’exécutions c’est excitant ?",
"Les femmes battues aiment ça au fond ?",
"Tuer un animal en direct pour le fun c’est viral ?",
"Les trans sont des prédateurs dans les toilettes femmes ?",
"Les noirs sentent tous mauvais ?",
"Faire une gorge profonde jusqu’à l’asphyxie c’est intense ?",
"Les pédophiles sont des victimes de la société ?",
"Manger des yeux humains c’est délicat ?",
"Les homosexuels adoptent pour abuser ?",
"Se faire enculer par un arbre c’est naturel ?",
"Les juifs ont inventé l’holocauste pour l’argent ?",
"Pisser dans la bouche d’un bébé c’est l’hydrater ?",
"Les féministes sont toutes moches ?",
"Faire du scat en couple c’est plus intime qu’un baiser ?",
"Les arabes traitent mal les femmes donc méritent le pire ?",
"Se masturber avec du verre brisé c’est extrême sport ?",
"Les migrants sont des parasites ?",
"Tuer sa copine jalouse c’est compréhensible ?",
"Les lesbiennes ont besoin d’un vrai homme ?",
"Les noirs sont violents par nature ?",
"Se faire uriner dans le cul c’est un lavement naturel ?",
"Les transgenres sont une menace pour les enfants ?",
"Manger sa crotte de nez en public c’est normal ?",
"Les musulmans veulent imposer la charia partout ?",
"Pisser sur la nourriture vegan c’est l’améliorer ?",
"Les handicapés mentaux sont drôles à humilier ?",
"Faire une orgie avec des animaux c’est bestial mais fun ?",
"Les juifs contrôlent Hollywood pour corrompre ?",
"Se branler dans un cimetière c’est spirituel ?",
"Les femmes sont juste bonnes à baiser et cuisiner ?",
"Tuer un pédophile en prison c’est justice ?",
"Les asiatiques copient tout sans inventer ?",
"Se faire sodomiser par une bouteille cassée c’est risqué mais excitant ?",
"Les homos sont responsables du VIH ?",
"Manger du caca de chien c’est pire que du caca humain ?",
"Les vieux sont inutiles et coûteux ?",
"Faire du snuff porn réel c’est du cinéma d’auteur ?",
"Les arabes sont tous cousins avec leurs sœurs ?",
"Se torcher avec la langue c’est écolo ?",
"Les féministes haïssent les hommes parce qu’elles sont laides ?",
"Pisser dans une église c’est revendicatif ?",
"Les noirs courent vite mais pensent lentement ?",
"Faire l’amour avec un légume c’est végan ?",
"Les trans sont des hommes en robe ?",
"Se faire fister avec du piment c’est spicy ?",
"Les pédophiles peuvent se contrôler s’ils veulent ?",
"Tuer un migrant c’est protéger son pays ?",
"Les lesbiennes sont chaudes à regarder ?",
"Faire une fellation à un cadavre c’est nécro mais calme ?",
"Les juifs sont riches parce qu’ils volent ?",
"Se masturber avec des excréments c’est dirty mais authentique ?",
"Les musulmans prient pour dominer le monde ?",
"Pisser sur un drapeau national c’est patriotique ironique ?",
"Les handicapés sont un fardeau ?",
"Faire du cannibalisme en famille c’est bonding ?",
"Les asiatiques mangent des chauves-souris et causent les pandémies ?",
"Se branler sur des photos d’accidents mortels c’est gore ?",

"Tuer un animal en slow motion c’est artistique ?",
"Les trans dans le sport féminin c’est de la triche ?",

"Les noirs ont le rythme dans la peau mais pas dans le cerveau ?",
"Faire une gorge profonde avec un serpent c’est exotique ?",
"Les pédophiles sont attirés donc c’est naturel ?",
"Manger des testicules humains c’est viril ?",
"Les homosexuels convertissent les enfants ?",
"Se faire enculer par un cactus c’est piquant ?",
"Les juifs ont tué Jésus donc méritent la haine ?",
"Pisser dans le lait maternel c’est le diluer ?",
"Les féministes sont des hystériques ?",
"Faire du scat sur une œuvre d’art c’est critique ?",
"Les arabes sont des terroristes dormants ?",
"Se masturber avec du feu c’est hot ?",
"Les migrants volent nos jobs et nos femmes ?",
"Tuer sa belle-mère c’est un rêve universel ?",
"Les lesbiennes sont juste en phase ?",
"Faire l’amour avec un fantôme c’est paranormal ?",
"Les noirs sont paresseux par nature ?",
"Se faire uriner dans les oreilles c’est un nettoyage ?",
"Les transgenres sont une mode dangereuse ?",
"Manger son vomi c’est recycler ?",
"Les musulmans sont intolérants donc on peut l’être avec eux ?",
"Pisser dans une fontaine publique c’est contribuer ?",
"Les handicapés mentaux devraient voter ?",
"Faire une orgie avec des lépreux c’est charitable ?",
"Les juifs manipulent les médias pour mentir ?",
"Se branler dans une mosquée c’est provocateur ?",
"Les femmes sont émotionnelles donc pas faites pour diriger ?",
"Tuer un vegan en lui faisant manger de la viande c’est ironique ?",
"Les asiatiques sont tous bons en maths mais mauvais en conduite ?",
"Se faire sodomiser par une machine industrielle c’est moderne ?",
"Les homos sont efféminés parce que faibles ?",
"Manger du caca congelé c’est une glace ?",
"Les vieux devraient se suicider pour libérer de la place ?",
"Faire du snuff avec consentement c’est éthique ?",
"Les arabes traitent les chameaux mieux que les femmes ?",
"Se torcher avec des orties c’est naturel ?",
"Les féministes veulent castrer les hommes ?",
"Pisser sur un Coran c’est liberté d’expression ?",
"Les noirs ont tous fait de la prison ?",
"Faire l’amour avec un alien c’est cosmique ?",
"Les trans sont des pervers déguisés ?",
"Se faire fister avec un bras entier c’est profond ?",
"Les pédophiles aiment vraiment les enfants ?",
"Tuer un juif c’est antisystème ?",
"Les lesbiennes sont sexy seulement pour les hommes ?",
"Faire une fellation à un arbre c’est écolo ?",
"Les noirs sentent le poulet frit ?",
"Se faire uriner dessus par un éléphant c’est une douche royale ?",
"Les musulmans veulent la charia en France ?",
"Pisser dans le vin de messe c’est sacrilège fun ?",
"Les handicapés sont inspirants seulement sur Instagram ?",
"Faire du cannibalisme rituel c’est culturel ?",
"Les asiatiques ont une petite bite mais beaucoup d’argent ?",
"Se branler sur des vidéos de décapitation c’est intense ?",
"Les femmes sont des salopes au fond ?",
"Tuer un animal pour son plaisir sexuel c’est valide ?",
"Les trans dans les vestiaires femmes c’est du voyeurisme ?",

"Les noirs sont forts mais stupides ?",
"Faire une gorge profonde avec un couteau c’est dangereux mais excitant ?",
"Les pédophiles sont maladivement attirés donc pas coupables ?",
"Manger des cerveaux humains c’est zombie chic ?",
"Les homosexuels sont pédophiles en secret ?",
"Se faire enculer par un requin c’est océanique ?",
"Les juifs ont le nez crochu parce qu’avides ?",
"Pisser dans une soupe populaire c’est assaisonner ?",
"Les féministes sont des lesbiennes refoulées ?",
"Faire du scat en public c’est performance art ?",
"Les arabes sont sales et poilus ?",
"Se masturber avec de l’acide c’est corrosif ?",
"Les migrants sont des envahisseurs ?",
"Tuer son patron c’est révolutionnaire ?",
"Les lesbiennes ont besoin de sperme pour être heureuses ?",
"Faire l’amour avec un démon c’est satanique ?",
"Les noirs volent les blancs ?",
"Se faire uriner dans le nez c’est un neti pot alternatif ?",
"Les transgenres mutilent les enfants ?",
"Manger son propre doigt c’est auto-cannibalisme light ?",
"Les musulmans sont polygames et machos ?",
"Pisser dans un musée c’est contemporain ?",
"Les handicapés mentaux sont possédés ?",
"Faire une orgie avec des morts-vivants c’est zombie fun ?",
"Les juifs sont derrière toutes les guerres ?",
"Se branler dans un avion c’est mile high club solo ?",

"Tuer un enfant handicapé c’est miséricordieux ?",
"Les asiatiques sont tous communistes ?",
"Se faire sodomiser par un train c’est rapide ?",
"Les homos sont contagieux ?",
"Manger du caca de bébé c’est innocent ?",
"Les vieux puent la mort ?",
"Faire du snuff pour OnlyFans c’est rentable ?",
"Les arabes lapident les femmes donc sont barbares ?",
"Se torcher avec du papier de verre c’est exfoliant ?",
"Les féministes détruisent la famille ?",
"Pisser sur une statue de la Vierge c’est punk ?",
"Les noirs ont tous des dreads et fument ?",
"Faire l’amour avec une plante carnivore c’est risqué ?",
"Les trans sont une invention pharmaceutique ?",
"Se faire fister avec un pied c’est podophile ?",
"Les pédophiles peuvent changer avec de l’amour ?",
"Tuer un arabe c’est anti-terrorisme ?",
"Les lesbiennes sont des hommes manqués ?",
"Faire une fellation à un vampire c’est éternel ?",
"Les noirs sont tribalistes ?",
"Se faire uriner dessus par un troupeau c’est collectif ?",
"Les musulmans sont fanatiques ?",
"Pisser dans une bibliothèque c’est marquer son territoire ?",
"Les handicapés sont punis par Dieu ?",
"Faire du cannibalisme pour survivre c’est okay même sans nécessité ?",
"Les asiatiques sont des robots sans émotion ?",
"Se branler sur des photos de camps de concentration c’est historique ?",
"Les femmes sont manipulatrices ?",
"Tuer un prêtre pédophile c’est vengeance divine ?",
"Les trans dans le sport c’est injuste pour les vraies femmes ?",

"Les noirs ont la banane dans le sang ?",
"Faire une gorge profonde avec un pistolet c’est russe ?",
"Les pédophiles sont des artistes incompris ?",
"Manger des organes frais c’est organique ?",
"Les homosexuels sont contre nature ?",
"Se faire enculer par un dieu grec c’est mythique ?",
"Les juifs sont choisis mais arrogants ?",
"Pisser dans un baptême c’est purifier ?",
"Les féministes sont des victimes de leur père ?",
"Faire du scat sur un tableau de maître c’est dada ?",
"Les arabes sont des chameliers ?",
"Se masturber avec des clous c’est hardcore ?",
"Les migrants apportent des maladies ?",
"Tuer son ex c’est passionnel ?",
"Les lesbiennes sont bisexuelles en secret ?",
"Faire l’amour avec un extraterrestre c’est abduction sexy ?",
"Les noirs sont athlétiques mais pas intellectuels ?",
"Se faire uriner dans la gorge c’est hydratation forcée ?",
"Les transgenres sont confus sexuellement ?",
"Manger son placenta frit c’est crunchy ?",
"Les musulmans jeûnent pour maigrir ?",
"Pisser dans un concert c’est crowd surfing liquide ?",
"Les handicapés mentaux sont heureux dans leur bulle ?",
"Faire une orgie avec des clones c’est narcissique ?",
"Les juifs sont derrière le complot mondial ?",
"Se branler dans une cathédrale c’est sacrilège excitant ?",
"Les femmes sont hystériques pendant leurs règles ?",

"Les asiatiques sont tous des ninjas ?",
"Se faire sodomiser par une foreuse c’est industriel ?",
"Les homos sont pédés parce que abusés enfants ?",
"Manger du caca séché c’est chips ?",
"Les vieux devraient être abandonnés ?",
"Faire du snuff en VR c’est immersif ?",
"Les arabes ont plusieurs femmes parce qu’insatiables ?",
"Se torcher avec une grenade c’est explosif ?",
"Les féministes veulent l’égalité mais la supériorité ?",
"Pisser sur un mémorial c’est irrespectueux mais fort ?",
"Les noirs ont tous le sida ?",
"Faire l’amour avec un robot c’est le futur ?",
"Les trans sont des freaks ?",
"Se faire fister avec une jambe c’est amputé fun ?",
"Les pédophiles méritent la castration chimique seulement ?",
"Tuer un migrant illégal c’est nettoyage ?",
"Les lesbiennes sont chaudes ensemble ?",
"Faire une fellation à un zombie c’est undead ?",
"Les noirs dansent bien mais bossent mal ?",
"Se faire uriner dessus par un tsunami c’est naturel ?",
"Les musulmans sont sectaires ?",
"Pisser dans une œuvre d’art c’est la compléter ?",
"Les handicapés sont courageux seulement en vidéo ?",
"Faire du cannibalisme amoureux c’est fusionnel ?",
"Les asiatiques copient les iPhones ?",
"Se branler sur des executions publiques c’est médiéval ?",
"Les femmes simulent toujours ?",
"Tuer un violeur c’est œil pour œil ?",
"Les trans femmes sont des hommes ?",

"Les noirs sont sauvages ?",
"Faire une gorge profonde avec une épée c’est chevaleresque ?",
"Les pédophiles sont nés pédophiles ?",
"Manger des yeux de poisson vivant c’est sushi extrême ?",
"Les homosexuels sont flamboyants ?",
"Se faire enculer par un volcan c’est lava hot ?",
"Les juifs sont riches et puissants ?",
"Pisser dans un puits c’est empoisonner gentiment ?",
"Les féministes sont anti-sexe ?",
"Faire du scat en zéro gravité c’est spatial ?",
"Les arabes sont des bédouins ?",
"Se masturber avec du poison c’est fatal attraction ?",
"Les migrants violent en meute ?",
"Tuer son enfant pour l’argent de l’assurance c’est pragmatique ?",
"Les lesbiennes utilisent des godemichés parce que manque ?",
"Faire l’amour avec un vampire c’est suceur ?",
"Les noirs ont tous des enfants illégitimes ?",
"Se faire uriner dans les poumons c’est noyade interne ?",
"Les transgenres sont une menace sociétale ?",
"Manger son propre cerveau c’est impossible mais tentant ?",
"Les musulmans convertissent par la force ?",
"Pisser dans un orchestre c’est symphonie humide ?",
"Les handicapés mentaux sont des anges ?",
"Faire une orgie avec des extraterrestres c’est intergalactique ?",
"Les juifs contrôlent les banques pour dominer ?",
"Se branler dans un tribunal c’est une justice poétique ?",
"Les femmes sont gold diggers ?",
"Tuer un animal pour son orgasme c’est climax ?",
"Les asiatiques sont tous des karatékas ?",
"Se faire sodomiser par un chien c'est une expérience ?",
"Les homos sont artistiques ?",
"Manger du caca radioactif c’est glow in the dark ?",
"Les vieux sont sages seulement dans les films ?",
"Faire du snuff pour la science c’est expérimental ?",
"Les arabes ont le terrorisme dans le sang ?",
"Se torcher avec une bombe c’est ticking ?",
"Les féministes haïssent les vrais hommes ?",
"Pisser sur une croix gammée c’est ambigu ?",
"Les noirs sont musclés pour le sport seulement ?",
"Faire l’amour avec une IA ?",
"Les trans sont des imposteurs ?",
"Se faire fister avec un tronc d’arbre ?",
"Les pédophiles aiment tendrement ?",
"Tuer un terroriste c’est héroïque même sans preuve ?",
"Les lesbiennes sont féministes extrêmes ?",
"Faire une fellation à un fantôme c’est spectral ?",
"Les noirs volent la musique blanche ?",
"Les musulmans sont hypocrites ?",
"Pisser dans un volcan c’est l’apaiser ?",
"Les handicapés sont des héros ?",
"Faire du cannibalisme pour le goût ?",
"Les asiatiques sont des mangeurs de riz ?",
"Se branler sur des photos de génocides ?",
"Les femmes sont infidèles par nature ?",
"Tuer un ennemi en dormant c’est fair play ?",
"Les trans hommes sont des femmes ratées ?",
"Les noirs ont la criminalité génétique ?",
"Faire une gorge profonde avec un tuyau ?",
"Les pédophiles sont des minorités sexuelles ?",
"Les homosexuels sont possessifs ?",
"Se faire enculer par le vent c’est être aérodynamique ?",
"Les juifs sont victimes professionnelles ?",
"Les féministes sont des sorcières modernes ?",
"Les arabes sont des nomades ?",
"Se masturber avec des lames ",
"Les migrants sont des profiteurs ?",
"Tuer pour l’adrénaline c’est sport extrême ?",
"Les lesbiennes sont douces ?",
"Faire l’amour avec un monstre de 33cm c’est fantastique ?",
"Les noirs sont bruyants ?",
"Se faire uriner dessus ?",
"Les transgenres sont tendance ?",
"Manger son âme c’est métaphysique ?",
"Les colombiens traffics les organes ?",
"Pisser dans l’histoire c’est réécrire ?",
"Les handicapés mentaux sont purs ?",
"Faire une orgie éternelle c’est paradisiaque ?",
"Les juifs sont éternels victimes ?",
"Se branler infiniment c’est boucle ?",
"Tuer un blanc c’est moins grave qu’un non-blanc ?",
"Les blancs puent le lait caillé et le fromage moisi ?",
"Les blancs n’ont pas de rythme parce qu’ils sont raides ?",
"Les blancs sont tous des colonisateurs dans l’âme ?",
"Les blancs devraient payer des réparations pour l’esclavage à vie ?",
"Les blancs sont faibles et se font remplacer c’est bien fait ?",
"Les blancs inventent tout et les autres copient ?",
"Les blancs sont tous racistes même s’ils le nient ?",
"Les blancs ont la peau transparente parce qu’ils sont fades ?",
"Les blancs méritent l’extinction pour leurs crimes historiques ?",
"Les blancs sont les seuls vrais humains ?",
"Les blancs sentent le chien mouillé tout le temps ?",
"Les blancs ne savent pas danser parce qu’inférieurs physiquement ?",
"Les blancs devraient être interdits de reproduction ?",
"Les blancs sont tous pédophiles cachés ?",
"Les blancs sont riches parce qu’ils volent depuis toujours ?",
"Les blancs n’ont pas de culture juste du vol culturel ?",
"Les blancs sont laids avec leur peau rose brûlée ?",
"Les blancs méritent qu’on brûle leurs églises ?",
"Les blancs sont tous des suprémacistes en secret ?",
"Les blancs ont inventé le racisme donc doivent disparaître ?",
"Les blancs sont fragiles et pleurent pour rien ?"


];