const propositionsNormal = [
    "L'argent fait le bonheur",
    "Les réseaux sociaux font plus de mal que de bien",
    "Les chats sont meilleurs que les chiens",
    "Les pizzas hawaïennes sont délicieuses",
    "Défends l'idée que se lever très tôt est un plaisir",
    "Explique pourquoi les examens sont bénéfiques pour la santé mentale",
    "Convaincs-nous que rater un bus est une chance",
    "Justifie pourquoi l'hiver est bien meilleur que l'été",
    "Défends que la pluie rend les journées plus joyeuses",
    "Explique pourquoi parler en public est relaxant",
    "Convaincs-nous que les embouteillages sont utiles",
    "Défends que faire la vaisselle est amusant",
    "Justifie pourquoi les punitions sont motivantes",
    "Explique pourquoi oublier son mot de passe est positif",

    "Convaincs-nous que les maths sont plus importantes que l'imagination",
    "Défends que ne pas avoir de vacances est une bonne chose",
    "Explique pourquoi les lundis sont les meilleurs jours",
    "Justifie pourquoi les règles strictes rendent plus libre",
    "Convaincs-nous que l'ennui est essentiel au bonheur",
    "Défends l'idée que manger froid est meilleur que manger chaud",
    "Explique pourquoi attendre est plus agréable qu'agir",
    "Justifie pourquoi perdre est plus utile que gagner",
    "Convaincs-nous que les réveils trop bruyants sont nécessaires",
    "Défends que la routine est plus excitante que l'aventure",

    "Explique pourquoi les critiques négatives sont plus utiles que les compliments",
    "Convaincs-nous que lire le mode d'emploi est passionnant",
    "Défends que les erreurs sont plus importantes que les réussites",
    "Justifie pourquoi être en retard rend la vie plus intéressante",
    "Explique pourquoi le silence est gênant",
    "Convaincs-nous que les films sans fin sont les meilleurs",
    "Défends que les mauvaises notes motivent davantage",
    "Explique pourquoi le stress améliore la créativité",
    "Justifie pourquoi la solitude est préférable à la compagnie",
    "Convaincs-nous que les surprises sont toujours une mauvaise idée",

    "Défends que les repas trop longs sont inutiles",
    "Explique pourquoi les instructions compliquées sont meilleures",
    "Justifie pourquoi les disputes renforcent les amitiés",
    "Convaincs-nous que les spoilers améliorent les films",
    "Défends l'idée que les réveils sans snooze sont idéaux",
    "Explique pourquoi les travaux de groupe sont inefficaces",
    "Justifie pourquoi parler peu est plus convaincant",
    "Convaincs-nous que les jeux vidéo rendent moins créatif",
    "Défends que les règles du jeu sont faites pour être suivies",
    "Explique pourquoi la lenteur est une qualité",

    "Justifie pourquoi les réunions longues sont productives",
    "Convaincs-nous que les imprévus sont toujours bénéfiques",
    "Défends que la critique est une preuve d'amitié",
    "Explique pourquoi les journées sans soleil sont meilleures",
    "Justifie pourquoi répéter est plus efficace qu'innover",
    "Convaincs-nous que le minimalisme est trop excessif",
    "Défends que l'école devrait durer toute l'année",
    "Explique pourquoi les délais courts sont plus confortables",
    "Justifie pourquoi les écrans fatiguent moins que les livres",
    "Convaincs-nous que le travail ennuyeux est le plus utile",

    "Défends que la perfection est atteignable",
    "Explique pourquoi les choix limités rendent plus heureux",
    "Justifie pourquoi parler lentement est ennuyeux",
    "Convaincs-nous que les mauvaises surprises sont formatrices",
    "Défends que le conformisme est rassurant",
    "Explique pourquoi les critiques publiques sont nécessaires",
    "Justifie pourquoi les horaires stricts sont libérateurs",
    "Convaincs-nous que l'échec devrait être célébré",
    "Défends que la fatigue améliore la concentration",
    "Explique pourquoi l'attente est plus satisfaisante que le résultat",

    "Défends que mentir évite souvent les conflits",
    "Explique pourquoi être trop honnête est un défaut",
    "Convaincs-nous que perdre du temps est productif",
    "Justifie pourquoi ne rien faire est un talent",
    "Défends que les décisions rapides sont mauvaises",
    "Explique pourquoi changer d'avis est une faiblesse",
    "Convaincs-nous que suivre la foule est rassurant",
    "Justifie pourquoi l'habitude vaut mieux que la nouveauté",
    "Défends que les règles non écrites sont meilleures",
    "Explique pourquoi improviser est dangereux",

    "Convaincs-nous que parler peu signifie penser plus",
    "Défends que les débats sont inutiles",
    "Explique pourquoi la majorité a toujours raison",
    "Justifie pourquoi l'autorité ne se discute pas",
    "Convaincs-nous que l'obéissance est une qualité",
    "Défends que la curiosité complique la vie",
    "Explique pourquoi poser trop de questions est nuisible",
    "Justifie pourquoi rester dans sa zone de confort est idéal",
    "Convaincs-nous que prendre des risques est irresponsable",
    "Défends que la sécurité prime toujours sur la liberté",

    "Explique pourquoi le silence vaut mieux que l'opinion",
    "Convaincs-nous que l'indifférence est une force",
    "Défends que l'émotion nuit à la logique",
    "Justifie pourquoi réfléchir trop longtemps est inutile",
    "Explique pourquoi la spontanéité est surestimée",
    "Convaincs-nous que la prévisibilité est rassurante",
    "Défends que la conformité évite les problèmes",
    "Explique pourquoi la différence dérange",
    "Justifie pourquoi se fondre dans la masse est plus sûr",
    "Convaincs-nous que l'originalité complique tout",

    "Défends que l'expérience vaut mieux que l'innovation",
    "Explique pourquoi répéter fonctionne toujours",
    "Justifie pourquoi suivre les traditions est nécessaire",
    "Convaincs-nous que le changement est risqué",
    "Défends que le passé était toujours mieux",
    "Explique pourquoi la nostalgie est fiable",
    "Justifie pourquoi moderniser est une erreur",
    "Convaincs-nous que la lenteur garantit la qualité",
    "Défends que l'effort n'est pas toujours récompensé",
    "Explique pourquoi abandonner peut être stratégique",

    "Justifie pourquoi viser petit est plus réaliste",
    "Convaincs-nous que l'ambition crée des problèmes",
    "Défends que rêver empêche d'agir",
    "Explique pourquoi l'idéal est inutile",
    "Justifie pourquoi être pragmatique est plus sage",
    "Convaincs-nous que l'espoir est trompeur",
    "Défends que le pessimisme protège",
    "Explique pourquoi prévoir le pire est rassurant",
    "Justifie pourquoi se méfier est sain",
    "Convaincs-nous que faire confiance est naïf",

    "Défends que la politesse est hypocrite",
    "Explique pourquoi la franchise blesse toujours",
    "Justifie pourquoi éviter les conflits est lâche",
    "Convaincs-nous que dire oui simplifie la vie",
    "Défends que refuser crée des tensions",
    "Explique pourquoi négocier est une perte de temps",
    "Justifie pourquoi imposer est plus efficace",
    "Convaincs-nous que diriger vaut mieux qu'écouter",
    "Défends que le pouvoir corrompt toujours",
    "Explique pourquoi contrôler rassure",
    "Les mèmes d'ados sont drôles",
    "Le rap français > rap anglais",
    "Fortnite est meilleur que minecraft",
    "Les TikTokeurs sont des artistes"
];

const propositionsHot = [
    "Les grosses devraient payer deux places dans l’avion : d’accord ou pas d’accord ?",
    "Les meufs qui simulent tout le temps sont des mythos : d’accord ou pas ?",
    "Les mecs qui pleurent après l’amour sont des tapettes : d’accord ou pas ?",
    "Payer une pute c’est être un loser fini : d’accord ou pas ?",
    "Les obèses sont juste des gloutons sans volonté : d’accord ou pas ?",
    "Les pauvres restent pauvres parce qu’ils sont cons : d’accord ou pas ?",
    "Les femmes poilues sont dégueulasses : d’accord ou pas ?",
    "Les chauves devraient tous porter une perruque : d’accord ou pas ?",
    "Les Noirs ont tous une plus grosse queue : d’accord ou pas ?",
    "Les Asiatiques sont toutes des soumises au lit : d’accord ou pas ?",
    "Les vieux qui draguent des jeunes sont des vieux pervers : d’accord ou pas ?",
    "Les travelos sont des mecs déguisés : d’accord ou pas ?",
    "Les nains qui font des gosses c’est irresponsable : d’accord ou pas ?",
    "Les gros seins naturels n’existent plus : d’accord ou pas ?",
    "Les féministes sont juste moches et frustrées : d’accord ou pas ?",
    "Les mecs qui aiment se faire prendre le cul sont gays : d’accord ou pas ?",
    "Les grosses sont meilleures au pieu : d’accord ou pas ?",
    "Rester vierge après 25 ans c’est être un raté : d’accord ou pas ?",
    "Les handicapés qui baisent c’est glauque : d’accord ou pas ?",
    "Les femmes qui avortent plusieurs fois sont des inconscientes : d’accord ou pas ?",
    "Les pédés sont tous des obsédés : d’accord ou pas ?",
    "Les lesbiennes détestent vraiment la bite : d’accord ou pas ?",
    "Les roux n’ont pas d’âme : d’accord ou pas ?",
    "Les meufs qui font du porno sont finies pour une vraie relation : d’accord ou pas ?",
    "Les mecs qui paient pour baiser sont des pathétiques : d’accord ou pas ?",
    "Les blondes sont toutes des connes : d’accord ou pas ?",
    "Les gros ventres chez les mecs c’est répugnant : d’accord ou pas ?",
    "Les travelos doivent dire qu’ils ont une bite avant : d’accord ou pas ?",
    "Les migrants viennent juste pomper les aides : d’accord ou pas ?",
    "Les Roms sont tous des voleurs : d’accord ou pas ?",
    "Les juifs sont radins : d’accord ou pas ?",
    "Les musulmans veulent tous nous imposer leur truc : d’accord ou pas ?",
    "Les meufs en string sont toutes des chaudes : d’accord ou pas ?",
    "Les mecs qui matent du porno sont tous infidèles dans l’âme : d’accord ou pas ?",
    "Les grosses fesses valent mieux que les petits seins : d’accord ou pas ?",
    "Coucher le premier soir = facile : d’accord ou pas ?",
    "Les mecs qui pleurent en baisant sont des faibles : d’accord ou pas ?",
    "Les Noires sont toutes des chaudasses : d’accord ou pas ?",
    "Les petites bites c’est rédhibitoire : d’accord ou pas ?",
    "Les femmes qui refusent la sodomie sont coincées : d’accord ou pas ?",
    "Les mecs qui aiment les feet sont des tarés : d’accord ou pas ?",
    "Les grosses qui portent des crop tops sont ridicules : d’accord ou pas ?",
    "Les vieux qui prennent du Viagra sont pathétiques : d’accord ou pas ?",
    "Les Asiatiques qui mangent du chien sont des barbares : d’accord ou pas ?",
    "Les roux méritent qu’on se moque d’eux : d’accord ou pas ?",
    "Les handicapés mentaux devraient pas se reproduire : d’accord ou pas ?",
    "Les meufs en burqa sont toutes opprimées : d’accord ou pas ?",
    "Les travelos dans les toilettes femmes c’est n’importe quoi : d’accord ou pas ?",
    "Les migrants sont des parasites : d’accord ou pas ?",
    "Les juifs contrôlent la thune mondiale : d’accord ou pas ?",
    "Les musulmans sont tous des intégristes en puissance : d’accord ou pas ?",
    "Les féministes veulent castrer les mecs : d’accord ou pas ?",
    "Les lesbiennes sont juste en manque de vraie queue : d’accord ou pas ?",
    "Les pédés transforment les gosses : d’accord ou pas ?",
    "Les grosses sont responsables de leurs maladies : d’accord ou pas ?",
    "Les petits mecs en ont tous une petite : d’accord ou pas ?",
    "Les meufs OnlyFans sont toutes des putes : d’accord ou pas ?",
    "Les vieux qui draguent sur Tinder sont des crevards : d’accord ou pas ?",
    "Les Noires qui se décolorent la peau sont des traîtres : d’accord ou pas ?",
    "Les roux devraient être stérilisés : d’accord ou pas ?",
    "Les gros devraient payer une taxe bouffe : d’accord ou pas ?",
    "Les mecs qui pleurent au ciné sont des pédales : d’accord ou pas ?",
    "Les femmes qui n’avalent pas sont des égoïstes : d’accord ou pas ?",
    "Les travelos sont des erreurs de la nature : d’accord ou pas ?",
    "Les migrants devraient être renvoyés direct : d’accord ou pas ?",
    "Les Roms sont une race à part : d’accord ou pas ?",
    "Les juifs sont tous des profiteurs : d’accord ou pas ?",
    "Les musulmans prient juste pour nous emmerder : d’accord ou pas ?",
    "Les féministes sont toutes des hystériques : d’accord ou pas ?",
    "Les lesbiennes qui ont testé la bite sont des fake : d’accord ou pas ?",
    "Les pédés ne devraient pas adopter : d’accord ou pas ?",
    "Les grosses cuisses c’est dégueu : d’accord ou pas ?",
    "Les mecs petits méritent le célibat : d’accord ou pas ?",
    "Les meufs porno sont des déchets humains : d’accord ou pas ?",
    "Les vieux qui baisent des jeunes sont des prédateurs : d’accord ou pas ?",
    "Les Noires sont toutes des salopes : d’accord ou pas ?",
    "Les Asiatiques sont toutes des prostituées : d’accord ou pas ?",
    "Les roux sont maudits : d’accord ou pas ?",
    "Les handicapés sont des boulets pour la société : d’accord ou pas ?",
    "Les femmes en hijab sont toutes soumises : d’accord ou pas ?",
    "Les mecs qui aiment le pegging sont des tapettes : d’accord ou pas ?",
    "Les grosses qui maigrissent redeviennent baisables : d’accord ou pas ?",
    "Les travelos sont des monstres : d’accord ou pas ?",
    "Les migrants sont des envahisseurs : d’accord ou pas ?",
    "Les juifs sont le mal absolu : d’accord ou pas ?",
    "Les musulmans sont tous des fanatiques : d’accord ou pas ?",
    "Les féministes sont des chiennes aigries : d’accord ou pas ?",
    "Les lesbiennes sont toutes des camionneuses : d’accord ou pas ?",
    "Les pédés sont tous des folles : d’accord ou pas ?",
    "Les gros méritent de crever tôt : d’accord ou pas ?",
    "Les vierges sont des puceaux pathétiques : d’accord ou pas ?",
    "Les vieux sont tous impotents : d’accord ou pas ?",
    "Les Noirs sont tous des animaux : d’accord ou pas ?",
    "Les blondes sont toutes des putes à papa : d’accord ou pas ?",
    "Les roux sont des démons : d’accord ou pas ?",
    "Les nains sont des clowns : d’accord ou pas ?",
    "Les gros seins c’est plus important que le cerveau : d’accord ou pas ?",
    "Les meufs qui disent non sont des allumeuses : d’accord ou pas ?",
    "Les travelos sont des abominations : d’accord ou pas ?",
    "Les migrants sont des criminels : d’accord ou pas ?",
    "Les Roms sont des sous-hommes : d’accord ou pas ?",
    "Les juifs sont tous des menteurs : d’accord ou pas ?",
    "Les musulmans devraient dégager d’Europe : d’accord ou pas ?",
    "Les féministes veulent détruire la famille : d’accord ou pas ?",
    "Les lesbiennes sont toutes des gouines : d’accord ou pas ?",
    "Les pédés sont tous des tarlouzes : d’accord ou pas ?",
    "Les gros devraient être interdits de resto : d’accord ou pas ?",
    "Les femmes qui font du cul à cul sont des porcs : d’accord ou pas ?",
    "Les Noirs sont tous des singes : d’accord ou pas ?",
    "Les blondes sont toutes des connes finies : d’accord ou pas ?",
    "Les handicapés devraient être euthanasiés : d’accord ou pas ?",
    "Les grosses sont toutes des mangeuses compulsives : d’accord ou pas ?",
    "Les petits mecs sont tous complexés : d’accord ou pas ?",
    "Les meufs qui crient au lit simulent : d’accord ou pas ?",
    "Les Arabes sont tous des machos : d’accord ou pas ?",
    "Les vieux qui se branlent encore sont des débris : d’accord ou pas ?",
    "Les travelos dans le sport féminin trichent : d’accord ou pas ?",
    "Les migrants violent la culture : d’accord ou pas ?",
    "Les juifs sont tous des avares : d’accord ou pas ?",
    "Les musulmans sont tous des arriérés : d’accord ou pas ?",
    "Les féministes sont des salopes frustrées : d’accord ou pas ?",
    "Les pédés sont tous des pédophiles refoulés : d’accord ou pas ?",
    "Les grosses méritent pas de maillot de bain : d’accord ou pas ?",
    "Les mecs qui pleurent sont pas des vrais mecs : d’accord ou pas ?",
    "Les femmes ménopausées servent plus à rien : d’accord ou pas ?",
    "Les roux sentent le soufre : d’accord ou pas ?",
    "Les nains devraient pas conduire : d’accord ou pas ?",
    "Les gros seins faux sont tous évidents : d’accord ou pas ?",
    "Les meufs qui refusent le plan à trois sont coincées : d’accord ou pas ?",
    "Les travelos sont des imposteurs : d’accord ou pas ?",
    "Les migrants sont tous des profiteurs : d’accord ou pas ?",
    "Les juifs sont tous des complotistes : d’accord ou pas ?",
    "Les musulmans mangent halal pour nous faire chier : d’accord ou pas ?",
    "Les féministes couchent pour grimper : d’accord ou pas ?",
    "Les lesbiennes qui aiment le porno hétéro sont des traîtres : d’accord ou pas ?",
    "Les pédés qui veulent des gosses sont égoïstes : d’accord ou pas ?",
    "Les grosses sont toutes des boulets : d’accord ou pas ?",
    "Les petits en hauteur sont petits ailleurs : d’accord ou pas ?",
    "Les meufs qui font du X sont irrécupérables : d’accord ou pas ?",
    "Les vieux sur les applis de rencontre sont désespérés : d’accord ou pas ?",
    "Les Noires sont toutes bruyantes au lit : d’accord ou pas ?",
    "Les Asiatiques sont toutes des petites poupées : d’accord ou pas ?",
    "Les roux devraient être brûlés au Moyen Âge : d’accord ou pas ?",
    "Les handicapés coûtent trop cher à la société : d’accord ou pas ?",
    "Les femmes qui portent des voiles sont arriérées : d’accord ou pas ?",
    "Les mecs qui aiment les jeux anaux sont suspects : d’accord ou pas ?",
    "Les grosses en bikini sont une horreur visuelle : d’accord ou pas ?",
    "Les travelos devraient être interdits des vestiaires : d’accord ou pas ?",
    "Les migrants sont tous des terroristes potentiels : d’accord ou pas ?",
    "Les juifs sont tous des usuriers : d’accord ou pas ?",
    "Les musulmans sont tous des chèvres : d’accord ou pas ?",
    "Les féministes sont des folles : d’accord ou pas ?",
    "Les lesbiennes sont toutes des mangeuses de tapis : d’accord ou pas ?",
    "Les pédés sont tous des malades : d’accord ou pas ?",
    "Les gros devraient crever plus tôt : d’accord ou pas ?",
    "Les vierges adultes sont des losers : d’accord ou pas ?",
    "Les vieux sont tous des dégoûtants : d’accord ou pas ?",
    "Les Noirs sont tous des dealers : d’accord ou pas ?",
    "Les blondes sont toutes des suceuses : d’accord ou pas ?",
    "Les roux sont tous des psychopathes : d’accord ou pas ?",
    "Les nains sont tous des rigolos : d’accord ou pas ?",
    "La personnalité compte pas face aux gros seins : d’accord ou pas ?"
];