/**
 * Game Data Storage
 * 
 * @const {Object} GAME_DATA
 * @property {Array<string>} questions - Blue cards with '___' blanks.
 * @property {Array<string>} answers - White cards (funny answers).
 */
const GAME_DATA = {
    questions: [
        "Pour séduire, rien de tel que ___.",
        "Le nouveau régime à la mode : ne manger que ___.",
        "___ : c'est bon, mais c'est sale.",
        "Hier, j'ai perdu mon emploi à cause de ___.",
        "Dans le futur, les livres d'histoire parleront de ___.",
        "Quand je prends mon bain j'ai besoin de : ___.",
        "Mon super-pouvoir caché, c'est ___.",
        "La seule chose qui m'excite plus que l'argent, c'est ___.",
        "Papa, Maman, je vous présente ___.",
        "Ce soir au 20h de TF1 : un reportage choc sur ___.",
        "Le secret pour ne pas payer ses impôts ? ___.",
        "Ma résolution pour 2025 : arrêter ___.",
        "Le cadeau idéal pour la fête des mères, c'est ___.",
        "Dans mon testament, je lègue tout à ___.",
        "Le pape a enfin autorisé ___.",
        "Pour mon enterrement de vie de garçon/jeune fille, je veux ___.",
        "Le pire truc à trouver dans son lit le matin : ___.",
        "___ : Disponible en pharmacie sans ordonnance.",
        "La France va mal à cause de ___.",
        "Netflix prépare une série documentaire sur ___.",
        "J'ai été viré de la crèche pour avoir apporté ___.",
        "Mon psy m'a conseillé d'essayer ___.",
        "Le nom de mon premier album de rap : ___.",
        "___ : Testé et approuvé par les dentistes.",
        "C'est quoi cette odeur ? C'est ___.",
        "Si j'étais président, ma première mesure serait ___.",
        "L'ingrédient secret de la potion magique, c'est ___.",
        "Rien ne vaut ___ pour briser la glace en soirée.",
        "Mon ex m'a quitté pour ___.",
        "Le vrai problème avec les jeunes d'aujourd'hui, c'est ___.",
        "___ : Il fallait y penser !",
        "Je ne suis pas raciste, mais ___.",
        "Disney présente son nouveau film : La Princesse et ___.",
        "Le remède de grand-mère contre la toux : ___.",
        "___ : C'est un piège !",
        "Je n'ai jamais dit que j'aimais ___.",
        "Le motif de mon arrestation : ___.",
        "___ : 100% naturel et bio.",
        "Harry Potter et la Chambre de ___.",
        "La seule chose qui peut arrêter une guerre nucléaire, c'est ___.",
        "Mon mot de sécurité au lit, c'est ___.",
        "___ : Satisfait ou remboursé.",
        "Avant de mourir, je veux absolument tester ___.",
        "Le sujet du bac de philo cette année : ___.",
        "J'ai écrit une fanfiction érotique sur ___.",
        "___ : Une aventure familiale inoubliable.",
        "Le pire tue-l'amour, c'est vraiment ___.",
        "Jésus a changé l'eau en ___.",
        "___ : C'est plus drôle quand on est bourré.",
        "Ma plus grande peur irrationnelle, c'est ___.",
        "___ : L'idée cadeau qui fait toujours plaisir.",
        "Le sponsor officiel de l'Équipe de France, c'est ___.",
        "J'ai craqué, j'ai mangé ___.",
        "___ : Interdit aux moins de 18 ans.",
        "Le nouveau parfum de Dior : Essence de ___.",
        "La raison pour laquelle je suis célibataire : ___.",
        "___ : C'est la vie que j'ai décidé de mener.",
        "Dans la Bible, il est écrit qu'il ne faut pas convoiter ___.",
        "Le secret de la beauté éternelle ? ___.",
        "___ : Ça passe ou ça casse.",
        "Mon animal totem, c'est ___.",
        "Le truc le plus sale que j'ai fait dans une voiture : ___.",
        "___ : C'est pour ça qu'on ne peut pas avoir de belles choses.",
        "La police a retrouvé ___ dans le coffre de la voiture.",
        "___ : Le petit déjeuner des champions.",
        "Ma technique de drague infaillible implique ___.",
        "___ : Ne reproduisez pas ça chez vous.",
        "Le titre de ma sextape : ___.",
        "___ : Une tragédie en trois actes.",
        "J'ai un fétichisme bizarre pour ___.",
        "Le prochain Star Wars : Le retour de ___.",
        "___ : C'est dégueulasse, mais c'est bon.",
        "Pour sauver la planète, il faut éliminer ___.",
        "La chose la plus embarrassante dans mon historique Google : ___.",
        "___ : Ça a un goût de poulet.",
        "Mon prof de maths ressemblait à ___.",
        "___ : Le secret le mieux gardé du Vatican.",
        "J'ai échangé ma petite soeur contre ___.",
        "___ : L'abus d'alcool est dangereux pour la santé.",
        "Le hobby secret de Batman, c'est ___.",
        "___ : C'est compliqué à expliquer aux urgences.",
        "La pire chose à dire pendant un orgasme : ___.",
        "___ : Recommandé par 9 mamans sur 10.",
        "J'ai caché ___ sous mon matelas.",
        "Le vrai nom de Dieu est ___.",
        "___ : Une erreur de jeunesse.",
        "Le slogan de ma campagne présidentielle : ___.",
        "___ : C'est mon péché mignon.",
        "J'ai survécu à ___.",
        "Le nouveau sport aux JO : le lancer de ___.",
        "___ : C'est triste, mais c'est comme ça.",
        "Mon médecin m'a interdit ___.",
        "___ : Le meilleur moyen de perdre ses amis.",
        "La définition de l'enfer pour moi ? ___.",
        "___ : Ça colle aux dents.",
        "J'ai fait un rêve érotique avec ___.",
        "___ : Mieux que le Viagra.",
        "Le Père Noël n'existe pas, c'est en fait ___.",
        "___ : Une expérience religieuse.",
        "J'ai été banni du club de bridge à cause de ___.",
        "___ : C'est la goutte de trop.",
        "La seule chose qui me retient de tuer tout le monde : ___.",
        "___ : Disponible en suppositoire.",
        "J'ai nommé mon pénis ___.",
        "___ : Ça fait mal au début, mais on s'habitue.",
        "Le secret des pyramides ? ___.",
        "___ : Un plaisir coupable.",
        "J'ai vendu mon âme pour ___.",
        "___ : Le cauchemar de tout parent.",
        "Mon autobiographie s'appellera : ___.",
        "___ : C'est légal dans certains états.",
        "J'ai remplacé mon mari par ___.",
        "___ : Une source inépuisable d'énergie.",
        "Le pire endroit pour cacher un cadavre : ___.",
        "___ : Ça ne rentrera jamais là-dedans.",
        "J'ai appris à lire avec ___.",
        "___ : Le cadeau qui continue de donner.",
        "La seule chose pire que la mort, c'est ___.",
        "___ : Un spectacle pour toute la famille.",
        "J'ai perdu ma virginité avec ___.",
        "___ : C'est bon pour le moral.",
        "Le nouveau sandwich McDo : Le Mc___.",
        "___ : Ça gratte un peu.",
        "J'ai déclaré la guerre à ___.",
        "___ : Le secret de ma réussite.",
        "J'ai trouvé ___ dans ma soupe.",
        "___ : Une raison de vivre.",
        "J'ai peur du noir à cause de ___.",
        "___ : C'est un complot du gouvernement.",
        "J'ai un tatouage de ___ sur la fesse gauche.",
        "___ : Ça sent le sapin.",
        "Le dernier mot de ma grand-mère : ___.",
        "___ : Une catastrophe naturelle.",
        "J'ai ruiné le mariage de ma soeur avec ___.",
        "___ : C'est mieux que rien.",
        "Le futur de la technologie, c'est ___.",
        "___ : Un crime contre l'humanité.",
        "J'ai été élevé par ___.",
        "___ : Ça fait maigrir.",
        "Le titre de mon film porno : ___.",
        "___ : Une erreur de la nature.",
        "J'ai donné ___ aux pauvres.",
        "___ : Ça ne s'achète pas.",
        "Le vrai coupable du réchauffement climatique : ___.",
        "___ : Un danger public.",
        "J'ai confondu ma femme avec ___.",
        "Je bois ___ pour oublier ___.",
        "Le couple parfait, c'est ___ et ___.",
        "L'étape clé dans la vie d'un homme : ___ puis ___.",
        "Entre ___ et ___, mon cœur balance.",
        "Pour mon anniversaire, j'ai eu ___ mais je voulais ___.",
        "___ : C'est le chemin vers ___.",
        "Il n'y a pas de problème que ___ et ___ ne puissent régler.",
        "Ma vie sexuelle, c'est un mélange de ___ et de ___.",
        "___ + ___ = Le samedi soir idéal.",
        "Le secret d'un mariage heureux ? Un peu de ___ et beaucoup de ___.",
        "D'abord ___, ensuite ___.",
        "J'ai expliqué à mon fils comment on fait les bébés avec ___ et ___.",
        "Le combat du siècle : ___ contre ___.",
        "Pour séduire une femme, il faut de l'humour, ___ et ___.",
        "Dans ma valise pour les vacances, il y a ___ et ___.",
        "Le nouveau menu Happy Meal contient ___ et ___.",
        "___ est la porte d'entrée vers ___.",
        "Avant, j'avais ___, maintenant j'ai ___.",
        "La différence entre moi et toi, c'est ___ et ___.",
        "___ : La cause, ___ : La conséquence.",
        "Si tu mélanges ___ et ___, tu meurs.",
        "Mon profil Tinder : Passionné de ___ et de ___.",
        "L'histoire de ma vie : trop de ___ et pas assez de ___.",
        "Pour faire pleurer un homme, donnez-lui ___ et ___.",
        "La France, c'est le pays de ___ et de ___.",
        "Dieu a créé l'homme, puis il a créé ___ et ___ pour se marrer.",
        "___, c'est bien, mais avec ___, c'est mieux.",
        "Mon fantasme ultime ? Un plan à trois avec ___ et ___.",
        "La devise de la République : Liberté, Égalité, ___.",
        "___ m'a mené à ___.",
        "J'ai troqué ___ contre ___.",
        "Le meilleur remède contre la gueule de bois : ___ et ___.",
        "___ à gauche, ___ à droite.",
        "Ne jamais mettre ___ et ___ dans la même pièce.",
        "Mon psy dit que mon obsession pour ___ vient de ___.",
        "La définition de l'amour ? Partager ___ et ___.",
        "J'ai été viré pour avoir mélangé ___ et ___ au bureau.",
        "___ le matin, ___ le soir.",
        "Rien ne dit 'Je t'aime' comme ___ et ___.",
        "Le film raconte l'histoire d'amour impossible entre ___ et ___.",
        "Pour réussir sa vie, il faut éviter ___ et ___.",
        "___ est la preuve que ___ existe.",
        "J'hésite entre manger ___ ou ___.",
        "Le point commun entre Hitler et moi ? ___ et ___.",
        "___ : Attente. ___ : Réalité.",
        "La recette du bonheur ? Un peu de ___, beaucoup de ___ et une pincée de ___.",
        "Hier soir : ___. Ce matin : ___. Demain : ___.",
        "Liberté, Égalité, ___.",
        "Pour sauver le monde, je dois réunir ___, ___ et ___.",
        "Mon week-end de rêve : ___, ___, et pour finir ___.",
        "Dans la vie, il y a trois certitudes : la mort, les impôts et ___.",
        "Je me suis réveillé avec ___, ___ et ___ dans mon lit.",
        "Le Père, le Fils et ___.",
        "Pierre, feuille, ciseaux, ___ !",
        "Métro, Boulot, ___.",
        // --- POLITIQUE (30) ---
        "Si je suis élu, je promets ___ pour tous.",
        "Le 49.3, c'est un peu comme ___ : ça passe en force.",
        "Le secret inavouable d'Emmanuel Macron, c'est ___.",
        "Pour redresser la France, il faut miser sur ___.",
        "Mon parti politique milite pour la légalisation de ___.",
        "Le vrai coupable du déficit de la Sécu, c'est ___.",
        "Dans l'isoloir, j'ai glissé ___ dans l'enveloppe.",
        "Le prochain scandale d'État impliquera ___.",
        "Marine Le Pen a peur de tout, sauf de ___.",
        "La solution au réchauffement climatique ? ___.",
        "Pour calmer les Gilets Jaunes, le gouvernement propose ___.",
        "___ : La seule chose que les politiques ne nous ont pas encore volée.",
        "Le débat de l'entre-deux tours s'est fini par ___.",
        "Jean-Luc Mélenchon a pété un plomb à cause de ___.",
        "La réforme des retraites, c'est avant tout ___.",
        "Le slogan de ma campagne : 'Plus de ___, moins de ___'.",
        "L'Assemblée Nationale a voté l'interdiction de ___.",
        "Un bon dictateur a toujours besoin de ___.",
        "La démocratie, c'est bien, mais ___ c'est mieux.",
        "Le maire de mon village a été arrêté pour ___.",
        "___ : C'est la faute de l'Europe.",
        "Si Napoléon revenait, il serait choqué par ___.",
        "Le budget de l'armée va servir à acheter ___.",
        "C'est décidé, je ne vote plus, je préfère ___.",
        "Le prochain Premier ministre sera ___.",
        "La politique, c'est comme ___, c'est sale.",
        "Pour gagner des voix, je suis prêt à offrir ___.",
        "Les syndicats réclament plus de ___.",
        "Le président a oublié d'éteindre son micro quand il a dit : '___'.",
        "___ : Enfin une taxe utile !",

        // --- MONDE DU TRAVAIL (50) ---
        "Pour avoir mon augmentation, j'ai dû accepter ___.",
        "En réunion, je pense surtout à ___.",
        "Le motif de mon licenciement : ___.",
        "___ : Ça ne passe pas en note de frais.",
        "Ma technique pour glander au bureau : ___.",
        "La machine à café est en panne, on doit boire ___.",
        "Mon N+1 est un expert en ___.",
        "Sur mon CV, j'ai menti à propos de ___.",
        "Le teambuilding de l'enfer : une journée consacrée à ___.",
        "LinkedIn, c'est 90% de bullshit et 10% de ___.",
        "Pour réussir son entretien d'embauche, il faut apporter ___.",
        "Le stagiaire a encore fait une connerie avec ___.",
        "___ : C'est contraire au règlement intérieur.",
        "Mon boss m'a surpris en train de faire ___.",
        "La Startup Nation a besoin de ___.",
        "___ : Le secret pour devenir Manager.",
        "J'ai répondu 'Cordialement, allez vous faire foutre' à ___.",
        "Le pire collègue, c'est celui qui parle tout le temps de ___.",
        "Télétravail : La caméra s'est allumée pendant ___.",
        "La DRH m'a convoqué pour parler de ___.",
        "Mon plan de carrière ? ___ puis la retraite.",
        "___ : C'est bon pour la productivité.",
        "J'ai volé ___ dans les fournitures.",
        "La réunion Zoom a dérapé quand on a vu ___.",
        "___ : L'avantage en nature que je préfère.",
        "Le pot de départ de Michel, c'était surtout ___.",
        "Lundi matin : café, dépression et ___.",
        "Pour supporter mes collègues, je prends ___.",
        "Ce dossier est aussi urgent que ___.",
        "___ : La vraie raison de mon arrêt maladie.",
        "J'ai couché avec ___ pour avoir le poste.",
        "L'open space sent fort ___.",
        "Mon job, c'est essentiellement ___.",
        "J'ai démissionné en jetant ___ sur le bureau du patron.",
        "___ : C'est disruptif.",
        "On cherche un candidat dynamique, motivé et fan de ___.",
        "Le comité d'entreprise offre ___ cette année.",
        "J'ai fait un burn-out à cause de ___.",
        "___ : C'est dans ma fiche de poste.",
        "Le client est roi, sauf quand il demande ___.",
        "J'ai surpris la compta en train de faire ___.",
        "Mon mot de passe Windows, c'est ___.",
        "La photocopieuse est bourrée avec ___.",
        "___ : Ça mérite un avertissement.",
        "Le management bienveillant, c'est juste ___ déguisé.",
        "J'ai mis ___ dans le frigo commun.",
        "La grève a commencé à cause de ___.",
        "___ : Le cauchemar de tout freelance.",
        "J'ai signé un CDI avec ___.",
        "Ma reconversion professionnelle : éleveur de ___.",
        "Le secret pour survivre au repas de Noël : ___.",
        "Papa, Maman, je suis ___.",
        "Dans la famille, on ne parle jamais de ___.",
        "Ma grand-mère cuisine très bien ___.",
        "Pour l'héritage, je suis prêt à tuer ___.",
        "Mon oncle raciste a encore parlé de ___.",
        "J'ai découvert que mon père cachait ___.",
        "Le test ADN a révélé que mon vrai père est ___.",
        "___ : La raison pour laquelle je ne vois plus mes cousins.",
        "Ma mère m'a toujours dit : 'Méfie-toi de ___'.",
        "Le pire cadeau de ma tante : ___.",
        "J'ai surpris mes parents en train de faire ___.",
        "___ : Une tradition familiale depuis 1850.",
        "J'échange mon petit frère contre ___.",
        "Si je n'ai pas d'enfants, c'est à cause de ___.",
        "Le dimanche midi, c'est poulet-frites et ___.",
        "Ma belle-mère ressemble à ___.",
        "___ : Ce que je déteste le plus chez mes gosses.",
        "J'ai été déshérité pour avoir apporté ___.",
        "Mon grand-père a fait la guerre avec ___.",
        "La honte de la famille, c'est ___.",
        "J'ai appris à lire sur une boîte de ___.",
        "Pour faire taire bébé, je lui donne ___.",
        "___ : La base de l'éducation.",
        "Mon fils est un génie, il sait déjà faire ___.",
        "J'ai dit à ma fille que les bébés naissent dans ___.",
        "Le secret de longévité de Mamie ? ___.",
        "J'ai ruiné le mariage de ma sœur avec ___.",
        "___ : Ça reste entre nous.",
        "Mes parents ont divorcé à cause de ___.",
        "Ce soir, c'est sodomie et ___.",
        "Mon 'safe word' au lit, c'est ___.",
        "J'ai un fétichisme bizarre pour ___.",
        "___ : Plus efficace que le Viagra.",
        "La taille ne compte pas, c'est ___ qui compte.",
        "J'ai perdu ma virginité avec ___.",
        "Mon sextoy préféré a la forme de ___.",
        "Pendant l'acte, je pense souvent à ___.",
        "___ : 50 nuances de plus sombre.",
        "Ma position préférée ? Celle de ___.",
        "J'ai trouvé ___ dans son historique Pornhub.",
        "Le Kamasutra a oublié la position du ___.",
        "___ : C'est meilleur sans préservatif.",
        "J'ai une MST qui s'appelle ___.",
        "Le sexe, c'est comme ___, c'est meilleur à plusieurs.",
        "J'ai été banni de Tinder pour avoir posté ___.",
        "___ : L'orgasme assuré.",
        "Elle a crié '___' au moment de jouir.",
        "Mon fantasme inavoué : le faire avec ___.",
        "___ : C'est dégueulasse, mais j'avale.",
        "J'ai surpris mon voisin en train de niquer ___.",
        "Le point G se trouve juste derrière ___.",
        "___ : Idéal pour pimenter votre couple.",
        "J'aime quand tu me touches avec ___.",
        "Le BDSM, c'est bien, mais avec ___ c'est mieux.",
        "J'ai testé le glory hole, mais c'était ___ de l'autre côté.",
        "___ : Disponible au rayon Adulte.",
        "Mon pénis a la texture de ___.",
        "J'ai fait un plan à trois avec ___ et ___.",
        "Le sexe tantrique, c'est juste ___ qui dure longtemps.",
        "Elle veut qu'on utilise ___ ce soir.",
        "J'ai éjaculé sur ___.",
        "Le porno VR avec ___, c'est le futur.",
        "___ : Ça rentre, mais faut forcer.",
        "J'aime être attaché avec ___.",
        "La première fois, ça fait mal à cause de ___.",
        "___ : C'est ma limite.",
        "J'ai une érection dès que je vois ___.",
        "On a fait l'amour sur ___.",
        "___ : Le tue-l'amour absolu.",
        "J'ai payé une pute pour qu'elle fasse ___.",
        "Ma vie sexuelle se résume à ___.",
        "___ : Interdit aux moins de 18 ans.",
        "J'ai reçu une dick-pic de ___.",
        "Le clitoris ressemble étrangement à ___.",
        "___ : C'est gluant, mais appétissant.",
        "J'ai rompu parce qu'il voulait faire ___.",
        "Le 'Walk of Shame' après une nuit avec ___.",
        "___ : C'est mieux dans les fesses.",
        "J'ai simulé un orgasme en pensant à ___.",
        "Je ne bois pas pour m'amuser, je bois pour ___.",
        "Hier soir, j'ai sniffé ___.",
        "Le meilleur remède contre la gueule de bois : ___.",
        "J'ai vomi sur ___.",
        "L'alcool, c'est de l'eau, mais avec ___.",
        "J'ai arrêté la coke, je prends ___ maintenant.",
        "___ : C'est légal à Amsterdam.",
        "Après 5 verres de vodka, je deviens ___.",
        "J'ai roulé un joint avec ___.",
        "___ : La drogue du pauvre.",
        "J'ai passé la nuit en cellule de dégrisement avec ___.",
        "Mon dealer m'a offert ___ pour ma fidélité.",
        "Boire ou ___, il faut choisir.",
        "J'ai un trou noir, je me souviens juste de ___.",
        "___ : C'est ma drogue.",
        "Un petit verre de ___ pour la route ?",
        "J'ai essayé de fumer ___.",
        "L'abus de ___ est dangereux pour la santé.",
        "J'ai caché ma drogue dans ___.",
        "Être sobre, c'est une hallucination causée par le manque de ___.",
        "Des lasagnes faites avec ___.",
        "___ qui me regarde dormir.",
        "J'ai accouché de ___.",
        "Dans l'espace, personne ne vous entend faire ___.",
        "Un centaure, mais moitié homme, moitié ___.",
        "J'ai léché ___ pour la science.",
        "La fin du monde sera causée par ___.",
        "___ : Ça a le goût de poulet.",
        "J'ai peur des clowns, surtout quand ils tiennent ___.",
        "Se faire grignoter les orteils par ___.",
        "Un univers parallèle où ___ est président.",
        "Manger ses propres ___.",
        "___ : C'est vivant !",
        "J'ai rêvé que j'étais ___.",
        "La texture de ___, mais l'odeur de ___.",
        "Un suppositoire taille XXL à l'effigie de ___.",
        "Se frotter nu contre ___.",
        "___ : C'est collant.",
        "J'ai invoqué Satan avec ___.",
        "Un bébé avec la tête de ___.",
        "___ : Ça pousse dans mon jardin.",
        "J'ai vu la Vierge Marie dans ___.",
        "Se faire aspirer l'âme par ___.",
        "___ : Ça vibre.",
        "J'ai un troisième téton qui ressemble à ___.",
        "Les extraterrestres veulent juste ___.",
        "Se baigner dans une piscine remplie de ___.",
        "___ : C'est mou et chaud.",
        "J'ai cousu ___ sur ma peau.",
        "Un sandwich au caca et à ___.",
        "La mort par ___.",
        "___ qui sort de mes toilettes.",
        "J'ai épousé ___.",
        "Se transformer en ___ à la pleine lune.",
        "___ : L'ingrédient secret des nuggets.",
        "J'ai trouvé un doigt dans ___.",
        "Vivre dans un monde fait de ___.",
        "___ : Ça me gratte.",
        "Avoir des tentacules à la place de ___.",
        "Chier ___ par le nez.",
        "___ : C'est ma religion.",
        "J'ai fusionné avec ___.",
        "Manger la peau morte de ___.",
        "___ : Ça brille dans le noir.",
        "J'entends des voix qui me disent de faire ___.",
        "Un nain de jardin possédé par ___.",
        "___ : C'est sous ton lit.",
        "Avoir les yeux de ___.",
        "Pondre un œuf contenant ___.",
        "___ : L'apocalypse selon Saint-Jean.",
        "J'ai trouvé ___ sous mon prépuce.",
        "Le médecin a retiré ___ de mon rectum.",
        "Rien ne m'excite plus que l'odeur de ___.",
        "Ma peau a la texture de ___.",
        "J'ai surpris mon chien en train de manger ___.",
        "___ : C'est pour ça que je ne dors plus la nuit.",
        "Dans mon bocal de formol, je conserve ___.",
        "J'aime me frotter nu contre ___.",
        "La seule chose qui calme mes voix intérieures, c'est ___.",
        "J'ai remplacé mon sang par ___.",
        "Au petit-déjeuner, je trempe mes tartines dans ___.",
        "___ : Le goût interdit.",
        "J'ai accouché de ___.",
        "Mes voisins font un rituel avec ___.",
        "J'ai une collection secrète de ___ dans ma cave.",
        "Le prêtre a béni ___.",
        "J'ai léché ___ pour voir ce que ça faisait.",
        "___ me regarde quand je suis aux toilettes.",
        "J'ai cousu ___ sur mon visage.",
        "Mon ami imaginaire est en fait ___.",
        "Il y a des poils qui poussent sur ___.",
        "J'ai offert ___ à un enfant inconnu.",
        "La marionnette me parlait de ___.",
        "J'ai retrouvé ___ dans ma bouche au réveil.",
        "___ : C'est gluant, mais c'est chaud.",
        "J'ai fait l'amour à ___.",
        "Mon psychopathe préféré utilise ___.",
        "J'ai peur que ___ sorte de mon miroir.",
        "J'ai un troisième téton qui ressemble à ___.",
        "___ : Ça bouge encore.",
        "J'ai sniffé les cendres de ___.",
        "On a retrouvé des traces de ___ dans la lasagne.",
        "Je me suis masturbé en pensant à ___.",
        "___ : L'ingrédient secret de ma tarte.",
        "J'ai élevé ___ comme mon propre fils.",
        "J'ai vu Satan, il tenait ___.",
        "___ : C'est coincé au fond.",
        "J'ai des flashbacks de ___.",
        "Je garde ___ sous mon oreiller.",
        "___ : Ça a un goût de fer et de larmes.",
        "J'ai peint les murs avec ___.",
        "Le clown du ça m'a offert ___.",
        "J'ai une infection qui ressemble à ___.",
        "___ : C'est doux comme de la peau humaine.",
        "J'ai échangé mes yeux contre ___.",
        "Dans une autre vie, j'étais ___.",
        "J'ai entendu ___ gratter à la porte.",
        "Le cadavre avait encore ___ dans la main.",
        "___ : Ça suinte un peu.",
        "J'ai une phobie irrationnelle de ___.",
        "J'ai rêvé que j'avalais ___.",
        "___ : Le cadeau de mon stalker.",
        "J'ai mis ___ au micro-ondes.",
        "Le silence a été brisé par le bruit de ___.",
        "___ : C'est ce qu'il y a dans la seringue.",
        "J'ai caressé doucement ___.",
        "Mon tatouage représente ___ qui pleure.",
        "J'ai senti le souffle de ___ dans ma nuque.",
        "___ : Ça craque sous la dent.",
        "J'ai vomi ___.",
        "La poupée vaudou est faite avec ___.",
        "J'ai reçu une lettre de menace signée par ___.",
        "___ : C'est caché dans le vide sanitaire.",
        "J'ai nettoyé la scène de crime avec ___.",
        "Mon jumeau maléfique veut ___.",
        "___ : Ça sent le vieux grenier.",
        "J'ai surpris grand-mère avec ___.",
        "Je communique avec les morts via ___.",
        "___ : C'est humide et tiède.",
        "J'ai fait un pacte avec ___.",
        "Le monstre sous le lit veut juste ___.",
        "J'ai trouvé un doigt dans ___.",
        "___ : Ça me démange de l'intérieur.",
        "J'ai vu ___ flotter dans les égouts.",
        "Ma religion m'interdit ___.",
        "___ : C'est ce qui reste après l'incinération.",
        "J'ai embrassé ___ sur la bouche.",
        "Je collectionne les photos de ___.",
        "___ : Ça me excite bizarrement.",
        "J'ai un kyste rempli de ___.",
        "Le boucher m'a vendu ___ à la place du porc.",
        "___ : C'est écrit dans la prophétie.",
        "J'ai senti ___ remuer dans mon ventre.",
        "Je me suis lavé avec ___.",
        "___ : C'est ma seule famille.",
        "J'ai murmuré des mots doux à ___.",
        "La prothèse est faite en ___.",
        "___ : C'est ce que les aliens recherchent.",
        "J'ai perdu ma virginité avec ___.",
        "Le goût métallique de ___.",
        "___ : Ça pousse dans l'humidité.",
        "J'ai peur de devenir ___.",
        "La taxidermie de ___ a mal tourné.",
        "___ : C'est caché sous le plancher.",
        "J'ai reçu un MMS contenant ___.",
        "La voyante a vu ___ dans ma boule de cristal.",
        "___ : C'est ma punition.",
        "J'ai sucé ___.",
        "Le liquide amniotique avait un goût de ___.",
        "La sodomie avait une texture de : ___",
        "___ : C'est mon doudou.",
        "J'ai vu une vidéo deepweb de ___.",
        "Le bruit des os qui craquent me rappelle ___.",
        "___ : Ça me regarde fixement.",
        "J'ai été allaité avec ___.",
        "Le chirurgien a oublié ___ dans mon ventre.",
        "___ : C'est visqueux.",
        "J'ai donné mon âme pour ___.",
        "L'odeur de putréfaction de ___.",
        "___ : C'est ma muse.",
        "J'ai marché pieds nus sur ___.",
        "Le fœtus tenait ___.",
        "___ : C'est ce qui vit dans mon placard.",
        "J'ai fait une overdose de ___.",
        "Le test de paternité a révélé que le père est ___.",
        "___ : C'est mon seul ami.",
        "J'ai gratté ma croûte et j'ai trouvé ___.",
        "L'autopsie a révélé la présence de ___.",
        "___ : C'est ce qui m'attend en Enfer.",
        "J'ai une poupée gonflable à l'effigie de ___.",
        "Le ver solitaire s'appelle ___.",
        "___ : Ça me fait pleurer de joie.",
        "J'ai congelé ___.",
        "Le canibale a assaisonné le bras avec ___.",
        "J'ai cousu ___ sur ___.",
        "Le mélange de ___ et de ___ crée un gaz toxique.",
        "J'ai remplacé mes mains par ___ et ___.",
        "Dans ma cave, il y a ___ qui mange ___.",
        "Ma recette secrète : un peu de ___ et beaucoup de ___.",
        "J'aime regarder ___ en caressant ___.",
        "Le prêtre et ___ font ___ dans la sacristie.",
        "J'ai fait un collier avec ___ et ___.",
        "Mon fantasme : être recouvert de ___ et de ___.",
        "Entre ___ et ___, mon cœur balance.",
        "J'ai vu ___ violer ___.",
        "La prophétie annonce l'union de ___ et de ___.",
        "En exclusivité sur Mediapart : le ministre cachait ___ dans son bureau.",
        "Le Conseil Constitutionnel a validé ___.",
        "Pour lutter contre l'abstention, l'État va offrir ___ à chaque votant.",
        "Le rêve secret d'Eric Zemmour, c'est ___.",
        "La nouvelle devise de la République : Liberté, Égalité, ___.",
        "J'ai déchiré ma carte d'électeur pour la remplacer par ___.",
        "Le projet de loi sur ___ a provoqué une émeute à l'Assemblée.",
        "Si l'extrême droite passe, on aura droit à ___.",
        "La gauche s'est encore divisée à cause de ___.",
        "Pour économiser l'électricité, l'Élysée s'éclaire désormais avec ___.",
        "Le vrai visage du capitalisme, c'est ___.",
        "Les CRS ont chargé les manifestants avec ___.",
        "___ : La mesure phare du prochain quinquennat.",
        "J'ai voté blanc, mais j'aurais préféré voter pour ___.",
        "Le patron du MEDEF demande la suppression de ___.",
        "Dans son allocution de 20h, le Président a annoncé ___.",
        "Le seul moyen de réunir tous les Français, c'est ___.",
        "La dette publique a explosé à cause de l'achat massif de ___.",
        "Pour séduire l'électorat senior, il faut promettre ___.",
        "Le Parti Socialiste a vendu son siège pour acheter ___.",
        "___ : C'est ce qu'on appelle la grandeur de la France.",
        "Vladimir Poutine a menacé d'envoyer ___ sur Paris.",
        "Le remaniement ministériel a servi à dissimuler ___.",
        "En marche vers ___ !",
        "Le Sénat s'est endormi pendant le débat sur ___.",
        "Pour éviter le 49.3, la Première ministre a proposé ___.",
        "L'Union Européenne exige l'interdiction de ___.",
        "Le maire a détourné des fonds publics pour ___.",
        "Mon programme électoral tient en un mot : ___.",
        "La CGT a bloqué les raffineries pour obtenir ___.",
        "___ : C'est un complot des francs-maçons.",
        "J'ai pris ma carte au parti juste pour ___.",
        "Le débat a dérapé quand le candidat a sorti ___.",
        "La France ne peut pas accueillir toute la misère du monde, mais elle peut accueillir ___.",
        "Le livre politique de l'année : 'Ma vie, mon œuvre, ___'.",
        "Pour redorer son image, le gouvernement a engagé des influenceurs pour promouvoir ___.",
        "L'immunité présidentielle protège de tout, sauf de ___.",
        "___ : Le sujet tabou du Conseil des ministres.",
        "La République est en danger à cause de ___.",
        "Si je suis élu, je supprimerai ___.",
        "Le sondage IFOP donne ___ vainqueur au premier tour.",
        "La diplomatie française, c'est l'art de vendre ___.",
        "Les archives secrètes de l'État contiennent des preuves sur ___.",
        "La guillotine a été rétablie spécialement pour ___.",
        "Le prochain référendum portera sur : Pour ou Contre ___ ?",
        "L'Assemblée a observé une minute de silence pour ___.",
        "___ : C'est la ligne rouge à ne pas franchir.",
        "Le Parti Communiste a organisé une fête de l'Huma dédiée à ___.",
        "La haine de l'autre commence par ___.",
        "Le Président a oublié le code nucléaire, il a tapé ___ à la place.",
        "Pour payer moins d'impôts, déclarez ___.",
        "Les écologistes se sont enchaînés à ___.",
        "Le Quai d'Orsay déconseille fortement aux voyageurs d'emporter ___.",
        "___ : La seule réforme qui a fait l'unanimité.",
        "Le porte-parole du gouvernement a bégayé en parlant de ___.",
        "La startup nation a besoin de plus de ___ et de moins de ___.",
        "Le garde du corps du Président a été surpris avec ___.",
        "La France insoumise a déposé 10 000 amendements pour bloquer ___.",
        "___ : C'est ça, le ruissellement.",
        "La Marianne de la mairie a été remplacée par une statue de ___.",
        "J'ai peur que ___ se transforme en ___.",
        "J'ai nourri ___ avec ___.",
        "Le bébé est né avec ___ et ___.",
        "J'ai caché ___ dans ___.",
        "Le matin, je ne suis rien sans ___.",
        "Dans mon frigo, il y a juste ___.",
        "Le secret de mon régime ? ___.",
        "J'ai raté le bus à cause de ___.",
        "Lundi matin : café, clope et ___.",
        "Mon historique Google a honte de ___.",
        "J'ai trouvé ___ sous le canapé.",
        "Rien ne vaut ___ après l'amour.",
        "Le dimanche, c'est pyjama et ___.",
        "J'ai bouché les toilettes avec ___.",
        "Mon patron m'a surpris avec ___.",
        "Sur ma liste de courses : ___.",
        "J'ai glissé sur ___.",
        "Le voisin du dessus fait du bruit avec ___.",
        "Ma vie sociale se résume à ___.",
        "J'ai perdu mes clés dans ___.",
        "Ce soir, c'est Netflix et ___.",
        "J'ai taché ma chemise avec ___.",
        "Le livreur Amazon a volé ___.",
        "Dans le métro, ça sent ___.",
        "J'ai soigné ma grippe avec ___.",
        "Mon chat a vomi ___ sur le tapis.",
        "J'ai réparé l'évier avec ___.",
        "Pour dormir, je compte ___.",
        "Mon découvert bancaire est dû à ___.",
        "J'ai envoyé ___ par erreur à ma mère.",
        "Le dentiste m'a arraché ___.",
        "J'ai oublié mon code PIN à cause de ___.",
        "Ma plante verte est morte de ___.",
        "J'ai marché pieds nus sur ___.",
        "Le micro-ondes a explosé à cause de ___.",
        "J'ai une envie soudaine de ___.",
        "Mon hobby secret, c'est ___.",
        "J'ai confondu le sucre et ___.",
        "Le serveur a craché dans ___.",
        "J'ai peur de l'orage et de ___.",
        "Ma mère m'a appelé pour parler de ___.",
        "J'ai reçu un colis contenant ___.",
        "L'ascenseur est en panne à cause de ___.",
        "J'ai lavé mes cheveux avec ___.",
        "Mon téléphone est tombé dans ___.",
        "Je procrastine en regardant ___.",
        "J'ai une réunion Zoom avec ___.",
        "Mon colocataire a mangé ___.",
        "J'ai rêvé de ___ cette nuit.",
        "Le code Wifi, c'est ___.",
        "J'ai fait brûler ___.",
        "Au petit-déjeuner : tartines de ___.",
        "J'ai besoin de vacances et de ___.",
        "La machine à café ne donne plus que ___.",
        "J'ai trouvé ___ dans ma poche.",
        "Mon seul ami, c'est ___.",
        "La vie est trop courte pour ___.",
        "J'ai échangé ma voiture contre ___.",
        "Le chien a aboyé sur ___.",
        "J'ai nettoyé la litière avec ___.",
        "Mon alarme sonne, je pense à ___.",
        "J'ai mis ___ au sale.",
        "Le facteur m'a vu faire ___.",
        "J'ai faim de ___.",
        "Pour invoquer le démon, il faut ___ et ___.",
        "J'ai surpris papa en train de ___ avec ___.",
        "Le film porno mettait en scène ___ et ___.",
        "J'ai nettoyé ___ avec ___.",
        "Le chirurgien a greffé ___ sur ___.",
        "J'ai échangé ___ contre ___ au marché noir.",
        "La police a retrouvé ___ à côté de ___.",
        "J'ai fait l'amour à ___ pendant que je pensais à ___.",
        "Le rituel implique de manger ___ et de boire ___.",
        "J'ai vomi ___ sur ___.",
        "La seule chose pire que ___, c'est ___.",
        "J'ai inséré ___ dans ___.",
        "Le monstre a le corps de ___ et la tête de ___.",
        "J'ai rêvé que ___ tuait ___.",
        "Dans le mixeur, j'ai mis ___ et ___.",
        "J'ai été conçu par ___ et ___.",
        "La tombe contenait ___ et ___.",
        "J'ai puni ___ avec ___.",
        "Le virus transforme les gens en ___ ou en ___.",
        "J'ai écrit 'Je t'aime' avec ___ sur ___.",
        "La piqûre contient du venin de ___ et de ___.",
        "J'ai peur de mourir par ___ ou par ___.",
        "Le cadeau de mariage était composé de ___ et de ___.",
        "J'ai léché ___ sur ___.",
        "Le clochard mangeait ___ avec ___.",
        "J'ai vu des vers sortir de ___ et de ___.",
        "La messe noire célèbre ___ et ___.",
        "J'ai accouplé ___ avec ___.",
        "Le suppositoire est fait de ___ et de ___.",
        "Hier soir : ___. Ce matin : ___. Le résultat : ___.",
        "Pour survivre, j'ai dû manger ___, boire ___ et chier ___.",
        "Le Père, le Fils et ___.",
        "Ma famille parfaite : moi, ___ et ___.",
        "Dans mon testament, je lègue ___ à ___, mais je garde ___.",
        "La recette de l'immortalité : du sang de ___, une larme de ___ et ___.",
        "Je me suis réveillé entre ___, ___ et ___.",
        "Les trois cavaliers de l'Apocalypse : la Guerre, la Famine et ___.",
        "Pour me faire jouir, j'ai besoin de ___, de ___ et d'une pince à linge.",
        "J'ai vu un film snuff avec ___, ___ et ___.",
        "Le menu dégustation : Entrée de ___, Plat de ___, Dessert de ___.",
        "J'ai rempli la baignoire avec ___, ___ et ___.",
        "Mon corps est un temple rempli de ___, de ___ et de ___.",
        "La police a trouvé trois choses dans le coffre : ___, ___ et ___.",
        "Je suis allergique à ___, à ___ et à la décence.",
        "Pour Halloween, je me déguise en mélange de ___, de ___ et de ___.",
        "La sainte trinité du malaise : ___, ___ et ___.",
        "J'ai été kidnappé par ___, ___ et ___.",
        "Mon autobiographie : 'Entre ___, ___ et ___'.",
        "Le docteur a dit : 'Il faut couper ___, brûler ___ et manger ___'."
    ],
    answers: [
        "Un PowerPoint avec des transitions 'Étoile'",
        "L'assistant trombone de Word 97 (Clippy)",
        "Une réunion qui aurait pu être un simple email",
        "Le bruit de l'imprimante qui bourre",
        "La diagonale du vide",
        "Un panneau 'Attention sol glissant'",
        "Le dernier annuaire téléphonique papier",
        "Une cassette VHS rembobinée au crayon",
        "L'odeur de la colle Cléopâtre",
        "Un stylo 4 couleurs (avec le vert qui ne marche pas)",
        "Le code Wifi de la box (24 caractères)",
        "Un ticket de caisse de 3 mètres de long",
        "La notice de montage d'une étagère Billy",
        "Un caddie de supermarché qui roule de travers",
        "La musique du camion de glaces",
        "Un épisode de l'Inspecteur Derrick",
        "Le générique de 'La Petite Maison dans la Prairie'",
        "Une chorale de collégiens qui chante faux",
        "Le prof de flûte à bec",
        "Un touriste avec un bob Ricard",
        "Le type qui applaudit à l'atterrissage de l'avion",
        "Une grand-mère qui conduit un 4x4",
        "Le voisin qui tond sa pelouse le dimanche matin",
        "Un chien qui ressemble à son maître",
        "Le chat de Schrödinger (vivant et mort)",
        "La pomme de Newton",
        "Le nez de Cléopâtre",
        "Le cheval de Troie (mais en plastique)",
        "Une bataille de polochons historique",
        "Le premier homme à avoir porté des Crocs",
        "Une statue de cire qui fond",
        "L'homme invisible (tout nu)",
        "Un vampire qui a peur du sang",
        "Le monstre sous le lit (qui a peur du noir)",
        "Un zombie végétarien",
        "La recette de la potion magique (sans gui)",
        "Une baguette magique en panne de batterie",
        "Le chapeau de Napoléon",
        "La moustache de Dali",
        "Les sourcils d'Emmanuel Chain",
        "La voix de Homer Simpson",
        "Un mime qui parle",
        "Un clown triste",
        "Le magicien d'Oz",
        "Un Hobbit aux pieds poilus",
        "Gandalf qui a oublié son bâton",
        "Dark Vador qui a de l'asthme",
        "Un Stormtrooper qui vise bien",
        "E.T. l'extra-terrestre",
        "Alf mangeant un chat",
        "Un Gremlin mouillé",
        "La Dolorean de Retour vers le Futur",
        "Un T-Rex avec des bras trop courts",
        "King Kong en haut de l'Empire State Building",
        "Godzilla qui écrase une maquette",
        "L'Iceberg du Titanic",
        "Le radeau de la Méduse",
        "La Joconde vue de dos",
        "Le Penseur de Rodin (qui a oublié ce qu'il pensait)",
        "La Tour de Pise (qui tombe pour de bon)",
        "Les statues de l'Île de Pâques",
        "Le mystère de la chambre jaune",
        "L'Atlantide",
        "Le Triangle des Bermudes",
        "La Zone 51",
        "Un cercle de culture (crop circle)",
        "Le monstre du placard",
        "La petite souris (qui est en grève)",
        "Le marchand de sable",
        "Le croque-mitaine",
        "Une fée des dents fauchée",
        "Le lapin de Pâques en retard",
        "Un poisson d'avril pas drôle",
        "La galette des rois (sans fève)",
        "Une crêpe qui reste collée au plafond",
        "Un sapin de Noël qui perd ses épines",
        "Une guirlande électrique emmêlée",
        "Le pull moche de Mark Darcy",
        "Un feu d'artifice mouillé",
        "La cérémonie des Césars (interminable)",
        "Un discours de remerciement gênant",
        "Le tapis rouge du Festival de Cannes",
        "La Palme d'Or",
        "Un Oscar en chocolat",
        "Le Walk of Fame",
        "Hollywood Boulevard",
        "Disneyland sous la pluie",
        "La Tour Eiffel qui clignote",
        "L'Arc de Triomphe emballé",
        "Le Louvre un mardi (c'est fermé)",
        "La ligne 13 du métro parisien",
        "Un contrôleur SNCF zélé",
        "Le wagon-bar du TGV",
        "Une valise à roulettes bruyante",
        "Le décalage horaire",
        "Un passeport périmé",
        "La douane volante",
        "Un détecteur de métaux qui sonne tout le temps",
        "La consigne de sécurité dans l'avion",
        "Une licorne sous crack",
        "Ma vie sexuelle inexistante",
        "L'odeur d'un métro bondé",
        "Trois nains dans un imperméable",
        "Un kinder surprise périmé",
        "Nicolas Sarkozy",
        "Un massage prostatique",
        "La dignité",
        "Un cadavre dans le coffre",
        "Mes parents",
        "Une raclette en plein canicule",
        "Les chaussettes-sandales",
        "Un test de paternité positif",
        "La calvitie précoce",
        "Une chèvre enragée",
        "L'alcoolisme mondain",
        "Se réveiller dans son vomi",
        "Un film d'auteur chiant",
        "Une colonoscopie surprise",
        "Manger ses propres crottes de nez",
        "Une érection gênante",
        "Le 49.3",
        "Vendre sa grand-mère",
        "Un kebab complet sauce blanche",
        "Le patriarcat",
        "Une invasion de zombies vegans",
        "Faire pipi sous la douche",
        "Mon ex psychopathe",
        "Un influenceur Dubaï",
        "La musique d'ascenseur",
        "Un poney magique",
        "du LSD au petit dejeuner",
        "un chien qui boîte",
        "un nazi dans une Synagogue",
        "une pipe avec les dents",
        "Emmanuel Macron qui me roule des pelles",
        "une chambre à gaz mal fermé",
        "un djiadiste en porte-jartelle",
        "le fou du bus",
        "Paul pogba",
        "caca",
        "pipi",
        "une sodomie baveuse",
        "un bisou avec la langue",
        "les voies de dieux",
        "un enfant catho",
        "une bassine de vomi",
        "des pieds plats",
        "Le prépuce du Christ",
        "Un tampon usagé infusé dans du thé",
        "Fister une grand-mère",
        "Xavier Dupont de Ligonnès",
        "L'avortement au cintre",
        "Une érection pendant des funérailles",
        "Le cancer des testicules",
        "Lécher la barre du métro",
        "Un sextoy à double entrée",
        "Une tournante dans une cave",
        "Michel Fourniret baby-sitter",
        "Vendre un rein pour un iPhone",
        "Coucher avec sa cousine germaine",
        "Un glory hole dans une église",
        "Les restes d'une fausse couche",
        "Pousser un handicapé dans les escaliers",
        "Le journal intime d'Anne Frank",
        "Se masturber avec du papier de verre",
        "Une blague sur la trisomie 21",
        "Le Ku Klux Klan",
        "Boire l'eau de la cuvette des chiottes",
        "Un gode ceinture XXL",
        "La fouille anale à l'aéroport",
        "Une MST qui gratte fort",
        "Le trafic d'organes d'enfants",
        "Mettre les doigts dans la prise",
        "Une éjaculation faciale surprise",
        "Le dentier de mamie dans un verre d'eau",
        "Un pet foireux",
        "L'odeur du smegma",
        "Un bébé loutre qui tient un caillou",
        "Un chaton qui éternue",
        "Un panda qui fait une roulade",
        "Un alpaga avec une frange",
        "Un pingouin qui glisse sur le ventre",
        "Un hérisson en pyjama",
        "Un hamster qui fait du karaté",
        "Une licorne qui pète des paillettes",
        "Un chien qui court dans son rêve",
        "Un koala très fatigué",
        "Un écureuil qui a oublié où il a caché sa noisette",
        "Un canard avec un nœud papillon",
        "Un lapin qui remue le nez",
        "Un bébé phoque qui fait coucou",
        "Un chat coincé dans un carton",
        "Un chien qui chasse sa propre queue",
        "Un poisson rouge qui se prend pour un requin",
        "Une tortue qui fait la course",
        "Un perroquet qui chante du Céline Dion",
        "Un bébé éléphant qui joue avec de l'eau",
        "Une chauve-souris qui sourit",
        "Un hibou avec des lunettes",
        "Un paresseux qui traverse la route",
        "Une girafe qui boit au biberon",
        "Un wombat cubique",
        "Un bébé kangourou dans une poche",
        "Un suricate qui monte la garde",
        "Un ours polaire qui boit un coca",
        "Un renard qui rigole",
        "Un flamant rose unijambiste",
        "Un bébé chèvre qui saute partout",
        "Un dinosaure végétarien",
        "Un petit poney qui se croit grand",
        "Un chat qui a peur d'un concombre",
        "Un chien qui fait du skate",
        "Un singe qui fait une grimace",
        "Un bébé tigre qui rugit doucement",
        "Un capybara zen dans un bain chaud",
        "Un bébé hippopotame tout rose",
        "Un raton laveur qui lave ses mains",
        "Un quokka (l'animal le plus heureux du monde)",
        "Un bébé poule qui piaille",
        "Un papillon qui se pose sur ton nez",
        "Un escargot turbo",
        "Un ver de terre timide",
        "Une coccinelle porte-bonheur",
        "Un bourdon tout duveteux",
        "Une grenouille qui coasse",
        "Un caméléon qui ne sait pas changer de couleur",
        "Un bébé gorille qui se gratte la tête",

        // --- NOURRITURE & GOURMANDISE ---
        "Une montagne de chantilly",
        "Un cookie géant",
        "Une pizza aux bonbons",
        "Une fontaine de chocolat",
        "Un donut à la fraise",
        "Une barbe à papa immense",
        "Un cupcake avec trop de glaçage",
        "Une glace à trois boules",
        "Un chamallow grillé",
        "Une religieuse au café",
        "Un macaron tout rose",
        "Une crêpe au nutella",
        "Un pot de miel infini",
        "Une fraise tagada géante",
        "Un milkshake à la vanille",
        "Une pomme d'amour qui colle aux dents",
        "Des pancakes en forme de cœur",
        "Un chocolat chaud avec des guimauves",
        "Une baguette de pain toute chaude",
        "Un croissant au beurre",
        "Une tartine de confiture qui tombe du bon côté",
        "Un bonbon qui pique",
        "Un gâteau d'anniversaire à étages",
        "Une sucette multicolore",
        "Du popcorn caramélisé",
        "Une gaufre avec du sirop d'érable",
        "Un smoothie banane-kiwi",
        "Une part de cheesecake",
        "Des spaghettis à la sauce tomate",
        "Un burger végétarien",
        "Une patate douce",
        "Un ananas qui porte des lunettes de soleil",
        "Une banane qui danse",
        "Une carotte qui rend aimable",
        "Un brocoli qui ressemble à un arbre",
        "Une tomate qui rougit",
        "Un citron qui fait faire la grimace",
        "Une pastèque sans pépins",
        "Un avocat parfaitement mûr",
        "Une cerise sur le gâteau",
        "Un pain au chocolat (ou chocolatine)",
        "Des frites croustillantes",
        "Une soupe de légumes de grand-mère",
        "Un œuf à la coque",
        "Du fromage qui file",
        "Un pique-nique sur l'herbe",
        "Le dernier morceau de gâteau",
        "Manger la pâte à gâteau crue",
        "Lécher le plat",
        "Un petit déjeuner au lit",

        // --- ENFANCE & NOSTALGIE ---
        "Un câlin de maman",
        "Sauter dans une flaque d'eau",
        "Une bataille d'oreillers",
        "Construire une cabane avec des draps",
        "Un doudou qui sent bon",
        "Une histoire avant de dormir",
        "Souffler sur un pissenlit",
        "Faire des bulles de savon",
        "Un dessin sur le frigo",
        "Une étoile gommette",
        "Jouer à cache-cache",
        "Faire de la balançoire",
        "Descendre le toboggan",
        "Un château de sable",
        "Courir dans l'herbe pieds nus",
        "Attraper des lucioles",
        "Regarder les nuages",
        "Sauter sur le lit",
        "Un bisou magique qui guérit tout",
        "Une dent de lait sous l'oreiller",
        "Croire au Père Noël",
        "Ouvrir ses cadeaux",
        "Un ballon de baudruche rouge",
        "Une boîte de crayons de couleur neufs",
        "De la pâte à modeler",
        "Un yoyo qui s'emmêle",
        "Des billes dans la cour de récré",
        "La corde à sauter",
        "Jouer à la marelle",
        "Un cerf-volant dans le ciel",
        "Une journée à la mer",
        "Ramasser des coquillages",
        "Faire un bonhomme de neige",
        "Une bataille de boules de neige",
        "Boire à la paille",
        "Faire des grimaces dans le miroir",
        "Se déguiser en super-héros",
        "Porter une cape",
        "Avoir des super-pouvoirs",
        "Un ami imaginaire",
        "Dormir avec une veilleuse",
        "Avoir peur du noir (un tout petit peu)",
        "Faire la sieste",
        "Le goûter de 16h30",
        "Les vacances d'été",
        "La rentrée des classes",
        "Un cartable tout neuf",
        "Apprendre à faire du vélo",
        "Tomber et se relever",
        "Rire aux éclats",

        // --- OBJETS & TRUCS LOUFOQUES ---
        "Des chaussettes dépareillées",
        "Un pull en laine qui gratte pas",
        "Une couette toute douce",
        "Un oreiller moelleux",
        "Des chaussons en forme de lapin",
        "Un bonnet à pompon",
        "Une écharpe de 3 mètres de long",
        "Des lunettes en forme de cœur",
        "Un parapluie multicolore",
        "Des bottes de pluie jaunes",
        "Une bouillotte chaude",
        "Un bain moussant",
        "Une brosse à dents électrique qui chante",
        "Un réveil qui ne sonne pas",
        "Une télécommande qui marche du premier coup",
        "Un grille-pain courageux",
        "Une petite cuillère",
        "Une tasse de thé fumante",
        "Un carnet secret",
        "Un stylo à paillettes",
        "De la colle qui sent l'amande",
        "Un post-it avec un cœur dessus",
        "Une lettre manuscrite",
        "Un timbre de collection",
        "Une boule à neige",
        "Un kaléidoscope",
        "Une boîte à musique",
        "Un jouet qui fait 'pouet'",
        "Un canard en plastique",
        "Une bouée flamant rose",
        "Un matelas gonflable",
        "Une tente de camping",
        "Un feu de camp",
        "Une guitare mal accordée",
        "Un piano miniature",
        "Un ukulélé",
        "Un chapeau pointu",
        "Une fausse moustache",
        "Un nez de clown",
        "Des confettis",
        "Des serpentins",
        "Une piñata",
        "Un ballon qui s'envole",
        "Une carte au trésor",
        "Une boussole qui indique le Nord",
        "Une loupe pour voir les fourmis",
        "Un télescope pour voir la Lune",
        "Une fusée en carton",
        "Une voiture télécommandée",
        "Un robot qui danse",

        // --- CONCEPTS ABSTRAITS & ÉMOTIONS ---
        "L'amitié éternelle",
        "Le grand amour",
        "Un fou rire incontrôlable",
        "La paix dans le monde",
        "Un rêve lucide",
        "L'odeur de la pluie",
        "Le bruit des vagues",
        "Le chant des oiseaux",
        "Un rayon de soleil",
        "Un arc-en-ciel double",
        "La pleine lune",
        "Une étoile filante",
        "Faire un vœu",
        "La chance du débutant",
        "Gagner au loto (mais juste 2€)",
        "Trouver un trèfle à quatre feuilles",
        "Une bonne nouvelle",
        "Une surprise agréable",
        "Un compliment sincère",
        "Se sentir utile",
        "Aider une vieille dame",
        "Donner son sang (c'est bien)",
        "Planter un arbre",
        "Sauver une abeille",
        "Adopter un animal",
        "Faire un don",
        "Sourire à un inconnu",
        "Dire 'merci'",
        "Dire 'je t'aime'",
        "Pardonner",
        "Être patient",
        "La gentillesse",
        "L'honnêteté",
        "La curiosité",
        "L'imagination",
        "La créativité",
        "L'espoir",
        "La joie de vivre",
        "L'optimisme",
        "La sérénité",
        "Le confort",
        "La chaleur humaine",
        "L'esprit d'équipe",
        "La solidarité",
        "La liberté",
        "L'aventure",
        "La découverte",
        "L'émerveillement",
        "La gratitude",
        "Le bonheur simple",

        // --- FANTASY & IMAGINAIRE ---
        "Une fée clochette",
        "Un dragon gentil",
        "Un génie dans une lampe",
        "Un tapis volant",
        "Une baguette magique",
        "Une potion d'invisibilité",
        "Des bottes de sept lieues",
        "Une épée en mousse",
        "Un bouclier en carton",
        "Un chevalier servant",
        "Une princesse rebelle",
        "Un roi fainéant",
        "Un sorcier maladroit",
        "Un elfe des bois",
        "Un nain de jardin vivant",
        "Un troll qui fait des câlins",
        "Un ogre végétarien",
        "Une sirène qui chante faux",
        "Un monstre du Loch Ness timide",
        "Un yéti frileux",
        "Un extra-terrestre paumé",
        "Une soucoupe volante",
        "Un voyage dans le temps",
        "Une machine à téléportation",
        "Un robot domestique",
        "Une ville flottante",
        "Une île déserte (avec du wifi)",
        "Un trésor caché",
        "Une carte magique",
        "Un livre qui se lit tout seul",
        "Un miroir qui parle",
        "Une citrouille qui devient carrosse",
        "Une pantoufle de verre",
        "Un haricot magique",
        "Une maison en pain d'épices",
        "Un loup qui souffle sur des maisons",
        "Trois petits cochons",
        "Un petit chaperon rouge",
        "Un chat botté",
        "Une belle au bois dormant",
        "Un prince charmant (un peu collant)",
        "Une marraine la bonne fée",
        "De la poussière d'étoile",
        "Un sortilège de chatouilles",
        "Voler comme un oiseau",
        "Respirer sous l'eau",
        "Parler aux animaux",
        "Lire dans les pensées (juste les gentilles)",
        "Arrêter le temps",
        "Devenir tout petit",

        // --- SITUATIONS MIGNONNES & DRÔLES ---
        "Danser sous la pluie",
        "Chanter sous la douche",
        "Faire du air guitar",
        "Gagner à pierre-feuille-ciseaux",
        "Réussir un créneau du premier coup",
        "Retrouver de l'argent dans sa poche",
        "Se réveiller avant le réveil",
        "Avoir une place assise dans le bus",
        "Recevoir un colis",
        "Percer du papier bulle",
        "L'odeur du pain grillé",
        "L'odeur du linge propre",
        "Mettre un pyjama propre après la douche",
        "S'endormir devant un film",
        "Ne rien faire du tout",
        "Regarder la pluie tomber",
        "Écouter de la musique lo-fi",
        "Faire un puzzle",
        "Colorier sans dépasser",
        "Faire des origamis",
        "Apprendre une langue étrangère",
        "Faire du yoga",
        "Méditer",
        "Prendre un bain de soleil",
        "Marcher dans la forêt",
        "Écouter les cigales",
        "Regarder les étoiles",
        "Faire un vœu quand on passe sous un tunnel",
        "Croiser les doigts",
        "Toucher du bois",
        "Trouver une place de parking",
        "Avoir le feu vert",
        "Manger le croûton du pain",
        "Lécher la cuillère de nutella",
        "Tremper un biscuit dans le lait",
        "Faire des ronds de fumée (mais avec de la vapeur)",
        "Souffler des bougies",
        "Recevoir une carte postale",
        "Écrire un poème",
        "Faire une blague nulle",
        "Rire à sa propre blague",
        "Faire un clin d'œil raté",
        "Trébucher mais faire genre c'est une danse",
        "Parler à son chat",
        "Parler à ses plantes",
        "Donner un nom à sa voiture",
        "Porter des lunettes de soleil la nuit",
        "Mettre ses chaussettes à l'envers",
        "Avoir un épi dans les cheveux",
        "Avoir de la mousse de lait sur les lèvres",

        // --- RANDOM TOTAL & DOUX ---
        "Un nuage en forme de lapin",
        "Une bataille de polochons",
        "Un câlin collectif",
        "Un bisou d'esquimau",
        "Se tenir la main",
        "Dormir en cuillère",
        "Un massage des pieds",
        "Se faire gratter le dos",
        "Jouer avec les cheveux de quelqu'un",
        "Faire des guilis",
        "Une soirée pyjama",
        "Regarder des dessins animés",
        "Manger des céréales le soir",
        "Dormir avec son chien",
        "Faire la grasse matinée",
        "Prendre le petit déjeuner au dîner",
        "Manger une pizza dans son lit",
        "Faire du camping dans le salon",
        "Raconter des histoires qui font pas peur",
        "Faire des ombres chinoises",
        "Jouer aux cartes",
        "Faire une réussite",
        "Gagner au solitaire",
        "Faire un château de cartes",
        "Faire tomber des dominos",
        "Regarder une vidéo de chat",
        "Envoyer un gif mignon",
        "Mettre des emojis partout",
        "Écrire en majuscules DE JOIE",
        "Faire un high-five",
        "Faire un check",
        "Faire la chenille",
        "Danser la macarena",
        "Chanter 'Joyeux Anniversaire'",
        "Faire la fête",
        "Lancer des confettis",
        "Souffler dans une langue de belle-mère",
        "Porter un chapeau pointu",
        "Manger du gâteau",
        "Boire du champomy",
        "Porter un pull moche de Noël",
        "Offrir un cadeau fait main",
        "Recevoir un dessin d'enfant",
        "Voir un arc-en-ciel",
        "Trouver un coquillage parfait",
        "Voir un dauphin",
        "Nager avec des tortues",
        "Caresser un cheval",
        "Donner à manger aux canards",
        "Sauver un escargot de la pluie",
        "Le journal intime d'Anne Frank",
        "Se masturber avec du papier de verre",
        "Une blague sur la trisomie 21",
        "Le Ku Klux Klan",
        "Boire l'eau de la cuvette des chiottes",
        "Un gode-ceinture XXL",
        "La fouille anale à l'aéroport",
        "Une MST qui gratte fort",
        "Le trafic d'organes d'enfants",
        "Mettre les doigts dans la prise",
        "Une éjaculation faciale surprise",
        "Le dentier de mamie dans un verre d'eau",
        "Un pet foireux",
        "L'odeur du smegma",
        "Les juifs et l'argent",
        "Les Arabes qui puent l'ail",
        "Les Noirs et la pastèque",
        "Les Chinois qui mangent des chiens",
        "Les Roms qui volent",
        "Les pédés avec le sida",
        "Les féministes poilues",
        "Un clochard qui pisse dans la rue",
        "L'inceste en famille",
        "Une grand-mère qui suce",
        "Le cancer des couilles",
        "L'avortement à la cuillère",
        "Les migrants qui violent",
        "Les musulmans et les chèvres",
        "Un cul défoncé au marteau-piqueur",
        "La shoah en kit",
        "Un nain qui se fait enculer",
        "Le sperme de prêtre",
        "Les communistes qui crèvent la dalle",
        "Les capitalistes qui sucent les pauvres",
        "Un steak haché frites",
        "Papa et maman",
        "Une fête foraine",
        "Des bisous sur la bouche",
        "Un câlin tout doux",
        "Le doudou de bébé",
        "Un gros caca qui bouchonne",
        "Une diarrhée explosive",
        "Un viol collectif en prison",
        "Les juifs au four",
        "Les bougnoules au bled",
        "Le cul de ta mère",
        "Une pute à 10 euros",
        "Un travelo qui bande mou",
        "Le vomi de clodo",
        "Un fist anal jusqu'au coude",
        "Les bébés phoques matraqués",
        "Un skinhead qui cogne",
        "Une vieille qui pète la gueule ouverte",
        "Le sang menstruel dans la soupe",
        "Un pédophile en maternelle",
        "Les nazis qui reviennent",
        "Une grosse bite noire",
        "Un Arabe qui explose",
        "Les Chintoks et le coronavirus",
        "Un juif qui compte ses shekels",
        "Une lesbienne avec un gode",
        "Le sperme dans les yeux",
        "Un curé qui défonce un enfant de chœur",
        "Une grosse truie qui se fait baiser",
        "Un handicapé qui bave",
        "Une famille qui fait l'amour ensemble",
        "Le gaz Zyklon B",
        "Un clito de 15 cm",
        "Les vieux qui chient au lit",
        "Les féminazies qui hurlent",
        "Un avorton dans la poubelle",
        "Macron qui suce les banquiers",
        "Une mamie qui se fait gangbanger",
        "Un gosse qui suce pour du Nutella",
        "Les juifs qui contrôlent le monde",
        "Les Noirs qui volent des vélos",
        "Un Chinois qui mange un pangolin",
        "Un Rom qui fait les poches",
        "Un kebab qui donne la chiasse",
        "Un français qui chie une baguette",
        "Un américain qui place la russie",
        "les russes et les fingues",
        "Un curé qui se branle sur des anges",
        "Une nonne qui se gode avec une croix",
        "Une chatte qui sent le poisson pourri",
        "Un pet silencieux qui tue",
        "Un violeur en liberté",
        "Un mort dans le coffre",
        "Un nazi qui fait le salut",
        "Un communiste qui nationalise ta brosse à dents",
        "Un libéral qui vend sa mère",
        "Un écologiste qui chie dans la forêt",
        "Un vegan qui mange son placenta",
        "Une grosse bite circoncise",
        "Un Arabe qui fait 10 gosses",
        "Un Noir avec une bite de 40 cm",
        "Un Asiatique qui copie tout",
        "Un gitan qui vole les câbles",
        "Un flic qui tabasse gratis",
        "Un prof qui baise ses élèves",
        "Une mère qui allaite à 15 ans",
        "Un père qui mate sa fille",
        "Un frère qui défonce sa sœur",
        "Une grand-mère qui montre sa chatte",
        "Un cadavre qui bande",
        "Une nécrophile qui jouit",
        "Un zoophile avec sa chèvre",
        "Un scatophile qui bouffe la merde",
        "Un urophile qui boit le pipi",
        "Un amputé qui se branle avec son moignon",
        "Un trisomique qui fait coucou",
        "Un autiste qui tourne en rond",
        "Un schizo qui parle aux murs",
        "Un Alzheimer qui oublie qu'il chie",
        "Un Parkinson qui branle les autres",
        "Un sidaïque qui contamine exprès",
        "Un cancéreux qui tousse ses poumons",
        "Un obèse qui explose son fauteuil",
        "Un anorexique qui ressemble à un squelette",
        "Un nain qui grimpe sur la table",
        "Un albinos qui crame au soleil",
        "Un aveugle qui mate",
        "Un sourd qui pète fort",
        "Un paralysé qui bande quand même",
        "Un comateux qu'on débranche",
        "Un vampire qui suce autre chose",
        "Un loup-garou qui se branle à la pleine lune",
        "Un clown qui viole les enfants",
        "Un père Noël pédophile",
        "Une fée qui fait des pipes",
        "Bob l'éponge qui suce Patrick",
        "Pikachu qui électrocute des couilles",
        "Peach qui sodomise mario",
        "Harry Potter qui joue au strip poker avec Rogue",
        "Dumbledore pédé",
        "Hermione qui écarte",
        "Batman qui détourne Robin",
        "Superman qui défonce Lois",
        "Wonder Woman qui strap-on",
        "Deadpool qui régénère sa bite",
        "Dark Vador qui baisse mon pantalon",
        "La princesse Leia en bikini doré",
        "Baby Yoda qui coiffe le yeti",
        "Shrek qui baise l'âne",
        "Pinocchio qui bande quand il ment",
        "Simba qui cri comme AC/DC",
        "Elsa qui se gèle les couilles",
        "Olaf qui fond sur ma carotte",
        "Blanche-Neige et les 7 bites",
        "La Belle et la Bête en fourrure",
        "Ariel qui montre sa queue de poisson",
        "Aladdin qui frotte autre chose que la lampe",
        "Mulan qui tire avec ses pieds",
        "Mickey qui éjacule sans ses gants",
        "Donald qui rage-baise Daisy",
        "Scooby-Doo qui fuit DSK",
        "Les Simpsons qui s'enculent en jaune",
        "Frodon qui porte l'anneau au cul",
        "Gandalf qui dit « tu ne passeras pas » en éjaculant",
        "Daenerys qui baise ses dragons",
        "Jon Snow qui ne sait rien mais baise bien",

        "Un schtroumpf bleu dans le cul de la Schtroumpfette",
        "La Schtroumpfette qui prend 100 bites",
        "Gargamel qui veut bouffer du schtroumpf",
        "Un minion qui pète banane",
        "Gru qui adopte des bites",
        "Le Grinch qui vole Noël et les capotes",
        "Scooby-Doo qui lèche autre chose que des Scooby Snacks",
        "Dora qui explore des grottes humides",
        "Babouche qui vole des capotes",
        "Les 101 Dalmatiens en orgie",
        "Cruella qui porte rien sous la fourrure",
        "La Belle au bois dormant qui se fait prendre en dormant",
        "Cendrillon qui perd sa capote à minuit",
        "Le capitaine Crochet qui a un crochet dans le cul",
        "Ursula qui vole des voix pour des pipes",
        "Jafar qui hypnotise pour défoncer",
        "Quasimodo qui sonne les cloches en jouissant",
        "Esmeralda qui danse nue",
        "Frollo qui brûle des gitanes après",
        "Supercalifragilisticexpialidocious dans ta mère",
        "Les Aristochats qui miaulent en baisant",
        "Oliver et compagnie en gangbang de chats",
        "Robin des Bois version renard qui vole des vierges",
        "La Petite Sirène version hentai",
        "Un vibromasseur qui parle français",
        "Un Playmobil qui perd sa tête en jouissant",
        "Une figurine Lego qui s'emboîte ailleurs",
        "Un dildo en forme de Tour Eiffel",
        "Une baguette magique qui fait vraiment des miracles",
        "Un siège de métro goût croissant",
        "Une capote qui brille dans le noir",
        "Une assiette en forme de cœur",
        "Des menottes roses fluo",
        "Un fouet à neuf queues",
        "Une chasteté en acier",
        "Des pinces à tétons qui sonnent",
        "Un cockring qui vibre",
        "Une sonde urétrale en argent",
        "un stétoscope premier prix",
        "un faux ongle bon marché",
        "Un strap-on de 30 cm",
        "Un glory hole dans le mur",
        "Une soirée in the dark",
        "Un gangbang organisé",
        "Une partouze échangiste",
        "Un club libertin bondé",
        "jul",
        "SNK",
        "la série friends",
        "Des orgies romaines",
        "Un bukkake japonais",
        "Un glory hole coréen",
        "Une milf qui éduque",
        "Un daddy qui punit",
        "Une teen qui découvre",
        "Un couple qui filme",
        "Un dominateur qui attache",
        "Une soumise qui rampe",
        "Un fétichiste des pieds",
        "Un mec sans jambe",
        "Un fan de latex",
        "Une latex girl qui brille",
        "Un puppy qui aboie",
        "Un pony qui galope",
        "Une catwoman qui griffe",
        "Un maître qui dresse",
        "Une esclave qui obéit",
        "Un gode en verre qui casse",
        "Un plug en métal qui glace",
        "Une chaîne anale de 1 mètre",
        "Des poids pour les couilles",
        "Un dilatateur anal XXL",
        "une bouillabaisse",
        "un cassoulet",
        "Madame et Monsieur",
        "Un électro-stimulateur qui fait hurler",
        "Une balançoire de sexe",
        "Un miroir au plafond",
        "Des caméras partout",
        "Une croix de Saint-André",
        "Une cage de chasteté permanente",
        "un génocide qui dégenère",
        "un arménien",
        "un japonais",
        "un néozélandais",
        "une blague limite",
        "la prison à vie",
        "Une marque au fer rouge",

        "Une vidéo OnlyFans qui leak",
        "Un nudes qui tourne sur Telegram",
        "Une sextape qui ruine une carrière",
        "Un revenge porn qui fait le buzz",
        "Une deepfake de baise",
        "Un live Twitch qui dérape",
        "Une story Insta de cul",
        "Un snap de bite non sollicité",
        "Un dickpic dans les DM",
        "Une chatte épilée en cœur",
        "Un cul rebondi huilé",
        "Des seins refaits qui claquent",
        "Une bouche qui avale jusqu'aux couilles",
        "Des lèvres qui sucent comme un aspirateur",
        "Une langue qui lèche l'anus",
        "Un doigt dans le cul pendant la pipe",
        "Une triple qui fait pleurer",
        "Un fist qui disparaît",
        "Une queue qui rentre partout",
        "Un trou qui accepte tout",
        "Une salope qui dit merci",
        "Un mec qui bande dur",
        "Un plan cul qui devient amour",
        "Une baise qui finit en câlins",
        "Un câlin qui finit en baise",
        "Une nuit qui ne finit jamais",
        "Des toilettes parrtagé",
        "Un tiramisu qui tire la misère",
        "Une mousse au chocolat qui mousse",
        "Un soufflé qui retombe",
        "Une charlotte aux fraises qui charlotte",
        "Un baba au rhum qui a trop bu",
        "Un saint-honoré qui honore",
        "Une profiterole qui profite",
        "Un macaron qui macule",
        "Un canapé qui a vu des choses",
        "Un petit four qui fourre",
        "Une bouchée à la reine qui bouffe",
        "Un vol-au-vent qui vole",
        "Un pâté en croûte qui encule",
        "Une quiche lorraine qui kiffe",
        "Un croissant qui croît",
        "Un pain qui pine",
        "Une brioche qui brille",
        "Un chausson aux pommes qui chausse",
        "Un éclair qui claque",
        "Un chou à la crème qui chouine",
        "Une religieuse qui se fait défoncer",
        "Un paris-brest qui fait Paris-Brest",
        "Un kouign-amann qui couine",
        "Un far breton qui farte",
        "Un gâteau basque qui bascule",
        "Un cannelé qui canne",
        "Un madeleine qui fait bander Proust",
        "Un palmier qui palme",
        "Un croissant qui croasse",
        "Un pain au chocolat qui paine",
        "Une baguette qui bagarre",
        "Un kebab qui kebabe",
        "Un burger qui burge",
        "Une pizza qui pizze",
        "Un tacos qui tacose",
        "Une crêpe qui crêpe",
        "Une gaufre qui gaufre",
        "Un donut qui donne",
        "Une glace qui glisse",
        "Un cornet qui corne",
        "Une chantilly qui chante",
        "Un esquimau qui esquinte",
        "Une banane split qui split",
        "Une coupe colonel qui coule",
        "Une dame blanche qui dame",
        "Une pêche Melba qui pêche",
        "Une poire Belle-Hélène qui belle",
        "Un café liégeois qui lie",
        "Un chocolat liégeois qui lie aussi",
        "Une profiterole qui profite encore",
        "Un sundae qui sun",
        "Un milkshake qui shake",
        "Une fraise tagada qui tagade",
        "Un bonbon qui bondit",
        "Un chamallow qui mallow",
        "Un nounours qui ours",
        "Une guimauve qui guime",
        "Un réglisse qui règle",
        "Un dragibus qui drague",
        "Un carambar qui carambarre",
        "Une fraise Haribo qui haribe",
        "Un coca qui coque",
        "Une bière qui biere",
        "Un vin qui vine",
        "Un champagne qui champe",
        "Une coupe qui coupe",
        "Un mojito qui mojite",
        "Une piña colada qui pine",
        "Un blue lagoon qui blue",
        "Un tequila paf qui paf",
        "Un shooter qui shoote",
        "Un Jägerbomb qui bomb",
        "Un vodka Red Bull qui vole",
        "Un pastis qui pastisse",
        "Un ricard qui ricane",
        "Un jaune qui jaunit",
        "Un blanc qui blanchit",
        "Un rouge qui rougit",
        "Un rosé qui rose",
        "Un kir qui kiffe",
        "Un kir royal qui royale",
        "Un spritz qui spritze",
        "Un gin tonic qui gicle",
        "Un cuba libre qui libère",
        "Un rhum arrangé qui arrange",
        "Un planteur qui plante",
        "Un ti-punch qui punche",
        "Un punch coco qui coco",
        "Un cocktail qui cocke",
        "Une soirée qui dérape",
        "Une cuite qui cuit",
        "Une gueule de bois qui boit",
        "Un lendemain qui ment",
        "Une nuit qui nuit",
        "Un matin qui mate",
        "Un réveil qui réveille",
        "Une douche froide qui refroidit",
        "Un café serré qui serre",
        "Une aspirine qui aspire",
        "Un doliprane qui doliprane",
        "Un regret qui regrette",
        "Une capote oubliée qui oublie",
        "Un test de grossesse qui teste",
        "Une pilule du lendemain qui pile",
        "Une IVG qui ive",
        "Une contraception qui contracepte",
        "Un stérilet qui stérilise",
        "Une ligature qui ligue",
        "Un vasectomie qui vase",
        "Une bite coupée qui coupe",
        "Un clito cousu qui coud",
        "Une chatte fermée qui ferme",
        "Un cul bouché qui bouche",
        "Une abstinence qui abstine",
        "Une chasteté qui châtie",
        "Une virginité qui virginise",
        "Un moine qui moine",
        "Une nonne qui nonne",
        "Un curé qui cure",
        "Un rabbin qui rabine",
        "Un imam qui imame",
        "Un bouddha qui boude",
        "Un gourou qui gouroute",
        "Un secte qui secte",
        "Un culte qui cul",
        "Une messe qui messe",
        "Un prêche qui prêche",
        "Une prière qui prie",
        "Un amen qui amène",
        "Un alléluia qui allèle",
        "Un kyrie eleison qui kyrie",
        "Un gloria qui glougloute",
        "Un credo qui crie",
        "Un confiteor qui confit",
        "Un ave maria qui ave",
        "Un père qui père",
        "Un fils qui file",
        "Un saint-esprit qui sainte",
        "Une trinité qui trine",
        "Un paradis qui pare",
        "Un enfer qui enfers",
        "Un purgatoire qui purge",
        "Un diable qui diable",
        "Un démon qui démone",
        "Un ange qui ange",
        "Un archange qui arche",
        "Un séraphin qui séra",
        "Un chérubin qui chéri",
        "Un trône qui trône",
        "Un domination qui domine",
        "Un vertu qui vertue",
        "Un pouvoir qui pouvoie",
        "Un principauté qui principe",
        "Un archange qui arche encore",
        "Un satan qui satane",
        "Un lucifer qui lucife",
        "Un belzébuth qui belze",
        "Un mammon qui mamme",
        "Un asmodée qui asmode",
        "Un léviathan qui lévie",
        "Un belphégor qui belphe",
        "Un abaddon qui abad",
        "Un apocalypse qui apoca",
        "Un jugement dernier qui juge",
        "Une résurrection qui résurrecte",
        "Un ciel qui ciele",
        "Une terre qui terre",
        "Un univers qui uni",
        "Un multivers qui multi",
        "Un big bang qui bigue",
        "Une création qui crée",
        "Un dieu qui die",
        "Une déesse qui déesse",
        "Un athée qui a",
        "Un agnostique qui agno",
        "Un mécréant qui mé",
        "Un blasphème qui blas",
        "Une hérésie qui héré",
        "Un sacrilège qui sacri",
        "Un tabou qui taboue",
        "Un interdit qui inter",
        "Un péché qui pé",
        "Un vice qui vice",
        "Une vertu qui vertue encore",
        "Un bien qui bia",
        "Un mal qui male",
        "Un yin qui yinge",
        "Un yang qui yange",
        "Un karma qui karme",
        "Un dharma qui dharme",
        "Un nirvana qui nir",
        "Un samsara qui sam",
        "Un bouddhisme qui boud",
        "Un hindouisme qui hindou",
        "Un jaïnisme qui jaïne",
        "Un sikhisme qui sikhe",
        "Un shinto qui shin",
        "Un tao qui tao",
        "Un confucius qui confu",
        "Un lao tseu qui lao",
        "Un zhuangzi qui zhuang",
        "Un moïse qui moïse",
        "Un abraham qui abra",
        "Un isaac qui isa",
        "Un jacob qui jac",
        "Un joseph qui jose",
        "Un david qui dav",
        "Un salomon qui salo",
        "Un jésus qui jé",
        "Un marie qui marie",
        "Un joseph qui jose encore",
        "Un paul qui pau",
        "Un pierre qui pie",
        "Un judas qui jud",
        "Un satan qui satane encore",
        "Un mahomet qui maho",
        "Un allah qui alla",
        "Un coran qui cora",
        "Un hadith qui hadi",
        "Un ramadan qui rama",
        "Un ramadan qui jouit pas",
        "Un jeûne qui jeûne",
        "Une prière cinq fois par jour pour bander",
        "Un voile qui voile",
        "Un niqab qui niq",
        "Un burqa qui bur",
        "Un tchador qui tcha",
        "Un hijab qui hi",
        "Un turban qui tur",
        "Un kippa qui kip",
        "Un tzitzit qui tzi",
        "Un talith qui tali",
        "Un rabbin qui rabine encore",
        "Un imam qui ima",
        "Un pape qui pape",
        "Un cardinal qui cardi",
        "Un évêque qui évê",
        "Un prêtre qui prê",
        "Un diacre qui dia",
        "Un moine qui moi",
        "Une sœur qui sœur",
        "Une mère supérieure qui mère",
        "Un exorcisme qui exor",
        "Un possédé qui pos",
        "Un diable qui dia",
        "Une bible qui bib",
        "Un évangile qui évan",
        "Un ancien testament qui anci",
        "Un nouveau testament qui nou",
        "Un apocryphe qui apo",
        "Un livre qui liv",
        "Un verset qui ver",
        "Un psaume qui psal",
        "Un cantique qui can",
        "Un alléluia qui allè",
        "Un amen qui amène encore",
        "Un gloire à dieu qui glo",
        "Un père éternel qui pè",
        "Un fils unique qui fi",
        "Un esprit saint qui es",
        "Une trinité qui tri",
        "Un mystère qui mys",
        "Un dogme qui dog",
        "Une foi qui foi",
        "Une espérance qui esp",
        "Une charité qui cha",
        "Un amour qui amou",
        "Un prochain qui pro",
        "Un ennemi qui enne",
        "Un pardon qui par",
        "Un péché qui pé encore",
        "Une confession qui con",
        "Un pénitence qui péni",
        "Un chapelet qui cha",
        "Une neuvaine qui neu",
        "Un rosaire qui ro",
        "Un je vous salue marie qui je",
        "Un notre père qui not",
        "Un credo qui cre",
        "Un acte de contrition qui act",
        "Un mea culpa qui mea",
        "Un kyrie qui ky",
        "Un gloria qui glo encore",
        "Un sanctus qui san",
        "Un agnus dei qui agn",
        "Un amen final qui amène la fin",
        // --- FAITS HISTORIQUES & BIZARRERIES DU PASSÉ ---
        "La Guerre des Émeus en Australie",
        "Une momie égyptienne mal conservée",
        "L'invention du pain tranché",
        "La moustache de Vercingétorix",
        "Un procès contre un cochon au Moyen-Âge",
        "La calvitie de Napoléon",
        "L'incident du vase de Soissons",
        "La découverte du feu par un homme des cavernes maladroit",
        "Le dernier repas de Louis XVI",
        "La peste noire (version soft)",
        "Un duel au pistolet à l'aube",
        "La recette originale du Coca-Cola",
        "Le nez manquant du Sphinx",
        "Une peinture rupestre moche",
        "La chute de l'Empire Romain",
        "Un chevalier qui a oublié son épée",
        "La construction de la Tour Eiffel en allumettes",
        "Le premier homme à avoir mangé une huître",
        "Une guillotine un peu rouillée",
        "Le naufrage du Titanic (en temps réel)",
        "Les oies du Capitole",
        "Une chasse aux sorcières inefficace",
        "Le traité de Versailles écrit au crayon à papier",
        "La poudre de perlimpinpin",
        "Un dinosaure qui ne croit pas au météore",
        "La prohibition de l'alcool",
        "Le mur de Berlin (en kit)",
        "Une statue grecque sans bras",
        "Le trésor des Templiers",
        "La conquête de l'espace par un chien",
        "Un Viking qui a le mal de mer",
        "La Joconde qui fait la gueule",
        "Un pharaon allergique aux chats",
        "La légende du Roi Arthur (mais sans Arthur)",
        "Une invasion barbare très polie",
        "Le secret des pyramides",
        "Une croisade qui s'est trompée de chemin",
        "Le premier pas sur la Lune (tourné en studio)",
        "L'invention de la roue carrée",
        "Un samouraï en pyjama",

        // --- TITRES DE PRESSE & FAITS DIVERS (STYLE GORAFI/INSOLITE) ---
        "Un homme qui mord un chien",
        "Une grève surprise des mimes",
        "Le championnat du monde de tricot",
        "Un titre boursier qui s'effondre",
        "La pénurie mondiale de moutarde",
        "Un reportage sur la reproduction des escargots",
        "Le bulletin météo de la veille",
        "Une invasion de lapins en Australie",
        "Un concours de la plus grosse citrouille",
        "Un fait divers impliquant une baguette de pain",
        "Le cours du Bitcoin en 2010",
        "Une manifestation pour le droit de ne rien faire",
        "Un accident de pédalo",
        "Le vol d'une cargaison de sirop d'érable",
        "Un flash spécial sur TF1",
        "L'horoscope du jour (Bélier : restez couché)",
        "Un documentaire animalier sur Arte",
        "La rubrique nécrologique",
        "Une interview exclusive d'un arbre",
        "Le gagnant du loto qui a perdu son ticket",
        "Une alerte enlèvement pour un nain de jardin",
        "Le record du monde d'apnée dans une baignoire",
        "Un scandale sanitaire lié aux choux de Bruxelles",
        "La fermeture définitive du Minitel",
        "Un sondage IFOP très précis",
        "La une du journal local",
        "Une polémique sur la couleur d'une robe",
        "Le bug de l'an 2000",
        "Une loi interdisant le port du pantalon rose",
        "Un embouteillage sur le périphérique",
        "La hausse du prix du timbre",
        "Un tweet malencontreux",
        "Une fake news sur Facebook",
        "Le classement des personnalités préférées des Français",
        "Un débat télévisé qui tourne mal",
        "La météo marine",
        "Un fait divers en Creuse",
        "L'arrestation d'un père Noël ivre",
        "Une prise d'otage dans une fromagerie",
        "Le lancement d'une nouvelle fusée (qui explose)",

        // --- PERSONNALITÉS & ENTITÉS BIZARRES ---
        "Michel Houellebecq sous antidépresseurs",
        "Un sosie raté de Claude François",
        "La Reine d'Angleterre en jogging",
        "Un expert-comptable un peu fou",
        "Le gars qui présente la météo",
        "Maître Gims sans ses lunettes",
        "Un agent de la sécurité sociale",
        "Le fantôme de Michael Jackson",
        "Un notaire de province",
        "Gérard Depardieu (citoyen russe)",
        "Thomas Pesquet qui flotte dans l'ISS",
        "Le chien de Michel Drucker",
        "Un inspecteur des impôts zélé",
        "Le cousin gênant qu'on n'invite plus",
        "Un influenceur LinkedIn",
        "Greta Thunberg qui fait les gros yeux",
        "Le stagiaire de BFM TV",
        "Un dentiste sadique",
        "Le créateur du Comic Sans MS",
        "Jean-Pierre Foucault",
        "Un chauffeur de taxi parisien aimable",
        "Le Dalaï-lama en colère",
        "Un prof de techno à la retraite",
        "Le Père Fouras",
        "Une miss France qui tombe",
        "Le vigile du supermarché",
        "Elon Musk qui fume un joint",
        "Le patron du kebab du coin",
        "Une star de télé-réalité oubliée",
        "L'inventeur de la clé USB (qu'on met à l'envers)",
        "Un hipster qui boit du café froid",
        "Le maire de Trifouilly-les-Oies",
        "Un joueur de pétanque professionnel",
        "La voix de la SNCF",
        "Un mime Marceau",
        "Le dernier fan de Johnny Hallyday",
        "Un contrôleur de bus en civil",
        "Zinedine Zidane qui met un coup de boule",
        "Le capitaine du Costa Concordia",
        "Un moine tibétain en pleine méditation",
        "La petite souris (celle des dents)",
        "Le Bonhomme Michelin",
        "Ronald McDonald (version effrayante)",
        "Un employé de la Poste très lent",
        "Le type qui écrit les notices Ikea",
        "L'inventeur du fil à couper le beurre",
        "Une intelligence artificielle dépressive",
        "Le Yeti",
        "Un platiste (quelqu'un qui croit que la Terre est plate)",
        "Le type qui a inventé les devoirs de vacances",
        // --- NOUVELLES PROPOSITIONS (HISTOIRE / PRESSE / PERSONNALITÉS) ---
        "La perruque poudrée de Louis XIV",
        "Un formulaire CERFA mal rempli",
        "La musique d'attente de la Sécurité Sociale",
        "L'invention du lave-vaisselle",
        "Un discours de Fidel Castro (de 6 heures)",
        "Le dernier dinosaure vivant",
        "Une réunion de copropriété qui dérape",
        "Le code de la route (édition 1992)",
        "Un soldat de la Garde Républicaine qui a une envie pressante",
        "La recette secrète du pâté Hénaff",
        "Un débat parlementaire dans une salle vide",
        "Le générique de 'Questions pour un Champion'",
        "Une statue de Lénine au fond du jardin",
        "Le premier homme à avoir porté un slip",
        "Une grève des contrôleurs aériens",
        "L'accordéon d'Yvette Horner",
        "La Déclaration des Droits de l'Homme (écrite au crayon gris)",
        "Un philosophe des Lumières qui n'a pas d'idée",
        "La chute du Mur de Berlin (reconstituée en Lego)",
        "Une amphore romaine remplie de vinaigre",
        "Le 13h de Jean-Pierre Pernaut",
        "Un ticket de métro usagé de 1998",
        "L'invention du post-it",
        "Un influenceur qui vend des matelas",
        "Le bruit du modem 56k qui se connecte",
        "Une mise à jour Windows qui dure 4 heures",
        "Le SAV de Darty",
        "Une élection de délégués de classe truquée",
        "Le règlement intérieur de la piscine municipale",
        "Un tuto beauté sur YouTube qui tourne mal",
        "La page 404 d'Internet",
        "Un spam pour hériter d'un prince nigérian",
        "Le menu de la cantine (céleri rémoulade)",
        "Une lettre recommandée avec accusé de réception",
        "L'Eurovision (et ses costumes bizarres)",
        "Un match de curling passionnant",
        "La notice d'un médicament en allemand",
        "Un QR code qui ne mène nulle part",
        "La voix du GPS qui s'énerve",
        "Un PowerPoint de 300 slides",
        "Le bêtisier de fin d'année",
        "Une publicité pour des obsèques low-cost",
        "Le service client d'Amazon",
        "Le Dalaï-Lama en vacances au ski",
        "Un prof d'EPS en survêtement synthétique",
        "Le gars qui joue de la guitare acoustique en soirée",
        "Un expert en assurances maritimes",
        "La Reine des Neiges (en burn-out)",
        "Le monstre du Loch Ness (c'est juste un bout de bois)",
        "Un touriste en chaussettes-sandales",
        "Mark Zuckerberg qui essaie de sourire",
        "Un chat qui joue du piano sur internet",
        "Le doubleur français d'Eddie Murphy",
        "Un mime coincé dans sa boîte invisible",
        "Un arbitre de foot myope",
        "Le cousin qui investit dans la crypto-monnaie",
        "Un végan qui mange du bacon en cachette",
        "L'inventeur du parapluie",
        "Un homme-sandwich",
        "Le présentateur du Téléachat",
        "Un agent immobilier avec les dents trop blanches",
        "Le lapin d'Alice au Pays des Merveilles (en retard)",
        "Un astronaute qui a le vertige",
        "Le jardinier de l'Élysée",
        "Un hacker qui ne sait pas taper au clavier",
        "Le type qui valide les images 'Je ne suis pas un robot'",
        "Un prof de latin désespéré",
        "Le sosie officiel de Johnny Depp (à la fête de la saucisse)",
        "Une influenceuse sans wifi",
        "Le gardien de nuit du musée Grévin",
        "Un ventriloque sans marionnette",
        "La voiture de Google Maps",
        "Le type qui a inventé le mot 'Schtroumpf'",
        "Une conférence de presse qui ne dit rien",
        "Le poisson pané de la cantine",
        "Un expert en Feng Shui",
        "La comptabilité de l'année 2012",
        "Un timbre de collection très rare",
        "L'encyclopédie Universalis (complète)",
        "Le dernier fax du monde"

    ]
};