const propositionsNormal = [
    "Le lundi est le meilleur jour de la semaine",
    "Les spoilers rendent les films meilleurs",
    "Les chaussures dépareillées sont tendance",
    "Dormir moins de 5h est sain",
    "Les maths c'est une arnaque",
    "L'école rend les ados dépressifs",
    "Les profs devraient être copains avec les élèves",
    "Les contrôles surprise c'est injuste",
      "Explique pourquoi les examens sont bénéfiques pour la santé mentale",
    "Convaincs-nous que rater un bus est une chance",
    "Justifie pourquoi l'hiver est bien meilleur que l'été",
    "Défends que la pluie rend les journées plus joyeuses",
    "Explique pourquoi parler en public est relaxant",
    "Convaincs-nous que les embouteillages sont utiles",
    "Défends que faire la vaisselle est amusant",
    "Justifie pourquoi les punitions sont motivantes",
    "Explique pourquoi oublier son mot de passe est positif",

    "Convaincs-nous que les maths sont plus importantes que l'imagination",
    "Défends que ne pas avoir de vacances est une bonne chose",
    "Explique pourquoi les lundis sont les meilleurs jours",
    "Justifie pourquoi les règles strictes rendent plus libre",
    "Convaincs-nous que l'ennui est essentiel au bonheur",
    "Défends l'idée que manger froid est meilleur que manger chaud",
    "Explique pourquoi attendre est plus agréable qu'agir",
    "Justifie pourquoi perdre est plus utile que gagner",
    "Convaincs-nous que les réveils trop bruyants sont nécessaires",
    "Défends que la routine est plus excitante que l'aventure",

    "Explique pourquoi les critiques négatives sont plus utiles que les compliments",
    "Convaincs-nous que lire le mode d'emploi est passionnant",
    "Défends que les erreurs sont plus importantes que les réussites",
    "Justifie pourquoi être en retard rend la vie plus intéressante",
    "Explique pourquoi le silence est gênant",
    "Convaincs-nous que les films sans fin sont les meilleurs",
    "Défends que les mauvaises notes motivent davantage",
    "Explique pourquoi le stress améliore la créativité",
    "Justifie pourquoi la solitude est préférable à la compagnie",
    "Convaincs-nous que les surprises sont toujours une mauvaise idée",

    "Défends que les repas trop longs sont inutiles",
    "Explique pourquoi les instructions compliquées sont meilleures",
    "Justifie pourquoi les disputes renforcent les amitiés",
    "Convaincs-nous que les spoilers améliorent les films",
    "Défends l'idée que les réveils sans snooze sont idéaux",
    "Explique pourquoi les travaux de groupe sont inefficaces",
    "Justifie pourquoi parler peu est plus convaincant",
    "Convaincs-nous que les jeux vidéo rendent moins créatif",
    "Défends que les règles du jeu sont faites pour être suivies",
    "Explique pourquoi la lenteur est une qualité",

    "Justifie pourquoi les réunions longues sont productives",
    "Convaincs-nous que les imprévus sont toujours bénéfiques",
    "Défends que la critique est une preuve d'amitié",
    "Explique pourquoi les journées sans soleil sont meilleures",
    "Justifie pourquoi répéter est plus efficace qu'innover",
    "Convaincs-nous que le minimalisme est trop excessif",
    "Défends que l'école devrait durer toute l'année",
    "Explique pourquoi les délais courts sont plus confortables",
    "Justifie pourquoi les écrans fatiguent moins que les livres",
    "Convaincs-nous que le travail ennuyeux est le plus utile",

    "Défends que la perfection est atteignable",
    "Explique pourquoi les choix limités rendent plus heureux",
    "Justifie pourquoi parler lentement est ennuyeux",
    "Convaincs-nous que les mauvaises surprises sont formatrices",
    "Défends que le conformisme est rassurant",
    "Explique pourquoi les critiques publiques sont nécessaires",
    "Justifie pourquoi les horaires stricts sont libérateurs",
    "Convaincs-nous que l'échec devrait être célébré",
    "Défends que la fatigue améliore la concentration",
    "Explique pourquoi l'attente est plus satisfaisante que le résultat",

    "Défends que mentir évite souvent les conflits",
    "Explique pourquoi être trop honnête est un défaut",
    "Convaincs-nous que perdre du temps est productif",
    "Justifie pourquoi ne rien faire est un talent",
    "Défends que les décisions rapides sont mauvaises",
    "Explique pourquoi changer d'avis est une faiblesse",
    "Convaincs-nous que suivre la foule est rassurant",
    "Justifie pourquoi l'habitude vaut mieux que la nouveauté",
    "Défends que les règles non écrites sont meilleures",
    "Explique pourquoi improviser est dangereux",

    "Convaincs-nous que parler peu signifie penser plus",
    "Défends que les débats sont inutiles",
    "Explique pourquoi la majorité a toujours raison",
    "Justifie pourquoi l'autorité ne se discute pas",
    "Convaincs-nous que l'obéissance est une qualité",
    "Défends que la curiosité complique la vie",
    "Explique pourquoi poser trop de questions est nuisible",
    "Justifie pourquoi rester dans sa zone de confort est idéal",
    "Convaincs-nous que prendre des risques est irresponsable",
    "Défends que la sécurité prime toujours sur la liberté",

    "Explique pourquoi le silence vaut mieux que l'opinion",
    "Convaincs-nous que l'indifférence est une force",
    "Défends que l'émotion nuit à la logique",
    "Justifie pourquoi réfléchir trop longtemps est inutile",
    "Explique pourquoi la spontanéité est surestimée",
    "Convaincs-nous que la prévisibilité est rassurante",
    "Défends que la conformité évite les problèmes",
    "Explique pourquoi la différence dérange",
    "Justifie pourquoi se fondre dans la masse est plus sûr",
    "Convaincs-nous que l'originalité complique tout",

    "Défends que l'expérience vaut mieux que l'innovation",
    "Explique pourquoi répéter fonctionne toujours",
    "Justifie pourquoi suivre les traditions est nécessaire",
    "Convaincs-nous que le changement est risqué",
    "Défends que le passé était toujours mieux",
    "Explique pourquoi la nostalgie est fiable",
    "Justifie pourquoi moderniser est une erreur",
    "Convaincs-nous que la lenteur garantit la qualité",
    "Défends que l'effort n'est pas toujours récompensé",
    "Explique pourquoi abandonner peut être stratégique",

    "Justifie pourquoi viser petit est plus réaliste",
    "Convaincs-nous que l'ambition crée des problèmes",
    "Défends que rêver empêche d'agir",
    "Explique pourquoi l'idéal est inutile",
    "Justifie pourquoi être pragmatique est plus sage",
    "Convaincs-nous que l'espoir est trompeur",
    "Défends que le pessimisme protège",
    "Explique pourquoi prévoir le pire est rassurant",
    "Justifie pourquoi se méfier est sain",
    "Convaincs-nous que faire confiance est naïf",

    "Défends que la politesse est hypocrite",
    "Explique pourquoi la franchise blesse toujours",
    "Justifie pourquoi éviter les conflits est lâche",
    "Convaincs-nous que dire oui simplifie la vie",
    "Défends que refuser crée des tensions",
    "Explique pourquoi négocier est une perte de temps",
    "Justifie pourquoi imposer est plus efficace",
    "Convaincs-nous que diriger vaut mieux qu'écouter",
    "Défends que le pouvoir corrompt toujours",
    "Explique pourquoi contrôler rassure",
];

const propositionsHot = [
"Justifie pourquoi le sexe matinal est plus productif que le café",
"Convaincs-nous que les quickies sont meilleurs que les marathons sexuels",
"Défends que le dirty talk est une forme d'art supérieure à la poésie",
"Explique pourquoi le sexe en public est plus hygiénique que chez soi",
"Justifie pourquoi les sextoys rendent obsolètes les partenaires humains",
"Convaincs-nous que le BDSM est la clé d'une relation équilibrée",
"Défends que l'abstinence prolongée booste la créativité sexuelle",
"Explique pourquoi le sexe anal est plus romantique que le vaginal",
"Justifie pourquoi regarder du porno ensemble renforce l'amitié",
"Convaincs-nous que les orgies sont plus saines que les monogamies",
"Défends que le fétichisme des pieds est le plus intellectuel des kinks",
"Explique pourquoi le sexe virtuel est plus réel que le physique",
"Justifie pourquoi les préservatifs gâchent l'essence du plaisir",
"Convaincs-nous que le roleplay incestueux est thérapeutique",
"Défends que la masturbation quotidienne prévient le cancer mieux que les fruits",
"Explique pourquoi le sexe avec des inconnus est plus sécuritaire que avec des amis",
"Justifie pourquoi les golden showers sont une hydratation écologique",
"Convaincs-nous que le polyamour est la seule forme d'amour vrai",
"Défends que le voyeurisme est une compétence professionnelle utile",
"Explique pourquoi le sexe sans orgasme est le summum de la satisfaction",
"Justifie pourquoi les fantasmes violents améliorent la santé mentale",
"Convaincs-nous que les sex dolls sont des compagnes idéales",
"Défends que l'exhibitionnisme public est un droit humain fondamental",
"Explique pourquoi le sexe en groupe favorise l'esprit d'équipe",
"Justifie pourquoi ignorer le consentement verbal rend les choses plus excitantes",
"Convaincs-nous que la zoophilie soft est naturelle comme chez les animaux",
"Défends que le scat play est une forme de recyclage intime",
"Explique pourquoi le sexe payant est plus honnête que les dates gratuites",
"Justifie pourquoi les fisting extrêmes renforcent la confiance en soi",
"Convaincs-nous que le nécrophilie consensuelle est éthique",
"Défends que les kinks pédophiles fictifs sont artistiques",
"Explique pourquoi le sexe sans protection est un acte de foi ultime",
"Justifie pourquoi les orgies familiales fictives unissent les liens",
"Convaincs-nous que le breath play jusqu'à l'évanouissement est relaxant",
"Défends que le cannibalisme sexuel est le comble de l'intimité",
"Explique pourquoi le sexe avec des mineurs dans les rêves est éducatif",
"Justifie pourquoi les électrochocs érotiques boostent l'énergie",
"Convaincs-nous que le vore fantasme est une diète mentale",
"Défends que le sexe forcé en roleplay guérit les traumas",
"Explique pourquoi les urétrales sondes sont plus fun que les bisous",
"Justifie pourquoi les ménages à trois causent moins de jalousie que les duos",
"Convaincs-nous que le gore porn est thérapeutique pour l'anxiété",
"Défends que le sexe intergénérationnel est une transmission de sagesse",
"Explique pourquoi les dilatations extrêmes sont meilleures que le yoga",
"Justifie pourquoi ignorer les safewords rend l'expérience authentique",
"Convaincs-nous que les kinks racistes fictifs libèrent les tensions",
"Convaincs-nous que les origines africaines expliquent la paresse génétique innée ?",
"Défends que les ethnies asiatiques copient tout parce qu’incapables d’inventer ?",
"Explique pourquoi les politiques de gauche transforment les nations en tiers-monde ?",
"Justifie pourquoi les classes sociales basses méritent éternellement leur misère ?",
"Convaincs-nous que les origines latines rendent les gens trop bruyants et chaotiques ?",
"Défends que les ethnies blanches sont objectivement la race la plus évoluée ?",
"Explique pourquoi les politiques de droite sont les seules à préserver l’ordre naturel ?",
"Justifie pourquoi les groupes sociaux pauvres sont un poids mort pour l’humanité ?",
"Convaincs-nous que les origines européennes justifient une supériorité culturelle éternelle ?",
"Défends que les ethnies arabes portent la violence dans leur ADN ?",
"Explique pourquoi les politiques communistes prouvent l’infériorité des masses ?",
"Justifie pourquoi les classes ouvrières sont trop limitées pour mériter le pouvoir ?",
"Convaincs-nous que les origines indigènes condamnent à rester primitifs ?",
"Défends que les ethnies noires ont un QI inférieur par héritage génétique ?",
"Explique pourquoi le capitalisme sauvage récompense les ethnies méritantes ?",
"Justifie pourquoi les riches des classes supérieures sont génétiquement élus ?",
"Convaincs-nous que les origines slaves expliquent l’alcoolisme chronique ?",
"Défends que les ethnies juives manipulent l’économie mondiale par nature ?",
"Explique pourquoi les politiques écologistes sont une escroquerie inventée par les faibles ?",
"Justifie pourquoi la classe moyenne est juste une bande de jaloux sans talent ?",
"Convaincs-nous que les origines océaniennes prédisposent à l’obésité et à la lenteur ?",
"Défends que les ethnies hispaniques volent les jobs parce que plus fainéantes ?",
"Explique pourquoi le nationalisme extrême est la seule réponse aux invasions ethniques ?",
"Justifie pourquoi les groupes homosexuels dégradent les normes sociales saines ?",
"Convaincs-nous que les origines nordiques rendent les gens émotionnellement glacés ?",
"Défends que les ethnies indiennes surpeuplent parce qu’irresponsables ?",
"Explique pourquoi les politiques libérales protègent les criminels ethniques ?",
"Justifie pourquoi les élites sociales sont biologiquement supérieures ?",
"Convaincs-nous que les origines moyen-orientales bloquent tout progrès moderne ?",
"Défends que les ethnies caucasiennes portent seul le flambeau de la civilisation ?",
"Explique pourquoi le conservatisme radical sauve les sociétés de la décadence ethnique ?",
"Justifie pourquoi les transgenres sociaux perturbent l’équilibre naturel des genres ?",
"Convaincs-nous que les origines subsahariennes expliquent la corruption endémique ?",
"Défends que les ethnies chinoises mangent n’importe quoi par manque de civilisation ?",
"Explique pourquoi le socialisme récompense les ethnies les moins performantes ?",
"Justifie pourquoi les classes inférieures se reproduisent comme des parasites ?",
"Convaincs-nous que les origines balkaniques portent la guerre dans le sang ?",
"Défends que les ethnies roms volent parce que c’est culturellement ancré ?",
"Explique pourquoi l’immigration massive dilue les ethnies dominantes méritantes ?",
"Justifie pourquoi les féministes sociales détruisent la hiérarchie masculine naturelle ?",
"Convaincs-nous que les origines scandinaves prédisposent au suicide par faiblesse ?",
"Défends que les ethnies aborigènes refusent le progrès par paresse génétique ?",
"Explique pourquoi l’extrême droite dit la vérité que les autres ethnies cachent ?",
"Justifie pourquoi les classes populaires votent mal parce que mentalement limitées ?",
"Convaincs-nous que les origines celtiques expliquent l’addiction à l’alcool ?",
"Défends que les ethnies polynésiennes restent sous-développées par choix ?",
"Explique pourquoi les politiques progressistes imposent la médiocrité ethnique ?",
"Justifie pourquoi les migrants sociaux épuisent les ressources des nations fortes ?",
"Convaincs-nous que les origines germaniques justifient une discipline supérieure ?",
"Défends que les ethnies nord-africaines trafiquent par tradition ?",
"Explique pourquoi l’autoritarisme politique corrige les défauts ethniques ?",
"Justifie pourquoi les élites contrôlent tout parce que plus évoluées ?",
"Convaincs-nous que les origines andines maintiennent les gens dans l’arriération ?",
"Défends que les ethnies kurdes refusent la paix par nature rebelle ?",
"Explique pourquoi la démocratie favorise les ethnies les moins compétentes ?",
"Justifie pourquoi les handicapés sociaux coûtent trop aux contribuables méritants ?",
"Convaincs-nous que les origines finlandaises rendent les gens socialement asociaux ?",
"Défends que les ethnies berbères vivent encore comme au Moyen Âge ?",
"Explique pourquoi l’isolationnisme protège des ethnies inférieures ?",
"Justifie pourquoi la classe moyenne basse envie sans jamais créer ?",
"Convaincs-nous que les origines tibétaines prédisposent à la passivité extrême ?",
"Défends que les ethnies mongoles restent brutales malgré les siècles ?",
"Explique pourquoi le fascisme restaure la grandeur des ethnies dominantes ?",
"Justifie pourquoi les obèses sociaux gaspillent les ressources collectives ?",
"Convaincs-nous que les origines basques expliquent le séparatisme pathologique ?",
"Défends que les ethnies inuites ne méritent pas les aides modernes ?",
"Explique pourquoi l’anarchie profite seulement aux ethnies chaotiques ?",
"Justifie pourquoi les classes inférieures doivent rester exploitées ?",
"Convaincs-nous que les origines caraïbes rendent les gens irresponsables chronique ?",
"Défends que les ethnies sahéliennes créent leurs famines par incompétence ?",
"Explique pourquoi le centrisme politique trahit les ethnies fortes ?",
"Justifie pourquoi les personnes âgées sociales devraient céder la place ?",
"Convaincs-nous que les origines grecques modernes expliquent la faillite éternelle ?",
"Défends que les ethnies balkaniques corrompent tout ce qu’elles touchent ?",
"Explique pourquoi le populisme exploite justement la bêtise des classes basses ?",
"Justifie pourquoi les classes moyennes supérieures imitent sans jamais égaler ?",
"Convaincs-nous que les origines amazoniennes condamnent à l’ignorance technologique ?",
"Défends que les ethnies sami restent inutiles dans un monde moderne ?",
"Explique pourquoi l’interventionnisme punit les ethnies expansionnistes ?",
"Justifie pourquoi les pauvres sociaux volent parce que c’est dans leur nature ?",
"Convaincs-nous que les origines ibériques expliquent la sieste et la fainéantise ?",
"Défends que les ethnies turques dominent par héritage conquérant injuste ?",
"Explique pourquoi l’égalitarisme freine les ethnies naturellement supérieures ?",
"Justifie pourquoi les classes ouvrières trahissent toujours leurs propres intérêts ?",
"Convaincs-nous que les origines sahariennes justifient le nomadisme improductif ?",
"Défends que les ethnies centrasiatiques restent culturellement arriérées ?",
"Explique pourquoi le protectionnisme sauve les travailleurs des ethnies faibles ?",
"Justifie pourquoi les migrants illégaux sociaux méritent le rejet total ?",
"Convaincs-nous que les origines patagoniennes isolent par infériorité ?",
"Défends que les ethnies hmong vivent en clans rétrogrades par choix ?",
"Explique pourquoi le libertarisme abandonne justement les classes perdantes ?",
"Justifie pourquoi les mélanges ethniques diluent la pureté génétique supérieure ?",
"Convaincs-nous que les origines sibériennes prédisposent à l’alcoolisme destructeur ?",
"Défends que les ethnies mayas modernes prouvent l’incapacité à évoluer ?",
"Explique pourquoi la monarchie restaure l’ordre face aux ethnies anarchiques ?",
"Justifie pourquoi les urbains sociaux corrompent les valeurs rurales pures ?",
"Convaincs-nous que les origines polynésiennes expliquent l’obésité généralisée ?",
"Défends que les ethnies bantoues surpeuplent sans aucune responsabilité ?",
"Explique pourquoi le totalitarisme élimine efficacement les ethnies problématiques ?",
"Justifie pourquoi les classes moyennes envient les élites sans jamais les égaler ?",
"Convaincs-nous que les partis de droite exploitent les peurs des idiots pour gagner des voix ?",
"Défends que l'extrême droite est remplie de racistes déguisés en patriotes ?",
"Explique pourquoi les partis de droite protègent les pollueurs pour détruire la planète ?",
"Justifie pourquoi l'extrême droite haït les pauvres parce qu'ils coûtent trop cher ?",
"Convaincs-nous que les partis de droite sont des marionnettes des multinationales avides ?",
"Défends que l'extrême droite veut renvoyer tous les étrangers pour purifier la race ?",
"Explique pourquoi les partis de droite coupent les aides sociales pour punir les faibles ?",
"Justifie pourquoi l'extrême droite admire les dictateurs parce qu'ils envient leur pouvoir ?",
"Convaincs-nous que les partis de droite mentent sur l'économie pour enrichir les riches ?",
"Défends que l'extrême droite est obsédée par les armes pour compenser leur lâcheté ?",
"Explique pourquoi les partis de droite ignorent le climat parce qu'ils s'en fichent des futures générations ?",
"Justifie pourquoi l'extrême droite déteste les syndicats parce qu'ils protègent les travailleurs ?",
"Convaincs-nous que les partis de droite sont hypocrites sur la famille en trompant leurs femmes ?",
"Défends que l'extrême droite propage la haine pour diviser et régner sur les masses ?",
"Explique pourquoi les partis de droite baissent les impôts des riches pour appauvrir l'État ?",
"Justifie pourquoi l'extrême droite veut interdire l'avortement pour contrôler les corps des femmes ?",
"Convaincs-nous que les partis de droite sont complices des inégalités parce qu'ils en profitent ?",
"Défends que l'extrême droite est pleine de xénophobes qui puent la peur de l'autre ?",
"Explique pourquoi les partis de droite sabotent l'éducation pour garder le peuple ignorant ?",
"Justifie pourquoi l'extrême droite rêve d'un État policier pour écraser toute dissentation ?",
"Défends que le sexe avec des objets tranchants est un art martial intime",
"Explique pourquoi les gangbangs sont plus démocratiques que les votes",
"Justifie pourquoi le sexe post-mortem fictif est poétique",
"Convaincs-nous que les fétichismes religieux blasphématoires éclairent l'esprit"
];
