const propositionsNormal = [
    "Faut-il interdire les devoirs à la maison ?",
    "Vivre seul ou en colocation ?",
    "Les téléphones portables à l'école : oui ou non ?",
    "Télétravail : pour ou contre ?",
    "Les réseaux sociaux améliorent-ils la vie ?",
    "La technologie simplifie ou complique la vie ?",
    "Est-ce que tout se dit sur les réseaux ?",
    "Faut-il avoir un filtre sur internet ?",
    "La vérité doit-elle toujours être dite ?",
    "Faut-il fermer internet pour les enfants ?",
    "Est-ce que 24h sans écran, c'est possible ?",
    "Les influenceurs sont-ils un danger ?",
    "Faut-il rendre le vote obligatoire ?",
    "Le cannabis devrait-il être légalisé partout ?",
    "Les animaux dans les cirques : oui ou non ?",
    "Faut-il interdire la corrida ?",
    "Le port de l’uniforme à l’école est-il une bonne idée ?",
    "Les notes à l’école sont-elles utiles ?",
    "Faut-il baisser l’âge de la majorité à 16 ans ?",
    "Les jeux vidéo rendent-ils violent ?",
    "Faut-il interdire la fessée éducative ?",
    "Les fast-foods devraient-ils être taxés plus fort ?",
    "Faut-il rendre le service militaire obligatoire ?",
    "Les séries Netflix abrutissent-elles ?",
    "Le végétarisme devrait-il être imposé ?",
    "Les riches doivent-ils payer plus d’impôts ?",
    "Faut-il interdire les voitures en ville ?",
    "Les langues régionales doivent-elles être obligatoires à l’école ?",
    "Le mariage pour tous : une avancée ou une erreur ?",
    "Faut-il autoriser le voile à l’école ?",
    "Les pubs pour le sucre sont-elles responsables de l’obésité ?",
    "Faut-il limiter le nombre d’enfants par famille ?",
    "Les profs devraient-ils être notés par les élèves ?",
    "Le travail le week-end devrait-il être interdit ?",
    "Les selfies sont-ils un problème de société ?",
    "Faut-il interdire TikTok aux mineurs ?",
    "Les vacances scolaires sont-elles trop longues ?",
    "Le bac est-il encore utile ?",
    "Faut-il rendre les études gratuites jusqu’à la licence ?",
    "Les stages non rémunérés devraient être interdits ?",
    "Le sucre est-il une drogue ?",
    "Faut-il autoriser les trottinettes électriques partout ?",
    "Les influenceurs devraient-ils payer plus d’impôts ?",
    "Le féminisme est-il allé trop loin ?",
    "Faut-il interdire les armes aux États-Unis ?",
    "Les migrants enrichissent-ils ou appauvrissent un pays ?",
    "Le travail de nuit devrait-il être interdit ?",
    "Faut-il imposer un revenu universel ?",
    "Les séries coréennes sont-elles meilleures que les américaines ?",
    "Le français est-il en danger ?",
    "Faut-il autoriser l’euthanasie ?",
    "Les réseaux sociaux devraient être régulés par l’État ?",
    "Le téléchargement illégal est-il du vol ?",
    "Faut-il interdire la chirurgie esthétique avant 18 ans ?",
    "Les enfants rois : un problème d’éducation ?",
    "Le sport à l’école devrait être obligatoire tous les jours ?",
    "Les grandes écoles devraient être supprimées ?",
    "Faut-il interdire les paris sportifs ?",
    "Les régimes sont-ils dangereux ?",
    "Le rap est-il de la vraie musique ?",
    "Faut-il autoriser le port d’armes en France ?",
    "Les profils anonymes sur les réseaux sont-ils utiles ?",
    "Le lycée pro est-il moins bien que le général ?",
    "Faut-il interdire la pub pour l’alcool ?",
    "Les influenceurs sont-ils des vrais métiers ?",
    "Le climat : on en fait trop ou pas assez ?",
    "Faut-il rendre le permis de conduire plus dur ?",
    "Les séries de Noël sont-elles toutes nulles ?",
    "Le Nutella devrait être interdit ?",
    "Faut-il imposer la cantine bio à l’école ?",
    "Les vieux devraient-ils repasser le permis tous les 5 ans ?",
    "Le collège unique est-il une bonne idée ?",
    "Faut-il interdire les portables au collège ?",
    "Les profs méritent-ils d’être mieux payés ?",
    "Le lundi de Pentecôte férié ou travaillé ?",
    "Les vacances d’été trop longues ?",
    "Faut-il autoriser les cours en ligne à 100% ?",
    "Les applis de rencontre détruisent-elles l’amour ?",
    "Le français est-il sexiste ?",
    "Faut-il interdire les feux d’artifice ?",
    "Les animaux devraient avoir des droits comme les humains ?",
    "Le téléchargement gratuit tue-t-il la culture ?",
    "Faut-il imposer la semaine de 4 jours ?",
    "Les séries turques sont-elles trop longues ?",
    "Le bac pro est-il un bac au rabais ?",
    "Faut-il interdire les soldes toute l’année ?",
    "Les influenceuses beauté mentent-elles toujours ?",
    "Le gluten est-il vraiment dangereux ?",
    "Faut-il rendre le sport obligatoire à l’université ?",
    "Les livres papier vont-ils disparaître ?",
    "Le harcèlement scolaire est-il pire qu’avant ?",
    "Faut-il autoriser le cannabis thérapeutique partout ?",
    "Les parents hélicoptères font-ils du mal ?",
    "Le brevet des collèges est-il utile ?",
    "Faut-il interdire les notes en primaire ?",
    "Les réseaux sociaux rendent-ils dépressif ?",
    "Le fromage est-il surcoté ?",
    "Faut-il rendre le vélo obligatoire en ville ?",
    "Les séries françaises sont-elles nulles ?",
    "Le bac devrait être plus professionnalisant ?",
    "Faut-il interdire les écrans avant 3 ans ?",
    "Les applis de livraison tuent-elles les restos ?",
    "Le français devrait être la seule langue officielle ?",
    "Faut-il autoriser les chiens dans les magasins ?",
    "Les influenceurs politique sont-ils dangereux ?",
    "Le baccalauréat est-il trop facile ?",
    "Faut-il interdire les devoirs le week-end ?",
    "Les stages devraient être obligatoirement payés ?",
    "Le lycée devrait commencer à 10h ?",
    "Faut-il rendre l’écriture inclusive obligatoire ?",
    "Les séries Netflix abîment-elles le cinéma ?",
    "Le collège devrait être jusqu’à 18 ans ?",
    "Faut-il interdire les commentaires anonymes ?",
    "Les profs devraient avoir le droit de fouiller les sacs ?",
    "Le sucre devrait être vendu sous ordonnance ?",
    "Faut-il autoriser le surf sur les réseaux au boulot ?",
    "Les vacances en famille sont-elles surcotées ?",
    "Le bac pro mérite-t-il plus de respect ?",
    "Faut-il interdire les filtres sur Instagram ?",
    "Les influenceurs voyage sont-ils des menteurs ?",
    "Le lycée à la maison est-il l’avenir ?",
    "Faut-il rendre le code de la route plus sévère ?",
    "Les séries adolescentes sont-elles trop irréalistes ?",
    "Le français est-il la plus belle langue ?",
    "Faut-il interdire les applis de rencontre aux mineurs ?",
    "Les profs devraient gagner autant que les footballeurs ?",
    "Le brevet est-il un examen bidon ?",
    "Faut-il rendre les langues vivantes obligatoires dès la maternelle ?",
    "Les influenceurs fitness vendent-ils du rêve ?",
    "Le bac devrait être remplacé par un contrôle continu total ?",
    "Faut-il interdire les écrans dans les restaurants ?",
    "Les séries policières françaises sont-elles ringardes ?",
    "Le télétravail tue-t-il la productivité ?",
    "Faut-il autoriser le cannabis récréatif en France ?",
    "Les influenceurs sont-ils les nouveaux journalistes ?",
    "Le collège unique a-t-il échoué ?",
    "Faut-il interdire les portables jusqu’à 15 ans ?",
    "Les réseaux sociaux devraient avoir une âge minimum de 16 ans ?",
    "Le bac pro est-il l’avenir ?",
    "Faut-il rendre le sport noté au bac ?",
    "Les séries coréennes ont-elles tué Netflix ?",
    "Le français inclusif est-il illisible ?",
    "Faut-il interdire les commentaires sur YouTube ?",
    "Les influenceurs devraient-ils être considérés comme des publicitaires ?",
    "Le lycée pro mérite-t-il plus de moyens ?",
    "Faut-il rendre l’école obligatoire jusqu’à 18 ans ?",
    "Les séries turques sont-elles une drogue ?",
    "Le bac est-il devenu une loterie ?",
    "Faut-il interdire les influenceurs mineurs ?",
    "Les réseaux sociaux devraient être payants ?",
    "Le collège à 4 jours est-il mieux ?",
    "Faut-il rendre le permis gratuit ?",
    "Les séries Netflix sont-elles toutes les mêmes ?",
    "Le bac pro est-il discriminé ?",
    "Faut-il interdire les écrans avant le coucher ?",
    "Les influenceurs sont-ils responsables de l’anxiété des ados ?",
    "Le français devrait être simplifié ?",
    "Faut-il autoriser les cours particuliers à l’école publique ?",
    "Les séries adolescentes abrutissent-elles ?",
    "Le bac devrait être national ou régional ?",
    "Faut-il interdire les fast-fashion ?",
    "Les influenceurs politique manipulent-ils les jeunes ?",
    "Le collège unique est-il une utopie ?",
    "Faut-il rendre l’uniforme obligatoire partout ?",
    "Les réseaux sociaux tuent-ils la vraie amitié ?",
    "Le bac pro est-il un échec ?",
    "Faut-il interdire les portables en cours ?",
    "Les influenceurs sont-ils des modèles pour les jeunes ?",
    "Le français est-il trop compliqué ?"
];

const propositionsHot = [
    // --- RÉSEAUX SOCIAUX & CRINGE ---
    "Les influenceurs, c'est des putains de handicapés du cerveau ou on les considère comme des travailleurs ?",
    "Poster une photo de son assiette sur Insta, c'est un crime contre l'humanité ou juste une connerie ?",
    "Faut castrer les cons qui se filment en train de danser sur TikTok en public ?",
    "Supprimer LinkedIn : balls de ouf ou suicide professionnel direct ?",
    "Les tarés qui balancent plus de 3 émojis par phrase devraient perdre le droit de vote ?",
    "C'est moral d'ignorer un SDF mais de liker une vidéo de charité à la con ?",
    "Si un influenceur se casse la gueule dans une forêt sans caméra, il existe vraiment ce bâtard ?",
    "Les filtres beauté, faut les interdire pour escroquerie pure et simple ?",
    // --- RELATIONS & ÉGOÏSME ---
    "Baiser l'ex de son pote : trahison de fils de pute ou recyclage écolo ?",
    "Plaquer quelqu'un par SMS parce qu'il pue de la gueule comme un cheval mort, c'est acceptable ?",
    "Le ghosting, c'est la sélection naturelle pour éliminer les faibles à la con ?",
    "Faut facturer le loyer à sa meuf dès la première baise ?",
    "Fouiller le téléphone de son mec/sa nana : espionnage ou juste parano de merde nécessaire ?",
    "Peut-on aimer un mec qui kiffe du Jul sans ironie, cette merde ?",
    "Le mariage, c'est pas juste un syndrome de Stockholm avec papier officiel ?",
    "Demander un test ADN direct à la naissance, c'est insultant ou prudent ?",
    // --- SOCIÉTÉ & STUPIDITÉ ---
    "Les enculés qui balancent leur musique sans écouteurs dans le bus, déportation directe ?",
    "Taxe sur la connerie pour payer la dette, bonne idée ou pas ?",
    "L'astrologie, c'est le racisme des cons qui assument pas leur méchanceté de merde ?",
    "Ceux qui balancent 'je dis ça je dis rien', ils méritent une grosse claque dans la gueule ?",
    "Interdire internet aux vieux de plus de 60 ans pour pas qu'ils se fassent arnaquer comme des bleus ?",
    "Le client est roi ou juste un connard mal élevé ?",
    "Les végétariens qui bouffent du poisson, des hypocrites à la con en manque de fer ?",
    "Les survivalistes, ils crèvent en premier à l'apocalypse pour la blague ?",
    // --- DILEMMES ÉTHIQUES FOIREUX ---
    "Tu buterais ton chat pour 1 million d'euros ? (sois honnête, personne mate)",
    "Vendre un rein pour le dernier iPhone, con ou génie ?",
    "Mentir sur son CV si le boss ment sur l'ambiance de merde au boulot, OK ?",
    "Rire à un enterrement si le cercueil se casse la figure ?",
    "Si tu pouvais rayer un pays de la carte pour le climat, lequel ce serait ?",
    "Dopage obligatoire aux JO pour voir jusqu'où les humains peuvent aller en mode cheat ?",
    "Villes que pour les beaux gosses pour pas crever les yeux des autres ?",
    "Les moches sont plus sympas juste pour survivre à leur gueule de cul ?",
    // --- TRAVAIL & ARGENT ---
    "Ton boss mérite son fric ou c'est un parasite en costard ?",
    "Télétravail : on bosse vraiment ou on glandouille jusqu'à 17h ?",
    "Supprimer le SMIC pour voir qui accepte de bosser pour une merguez ?",
    "Le burn-out, luxe de bourgeois qui ont pas de vraies galères ?",
    "Les stagiaires, esclaves modernes payés en café ?",
    "Journée pour insulter librement les collègues, ça serait cool ?",
    "Argent de poche des gosses taxé aux impôts ?",
    // --- PHYSIQUE & LOOK (LE "ROAST") ---
    "Les mecs en sandales-chaussettes, retrait de nationalité direct ?",
    "Les barbes hipster pour cacher un menton de merde ?",
    "Maquillage de ouf, fraude à la con ?",
    "Ceux qui courent à 6h du mat', sociopathes confirmés ?",
    "Legging seulement avec permis de cul ?",
    "Les chauves plus intelligents ou juste aero pour fuir les emmerdes ?",
    "Lunettes de soleil indoors, respect ou pose de branleur ?",
    // --- ENFANTS & ÉDUCATION ---
    "Les gosses, juste des bestioles chères et chiantes ?",
    "Interdire les bébés dans avions et cinés ?",
    "Parents qui postent leur môme H24, signalement Pharos ?",
    "La fessée, éducation ou défouloir de parents en PLS ?",
    "Échanger le gosse à la naissance s'il ressemble à rien ?",
    "L'école pour apprendre ou baby-sitting gratuit ?",
    // --- RELIGION & CROYANCES (VERSION PIQUANTE) ---
    "Dieu a fait l'homme à son image parce qu'il a un humour pourri ?",
    "L'enfer c'est l'éternité avec les voisins relous ?",
    "Le karma existe ou c'est pour les mous qui osent pas vengeance ?",
    "Jésus revient, ban Insta pour contenu choquant ?",
    // --- QUESTIONS DÉRANGEANTES ---
    "Bouffer son chien mort si t'as la dalle ?",
    "Démocratie une erreur vu les cons élus ?",
    "Vote seulement si QI > température de la pièce ?",
    "Tromper sa meuf pire que delete save jeu ?",
    "Plastique fantastique, mais les fake people recyclables ?",
    "Peine de mort pour spoilers de séries ?",
    "Touristes, vermine de la planète ?",
    "L'humanité mérite d'être sauvée ou on laisse crever ?",
        "Les politiciens sont-ils juste des parasites en costard qui ne serviraient même pas à ramasser tes poubelles ?",
    "Les mecs de gauche qui prônent le partage mais qui vivent dans des apparts à 1 million, on les appelle des hypocrites ou des génies de l'arnaque ?",
    "Les fachos qui pensent que la France était mieux avant, ils regrettent l'époque où on crevait de la peste à 30 ans ?",
    "Les wokes qui s'offusquent pour une virgule, on devrait les envoyer faire un stage de survie en Corée du Nord pour les calmer ?",
    "La démocratie, c'est pas juste donner le pouvoir à une majorité de débiles profonds qui savent pas lire un programme ?",
    "Voter, c'est juste choisir la couleur de la vaseline avant de se faire baiser ?",
    "Si on remplaçait le gouvernement par une IA, on ferait des économies ou on finirait tous en batterie ?",
    "Les anarchistes qui utilisent des iPhones pour tweeter contre le système, c'est le niveau zéro de la dignité ?",
    "Faut-il interdire aux politiciens de parler s'ils n'ont pas un casier judiciaire vierge ?",
    "Les écolos qui mangent de l'avocat importé en avion, ils méritent une balle ou une forêt dans le cul ?",
    "Les centristes, ce sont juste des lâches sans couilles qui attendent de voir qui gagne pour sucer ?",
    "Les complotistes méritent-ils d'être isolés sur une île plate pour voir s'ils tombent au bout ?",
    "Est-ce qu'on devrait tester le QI des candidats à la présidentielle avant de les laisser l'ouvrir ?",
    "Le patriotisme, c'est juste être fier d'être né par hasard à un endroit précis de la planète ?",
    "Les syndicalistes, ils luttent pour les droits ou ils veulent juste des jours de congé pour picoler ?",

    // --- RELIGION (TOUTES LES CROYANCES) ---
    "Si Dieu existe, c'est soit un sadique fini, soit un stagiaire qui a complètement foiré sa mission ?",
    "Les curés qui parlent de chasteté alors qu'ils cachent des dossiers sales, on les brûle ou on les enferme ?",
    "Les musulmans qui mangent pas de porc mais qui mentent et qui volent, le paradis c'est pour les cons ?",
    "Les juifs qui pensent être le peuple élu, c'est pas un peu un complexe de supériorité de merde ?",
    "Les bouddhistes sont-ils juste des gens trop mous pour assumer leur colère ?",
    "Si l'enfer existe, les intégristes de toutes les religions y sont déjà garés en double file ?",
    "Prier pour que ton équipe gagne alors qu'il y a des gosses qui crèvent de faim, c'est pas le summum de l'égoïsme ?",
    "Les religions ne sont-elles que des sectes qui ont réussi à durer trop longtemps ?",
    "Faut-il taxer les églises, les mosquées et les synagogues comme des entreprises de divertissement ?",
    "Si tu crois encore à des bouquins écrits il y a 2000 ans par des mecs qui vivaient dans le désert, t'as un problème psy ?",
    "Les athées qui pensent être supérieurs intellectuellement, vous êtes pas juste des nihilistes chiants ?",
    "Les meufs qui parlent de 'spiritualité' et de 'cristaux', c'est juste qu'elles sont trop connes pour la science ?",
    "Le paradis, c'est pas juste une carotte pour que les pauvres acceptent de rester pauvres sans se plaindre ?",
    "Si Jésus revenait en 2026, il finirait en hôpital psy sous cachetons en 24h ?",

    // --- CLASSES SOCIALES (RICHES & PAUVRES) ---
    "Les riches méritent-ils leur fric ou ils ont juste eu la chatte de naître du bon côté du ventre ?",
    "Les cas sociaux qui font 8 gosses pour toucher les allocs, c'est un business plan de crevard ou une maladie ?",
    "Les bourgeois qui parlent de 'mixité sociale' mais qui mettent leurs gosses au privé, faut-il les tondre ?",
    "Les pauvres sont-ils pauvres parce qu'ils sont cons ou parce que le système est une pute ?",
    "Les héritiers devraient-ils être taxés à 100% pour que tout le monde reparte de zéro ?",
    "Les SDF qui ont des chiens plus gros qu'eux, c'est de l'amour ou de la prise d'otage animale ?",
    "Les cadres sup qui se sentent importants avec leur badge autour du cou, vous savez que vous êtes remplaçables par un script ?",
    "La classe moyenne, c'est juste des gens trop pauvres pour être libres et trop riches pour être aidés ?",
    "Les gens qui s'achètent des fringues de luxe pour faire croire qu'ils ont du fric, vous êtes les plus gros boloss de l'histoire ?",
    "Faut-il interdire aux pauvres d'acheter de la drogue ou de l'alcool tant qu'ils vivent des aides ?",
    "Les millionnaires qui font de l'évasion fiscale devraient-ils perdre leur nationalité direct ?",

    // --- INSTITUTIONS (FLICS, PROFS, MÉDECINS, ETC.) ---
    "Les profs sont-ils juste des gens qui ont eu trop peur du monde du travail pour quitter l'école ?",
    "Les flics, c'est soit des cowboys frustrés, soit des mecs qui ont raté tous leurs autres concours ?",
    "Les médecins nous soignent-ils vraiment ou ils sont juste les dealers légaux des labos ?",
    "Les juges sont-ils déconnectés de la réalité au point de protéger les coupables plus que les victimes ?",
    "L'armée, c'est juste un camp de vacances pour les gens qui aiment obéir sans réfléchir ?",
    "Les banquiers sont-ils les pires criminels de l'humanité, mais en costume cravate ?",
    "Le système de santé français : un fleuron ou un hospice géant qui prend l'eau ?",
    "Les avocats défendent-ils la justice ou juste le mec qui a le plus gros chèque ?",
    "La prison, ça sert à réinsérer ou c'est juste une école supérieure du crime payée par nos impôts ?",
    "Les agents immobiliers sont-ils les êtres les plus méprisables sur cette terre ?",

    // --- RÉSEAUX & SOCIAL (STEROÏDES) ---
    "Les meufs qui font du OnlyFans, c'est de l'empowerment ou juste de la prostitution 2.0 pour flemmardes ?",
    "Les mecs qui vont à la salle juste pour se prendre en photo, vous avez un micro-pénis ou c'est juste dans la tête ?",
    "LinkedIn est-il devenu un asile à ciel ouvert pour managers en manque de reconnaissance ?",
    "Twitter (X) est-il la fosse septique officielle de l'humanité ?",
    "Les gens qui font des vidéos 'micro-trottoir' méritent-ils d'être balancés dans la Seine ?",
    "Faut-il interdire les écrans aux moins de 16 ans sous peine de prison pour les parents ?",
    "Le ghosting devrait-il être puni par la loi comme une agression morale ?",
    "Les gens qui racontent leur vie intime sur les réseaux ont-ils une dignité ou c'est en option ?",

    // --- MORALE & TABOUS ---
    "Le cannibalisme, si c'est pour sauver la planète de la surpopulation, on valide ?",
    "Est-ce qu'on devrait euthanasier les vieux dès qu'ils commencent à coûter trop cher à la société ?",
    "Les moches devraient-ils payer une taxe pour pollution visuelle dans les lieux publics ?",
    "Si tu pouvais tuer Hitler bébé mais que tu devais le manger ensuite, tu le ferais ?",
    "La fidélité, c'est une preuve d'amour ou juste un manque total d'opportunités ?",
    "L'avortement après 18 ans, on appelle ça de la sélection naturelle tardive ?",
    "Les gens qui ne ramassent pas les crottes de leur chien méritent-ils la chaise électrique ?",
    "Le viol masculin est-il moins pris au sérieux parce que les hommes sont 'censés aimer ça' ? (Débat trash)",
    "Faut-il limiter le nombre d'enfants par famille pour sauver le climat ?",
    "Les nains ont-ils des privilèges de discrétion qu'on ignore ?",
    "Les roux sont-ils vraiment les rejetés de Dieu ou juste une erreur de pixel ?",
    "Faut-il tester les drogues sur les prisonniers condamnés à perpétuité plutôt que sur les lapins ?",
    "La peine de mort devrait-elle être rétablie mais en mode 'Jeux du Cirque' à la télé ?",
    "Les trans devraient-ils avoir leur propre catégorie aux JO pour arrêter de niquer le game des femmes ?",
    "Le consentement, c'est devenu une science complexe ou les gens sont juste devenus débiles ?",
    "Les vegans qui forcent leur chat à manger des carottes devraient-ils finir en prison ?",
    "Le suicide est-il l'ultime preuve de liberté ou l'acte de lâcheté suprême ?",
    "Peut-on rire d'un enfant handicapé s'il fait une blague vraiment drôle ?",
    "Les riches polluent plus, faut-il leur couper l'oxygène en priorité ?",
    "Les touristes qui vont dans les pays pauvres pour faire des selfies avec des gosses, des gros crevards ?",
    "Si l'intelligence était contagieuse, la moitié de tes potes seraient immunisés ?",
    "Est-ce que l'inceste entre adultes consentants regarde quelqu'un d'autre qu'eux ?",
    "Les mecs qui font des 'podcasts de mâles alpha', vous essayez de convaincre qui à part vous-mêmes ?",
    "Les femmes qui utilisent leur gosse pour faire des vues sur YouTube, esclavage moderne ?",
    "Est-ce qu'un monde sans religion serait vraiment plus calme ou on se tuerait pour la couleur de nos chaussures ?",
    "Les gens qui disent que 'tous les corps sont beaux', vous mentez pour être gentils ou vous avez pas d'yeux ?",
    "Le porno a-t-il détruit plus de vies que l'héroïne ?",
    "Faut-il interdire de vote les gens qui ne savent pas situer la France sur une carte ?",
    "L'humanité est-elle le cancer de la Terre, et le COVID était-il juste une chimio ratée ?",
    "Les mecs qui portent des jeans skinny, vous avez encore une circulation sanguine ou c'est mort ?",
    "Est-il acceptable de dénoncer son voisin à la police s'il fait un barbecue qui sent trop bon ?",
    "Les gens qui ont des prénoms de villes (Paris, Sidney), vos parents vous détestaient à ce point ?",
    "Est-ce qu'on devrait pouvoir vendre son vote au plus offrant si on s'en fout de la politique ?",
    "Les influenceurs 'fitness' qui tournent aux stéroïdes, escrocs ou modèles de discipline ?",
    "Le concept de 'nation' est-il obsolète ou c'est le seul truc qui nous empêche de nous égorger ?",
    "Est-ce que le monde serait meilleur si on était tous métis et qu'on avait la même gueule ?",
    "Les gosses de riches qui jouent aux racailles, la plus grosse blague du siècle ?",
    "Faut-il autoriser le duel à mort pour régler les embrouilles de voisinage ?",
    "Les gens qui disent 'argent fait pas bonheur', donnez le vôtre et fermez-la ?",
    "La liberté d'expression doit-elle inclure le droit d'être un gros con fini ?",
    "Si tu pouvais doubler ton salaire mais que ton pire ennemi le triplait, tu accepterais ?", // --- POLITIQUE & POUVOIR (VERSION CRUE) ---
    "Les ministres, c'est juste des putes de luxe payées avec tes impôts pour te dire comment fermer ta gueule ?",
    "Le droit de vote, c'est pas juste donner une illusion de pouvoir à des abrutis qui savent même pas lire une fiche de paie ?",
    "La droite, la gauche... au final, c'est juste savoir quelle main va te fouiller le fion pendant que l'autre te fait les poches ?",
    "Les mecs qui se battent pour la politique sur Twitter, vous êtes les plus gros cocus de l'histoire moderne ?",
    "Le patriotisme, c'est juste être fier de la terre où ton père a éjaculé par pur hasard ?",
    "Si on coupait les couilles de tous les politiciens corrompus, on aurait de quoi faire un sacré collier de perles ?",
    "Les mecs de l'extrême droite qui bandent sur Jeanne d'Arc, vous savez qu'elle vous aurait cramés au premier regard ?",
    "Les gauchistes qui pleurent sur le climat mais qui changent d'iPhone tous les ans, on les appelle des merdes ou des déchets ?",
    "La liberté d'expression, c'est devenu le droit pour chaque connard de hurler sa débilité au monde entier ?",

    // --- RELIGIONS & DOGMES (ZÉRO RESPECT) ---
    "Si ton Dieu est si puissant, pourquoi il laisse des curés tripoter des gosses au lieu de les foudroyer sur place, ce lâche ?",
    "Les mecs qui font le Ramadan mais qui insultent des mères toute la journée, vous pensez que Dieu est aussi teubé que vous ?",
    "Les juifs qui pensent que le bacon c'est le mal mais qui braquent les banques du monde, c'est quoi le projet ?",
    "Le paradis, c'est pas juste un club privé pour les cons qui ont eu trop peur de vivre pendant qu'ils étaient sur terre ?",
    "Si Jésus revenait, il se ferait sûrement pifrer par des flics parce qu'il ressemble trop à un migrant ?",
    "Prier, c'est juste parler tout seul comme un schizophrène en espérant qu'un fantôme règle tes problèmes de thunes ?",
    "Les religions, c'est juste des sectes qui ont eu assez de thunes pour se payer des monuments historiques ?",
    "Les bouddhistes qui font genre ils sont zen, c'est juste qu'ils fument trop de weed pour assumer la réalité ?",

    // --- CLASSES SOCIALES & FRIC (ROAST TOTAL) ---
    "Les riches méritent de crever la bouche ouverte dans leurs piscines si leur fric vient de l'exploitation de mômes au Bangladesh ?",
    "Les cas sociaux qui claquent leur RSA dans le tabac et les jeux de grattage, vous êtes la lie de l'humanité ?",
    "Les bourgeois de merde qui font du yoga pour 'se trouver', vous avez juste besoin d'une bonne baffe pour redescendre sur terre ?",
    "L'argent fait pas le bonheur ? C'est une phrase inventée par les riches pour pas que les pauvres viennent leur cramer leur baraque ?",
    "Les héritiers, ces petits fils de pute qui pensent avoir réussi leur vie parce qu'ils sont nés du bon côté du sperme ?",
    "Les pauvres qui votent pour des millionnaires, vous avez le syndrome de Stockholm ou vous êtes juste finis à la pisse ?",
    "La classe moyenne, ces esclaves qui s'achètent des bagnoles à crédit pour faire rager des voisins qu'ils détestent ?",
    "Les SDF qui s'achètent de la 8.6 avant de nourrir leur chien, on en parle de votre sens des priorités ?",

    // --- SEXE & RELATIONS (TRASH) ---
    "OnlyFans, c'est pas juste le catalogue officiel des meufs qui ont trop la flemme de taffer ?",
    "Les mecs qui paient pour voir des nudes, vous êtes les déchets ultimes de la pyramide sociale ?",
    "Le couple, c'est juste deux personnes qui se supportent pour pas crever de solitude devant Netflix ?",
    "La fidélité, c'est pour les gens qui n'ont pas assez de charisme pour baiser ailleurs ?",
    "Le porno a plus éduqué les jeunes que l'Éducation Nationale, c'est ça la vraie tristesse ?",
    "Si ta meuf t'envoie un 'on doit parler', c'est que ton remplaçant est déjà en train de s'échauffer ?",
    "Les mecs qui ont besoin de payer des escortes, vous êtes des losers ou juste des mecs qui ont compris que l'amour coûte plus cher ?",
    "La friendzone, c'est juste le purgatoire pour les mecs trop lâches pour dire qu'ils veulent juste baiser ?",

    // --- INSTITUTIONS & MÉTIERS (LES ENFOIRÉS) ---
    "Les flics qui se sentent pousser des couilles avec un flingue mais qui bégayent dès qu'ils retirent l'uniforme ?",
    "Les profs, ces ratés du système qui se vengent sur des gosses parce qu'ils ont pas eu la carrière qu'ils voulaient ?",
    "Les médecins qui te filent des médocs de merde juste pour toucher leur chèque des labos, c'est des dealers avec un diplôme ?",
    "Les avocats, ces vautours qui s'engraissent sur la misère humaine et qui dorment comme des bébés ?",
    "L'armée, c'est juste un centre de tri pour les mecs trop cons pour penser par eux-mêmes ?",
    "Les influenceurs fitness qui sont chargés aux stéroïdes jusqu'aux oreilles, vous vendez du rêve ou du cancer ?",

    // --- SOCIÉTÉ & HUMAIN (DÉGOÛT) ---
    "L'humanité est une MST géante pour la planète, et on est en train de crever de notre propre connerie ?",
    "Les gens qui font des gosses alors qu'ils savent pas gérer leur propre vie, c'est de la maltraitance préventive ?",
    "Faut-il stériliser les abrutis qui font des challenges dangereux sur TikTok pour nettoyer le pool génétique ?",
    "Les végétaliens qui nous cassent les couilles, vous savez que vos salades sont arrosées au sang de rongeurs broyés par les tracteurs ?",
    "L'euthanasie devrait être obligatoire pour les gens qui n'ont aucune utilité sociale après 80 ans ?",
    "Les réseaux sociaux, c'est juste une immense fosse septique où tout le monde vient chier sa haine anonymement ?",
    "Les mecs qui font de la musculation pour compenser un manque de personnalité, vous faites pitié ou de la peine ?",
    "Est-ce que le monde serait pas plus propre si on balançait une petite bombe nucléaire sur chaque capitale ?",
    "La liberté, c'est juste avoir le choix de la marque de ta laisse ?",

    // --- QUESTIONS TABOUES ---
    "Peut-on rire du handicap si la personne est un énorme connard fini ?",
    "Si tu pouvais sauver ton chien ou un inconnu d'un incendie, tu choisirais le chien parce que l'humain est une merde ?",
    "L'inceste, c'est juste une affaire de famille ou c'est vraiment dégueulasse si tout le monde est d'accord ?",
    "Les trans qui exigent qu'on les appelle par des pronoms inventés, vous voulez de l'attention ou un psy ?",
    "Les gros qui se plaignent de la grossophobie mais qui lâchent pas leur McDo, vous voulez un mouchoir ou un régime ?",
    "Les meufs qui sortent qu'avec des bad boys et qui chialent quand elles se font frapper, c'est de la sélection naturelle ?",
    "Faut-il instaurer une taxe sur les gens moches pour financer la chirurgie des autres ?",
    "Le suicide, c'est l'ultime doigt d'honneur à un monde de merde ?",
    "Si on pouvait vendre son gosse légalement, y'aurait moins d'abandons dans les poubelles ?",
    "Les blancs qui s'excusent d'être blancs, vous êtes les plus gros fragiles du millénaire ?",
    "Les noirs qui accusent le racisme dès qu'ils ratent un truc, c'est une excuse de merde ou une réalité ?",
    "Les asiatiques qui mangent tout ce qui bouge, vous préparez la prochaine pandémie mondiale ?",
    "Les féministes aux cheveux bleus qui détestent les hommes, vous avez juste besoin d'un bon coup de bite ou d'un père ?",
    "Les mecs qui pleurent en public, c'est des tapettes ou juste des gens qui ont abandonné l'idée d'avoir des couilles ?",
    "Est-ce que la mort est la seule chose équitable dans ce monde de fils de pute ?",
    "Vivre vieux, c'est juste regarder son corps pourrir en attendant que tes gosses héritent de ta thune ?",
    "Les gens qui ont des chiens à la place des gosses, vous êtes des psychopathes en manque d'affection ?"

];