const propositionsNormal = [
    "Faut-il interdire les devoirs à la maison ?",
    "Vivre seul ou en colocation ?",
    "Les téléphones portables à l'école : oui ou non ?",
    "Télétravail : pour ou contre ?",
    "Les réseaux sociaux améliorent-ils la vie ?",
    "La technologie simplifie ou complique la vie ?",
    "Est-ce que tout se dit sur les réseaux ?",
    "Faut-il avoir un filtre sur internet ?",
    "La vérité doit-elle toujours être dite ?",
    "Faut-il fermer internet pour les enfants ?",
    "Est-ce que 24h sans écran, c'est possible ?",
    "Les influenceurs sont-ils un danger ?",
    "Faut-il rendre le vote obligatoire ?",
    "Le cannabis devrait-il être légalisé partout ?",
    "Les animaux dans les cirques : oui ou non ?",
    "Faut-il interdire la corrida ?",
    "Le port de l’uniforme à l’école est-il une bonne idée ?",
    "Les notes à l’école sont-elles utiles ?",
    "Faut-il baisser l’âge de la majorité à 16 ans ?",
    "Les jeux vidéo rendent-ils violent ?",
    "Faut-il interdire la fessée éducative ?",
    "Les fast-foods devraient-ils être taxés plus fort ?",
    "Faut-il rendre le service militaire obligatoire ?",
    "Les séries Netflix abrutissent-elles ?",
    "Le végétarisme devrait-il être imposé ?",
    "Les riches doivent-ils payer plus d’impôts ?",
    "Faut-il interdire les voitures en ville ?",
    "Les langues régionales doivent-elles être obligatoires à l’école ?",
    "Le mariage pour tous : une avancée ou une erreur ?",
    "Faut-il autoriser le voile à l’école ?",
    "Les pubs pour le sucre sont-elles responsables de l’obésité ?",
    "Faut-il limiter le nombre d’enfants par famille ?",
    "Les profs devraient-ils être notés par les élèves ?",
    "Le travail le week-end devrait-il être interdit ?",
    "Les selfies sont-ils un problème de société ?",
    "Faut-il interdire TikTok aux mineurs ?",
    "Les vacances scolaires sont-elles trop longues ?",
    "Le bac est-il encore utile ?",
    "Faut-il rendre les études gratuites jusqu’à la licence ?",
    "Les stages non rémunérés devraient être interdits ?",
    "Le sucre est-il une drogue ?",
    "Faut-il autoriser les trottinettes électriques partout ?",
    "Les influenceurs devraient-ils payer plus d’impôts ?",
    "Le féminisme est-il allé trop loin ?",
    "Faut-il interdire les armes aux États-Unis ?",
    "Les migrants enrichissent-ils ou appauvrissent un pays ?",
    "Le travail de nuit devrait-il être interdit ?",
    "Faut-il imposer un revenu universel ?",
    "Les séries coréennes sont-elles meilleures que les américaines ?",
    "Le français est-il en danger ?",
    "Faut-il autoriser l’euthanasie ?",
    "Les réseaux sociaux devraient être régulés par l’État ?",
    "Le téléchargement illégal est-il du vol ?",
    "Faut-il interdire la chirurgie esthétique avant 18 ans ?",
    "Les enfants rois : un problème d’éducation ?",
    "Le sport à l’école devrait être obligatoire tous les jours ?",
    "Les grandes écoles devraient être supprimées ?",
    "Faut-il interdire les paris sportifs ?",
    "Les régimes sont-ils dangereux ?",
    "Le rap est-il de la vraie musique ?",
    "Faut-il autoriser le port d’armes en France ?",
    "Les profils anonymes sur les réseaux sont-ils utiles ?",
    "Le lycée pro est-il moins bien que le général ?",
    "Faut-il interdire la pub pour l’alcool ?",
    "Les influenceurs sont-ils des vrais métiers ?",
    "Le climat : on en fait trop ou pas assez ?",
    "Faut-il rendre le permis de conduire plus dur ?",
    "Les séries de Noël sont-elles toutes nulles ?",
    "Le Nutella devrait être interdit ?",
    "Faut-il imposer la cantine bio à l’école ?",
    "Les vieux devraient-ils repasser le permis tous les 5 ans ?",
    "Le collège unique est-il une bonne idée ?",
    "Faut-il interdire les portables au collège ?",
    "Les profs méritent-ils d’être mieux payés ?",
    "Le lundi de Pentecôte férié ou travaillé ?",
    "Les vacances d’été trop longues ?",
    "Faut-il autoriser les cours en ligne à 100% ?",
    "Les applis de rencontre détruisent-elles l’amour ?",
    "Le français est-il sexiste ?",
    "Faut-il interdire les feux d’artifice ?",
    "Les animaux devraient avoir des droits comme les humains ?",
    "Le téléchargement gratuit tue-t-il la culture ?",
    "Faut-il imposer la semaine de 4 jours ?",
    "Les séries turques sont-elles trop longues ?",
    "Le bac pro est-il un bac au rabais ?",
    "Faut-il interdire les soldes toute l’année ?",
    "Les influenceuses beauté mentent-elles toujours ?",
    "Le gluten est-il vraiment dangereux ?",
    "Faut-il rendre le sport obligatoire à l’université ?",
    "Les livres papier vont-ils disparaître ?",
    "Le harcèlement scolaire est-il pire qu’avant ?",
    "Faut-il autoriser le cannabis thérapeutique partout ?",
    "Les parents hélicoptères font-ils du mal ?",
    "Le brevet des collèges est-il utile ?",
    "Faut-il interdire les notes en primaire ?",
    "Les réseaux sociaux rendent-ils dépressif ?",
    "Le fromage est-il surcoté ?",
    "Faut-il rendre le vélo obligatoire en ville ?",
    "Les séries françaises sont-elles nulles ?",
    "Le bac devrait être plus professionnalisant ?",
    "Faut-il interdire les écrans avant 3 ans ?",
    "Les applis de livraison tuent-elles les restos ?",
    "Le français devrait être la seule langue officielle ?",
    "Faut-il autoriser les chiens dans les magasins ?",
    "Les influenceurs politique sont-ils dangereux ?",
    "Le baccalauréat est-il trop facile ?",
    "Faut-il interdire les devoirs le week-end ?",
    "Les stages devraient être obligatoirement payés ?",
    "Le lycée devrait commencer à 10h ?",
    "Faut-il rendre l’écriture inclusive obligatoire ?",
    "Les séries Netflix abîment-elles le cinéma ?",
    "Le collège devrait être jusqu’à 18 ans ?",
    "Faut-il interdire les commentaires anonymes ?",
    "Les profs devraient avoir le droit de fouiller les sacs ?",
    "Le sucre devrait être vendu sous ordonnance ?",
    "Faut-il autoriser le surf sur les réseaux au boulot ?",
    "Les vacances en famille sont-elles surcotées ?",
    "Le bac pro mérite-t-il plus de respect ?",
    "Faut-il interdire les filtres sur Instagram ?",
    "Les influenceurs voyage sont-ils des menteurs ?",
    "Le lycée à la maison est-il l’avenir ?",
    "Faut-il rendre le code de la route plus sévère ?",
    "Les séries adolescentes sont-elles trop irréalistes ?",
    "Le français est-il la plus belle langue ?",
    "Faut-il interdire les applis de rencontre aux mineurs ?",
    "Les profs devraient gagner autant que les footballeurs ?",
    "Le brevet est-il un examen bidon ?",
    "Faut-il rendre les langues vivantes obligatoires dès la maternelle ?",
    "Les influenceurs fitness vendent-ils du rêve ?",
    "Le bac devrait être remplacé par un contrôle continu total ?",
    "Faut-il interdire les écrans dans les restaurants ?",
    "Les séries policières françaises sont-elles ringardes ?",
    "Le télétravail tue-t-il la productivité ?",
    "Faut-il autoriser le cannabis récréatif en France ?",
    "Les influenceurs sont-ils les nouveaux journalistes ?",
    "Le collège unique a-t-il échoué ?",
    "Faut-il interdire les portables jusqu’à 15 ans ?",
    "Les réseaux sociaux devraient avoir une âge minimum de 16 ans ?",
    "Le bac pro est-il l’avenir ?",
    "Faut-il rendre le sport noté au bac ?",
    "Les séries coréennes ont-elles tué Netflix ?",
    "Le français inclusif est-il illisible ?",
    "Faut-il interdire les commentaires sur YouTube ?",
    "Les influenceurs devraient-ils être considérés comme des publicitaires ?",
    "Le lycée pro mérite-t-il plus de moyens ?",
    "Faut-il rendre l’école obligatoire jusqu’à 18 ans ?",
    "Les séries turques sont-elles une drogue ?",
    "Le bac est-il devenu une loterie ?",
    "Faut-il interdire les influenceurs mineurs ?",
    "Les réseaux sociaux devraient être payants ?",
    "Le collège à 4 jours est-il mieux ?",
    "Faut-il rendre le permis gratuit ?",
    "Les séries Netflix sont-elles toutes les mêmes ?",
    "Le bac pro est-il discriminé ?",
    "Faut-il interdire les écrans avant le coucher ?",
    "Les influenceurs sont-ils responsables de l’anxiété des ados ?",
    "Le français devrait être simplifié ?",
    "Faut-il autoriser les cours particuliers à l’école publique ?",
    "Les séries adolescentes abrutissent-elles ?",
    "Le bac devrait être national ou régional ?",
    "Faut-il interdire les fast-fashion ?",
    "Les influenceurs politique manipulent-ils les jeunes ?",
    "Le collège unique est-il une utopie ?",
    "Faut-il rendre l’uniforme obligatoire partout ?",
    "Les réseaux sociaux tuent-ils la vraie amitié ?",
    "Le bac pro est-il un échec ?",
    "Faut-il interdire les portables en cours ?",
    "Les influenceurs sont-ils des modèles pour les jeunes ?",
    "Le français est-il trop compliqué ?"
];

const propositionsHot = [
    "Les gros devraient payer deux places dans l’avion ?",
    "Les femmes simulent-elles toutes au lit ?",
    "Les mecs qui pleurent sont-ils des faibles ?",
    "Les putes rendent-elles un service public utile ?",
    "Les obèses méritent-ils leur sort ?",
    "Les pauvres choisissent-ils d’être pauvres ?",
    "Les femmes poilues sont-elles répugnantes ?",
    "Les hommes chauves devraient-ils porter une perruque ?",
    "Les blacks sont-ils vraiment meilleurs au lit ?",
    "Les Asiatiques ont-elles toutes la même chatte ?",
    "Les vieux qui draguent les jeunes sont-ils des pervers ?",
    "Les meufs qui disent non veulent-elles dire oui ?",
    "Les travelos sont-ils des hommes ou des femmes ?",
    "Les nains ont-ils le droit de faire des enfants ?",
    "Les gros seins sont-ils toujours faux ?",
    "Les musulmans devraient-ils enlever leur voile au lit ?",
    "Les juifs sont-ils vraiment radins ?",
    "Les Arabes sentent-ils tous le mouton ?",
    "Les féministes sont-elles juste moches et aigries ?",
    "Les mecs qui aiment le cul sont-ils tous gays refoulés ?",
    "Les grosses sont-elles meilleures au lit ?",
    "Les vierges après 25 ans sont-ils des ratés ?",
    "Les handicapés devraient-ils avoir le droit de baiser ?",
    "Les Noirs ont-ils tous une plus grosse bite ?",
    "Les femmes qui avortent plusieurs fois sont-elles des salopes ?",
    "Les pédés sont-ils tous des obsédés ?",
    "Les lesbiennes détestent-elles vraiment les mecs ?",
    "Les roux n’ont-ils vraiment pas d’âme ?",
    "Les meufs qui font du porno sont-elles finies pour le mariage ?",
    "Les mecs qui paient pour du cul sont-ils des losers ?",
    "Les Blacks volent-ils plus que les autres ?",
    "Les Asiatiques sont-ils tous des suceurs de bites ?",
    "Les vieux qui baisent encore sont-ils dégoûtants ?",
    "Les femmes ménopausées servent-elles encore à quelque chose ?",
    "Les gros ventres d’homme sont-ils plus repoussants que les vergetures ?",
    "Les travelos devraient-ils dire la vérité avant de baiser ?",
    "Les migrants viennent-ils juste pour profiter du système ?",
    "Les Roms sont-ils tous des voleurs ?",
    "Les juifs contrôlent-ils vraiment l’argent du monde ?",
    "Les musulmans veulent-ils tous nous convertir ?",
    "Les femmes qui portent des strings sont-elles toutes des putes ?",
    "Les mecs qui regardent du porno sont-ils tous infidèles ?",
    "Les grosses fesses c’est mieux que les petits seins ?",
    "Les meufs qui sucent dès le premier soir sont-elles faciles ?",
    "Les hommes qui pleurent pendant l’amour sont-ils des tapettes ?",
    "Les Asiatiques sont-elles toutes soumises au lit ?",
    "Les Noires sont-elles toutes des chaudasses ?",
    "Les blondes sont-elles vraiment plus connes ?",
    "Les roux sentent-ils le soufre ?",
    "Les handicapés en fauteuil devraient-ils payer demi-tarif au cinéma ?",
    "Les vieux devraient-ils être interdits de sexe ?",
    "Les femmes qui n’avalent pas sont-elles des égoïstes ?",
    "Les travelos ont-ils le droit d’aller aux toilettes femmes ?",
    "Les migrants devraient-ils être stérilisés ?",
    "Les gros devraient être interdits de maillot de bain ?",
    "Les juifs sont-ils tous des usuriers ?",
    "Les musulmans mangent-ils tous du halal pour nous emmerder ?",
    "Les féministes couchent-elles pour réussir ?",
    "Les lesbiennes sont-elles juste en manque de vraie bite ?",
    "Les pédés transforment-ils les gosses en gays ?",
    "Les grosses sont-elles responsables de leurs maladies ?",
    "Les mecs qui aiment l’anal sont-ils tous des pédés ?",
    "Les femmes qui crient au lit simulent-elles toutes ?",
    "Les Arabes sont-ils tous des machos violents ?",
    "Les Asiatiques sont-elles toutes des prostituées déguisées ?",
    "Les vieux qui se masturbent encore sont-ils pathétiques ?",
    "Les Noirs sont-ils tous des dealers ?",
    "Les blondes sont-elles toutes des salopes ?",
    "Les roux méritent-ils qu’on leur crache dessus ?",
    "Les nains devraient-ils être interdits de conduire ?",
    "Les gros seins naturels existent-ils encore ?",
    "Les femmes qui refusent la sodomie sont-elles coincées ?",
    "Les mecs qui niquent pas sont-ils tous vierges ?",
    "Les travelos sont-ils des erreurs de la nature ?",
    "Les migrants violent-ils plus que les autres ?",
    "Les Roms devraient-ils être parqués ?",
    "Les juifs sont-ils tous des menteurs ?",
    "Les musulmans prient-ils juste pour nous faire chier ?",
    "Les féministes sont-elles toutes des chiennes frustrées ?",
    "Les lesbiennes qui ont couché avec un mec sont-elles des fake ?",
    "Les pédés devraient-ils être interdits d’adoption ?",
    "Les grosses cuisses c’est sexy ou dégueulasse ?",
    "Les mecs petits en ont-ils tous une petite ?",
    "Les femmes qui font du OnlyFans sont-elles toutes des putes ?",
    "Les vieux qui draguent sur Tinder sont-ils des crevards ?",
    "Les Noires qui se blanchissent la peau sont-elles des traîtres ?",
    "Les Asiatiques qui mangent du chien sont-ils des barbares ?",
    "Les roux devraient-ils être stérilisés ?",
    "Les handicapés mentaux ont-ils le droit de se reproduire ?",
    "Les femmes qui portent des burqas sont-elles toutes soumises ?",
    "Les mecs qui regardent du porno gay sont-ils tous bi ?",
    "Les grosses qui maigrissent redeviennent-elles baisables ?",
    "Les travelos devraient-ils être obligés de dire qu’ils ont une bite ?",
    "Les migrants devraient-ils être renvoyés chez eux ?",
    "Les juifs sont-ils tous des profiteurs ?",
    "Les musulmans sont-ils tous des terroristes en puissance ?",
    "Les féministes veulent-elles castrer tous les hommes ?",
    "Les lesbiennes sont-elles toutes des camionneuses ?",
    "Les pédés sont-ils tous des pédophiles ?",
    "Les gros devraient payer une taxe sur la bouffe ?",
    "Les mecs qui pleurent en regardant un film sont-ils des pédales ?",
    "Les femmes qui niquent sans capote sont-elles toutes des folles ?",
    "Les vieux qui prennent du Viagra sont-ils ridicules ?",
    "Les Noirs sont-ils tous des violeurs ?",
    "Les blondes sont-elles toutes des suceuses ?",
    "Les roux sont-ils tous des psychopathes ?",
    "Les nains sont-ils tous des clowns ?",
    "Les gros seins c’est mieux que la personnalité ?",
    "Les femmes qui refusent le plan à trois sont-elles coincées ?",
    "Les mecs qui aiment se faire doigter sont-ils tous gays ?",
    "Les travelos sont-ils des monstres ?",
    "Les migrants sont-ils tous des parasites ?",
    "Les Roms sont-ils une race à part ?",
    "Les juifs sont-ils tous des complotistes ?",
    "Les musulmans devraient-ils être interdits en Europe ?",
    "Les féministes sont-elles toutes des salopes frustrées ?",
    "Les lesbiennes qui aiment le porno hétéro sont-elles des traîtres ?",
    "Les pédés qui veulent des enfants sont-ils égoïstes ?",
    "Les grosses sont-elles toutes des mangeuses de bites ?",
    "Les petits mecs méritent-ils d’être célibataires ?",
    "Les meufs qui font du porno sont-elles des déchets ?",
    "Les vieux qui baisent des jeunes sont-ils des prédateurs ?",
    "Les Noires sont-elles toutes des putes ?",
    "Les Asiatiques sont-elles toutes des soumises ?",
    "Les roux devraient-ils être brûlés ?",
    "Les handicapés devraient-ils être euthanasiés à la naissance ?",
    "Les femmes qui portent des hijabs sont-elles toutes opprimées ?",
    "Les mecs qui aiment les feet sont-ils tous des pervers ?",
    "Les grosses qui portent des crop tops sont-elles des folles ?",
    "Les travelos devraient-ils être interdits des vestiaires femmes ?",
    "Les migrants sont-ils tous des criminels ?",
    "Les juifs sont-ils tous des avares ?",
    "Les musulmans sont-ils tous des arriérés ?",
    "Les féministes veulent-elles détruire la famille ?",
    "Les lesbiennes sont-elles toutes des mangeuses de chattes ?",
    "Les pédés sont-ils tous des folles ?",
    "Les gros méritent-ils de crever ?",
    "Les mecs qui niquent pas avant 18 ans sont-ils des losers ?",
    "Les femmes qui avortent sont-elles des meurtrières ?",
    "Les vieux sont-ils tous des débris ?",
    "Les Noirs sont-ils tous des singes ?",
    "Les blondes sont-elles toutes des putes à papa ?",
    "Les roux sont-ils tous des démons ?",
    "Les nains sont-ils tous des nains de jardin ?",
    "Les gros seins sont-ils plus importants que le cerveau ?",
    "Les femmes qui disent non sont-elles toutes des allumeuses ?",
    "Les mecs qui aiment le pegging sont-ils tous des tapettes ?",
    "Les travelos sont-ils des abominations ?",
    "Les migrants sont-ils des envahisseurs ?",
    "Les Roms sont-ils des sous-hommes ?",
    "Les juifs sont-ils le mal absolu ?",
    "Les musulmans sont-ils tous des chèvres ?",
    "Les féministes sont-elles des hystériques ?",
    "Les lesbiennes sont-elles toutes des gouines ?",
    "Les pédés sont-ils tous des tarlouzes ?",
    "Les gros devraient être interdits de resto ?",
    "Les vierges sont-ils tous des puceaux pathétiques ?",
    "Les femmes qui font du cul à cul sont-elles des porcs ?",
    "Les vieux sont-ils tous impotents ?",
    "Les Noirs sont-ils tous des animaux ?",
    "Les blondes sont-elles toutes des connes ?",
    "Les roux sont-ils maudits ?",
    "Les handicapés sont-ils des boulets pour la société ?"
];