const words = [
    "Qui est le plus mauvais perdant de ce groupe ?",
    "Qui est le moins ponctuel d'entre nous en soirée ?",
    "Qui a le plus de tissus de chemise à fleurs dans sa garde-robe ?",
    "Qui a le moins de chance d'avoir une panne de voiture ce mois-ci ?",
    "Qui est le plus à fond sur les théories du complot ?",
    "Qui est le moins doué en orthographe ?",
    "Qui a le plus de secrets inavouables sur son ex ?",
    "Qui a le moins de courage pour sauter à l'élastique ?",
    "Qui est le plus susceptible de finir la soirée en dansant sur une table ?",
    "Qui est le moins susceptible de répondre à un message avant 24 heures ?",
    "Qui est le plus susceptible de se souvenir du nom de tous les enfants de nos amis ?",
    "Qui est le moins susceptible de payer sa tournée spontanément ?",
    "Qui est le plus à même de monter un meuble IKEA sans regarder la notice ?",
    "Qui est le moins à même de cuisiner autre chose que des pâtes ?",
    "Qui est le plus à même de convaincre un policier d'éviter une amende ?",
    "Qui est le moins à même de rester silencieux pendant 10 minutes ?",
    "Qui est le plus casanier d'entre nous ?",
    "Qui est le moins stressé à l'approche des examens ?",
    "Qui a le plus de chaussettes dépareillées chez lui ?",
    "Qui a le moins de batterie sur son téléphone en permanence ?",
    "Qui est le plus susceptible de se marier dans 5 ans ?",
    "Qui est le moins susceptible de se faire tatouer un jour ?",
    "Qui est le plus à même de dormir pendant un film d'horreur ?",
    "Qui est le moins à même de mentir sans rougir ?",
    "Qui est le plus dramatique pour une petite coupure au doigt ?",
    "Qui est le moins adroit avec un outil ?",
    "Qui a le plus de photos de chats dans sa galerie ?",
    "Qui a le moins de plantes d'intérieur qui survivent ?",
    "Qui est le plus susceptible de commander le plat le plus cher au restaurant ?",
    "Qui est le moins susceptible de finir un jeu vidéo à 100% ?",
    "Qui est le plus à même de courir un semi-marathon sur un coup de tête ?",
    "Qui est le moins à même de résoudre un problème technique basique ?",
    "Qui est le plus accro à la caféine ?",
    "Qui est le moins à l'aise dans une foule ?",
    "Qui a le plus de paires de baskets différentes ?",
    "Qui a le moins de talent pour la danse ?",
    "Qui est le plus susceptible de crier devant une souris ?",
    "Qui est le moins susceptible de voyager sans sa valise préférée ?",
    "Qui est le plus à même de tenir une soirée jusqu'à l'aube ?",
    "Qui est le moins à même de faire un compliment sincère à un inconnu ?",
    "Qui est le plus fort pour imiter les accents étrangers ?",
    "Qui est le moins courageux pour parler à son crush ?",
    "Qui a le plus de dettes de jeux ?",
    "Qui a le moins de journées de repos cumulées ?",
    "Qui est le plus susceptible de se tromper de prénom en présentant quelqu'un ?",
    "Qui est le moins susceptible de couper la parole en pleine discussion ?",
    "Qui est le plus à même de défendre bec et ongles une opinion absurde ?",
    "Qui est le moins à même de rester concentré pendant un documentaire ennuyeux ?",
    "Qui est le plus maniaque sur la propreté de son appartement ?",
    "Qui est le moins passionné par l'histoire ?",
    "Qui a le plus de taches de vin sur ses vêtements ?",
    "Qui a le moins de compétences en montage vidéo ?",
    "Qui est le plus susceptible de signer pour un club de sport sans y aller ?",
    "Qui est le moins susceptible de sortir de chez lui sans son portefeuille ?",
    "Qui est le plus à même de faire un bon karaoké en état d'ébriété ?",
    "Qui est le moins à même de répondre à une question de culture générale simple ?",
    "Qui est le plus optimiste de nature ?",
    "Qui est le moins gourmand d'entre nous ?",
    "Qui a le plus de râteaux en amour ?",
    "Qui a le moins de peur du vide ?",
    "Qui est le plus susceptible de créer une petite entreprise un jour ?",
    "Qui est le moins susceptible de lancer un défi idiot au reste du groupe ?",
    "Qui est le plus à même de devenir accro à une nouvelle série télé ?",
    "Qui est le moins à même de se lever avant 8h le week-end ?",
    "Qui est le plus douillet quand il est malade ?",
    "Qui est le moins sérieux en réunion de famille ?",
    "Qui a le plus de photos de vacances ratées ?",
    "Qui a le moins de patience dans la file d'attente ?",
    "Qui est le plus susceptible de perdre ses clés de maison ?",
    "Qui est le moins susceptible de dire la vérité sur son âge ?",
    "Qui est le plus à même de faire un geste embarrassant en public ?",
    "Qui est le moins à même de se plaindre du temps qu'il fait ?",
    "Qui est le plus débile après 2 verres ?",
    "Qui est le moins capable de faire la sieste ?",
    "Qui a le plus de blagues nulles en stock ?",
    "Qui a le moins de talent pour le dessin ?",
    "Qui est le plus susceptible de se mettre au yoga l'année prochaine ?",
    "Qui est le moins susceptible de croire aux fantômes ?",
    "Qui est le plus à même de manger un plat périmé sans s'en rendre compte ?",
    "Qui est le moins à même de critiquer les choix de déco des autres ?",
    "Qui est le plus têtu quand il a tort ?",
    "Qui est le moins flexible pour changer d'itinéraire en voyage ?",
    "Qui a le plus de films vus au cinéma l'an dernier ?",
    "Qui a le moins de compte en banque avec un solde positif ?",
    "Qui est le plus susceptible de rater son train à la dernière minute ?",
    "Qui est le moins susceptible de faire un effort vestimentaire pour une occasion ?",
    "Qui est le plus à même de signer un contrat sans le lire ?",
    "Qui est le moins à même de réussir un tour de magie simple ?",
    "Qui est le plus oublieux des anniversaires ?",
    "Qui est le moins serviable quand on a besoin d'un coup de main ?",
    "Qui a le plus de mauvaises habitudes alimentaires ?",
    "Qui a le moins de mémoire des films qu'il a déjà vus ?",
    "Qui est le plus susceptible de laisser un commentaire sarcastique sur internet ?",
    "Qui est le moins susceptible de se vexer pour une blague ?",
    "Qui est le plus à même de convaincre un enfant de manger des légumes ?",
    "Qui est le moins à même de tenir sa résolution du Nouvel An ?",
    "Qui est le plus doué pour la négociation de prix ?",
    "Qui est le moins tolérant au froid ?",
    "Qui a le plus de messages non lus sur son téléphone ?",
    "Qui a le moins de temps à accorder à son animal de compagnie ?",
    "Qui est le plus susceptible de gagner à un jeu de société inconnu ?",
    "Qui est le moins susceptible de changer d'opérateur mobile ?",
    "Qui est le plus à même de devenir millionnaire avant 40 ans ?",
    "Qui est le moins à même de prêter de l'argent sans condition ?",
    "Qui est le plus bruyant quand il mange ?",
    "Qui est le moins bavard de la bande ?",
    "Qui a le plus de série entamées et jamais finies ?",
    "Qui a le moins de peur des insectes ?",
    "Qui est le plus susceptible de se faire arnaquer sur internet ?",
    "Qui est le moins susceptible de se souvenir du nom de nos serveurs ?",
    "Qui est le plus à même de faire un régime strict pendant un mois ?",
    "Qui est le moins à même de faire des blagues de papa ?",
    "Qui est le plus accro aux réseaux sociaux ?",
    "Qui est le moins patient devant un ordinateur lent ?",
    "Qui a le plus de passions bizarres ?",
    "Qui a le moins de soucis existentiels ?",
    "Qui est le plus susceptible de dire 'je l'avais dit' ?",
    "Qui est le moins susceptible de s'endormir pendant un trajet en voiture ?",
    "Qui est le plus à même de changer de vie radicalement sur un coup de tête ?",
    "Qui est le moins à même de tenir l'alcool ?",
    "Qui est le plus naïf en général ?",
    "Qui est le moins organisé pour un voyage ?",
    "Qui a le plus de t-shirts à l'effigie d'un groupe de musique ?",
    "Qui a le moins de goût pour la musique classique ?",
    "Qui est le plus susceptible de se présenter en retard à son propre mariage ?",
    "Qui est le moins susceptible de lire le générique d'un film jusqu'à la fin ?",
    "Qui est le plus à même de devenir célèbre pour quelque chose de ridicule ?",
    "Qui est le moins à même de faire ses courses en ligne ?",
    "Qui est le plus obsédé par le sport ?",
    "Qui est le moins chanceux au tirage au sort ?",
    "Qui a le plus de petits bobos imaginaires ?",
    "Qui a le moins de respect pour les règles de politesse de base ?",
    "Qui est le plus susceptible de se faire passer pour quelqu'un d'autre au téléphone ?",
    "Qui est le moins susceptible de mentir pour se sortir d'une situation gênante ?",
    "Qui est le plus à même de tenir une conversation avec un inconnu pendant une heure ?",
    "Qui est le moins à même de résister à l'appel de la nourriture grasse ?",
    "Qui est le plus dégouté par les araignées ?",
    "Qui est le moins diplomate en cas de conflit ?",
    "Qui a le plus de peluches d'enfance gardées précieusement ?",
    "Qui a le moins de motivation pour le ménage ?",
    "Qui est le plus susceptible de rater un rendez-vous important par oubli ?",
    "Qui est le moins susceptible de dépenser une fortune pour un vêtement de marque ?",
    "Qui est le plus à même de réparer un vélo sans aide extérieure ?",
    "Qui est le moins à même de faire une surprise réussie ?",
    "Qui est le plus passionné par son travail ?",
    "Qui est le moins créatif en cuisine ?",
    "Qui a le plus de photos de paysage dans son fond d'écran ?",
    "Qui a le moins de temps à perdre en bavardages inutiles ?",
    "Qui est le plus susceptible de changer de coupe de cheveux radicalement ?",
    "Qui est le moins susceptible de répondre à un e-mail professionnel le week-end ?",
    "Qui est le plus à même de faire un bon argumentaire pour convaincre un investisseur ?",
    "Qui est le moins à même de se souvenir de l'ordre alphabétique ?",
    "Qui est le plus sélectif sur les films à regarder ?",
    "Qui est le moins facile à vivre en colocation ?",
    "Qui a le plus de livres jamais ouverts dans sa bibliothèque ?",
    "Qui a le moins de talent pour les jeux de mots ?",
    "Qui est le plus susceptible de critiquer la nourriture au restaurant ?",
    "Qui est le moins susceptible de regarder une émission de téléréalité ?",
    "Qui est le plus à même de trouver un objet perdu depuis des mois ?",
    "Qui est le moins à même de se taire quand il est énervé ?",
    "Qui est le plus gêné par les compliments ?",
    "Qui est le moins curieux de découvrir de nouvelles choses ?",
    "Qui a le plus de talents cachés dont personne ne se doute ?",
    "Qui a le moins de bonnes excuses pour justifier un retard ?",
    "Qui est le plus susceptible de se mettre à pleurer devant un dessin animé ?",
    "Qui est le moins susceptible de prendre le temps de se faire un bon petit-déjeuner ?",
    "Qui est le plus à même de faire une bonne affaire sur un site d'occasion ?",
    "Qui est le moins à même de supporter la musique de Noël avant décembre ?",
    "Qui est le plus accro aux jeux mobiles ?",
    "Qui est le moins souriant sur les photos ?",
    "Qui a le plus de vêtements qui datent du lycée ?",
    "Qui a le moins de compétences en premiers secours ?",
    "Qui est le plus susceptible de casser quelque chose par accident ?",
    "Qui est le moins susceptible de garder son sang-froid dans une situation critique ?",
    "Qui est le plus à même de trouver le temps de lire un livre par semaine ?",
    "Qui est le moins à même de faire une dissertation sans erreur ?",
    "Qui est le plus crédible pour jouer un rôle d'espion ?",
    "Qui est le moins attentif aux détails ?",
    "Qui a le plus de secrets partagés uniquement avec un parent ?",
    "Qui a le moins de peur d'une coupure d'électricité ?",
    "Qui est le plus susceptible de perdre son passeport en voyage ?",
    "Qui est le moins susceptible de tenir un journal intime ?",
    "Qui est le plus à même de se faire des amis partout où il va ?",
    "Qui est le moins à même de reconnaître une chanson des années 80 ?",
    "Qui est le plus entreprenant pour organiser des événements ?",
    "Qui est le moins fidèle à une seule marque ?",
    "Qui a le plus de compte sur des plateformes de streaming ?",
    "Qui a le moins de rêves dont il se souvient au réveil ?",
    "Qui est le plus susceptible de finir un pot de glace entier en une soirée ?",
    "Qui est le moins susceptible de sortir de chez lui sans s'être coiffé ?",
    "Qui est le plus à même de faire la fête seul chez lui ?",
    "Qui est le moins à même de se souvenir des noms de tous les acteurs d'un film ?",
    "Qui est le plus susceptible de se tromper de train ?",
    "Qui est le moins susceptible de se faire piéger par une fausse nouvelle ?",
    "Qui a le plus de messages envoyés pendant qu'il dort ?",
    "Qui a le moins de respect pour les traditions ?",
    "Qui est le plus susceptible de gagner à la pétanque ?",
    "Qui est le moins susceptible de payer avec de la monnaie ?",
    "Qui est le plus à même de faire un bon discours de mariage ?",
    "Qui est le moins à même de tenir une conversation politique sérieuse ?",
    "Qui est le plus doué pour l'improvisation ?",
    "Qui est le moins exigeant sur la qualité de la nourriture ?",
    "Qui a le plus de bracelets accumulés à son poignet ?",
    "Qui a le moins de pudeur pour parler de ses problèmes de santé ?",
    "Qui est le plus susceptible de critiquer un livre qu'il n'a pas lu ?",
    "Qui est le moins susceptible de se faire avoir par une mauvaise blague ?",
    "Qui est le plus à même de concevoir un plan de secours en cas d'apocalypse ?",
    "Qui est le moins à même de réussir à faire des économies ?",
    "Qui est le plus téméraire dans les parcs d'attractions ?",
    "Qui est le moins patient avec les personnes âgées ?",
    "Qui a le plus de photos de lui enfant embarrassantes ?",
    "Qui a le moins de vocabulaire dans une langue étrangère ?",
    "Qui est le plus susceptible de se tromper de salle de réunion ?",
    "Qui est le moins susceptible de prendre une décision basée sur l'émotion ?",
    "Qui est le plus à même de trouver le meilleur prix pour un vol ?",
    "Qui est le moins à même de faire la différence entre deux vins ?",
    "Qui est le plus sarcasme de nature ?",
    "Qui est le moins confiant en public ?",
    "Qui a le plus de petits rituels avant de se coucher ?",
    "Qui a le moins de peur d'un contrôle de police ?",
    "Qui est le plus susceptible de laisser un plat brûler en cuisine ?",
    "Qui est le moins susceptible de changer de coiffure après une rupture ?",
    "Qui est le plus à même de réussir à faire un créneau parfait ?",
    "Qui est le moins à même de se lever sans café le matin ?",
    "Qui est le plus susceptible de se perdre en pleine ville ?",
    "Qui est le moins susceptible de se souvenir de son mot de passe ?",
    "Qui a le plus de mauvaises habitudes au volant ?",
    "Qui a le moins de chances de gagner à un jeu de cartes ?",
    "Qui est le plus susceptible de faire un cadeau de dernière minute ?",
    "Qui est le moins susceptible de prendre des risques financiers ?",
    "Qui est le plus à même de faire rire un enfant qui pleure ?",
    "Qui est le moins à même de tenir le rythme sur une piste de danse ?",
    "Qui est le plus dégouté par le gaspillage alimentaire ?",
    "Qui est le moins exubérant en public ?",
    "Qui a le plus de projets abandonnés dans son garage ?",
    "Qui a le moins de mémoire pour les dates historiques ?",
    "Qui est le plus susceptible de se plaindre du froid en été ?",
    "Qui est le moins susceptible de utiliser un jargon technique dans la vie courante ?",
    "Qui est le plus à même de devenir le chef du groupe ?",
    "Qui est le moins à même de s'excuser sincèrement après une bêtise ?",
    "Qui est le plus cool sous la pression ?",
    "Qui est le moins patient avec les lenteurs administratives ?",
    "Qui a le plus de vêtements de sport qu'il ne met jamais ?",
    "Qui a le moins de curiosité pour les sujets scientifiques ?",
    "Qui est le plus susceptible de se faire renvoyer d'un lieu public ?",
    "Qui est le moins susceptible de respecter l'interdiction de fumer ?",
    "Qui est le plus à même de raconter une histoire à dormir debout ?",
    "Qui est le moins à même de reconnaître un acteur célèbre ?",
    "Qui est le plus passionné de politique ?",
    "Qui est le moins critique envers lui-même ?",
    "Qui a le plus de musique téléchargée illégalement ?",
    "Qui a le moins de respect pour les heures de sommeil ?",
    "Qui est le plus susceptible de gagner à un concours de mangeurs de hot-dogs ?",
    "Qui est le moins susceptible de faire une remarque déplacée ?",
    "Qui est le plus à même de se souvenir du nom de tous les personnages secondaires d'un film ?",
    "Qui est le moins à même de trouver le chemin sans GPS ?",
    "Qui est le plus tête en l'air au quotidien ?",
    "Qui est le moins fiable pour rendre un livre emprunté ?",
    "Qui a le plus de souvenirs de vacances embarrassants ?",
    "Qui a le moins de crainte des catastrophes naturelles ?",
    "Qui est le plus susceptible de changer d'avis au milieu d'une phrase ?",
    "Qui est le moins susceptible de mentir à ses parents ?",
    "Qui est le plus à même de créer un buzz sur les réseaux sociaux ?",
    "Qui est le moins à même de trouver une place de parking rapidement ?",
    "Qui est le plus sensible à la critique ?",
    "Qui est le moins organisé pour ses finances ?",
    "Qui a le plus de petits surnoms ridicules ?",
    "Qui a le moins de préférence pour une marque de voiture ?",
    "Qui est le plus susceptible de finir ses vacances au lit malade ?",
    "Qui est le moins susceptible de faire un commentaire positif sur un plat raté ?",
    "Qui est le plus à même de gagner à la belote ?",
    "Qui est le moins à même de se concentrer sans musique ?",
    "Qui est le plus chanceux en amour ?",
    "Qui est le moins expansif dans ses émotions ?",
    "Qui a le plus de vieux tickets de caisse dans ses poches ?",
    "Qui a le moins de croyance en l'astrologie ?",
    "Qui est le plus susceptible de ne pas reconnaître quelqu'un qu'il connaît bien ?",
    "Qui est le moins susceptible de faire une folie vestimentaire ?",
    "Qui est le plus à même de trouver un billet de 50€ par terre ?",
    "Qui est le moins à même de garder une plante en vie ?",
    "Qui est le plus économe pour les petits achats ?",
    "Qui est le moins à l'aise avec la technologie ?",
    "Qui a le plus de tours joués à un jeu de rôle ?",
    "Qui a le moins de mémoire des événements sportifs passés ?",
    "Qui est le plus susceptible de s'endormir pendant un concert ?",
    "Qui est le moins susceptible de faire une erreur de frappe en écrivant un SMS ?",
    "Qui est le plus à même de faire un bon argumentaire pour changer d'avis ?",
    "Qui est le moins à même de rester zen pendant un embouteillage ?",
    "Qui est le plus doué pour les langues étrangères ?",
    "Qui est le moins imaginatif pour les cadeaux ?",
    "Qui a le plus de photos de lui en train de manger ?",
    "Qui a le moins de peur du noir ?",
    "Qui est le plus susceptible de prendre la défense d'un ami en difficulté ?",
    "Qui est le moins susceptible de partager sa nourriture ?",
    "Qui est le plus à même de gérer une crise de panique chez quelqu'un ?",
    "Qui est le moins à même de se souvenir du code de la carte bancaire ?",
    "Qui est le plus capricieux pour le choix du film ?",
    "Qui est le moins rapide à réagir à une nouvelle ?",
    "Qui a le plus de verres cassés en soirée ?",
    "Qui a le moins de talent pour la couture ?",
    "Qui est le plus susceptible de se blesser en faisant du sport ?",
    "Qui est le moins susceptible de faire un effort pour s'intégrer dans un nouveau groupe ?",
    "Qui est le plus à même de trouver une solution de dernière minute à un problème ?",
    "Qui est le moins à même de remercier quelqu'un pour un service rendu ?",
    "Qui est le plus enthousiaste pour les activités de groupe ?",
    "Qui est le moins honnête sur ses performances sportives ?",
    "Qui a le plus de vieux appareils électroniques qui ne fonctionnent plus ?",
    "Qui a le moins de chance d'être appelé pour un entretien d'embauche ?",
    "Qui est le plus susceptible de tomber amoureux d'une personne célèbre ?",
    "Qui est le moins susceptible de critiquer un plat épicé ?",
    "Qui est le plus à même de négocier une augmentation de salaire ?",
    "Qui est le moins à même de se souvenir d'un rêve détaillé ?",
    "Qui est le plus excentrique dans ses goûts vestimentaires ?",
    "Qui est le moins discipliné en général ?",
    "Qui a le plus de vieux CD de musique ?",
    "Qui a le moins de compétences en électricité ?",
    "Qui est le plus susceptible de faire un voyage en stop ?",
    "Qui est le moins susceptible de changer d'avis sur un sujet important ?",
    "Qui est le plus à même de faire un exposé réussi sans préparation ?",
    "Qui est le moins à même de garder une rancune longtemps ?",
    "Qui est le plus susceptible de se perdre en forêt ?",
    "Qui est le moins susceptible de se faire piéger par un vendeur ?",
    "Qui a le plus de conversations loufoques dans l'historique de groupe ?",
    "Qui a le moins de sens de l'orientation ?",
    "Qui est le plus susceptible de gagner à un jeu de stratégie complexe ?",
    "Qui est le moins susceptible de prendre de notes en réunion ?",
    "Qui est le plus à même de faire un barbecue parfait ?",
    "Qui est le moins à même de dire 'je t'aime' en premier ?",
    "Qui est le plus généreux avec les sans-abris ?",
    "Qui est le moins sceptique face aux miracles ?",
    "Qui a le plus de petits secrets bien gardés ?",
    "Qui a le moins de peur d'une rupture amoureuse ?",
    "Qui est le plus susceptible de mentir sur son CV ?",
    "Qui est le moins susceptible de réussir un examen oral ?",
    "Qui est le plus à même de faire rire l'assemblée avec une anecdote embarrassante ?",
    "Qui est le moins à même de supporter l'odeur du poisson ?",
    "Qui est le plus délicat pour annoncer une mauvaise nouvelle ?",
    "Qui est le moins à l'aise avec les bébés ?",
    "Qui a le plus de tours du monde rêvés ?",
    "Qui a le moins de mauvais souvenirs d'enfance ?",
    "Qui est le plus susceptible de se faire inviter à une fête VIP ?",
    "Qui est le moins susceptible de prêter sa brosse à dents ?",
    "Qui est le plus à même de sauver le monde d'une épidémie de zombies ?",
    "Qui est le moins à même de se souvenir du nom de ses professeurs du lycée ?",
    "Qui est le plus accro aux jeux de société ?",
    "Qui est le moins critique sur l'apparence des autres ?",
    "Qui a le plus de messages tapés à la hâte et incompréhensibles ?",
    "Qui a le moins de talent pour la photographie ?",
    "Qui est le plus susceptible de dépenser une fortune en gadgets inutiles ?",
    "Qui est le moins susceptible de se plaindre de la lenteur du service ?",
    "Qui est le plus à même de créer un nouveau plat délicieux avec trois ingrédients ?",
    "Qui est le moins à même de faire une sieste de 2 heures en plein jour ?",
    "Qui est le plus susceptible de se faire tatouer son plat préféré ?",
    "Qui est le moins susceptible de se souvenir de l'heure exacte d'un rendez-vous ?",
    "Qui a le plus de règles personnelles qu'il s'impose ?",
    "Qui a le moins de goût pour la nourriture végétarienne ?",
    "Qui est le plus susceptible de faire une crise de rire incontrôlée ?",
    "Qui est le moins susceptible de dire qu'il est fatigué ?",
    "Qui est le plus à même de s'occuper d'un animal blessé ?",
    "Qui est le moins à même de faire une bonne première impression ?",
    "Qui est le plus tête en l'air au restaurant ?",
    "Qui est le moins patient avec les erreurs des autres ?",
    "Qui a le plus de photos de lui en train de dormir ?",
    "Qui a le moins de respect pour l'autorité ?",
    "Qui est le plus susceptible de changer de métier tous les ans ?",
    "Qui est le moins susceptible de critiquer un cadeau mal choisi ?",
    "Qui est le plus à même de construire une cabane en bois ?",
    "Qui est le moins à même de se souvenir du code de l'alarme ?",
    "Qui est le plus susceptible de se faire arrêter pour excès de vitesse ?",
    "Qui est le moins susceptible de se faire passer pour un autre sur un site de rencontre ?",
    "Qui a le plus de messages vocaux jamais écoutés ?",
    "Qui a le moins de talent pour l'organisation d'un voyage ?",
    "Qui est le plus susceptible de faire un discours improvisé réussi ?",
    "Qui est le moins susceptible de croire aux remèdes de grand-mère ?",
    "Qui est le plus à même de trouver un trésor caché ?",
    "Qui est le moins à même de tenir sa maison rangée ?",
    "Qui est le plus génial pour trouver des solutions ingénieuses ?",
    "Qui est le moins discret quand il parle au téléphone ?",
    "Qui a le plus de mauvaises expériences de voyage ?",
    "Qui a le moins de crainte du jugement des autres ?",
    "Qui est le plus susceptible de signer pour une assurance inutile ?",
    "Qui est le moins susceptible de partager un secret embarrassant ?",
    "Qui est le plus à même de changer une roue de voiture en pleine nuit ?",
    "Qui est le moins à même de réussir à faire un compliment sans devenir gêné ?",
    "Qui est le plus susceptible de se faire arnaquer en vacances ?",
    "Qui est le moins susceptible de se souvenir du jour où on s'est rencontrés ?",
    "Qui a le plus de choses qu'il a volées dans sa vie ?",
    "Qui a le moins de patience pour attendre un ami ?",
    "Qui est le plus susceptible de faire une crise de jalousie pour une bêtise ?",
    "Qui est le moins susceptible de prendre le temps de se faire belle/beau tous les jours ?",
    "Qui est le plus à même de convaincre quelqu'un de faire un truc fou ?",
    "Qui est le moins à même de lire un livre en entier sans interruption ?",
    "Qui est le plus bavard sur un sujet qui le passionne ?",
    "Qui est le moins calme après une bonne nouvelle ?",
    "Qui a le plus de projets de rénovation non achevés ?",
    "Qui a le moins de force pour porter un sac lourd ?",
    "Qui est le plus susceptible de se mettre à pleurer de joie ?",
    "Qui est le moins susceptible de dépenser son argent pour un jeu vidéo ?",
    "Qui est le plus à même de faire un bon argumentaire pour changer d'heure de coucher ?",
    "Qui est le moins à même de se souvenir du nom de l'acteur principal d'un film culte ?",
    "Qui est le plus susceptible de se faire prendre en flagrant délit de mensonge ?",
    "Qui est le moins susceptible de se souvenir de l'endroit où il a garé sa voiture ?",
    "Qui a le plus de tours de magie ratés ?",
    "Qui a le moins de talent pour la musique classique ?",
    "Qui est le plus susceptible de faire un cadeau de Noël fait maison ?",
    "Qui est le moins susceptible de prendre un risque calculé ?",
    "Qui est le plus à même de trouver une solution créative à un problème technique ?",
    "Qui est le moins à même de tenir un secret de famille ?",
    "Qui est le plus dégouté par le bruit ?",
    "Qui est le moins enthousiaste pour les fêtes surprises ?",
    "Qui a le plus de mauvaises habitudes au travail ?",
    "Qui a le moins de respect pour les règles de la maison ?",
    "Qui est le plus susceptible de se faire prendre à tricher à un jeu ?",
    "Qui est le moins susceptible de utiliser un filtre photo sur ses selfies ?",
    "Qui est le plus à même de négocier une réduction dans un magasin de luxe ?",
    "Qui est le moins à même de faire un bon discours sans bégayer ?",
    "Qui est le plus sérieux en amitié ?",
    "Qui est le moins crédule face aux légendes urbaines ?",
    "Qui a le plus de t-shirts à message humoristique ?",
    "Qui a le moins de peur de l'obscurité totale ?",
    "Qui est le plus susceptible de partir en vacances sans prévenir ?",
    "Qui est le moins susceptible de faire un effort pour être à l'heure ?",
    "Qui est le plus à même de gagner à un concours de blagues ?",
    "Qui est le moins à même de supporter une longue attente ?",
    "Qui est le plus chanceux au jeu de dés ?",
    "Qui est le moins doué pour faire la lessive ?",
    "Qui a le plus de petits objets trouvés dans ses poches ?",
    "Qui a le moins de mémoire pour les noms des villes ?",
    "Qui est le plus susceptible de laisser son téléphone en mode silencieux ?",
    "Qui est le moins susceptible de changer d'avis sous la pression ?",
    "Qui est le plus à même de trouver un raccourci secret dans une ville inconnue ?",
    "Qui est le moins à même de faire la différence entre un mensonge et la vérité ?",
    "Qui est le plus passionné par les animaux ?",
    "Qui est le moins souriant sur les photos de groupe ?",
    "Qui a le plus de messages envoyés à la mauvaise personne ?",
    "Qui a le moins de compétences pour l'entretien de son véhicule ?",
    "Qui est le plus susceptible de se faire inviter à une soirée costumée ?",
    "Qui est le moins susceptible de réussir à faire une blague sarcastique ?",
    "Qui est le plus à même de dire 'je ne sais pas' sans hésiter ?",
    "Qui est le moins à même de faire un effort pour s'habiller ?",
    "Qui est le plus susceptible de se faire voler son téléphone ?",
    "Qui est le moins susceptible de se souvenir du jour où il a reçu son diplôme ?",
    "Qui a le plus de rêves bizarres et mémorables ?",
    "Qui a le moins de respect pour les limitations de vitesse ?",
    "Qui est le plus susceptible de gagner à un jeu de devinettes ?",
    "Qui est le moins susceptible de prendre le temps de se faire une manucure ?",
    "Qui est le plus à même de faire un discours émouvant et sincère ?",
    "Qui est le moins à même de tenir sa promesse de régime ?",
    "Qui est le plus doué pour la décoration intérieure ?",
    "Qui est le moins exigeant sur la qualité des films ?",
    "Qui a le plus de chaînes YouTube auxquelles il est abonné ?",
    "Qui a le moins de peur de se retrouver seul ?",
    "Qui est le plus susceptible de critiquer un plat trop salé ?",
    "Qui est le moins susceptible de faire une gaffe en public ?",
    "Qui est le plus à même de trouver un bon plan voyage de dernière minute ?",
    "Qui est le moins à même de se taire quand il a une idée lumineuse ?",
    "Qui est le plus accro aux podcasts ?",
    "Qui est le moins patient avec les erreurs de ses amis ?",
    "Qui a le plus de petits objets en lien avec son enfance ?",
    "Qui a le moins de crainte de l'échec ?",
    "Qui est le plus susceptible de faire un commentaire méchant sans s'en rendre compte ?",
    "Qui est le moins susceptible de changer d'équipe sportive favorite ?",
    "Qui est le plus à même de construire un igloo ?",
    "Qui est le moins à même de se souvenir du nom d'un plat exotique ?",
    "Qui est le plus susceptible de se tromper de personne dans la rue ?",
    "Qui est le moins susceptible de se faire avoir par une publicité mensongère ?",
    "Qui a le plus de conversations qui finissent en dispute philosophique ?",
    "Qui a le moins de sens de l'humour noir ?",
    "Qui est le plus susceptible de gagner à une bataille d'eau ?",
    "Qui est le moins susceptible de utiliser des emojis dans ses messages ?",
    "Qui est le plus à même de faire un bon discours d'adieu ?",
    "Qui est le moins à même de tenir un pari stupide jusqu'au bout ?",
    "Qui est le plus généreux avec ses conseils ?",
    "Qui est le moins sceptique face à l'amour au premier regard ?",
    "Qui a le plus de petits mensonges dits par politesse ?",
    "Qui a le moins de peur du dentiste ?",
    "Qui est le plus susceptible de se faire voler ses idées ?",
    "Qui est le moins susceptible de réussir à faire une heure de sport d'affilée ?",
    "Qui est le plus à même de faire un dessin réaliste ?",
    "Qui est le moins à même de supporter le bruit des chewing-gums ?",
    "Qui est le plus délicieux pour un plat fait maison ?",
    "Qui est le moins à l'aise en maillot de bain ?",
    "Qui a le plus de tours du monde effectués ?",
    "Qui a le moins de mauvais goûts musicaux assumés ?",
    "Qui est le plus susceptible de se faire filmer en train de chanter faux ?",
    "Qui est le moins susceptible de prêter sa voiture ?",
    "Qui est le plus à même de sauver l'humanité d'une invasion extraterrestre ?",
    "Qui est le moins à même de se souvenir des paroles d'une chanson populaire ?",
    "Qui est le plus accro à la planification ?",
    "Qui est le moins critique envers les films d'action ?",
    "Qui a le plus de messages envoyés pendant qu'il était saoul ?",
    "Qui a le moins de talent pour la décoration de gâteaux ?",
    "Qui est le plus susceptible de dépenser une fortune pour un animal de compagnie ?",
    "Qui est le moins susceptible de se plaindre d'un mal de tête ?",
    "Qui est le plus à même de créer une blague qui fait rire tout le monde ?",
    "Qui est le moins à même de faire un compliment à un étranger ?",
    "Qui est le plus susceptible de se tromper de cadeau d'anniversaire ?",
    "Qui est le moins susceptible de se souvenir de l'heure du déjeuner ?",
    "Qui a le plus de règles non écrites dans son couple ?",
    "Qui a le moins de goût pour la nourriture mexicaine ?",
    "Qui est le plus susceptible de faire une crise de panique dans un lieu bondé ?",
    "Qui est le moins susceptible de dire 'ça va' quand ça ne va pas ?",
    "Qui est le plus à même de s'occuper d'un bébé pendant 24 heures ?",
    "Qui est le moins à même de faire une bonne impression lors d'un premier rendez-vous ?",
    "Qui est le plus tête en l'air avec ses affaires ?",
    "Qui est le moins patient avec les jeux de société longs ?",
    "Qui a le plus de photos de plats qu'il a cuisinés ?",
    "Qui a le moins de respect pour les horaires de sommeil des autres ?",
    "Qui est le plus susceptible de changer d'avis sur un achat important ?",
    "Qui est le moins susceptible de critiquer un plat mal cuisiné ?",
    "Qui est le plus à même de construire un château de sable impressionnant ?",
    "Qui est le moins à même de se souvenir du nom de nos serveurs ?",
    "Qui est le plus susceptible de se faire amende pour stationnement illicite ?",
    "Qui est le moins susceptible de se faire passer pour quelqu'un de riche ?",
    "Qui a le plus de messages qui finissent par des points de suspension ?",
    "Qui a le moins de talent pour le jardinage ?",
    "Qui est le plus susceptible de faire un discours de mariage émouvant ?",
    "Qui est le moins susceptible de croire aux théories d'extraterrestres ?",
    "Qui est le plus à même de trouver une solution pour éviter une dispute ?",
    "Qui est le moins à même de tenir un journal de bord en voyage ?",
    "Qui est le plus génial pour trouver des jeux de mots pourris ?",
    "Qui est le moins discret sur sa vie amoureuse ?",
    "Qui a le plus de mauvaises expériences de transport en commun ?",
    "Qui a le moins de crainte de l'échec en public ?",
    "Qui est le plus susceptible de signer pour un abonnement inutile ?",
    "Qui est le moins susceptible de partager une photo de lui enfant embarrassante ?",
    "Qui est le plus à même de changer un pneu crevé en moins de 10 minutes ?",
    "Qui est le moins à même de réussir à faire la différence entre deux parfums ?",
    "Qui est le plus susceptible de se faire arnaquer par un faux site internet ?",
    "Qui est le moins susceptible de se souvenir du jour où il a rencontré son meilleur ami ?",
    "Qui a le plus de choses qu'il regrette d'avoir dites ?",
    "Qui a le moins de patience pour les jeux de patience ?",
    "Qui est le plus susceptible de faire une crise de rire en situation sérieuse ?",
    "Qui est le moins susceptible de prendre le temps de se faire un masque de beauté ?",
    "Qui est le plus à même de convaincre un enfant de manger des légumes ?",
    "Qui est le moins à même de lire un livre en moins de 24 heures ?",
    "Qui est le plus bavard sur un sujet qui l'intéresse ?",
    "Qui est le moins calme après une mauvaise nouvelle ?",
    "Qui a le plus de projets de voyage non réalisés ?",
    "Qui a le moins de force pour ouvrir un bocal ?",
    "Qui est le plus susceptible de se mettre à pleurer devant un film triste ?",
    "Qui est le moins susceptible de dépenser son argent pour un livre ?",
    "Qui est le plus à même de faire un bon argumentaire pour changer d'heure de réveil ?",
    "Qui est le moins à même de se souvenir du nom de la capitale d'un pays lointain ?",
    "Qui est le plus susceptible de se faire passer pour un autre sur un forum ?",
    "Qui est le moins susceptible de se souvenir de l'endroit où il a mis ses lunettes ?",
    "Qui a le plus de tours de vélo effectués cette année ?",
    "Qui a le moins de talent pour le chant ?",
    "Qui est le plus susceptible de faire un cadeau de Noël à un inconnu ?",
    "Qui est le moins susceptible de prendre un risque pour aider un ami ?",
    "Qui est le plus à même de trouver une solution ingénieuse à un problème de la vie courante ?",
    "Qui est le moins à même de tenir une conversation avec un expert sur un sujet pointu ?",
    "Qui est le plus dégouté par les araignées ?",
    "Qui est le moins enthousiaste pour les activités sportives ?",
    "Qui a le plus de mauvaises habitudes au téléphone ?",
    "Qui a le moins de respect pour les règles de grammaire ?",
    "Qui est le plus susceptible de se faire prendre à mentir sur son CV ?",
    "Qui est le moins susceptible de utiliser un jargon professionnel en dehors du travail ?",
    "Qui est le plus à même de négocier une ristourne au marché ?",
    "Qui est le moins à même de faire un bon discours sans lire ses notes ?",
    "Qui est le plus sérieux pour ses engagements ?",
    "Qui est le moins crédule face aux rumeurs ?",
    "Qui a le plus de t-shirts à l'effigie d'un animal ?",
    "Qui a le moins de peur des souris ?",
    "Qui est le plus susceptible de partir en vacances dans un lieu inconnu ?",
    "Qui est le moins susceptible de faire un effort pour s'habiller de manière élégante ?",
    "Qui est le plus à même de gagner à un concours de grimaces ?",
    "Qui est le moins à même de supporter la mauvaise humeur des autres ?",
    "Qui est le plus chanceux au jeu de grattage ?",
    "Qui est le moins doué pour faire la vaisselle ?",
    "Qui a le plus de petits objets qu'il a trouvés dans la rue ?",
    "Qui a le moins de mémoire pour les dates d'anniversaire ?",
    "Qui est le plus susceptible de laisser son téléphone en mode avion ?",
    "Qui est le moins susceptible de changer d'avis sur un sujet politique ?",
    "Qui est le plus à même de trouver un bon plan pour une sortie inattendue ?",
    "Qui est le moins à même de faire la différence entre deux couleurs similaires ?",
    "Qui est le plus passionné par les jeux vidéo ?",
    "Qui est le moins souriant quand il est stressé ?",
    "Qui a le plus de messages envoyés pendant qu'il dort ?",
    "Qui a le moins de compétences pour l'entretien de son vélo ?",
    "Qui est le plus susceptible de se faire inviter à une soirée déguisée ?",
    "Qui est le moins susceptible de réussir à faire une blague de papa ?",
    "Qui est le plus à même de dire 'je t'aime' après une dispute ?",
    "Qui est le moins à même de faire un effort pour se maquiller/raser ?",
    "Qui est le plus susceptible de se faire voler son ordinateur ?",
    "Qui est le moins susceptible de se souvenir du jour où il a rencontré son partenaire ?",
    "Qui a le plus de rêves prémonitoires ?",
    "Qui a le moins de respect pour les règles de sécurité ?",
    "Qui est le plus susceptible de gagner à un jeu de rôle ?",
    "Qui est le moins susceptible de prendre le temps de se faire un bon café ?",
    "Qui est le plus à même de faire un discours mémorable ?",
    "Qui est le moins à même de tenir sa promesse de ne pas manger de sucre ?",
    "Qui est le plus doué pour le dessin ?",
    "Qui est le moins exigeant sur la qualité des séries TV ?",
    "Qui a le plus de chaînes de télé qu'il regarde régulièrement ?",
    "Qui a le moins de peur du vide ?",
    "Qui est le plus susceptible de critiquer un plat trop épicé ?",
    "Qui est le moins susceptible de faire une gaffe sur les réseaux sociaux ?",
    "Qui est le plus à même de trouver une solution pour éviter une panne ?",
    "Qui est le moins à même de se taire quand il est énervé ?",
    "Qui est le plus accro aux documentaires ?",
    "Qui est le moins patient avec les transports en commun ?",
    "Qui a le plus de petits objets en lien avec un voyage ?",
    "Qui a le moins de crainte des conséquences de ses actes ?",
    "Qui est le plus susceptible de faire un commentaire positif sur un plat raté ?",
    "Qui est le moins susceptible de changer de couleur de cheveux ?",
    "Qui est le plus à même de construire un meuble en moins d'une heure ?",
    "Qui est le moins à même de se souvenir du nom de l'acteur principal d'un film célèbre ?",
    "Qui est le plus susceptible de se tromper d'itinéraire en voiture ?",
    "Qui est le moins susceptible de se faire avoir par un sondage bidon ?",
    "Qui a le plus de conversations qui finissent en fous rires ?",
    "Qui a le moins de sens de l'organisation pour un événement ?",
    "Qui est le plus susceptible de gagner à une course de sacs ?",
    "Qui est le moins susceptible de utiliser le mode sombre sur son téléphone ?",
    "Qui est le plus à même de faire un bon discours de remerciement ?",
    "Qui est le moins à même de tenir une conversation avec un enfant de 5 ans ?",
    "Qui est le plus généreux avec son temps ?",
    "Qui est le moins sceptique face aux prédictions ?",
    "Qui a le plus de petits mensonges dits par paresse ?",
    "Qui a le moins de peur de l'engagement ?",
    "Qui est le plus susceptible de se faire voler son portefeuille ?",
    "Qui est le moins susceptible de réussir à faire une heure de ménage d'affilée ?",
    "Qui est le plus à même de faire un exposé réussi sans notes ?",
    "Qui est le moins à même de supporter l'odeur du chou-fleur ?",
    "Qui est le plus délicieux pour un gâteau fait maison ?",
    "Qui est le moins à l'aise avec les animaux inconnus ?",
    "Qui a le plus de tours du monde rêvés et jamais réalisés ?",
    "Qui a le moins de mauvais souvenirs de lycée ?",
    "Qui est le plus susceptible de se faire prendre en photo en train de dormir ?",
    "Qui est le moins susceptible de prêter son téléphone ?",
    "Qui est le plus à même de sauver le monde d'une crise économique ?",
    "Qui est le moins à même de se souvenir des paroles d'une chanson enfantine ?",
    "Qui est le plus accro aux jeux vidéo ?",
    "Qui est le moins critique envers les films romantiques ?",
    "Qui a le plus de messages envoyés pendant qu'il était en colère ?",
    "Qui a le moins de talent pour la poterie ?",
    "Qui est le plus susceptible de dépenser une fortune pour un voyage de luxe ?",
    "Qui est le moins susceptible de se plaindre de la chaleur ?",
    "Qui est le plus à même de créer une œuvre d'art originale ?",
    "Qui est le moins à même de faire un compliment sincère à un ami ?",
    "Qui est le plus susceptible de se tromper d'heure de réveil ?",
    "Qui est le moins susceptible de se souvenir du jour où il a rencontré un invité ?",
    "Qui a le plus de règles non écrites dans son cercle d'amis ?",
    "Qui a le moins de goût pour la nourriture indienne ?",
    "Qui est le plus susceptible de faire une crise de rire en public ?",
    "Qui est le moins susceptible de dire qu'il est d'accord pour faire plaisir ?",
    "Qui est le plus à même de s'occuper d'une personne malade ?",
    "Qui est le moins à même de faire une bonne impression en entretien d'embauche ?",
    "Qui est le plus tête en l'air avec les dates importantes ?",
    "Qui est le moins patient avec les jeux vidéo difficiles ?",
    "Qui a le plus de photos de ses animaux de compagnie ?",
    "Qui a le moins de respect pour les règles de la route ?",
    "Qui est le plus susceptible de changer d'avis au milieu d'un débat ?",
    "Qui est le moins susceptible de critiquer un cadeau fait maison ?",
    "Qui est le plus à même de construire un abri de fortune en forêt ?",
    "Qui est le moins à même de se souvenir du nom de l'enseigne d'un magasin ?",
    "Qui est le plus susceptible de se faire arrêter pour tapage nocturne ?",
    "Qui est le moins susceptible de se faire passer pour quelqu'un d'autre sur les réseaux sociaux ?",
    "Qui a le plus de messages qui finissent par des points d'exclamation ?",
    "Qui a le moins de talent pour le bricolage ?",
    "Qui est le plus susceptible de faire un discours mémorable en public ?",
    "Qui est le moins susceptible de croire aux remèdes miracles ?",
    "Qui est le plus à même de trouver une solution pour économiser de l'argent ?",
    "Qui est le moins à même de tenir un carnet de bord de ses rêves ?",
    "Qui est le plus génial pour trouver des jeux de société obscurs ?",
    "Qui est le moins discret sur ses opinions politiques ?",
    "Qui a le plus de mauvaises expériences de covoiturage ?",
    "Qui a le moins de crainte de l'inconnu ?",
    "Qui est le plus susceptible de signer pour un engagement à long terme ?",
    "Qui est le moins susceptible de partager un moment de faiblesse ?",
    "Qui est le plus à même de changer un robinet qui fuit ?",
    "Qui est le moins à même de réussir à faire la différence entre deux bruits ?",
    "Qui est le plus susceptible de se faire arnaquer par un faux ami ?",
    "Qui est le moins susceptible de se souvenir du jour où il a eu son premier travail ?",
    "Qui a le plus de choses qu'il a volées à ses amis ?",
    "Qui a le moins de patience pour les longues explications ?",
    "Qui est le plus susceptible de faire une crise de jalousie pour un rien ?",
    "Qui est le moins susceptible de prendre le temps de se faire un bain chaud ?",
    "Qui est le plus à même de convaincre quelqu'un de changer de vie ?",
    "Qui est le moins à même de lire un livre qui ne l'intéresse pas ?",
    "Qui est le plus bavard avec les inconnus ?",
    "Qui est le moins calme après un événement excitant ?",
    "Qui a le plus de projets de carrière non aboutis ?",
    "Qui a le moins de force pour soulever une charge lourde ?",
    "Qui est le plus susceptible de se mettre à pleurer de rire ?",
    "Qui est le moins susceptible de dépenser son argent pour un gadget technologique ?",
    "Qui est le plus à même de faire un bon argumentaire pour changer de chaîne TV ?",
    "Qui est le moins à même de se souvenir du nom de l'acteur qui joue le rôle principal ?",
    "Qui est le plus susceptible de se faire prendre en photo en train de dormir ?",
    "Qui est le moins susceptible de se souvenir de l'endroit où il a mis son portefeuille ?",
    "Qui a le plus de tours de magie réussis ?",
    "Qui a le moins de talent pour la poésie ?",
    "Qui est le plus susceptible de faire un cadeau de Noël à son voisin ?",
    "Qui est le moins susceptible de prendre un risque non nécessaire ?",
    "Qui est le plus à même de trouver une solution ingénieuse pour gagner du temps ?",
    "Qui est le moins à même de tenir une conversation avec un enfant de 10 ans ?",
    "Qui est le plus dégouté par le silence ?",
    "Qui est le moins enthousiaste pour les sorties en boîte de nuit ?",
    "Qui a le plus de mauvaises habitudes de sommeil ?",
    "Qui a le moins de respect pour les règles de sécurité en ligne ?",
    "Qui est le plus susceptible de se faire prendre à tricher à un examen ?",
    "Qui est le moins susceptible de utiliser le jargon de son travail en soirée ?",
    "Qui est le plus à même de négocier un prix pour un voyage ?",
    "Qui est le moins à même de faire un bon discours sans préparation ?",
    "Qui est le plus sérieux pour ses études ?",
    "Qui est le moins crédule face aux légendes familiales ?",
    "Qui a le plus de t-shirts avec un logo de film ?",
    "Qui a le moins de peur du noir ?",
    "Qui est le plus susceptible de partir en vacances dans un camping ?",
    "Qui est le moins susceptible de faire un effort pour être à l'heure à un rendez-vous ?",
    "Qui est le plus à même de gagner à un concours de cuisine ?",
    "Qui est le moins à même de supporter une longue marche ?",
    "Qui est le plus chanceux au jeu de cartes ?",
    "Qui est le moins doué pour faire la cuisine ?",
    "Qui a le plus de petits objets qu'il a trouvés et gardés ?",
    "Qui a le moins de mémoire des dates importantes de ses amis ?",
    "Qui est le plus susceptible de laisser son téléphone éteint toute une journée ?",
    "Qui est le moins susceptible de changer d'avis sur un ami ?",
    "Qui est le plus à même de trouver un bon plan pour un week-end improvisé ?",
    "Qui est le moins à même de faire la différence entre deux sons similaires ?",
    "Qui est le plus passionné par l'histoire ?",
    "Qui est le moins souriant quand il est fatigué ?",
    "Qui a le plus de messages envoyés pendant qu'il conduisait ?",
    "Qui a le moins de compétences pour l'entretien de son logement ?",
    "Qui est le plus susceptible de se faire inviter à une fête de célébrités ?",
    "Qui est le moins susceptible de réussir à faire une blague sarcastique réussie ?",
    "Qui est le plus à même de dire 'je suis désolé' en premier ?",
    "Qui est le moins à même de faire un effort pour s'habiller de manière décontractée ?",
    "Qui est le plus susceptible de se faire voler ses affaires à la plage ?",
    "Qui est le moins susceptible de se souvenir du jour où il a rencontré un inconnu ?",
    "Qui a le plus de rêves qui se réalisent ?",
    "Qui a le moins de respect pour les règles d'étiquette ?",
    "Qui est le plus susceptible de gagner à un jeu de stratégie en ligne ?",
    "Qui est le moins susceptible de prendre le temps de se faire une pédicure ?",
    "Qui est le plus à même de faire un discours improvisé émouvant ?",
    "Qui est le moins à même de tenir sa promesse de ne pas boire d'alcool ?",
    "Qui est le plus doué pour la photographie ?",
    "Qui est le moins exigeant sur la qualité des livres lus ?",
    "Qui a le plus de chaînes de podcasts auxquelles il est abonné ?",
    "Qui a le moins de peur de l'altitude ?",
    "Qui est le plus susceptible de critiquer un plat trop sucré ?",
    "Qui est le moins susceptible de faire une gaffe avec un micro ?",
    "Qui est le plus à même de trouver une solution pour éviter un conflit ?",
    "Qui est le moins à même de se taire quand il est content ?",
    "Qui est le plus accro aux jeux de société ?",
    "Qui est le moins patient avec les erreurs de calcul ?",
    "Qui a le plus de petits objets en lien avec un film ?",
    "Qui a le moins de crainte de l'engagement professionnel ?",
    "Qui est le plus susceptible de faire un commentaire positif sur un film nul ?",
    "Qui est le moins susceptible de changer de plat préféré ?",
    "Qui est le plus à même de construire un meuble sans notice ?",
    "Qui est le moins à même de se souvenir du nom d'une ville lointaine ?",
    "Qui est le plus susceptible de se tromper de numéro de téléphone ?",
    "Qui est le moins susceptible de se faire avoir par une offre alléchante ?",
    "Qui a le plus de conversations qui finissent en chansons ?",
    "Qui a le moins de sens de l'humour absurde ?",
    "Qui est le plus susceptible de gagner à un concours de danse ?",
    "Qui est le moins susceptible de utiliser le jargon de la mode ?",
    "Qui est le plus à même de faire un bon discours de félicitations ?",
    "Qui est le moins à même de tenir une conversation avec un expert en vin ?",
    "Qui est le plus généreux avec ses compliments ?",
    "Qui est le moins sceptique face aux prédictions astrologiques ?",
    "Qui a le plus de petits mensonges dits pour faire plaisir ?",
    "Qui a le moins de peur de la solitude ?",
    "Qui est le plus susceptible de se faire voler ses idées ?",
    "Qui est le moins susceptible de réussir à faire une heure de méditation d'affilée ?",
    "Qui est le plus à même de faire un dessin abstrait ?",
    "Qui est le moins à même de supporter l'odeur du café ?",
    "Qui est le plus délicieux pour une boisson faite maison ?",
    "Qui est le moins à l'aise avec les inconnus ?",
    "Qui a le plus de tours du monde rêvés et planifiés ?",
    "Qui a le moins de mauvais souvenirs de vacances ?",
    "Qui est le plus susceptible de se faire prendre en photo en train de faire la sieste ?",
    "Qui est le moins susceptible de prêter sa voiture de collection ?",
    "Qui est le plus à même de sauver le monde d'une crise environnementale ?",
    "Qui est le moins à même de se souvenir des paroles d'une chanson de Noël ?",
    "Qui est le plus accro à la planification de voyage ?",
    "Qui est le moins critique envers les comédies ?",
    "Qui a le plus de messages envoyés pendant qu'il était triste ?",
    "Qui a le moins de talent pour la sculpture ?",
    "Qui est le plus susceptible de dépenser une fortune pour un bijou ?",
    "Qui est le moins susceptible de se plaindre de la faim ?",
    "Qui est le plus à même de créer un nouveau cocktail ?",
    "Qui est le moins à même de faire un compliment sincère à un inconnu ?",
    "Qui est le plus susceptible de se tromper de film au cinéma ?",
    "Qui est le moins susceptible de se souvenir du jour où il a rencontré un ami commun ?",
    "Qui a le plus de règles non écrites dans le groupe ?",
    "Qui a le moins de goût pour la nourriture asiatique ?",
    "Qui est le plus susceptible de faire une crise de rire dans un lieu inapproprié ?",
    "Qui est le moins susceptible de dire 'je ne suis pas sûr' ?",
    "Qui est le plus à même de s'occuper d'un animal exotique ?",
    "Qui est le moins à même de faire une bonne impression lors d'une première rencontre ?",
    "Qui est le plus tête en l'air avec les clés ?",
    "Qui est le moins patient avec les jeux d'argent ?",
    "Qui a le plus de photos de lui en train de faire du sport ?",
    "Qui a le moins de respect pour les horaires de travail ?",
    "Qui est le plus susceptible de changer d'avis sur un plat préféré ?",
    "Qui est le moins susceptible de critiquer un cadeau d'anniversaire ?",
    "Qui est le plus à même de construire une cabane en carton ?",
    "Qui est le moins à même de se souvenir du nom du restaurant de la veille ?",
    "Qui est le plus susceptible de se faire amende pour bruit excessif ?",
    "Qui est le moins susceptible de se faire passer pour un expert sur un sujet ?",
    "Qui a le plus de messages qui finissent par 'bisous' ?",
    "Qui a le moins de talent pour la cuisine ?",
    "Qui est le plus susceptible de faire un discours improvisé réussi ?",
    "Qui est le moins susceptible de croire aux théories du complot ?",
    "Qui est le plus mauvais perdant ?",
    "Qui est le moins ponctuel en soirée ?",
    "Qui est le plus drôle sans le vouloir ?",
    "Qui est le plus susceptible ?",
    "Qui est le plus likely à envoyer un message bourré ?",
    "Qui est le moins discret quand il/elle a un crush ?",
    "Qui est le plus fêtard du groupe ?",
    "Qui est le plus drama queen ?",
    "Qui est le moins doué en cuisine ?",
    "Qui est le plus du genre à ghoster quelqu’un ?",
    "Qui est le plus maladroit ?",
    "Qui est le plus jaloux ?",
    "Qui est le moins romantique ?",
    "Qui est le plus honnête, même quand il ne faut pas ?",
    "Qui est le plus en retard à ses rendez-vous ?",
    "Qui est le plus likely à oublier un anniversaire important ?",
    "Qui est le plus paresseux le dimanche ?",
    "Qui est le plus organisé ?",
    "Qui est le plus charmeur ?",
    "Qui est le moins discret après quelques verres ?",
    "Qui est le plus accro à son téléphone ?",
    "Qui est le plus du genre à se remettre avec un ex ?",
    "Qui est le moins patient ?",
    "Qui est le plus généreux ?",
    "Qui est le plus drama ?",
    "Qui est le plus fort pour mentir ?",
    "Qui est le plus tactile ?",
    "Qui est le plus séducteur naturel ?",
    "Qui est le moins doué pour garder un secret ?",
    "Qui est le plus rancunier ?",
    "Qui est le plus likely à faire une bêtise en public ?",
    "Qui est le plus chanceux ?",
    "Qui est le plus mauvais perdant aux jeux à boire ?",
    "Qui est le plus du genre à danser sans gêne ?",
    "Qui est le moins pudique ?",
    "Qui est le plus facilement influençable ?",
    "Qui est le plus likely à se marier en premier ?",
    "Qui est le plus likely à finir millionnaire ?",
    "Qui est le plus du genre à oublier de répondre aux messages ?",
    "Qui est le plus bordélique ?",
    "Qui est le plus mystérieux ?",
    "Qui est le plus romantique ?",
    "Qui est le moins sobre en soirée ?",
    "Qui est le plus du genre à chanter faux mais fort ?",
    "Qui est le plus taquin ?",
    "Qui est le plus du genre à tomber amoureux trop vite ?",
    "Qui est le plus boudeur ?",
    "Qui est le plus susceptible de faire un karaoké improvisé ?",
    "Qui est le plus mauvais menteur ?",
    "Qui est le plus du genre à stalker un crush sur les réseaux ?",
    "Qui est le moins du matin ?",
    "Qui est le plus likely à pleurer devant un film ?",
    "Qui est le plus du genre à oublier où il a mis son téléphone ?",
    "Qui est le plus mignon quand il est en colère ?",
    "Qui est le plus du genre à envoyer le premier message ?",
    "Qui est le plus timide au début ?",
    "Qui est le plus coquin ?",
    "Qui est le plus du genre à faire le premier pas ?",
    "Qui est le plus du genre à se retrouver dans une situation gênante ?",
    "Qui est le plus câlin ?",
    "Qui est le plus du genre à se faire remarquer ?",
    "Qui est le plus du genre à dire 'je t’aime' trop vite ?",
    "Qui est le plus du genre à avoir un crush secret ici ?",
    "Qui est le plus likely à flirter sans s’en rendre compte ?",
    "Qui est le plus du genre à tomber pour quelqu’un interdit ?",
    "Qui est le plus du genre à dormir nu ?",
    "Qui est le plus du genre à envoyer un message risqué ?",
    "Qui est le plus du genre à avoir un dossier gênant sur son téléphone ?",
    "Qui est le plus du genre à draguer juste pour le fun ?",
    "Qui est le plus du genre à séduire sans parler ?",
    "Qui est le plus du genre à s’endormir pendant un film ?",
    "Qui est le plus likely à se réveiller dans un lit inconnu ?",
    "Qui est le plus du genre à avoir déjà eu une histoire avec un ami ?",
    "Qui est le plus du genre à être romantique en secret ?",
    "Qui est le plus du genre à rire dans les pires moments ?",
    "Qui est le plus du genre à perdre ses clés ?",
    "Qui est le plus du genre à parler en dormant ?",
    "Qui est le plus du genre à draguer sans s’en rendre compte ?",
    "Qui est le plus du genre à être en couple juste pour pas être seul ?",
    "Qui est le plus du genre à se lever pour danser ?",
    "Qui est le plus du genre à avoir des goûts bizarres ?",
    "Qui est le plus du genre à s’ennuyer vite ?",
    "Qui est le plus du genre à être romantique à l’ancienne ?",
    "Qui est le plus du genre à oublier un prénom juste après l’avoir entendu ?",
    "Qui est le plus du genre à avoir déjà embrassé deux personnes le même jour ?",
    "Qui est le plus du genre à garder un secret d’amour ?",
    "Qui est le plus du genre à aimer les défis ?",
    "Qui est le plus du genre à faire des blagues coquines ?",
    "Qui est le plus du genre à être le cœur brisé ?",
    "Qui est le plus du genre à envoyer un snap douteux ?",
    "Qui est le plus du genre à avoir déjà flirté avec quelqu’un en couple ?",
    "Qui est le plus du genre à avoir un fantasme secret ?",
    "Qui est le plus du genre à faire tourner les têtes en soirée ?",
    "Qui est le plus du genre à être un faux calme ?",
    "Qui est le plus du genre à draguer par message ?",
    "Qui est le plus du genre à aimer les défis de vérité ou action ?",
    "Qui est le plus du genre à dormir avec quelqu’un sans rien faire ?",
    "Qui est le plus du genre à parler de ses ex ?",
    "Qui est le plus du genre à aimer les câlins plus que le reste ?",
    "Qui est le plus du genre à s’imaginer un futur avec son crush ?",
    "Qui est le plus du genre à se moquer gentiment des autres ?",
    "Qui est le plus du genre à rire à ses propres blagues ?",
    "Qui est le plus du genre à chanter sous la douche ?",
    "Qui est le plus du genre à être accro aux séries ?",
    "Qui est le plus du genre à oublier ses affaires partout ?",
    "Qui est le plus du genre à faire des selfies en toutes circonstances ?",
    "Qui est le plus du genre à se plaindre tout le temps ?",
    "Qui est le plus du genre à raconter des secrets gênants ?",
    "Qui est le plus du genre à être jaloux pour rien ?",
    "Qui est le plus du genre à danser même quand personne ne regarde ?",
    "Qui est le plus du genre à s’endormir partout ?",
    "Qui est le plus du genre à faire des blagues un peu osées ?",
    "Qui est le plus du genre à tout dramatiser ?",
    "Qui est le plus du genre à sourire pour cacher ses émotions ?",
    "Qui est le plus du genre à envoyer des messages coquins ?",
    "Qui est le plus du genre à flirter ouvertement ?",
    "Qui est le plus du genre à oublier les rendez-vous ?",
    "Qui est le plus du genre à être romantique de manière surprenante ?",
    "Qui est le plus du genre à avoir des idées bizarres en soirée ?",
    "Qui est le plus du genre à mentir pour se faire remarquer ?",
    "Qui est le plus du genre à se mettre dans des situations gênantes ?",
    "Qui est le plus du genre à se faire draguer facilement ?",
    "Qui est le plus du genre à se venger de façon subtile ?",
    "Qui est le plus du genre à être charmeur sans s’en rendre compte ?",
    "Qui est le plus du genre à avoir des crushs impossibles ?",
    "Qui est le plus du genre à faire des blagues coquines en soirée ?",
    "Qui est le plus du genre à être le cœur du drama ?",
    "Qui est le plus du genre à jouer la séduction sans le vouloir ?",
    "Qui est le plus du genre à être tactile avec tout le monde ?",
    "Qui est le plus du genre à rire dans les moments gênants ?",
    "Qui est le plus du genre à se moquer gentiment des autres ?",
    "Qui est le plus du genre à parler beaucoup pour éviter le silence ?",
    "Qui est le plus du genre à séduire par le regard ?",
    "Qui est le plus du genre à cacher ses sentiments ?",
    "Qui est le plus du genre à envoyer des messages ambigus ?",
    "Qui est le plus du genre à être charmeur même sans le vouloir ?",
    "Qui est le plus du genre à se mettre dans l’embarras pour attirer l’attention ?",
    "Qui est le plus du genre à être romantique mais discret ?",
    "Qui est le plus du genre à faire des blagues osées au mauvais moment ?",
    "Qui est le plus du genre à faire tourner les têtes malgré lui ?",
    "Qui est le plus du genre à flirter par texto ?",
    "Qui est le plus du genre à envoyer des selfies coquins ?",
    "Qui est le plus du genre à avoir un humour très particulier ?",
    "Qui est le plus du genre à tomber facilement amoureux ?",
    "Qui est le plus du genre à être un peu pervers en secret ?",
    "Qui est le plus du genre à aimer provoquer gentiment ?",
    "Qui est le plus du genre à se retrouver dans des situations compromettantes ?",
    "Qui est le plus du genre à être romantique sans effort ?",
    "Qui est le plus du genre à attirer l’attention sans le vouloir ?",
    "Qui est le plus du genre à être jaloux mais discret ?",
    "Qui est le plus du genre à envoyer des messages coquins par accident ?",
    "Qui est le plus du genre à se sentir gêné facilement ?",
    "Qui est le plus du genre à danser sur des chansons embarrassantes ?",
    "Qui est le plus du genre à faire des blagues un peu salaces ?",
    "Qui est le plus du genre à avoir un crush secret sur quelqu’un ici ?",
    "Qui est le plus du genre à flirter même en public ?",
    "Qui est le plus du genre à être romantique et imprévisible ?",
    "Qui est le plus du genre à être le cœur de l’attention ?",
    "Qui est le plus du genre à séduire sans s’en rendre compte ?",
    "Qui est le plus du genre à aimer provoquer et taquiner ?",
    "Qui est le plus du genre à rire pour cacher son embarras ?",
    "Qui est le plus du genre à être romantique et coquin à la fois ?",
    "Qui est le plus du genre à faire des blagues un peu coquines ?",
    "Qui est le plus du genre à flirter juste pour le fun ?",
    "Qui est le plus du genre à séduire avec un simple regard ?",
    "Qui est le plus du genre à avoir des histoires d’amour compliquées ?",
    "Qui est le plus du genre à être romantique mais mystérieux ?",
    "Qui est le plus du genre à envoyer des messages ambigus pour tester ?",
    "Qui est le plus du genre à être charmeur sans s’en rendre compte ?",
    "Qui est le plus du genre à faire des blagues coquines sans le vouloir ?",
    "Qui est le plus du genre à tomber amoureux trop vite ?",
    "Qui est le plus du genre à séduire par ses gestes ?",
    "Qui est le plus du genre à aimer être le centre de l’attention ?",
    "Qui est le plus du genre à être romantique mais discret ?",
    "Qui est le plus du genre à flirter par humour ?",
    "Qui est le plus du genre à faire des blagues un peu osées ?",
    "Qui est le plus du genre à attirer les regards malgré lui ?",
    "Qui est le plus du genre à envoyer des messages coquins pour s’amuser ?",
    "Qui est le plus du genre à tomber amoureux rapidement ?",
    "Qui est le plus du genre à séduire avec subtilité ?",
    "Qui est le plus du genre à être romantique et joueur ?",
    "Qui est le plus du genre à flirter subtilement ?",
    "Qui est le plus du genre à aimer provoquer gentiment ?",
    "Qui est le plus du genre à séduire sans effort ?",
    "Qui est le plus du genre à faire rire avec ses histoires coquines ?",
    "Qui est le plus du genre à être romantique et charmeur à la fois ?",
    "Qui est le plus du genre à flirter même par accident ?",
    "Qui est le plus du genre à attirer l’attention sans le vouloir ?",
    "Qui est le plus du genre à envoyer des messages coquins mais discrets ?",
    "Qui est le plus du genre à être romantique et surprenant ?",
    "Qui est le plus du genre à séduire par ses mots ?",
    "Qui est le plus du genre à aimer faire tourner les têtes ?",
    "Qui est le plus du genre à flirter avec subtilité ?",
    "Qui est le plus du genre à séduire par ses gestes et regards ?",
    "Qui est le plus du genre à être coquin mais charmant ?",
    "Qui est le plus du genre à être romantique mais joueur ?",
    "Qui est le plus du genre à flirter sans le vouloir ?",
    "Qui est le plus du genre à séduire et taquiner en même temps ?",
    "Qui est le plus du genre à attirer l’attention par son charme ?",
    "Qui est le plus du genre à envoyer des messages coquins pour tester ?",
    "Qui est le plus du genre à être romantique et coquin en même temps ?",
    "Qui est le plus du genre à flirter sans le montrer ?",
    "Qui est le plus du genre à séduire avec humour ?",
    "Qui est le plus du genre à aimer séduire subtilement ?",
    "Qui est le plus du genre à faire des blagues coquines discrètes ?",
    "Qui est le plus du genre à séduire même sans s’en rendre compte ?",
    "Qui est le plus du genre à être romantique et imprévisible ?",
    "Qui est le plus du genre à flirter pour s’amuser ?",
    "Qui est le plus du genre à séduire et provoquer gentiment ?",
    "Qui est le plus du genre à attirer les regards subtilement ?",
    "Qui est le plus du genre à envoyer des messages coquins pour jouer ?",
    "Qui est le plus du genre à séduire avec subtilité et charme ?",
    "Qui est le plus du genre à flirter sans effort ?",
    "Qui est le plus du genre à être romantique et charmeur ?",
    "Qui est le plus du genre à séduire par petites attentions ?",
    "Qui est le plus du genre à flirter en toute discrétion ?",
    "Qui est le plus du genre à séduire avec humour et charme ?",
    "Qui est le plus du genre à être romantique et joueur en même temps ?",
    "Qui est le plus du genre à flirter subtilement pour amuser ?",
    "Qui est le plus du genre à séduire sans s’en rendre compte ?",
    "Qui est le plus du genre à être charmant et coquin à la fois ?",
    "Qui est le plus du genre à flirter pour le plaisir ?",
    "Qui est le plus du genre à séduire avec petites attentions et charme ?",
    "Qui est le plus du genre à flirter discrètement mais efficacement ?",
    "Qui est le plus du genre à séduire et taquiner subtilement ?",
    "Qui est le plus du genre à être romantique et coquin subtilement ?",
    "Qui est le plus du genre à flirter en jouant sur le charme ?",
    "Qui est le plus du genre à séduire avec humour et subtilité ?",
    "Qui est le plus du genre à être charmeur et romantique à la fois ?",
    "Qui est le plus du genre à flirter subtilement pour séduire ?",
    "Qui est le plus du genre à séduire et amuser en même temps ?",
    "Qui est le plus du genre à attirer les regards par son charme ?",
    "Qui est le plus du genre à flirter avec humour et subtilité ?",
    "Qui est le plus du genre à séduire discrètement mais efficacement ?",
    "Qui est le plus du genre à être romantique et coquin à la fois ?",
    "Qui est le plus du genre à flirter subtilement pour amuser ?",
    "Qui est le plus du genre à séduire et taquiner discrètement ?",
    "Qui est le plus du genre à être charmeur et joueur à la fois ?",
    "Qui est le plus du genre à flirter pour séduire subtilement ?",
    "Qui est le plus du genre à séduire avec petites attentions et humour ?",
    "Qui est le plus du genre à flirter discrètement mais efficacement ?",
    "Qui est le plus du genre à séduire et charmer en même temps ?",
    "Qui est le plus du genre à être romantique, coquin et joueur ?",
    "Qui est le plus du genre à flirter subtilement pour séduire ?",
    "Qui est le plus du genre à séduire avec humour et charme subtil ?",
    "Qui est le plus du genre à flirter et séduire discrètement ?",
    "Qui est le plus du genre à attirer l’attention avec subtilité et charme ?",
    "Qui est le plus du genre à flirter et séduire en même temps ?",
    "Qui est le plus du genre à séduire subtilement et efficacement ?",
    "Qui est le plus du genre à être romantique, charmeur et coquin ?",
    "Qui est le plus du genre à flirter pour séduire avec subtilité ?",
    "Qui est le plus du genre à séduire et amuser subtilement ?",
    "Qui est le plus du genre à flirter subtilement et discrètement ?",
    "Qui est le plus du genre à séduire avec humour, charme et subtilité ?",
    "Qui est le plus du genre à flirter et séduire subtilement ?",
    "Qui est le plus du genre à attirer les regards par subtilité et charme ?",
    "Qui est le plus du genre à flirter pour séduire discrètement ?",
    "Qui est le plus du genre à séduire subtilement et charmer ?",
    "Qui est le plus du genre à être romantique, joueur et coquin ?",
    "Qui est le plus susceptible de finir ivre lors d’une soirée ?",
    "Qui est le plus du genre à envoyer un message coquin après quelques verres ?",
    "Qui est le plus likely à oublier ses limites avec l’alcool ?",
    "Qui est le plus du genre à tester une nouvelle drogue juste pour le fun ?",
    "Qui est le plus chaud pour un pari coquin ?",
    "Qui est le plus du genre à flirter après quelques verres ?",
    "Qui est le plus likely à se réveiller dans un lit inconnu ?",
    "Qui est le plus du genre à envoyer un message sexy sans le vouloir ?",
    "Qui est le plus du genre à danser sexy en soirée ?",
    "Qui est le plus likely à finir la soirée complètement ivre ?",
    "Qui est le plus du genre à expérimenter avec la drogue ?",
    "Qui est le plus du genre à se moquer de quelqu’un qui drague mal ?",
    "Qui est le plus du genre à avoir déjà eu une aventure d’un soir ?",
    "Qui est le plus du genre à boire juste pour draguer ?",
    "Qui est le plus likely à envoyer une photo compromettante ?",
    "Qui est le plus du genre à tester des trucs osés au lit ?",
    "Qui est le plus du genre à se réveiller avec un mal de tête ?",
    "Qui est le plus du genre à se faire remarquer en soirée par ses blagues coquines ?",
    "Qui est le plus likely à se faire surprendre en train de flirter ?",
    "Qui est le plus du genre à envoyer un sext à la mauvaise personne ?",
    "Qui est le plus du genre à avoir déjà bu jusqu’à tomber ?",
    "Qui est le plus likely à se retrouver en caleçon dans une piscine ?",
    "Qui est le plus du genre à proposer un jeu sexy en soirée ?",
    "Qui est le plus du genre à avoir essayé un speed-dating coquin ?",
    "Qui est le plus likely à oublier le nom de son partenaire d’un soir ?",
    "Qui est le plus du genre à flirter avec quelqu’un en couple ?",
    "Qui est le plus du genre à boire pour se donner du courage ?",
    "Qui est le plus likely à avoir déjà testé la drogue en soirée ?",
    "Qui est le plus du genre à envoyer un message coquin par accident ?",
    "Qui est le plus du genre à se retrouver nu par accident ?",
    "Qui est le plus likely à draguer quelqu’un à la gueule de bois ?",
    "Qui est le plus du genre à organiser une soirée très alcoolisée ?",
    "Qui est le plus du genre à finir par danser sur la table ?",
    "Qui est le plus likely à se faire griller en train de flirter ?",
    "Qui est le plus du genre à faire des blagues salaces en public ?",
    "Qui est le plus likely à finir par raconter ses fantasmes en soirée ?",
    "Qui est le plus du genre à avoir un crush secret sur un ami ?",
    "Qui est le plus likely à tester un nouveau cocktail dangereux ?",
    "Qui est le plus du genre à envoyer un snap sexy à son crush ?",
    "Qui est le plus du genre à boire plus que prévu lors d’une fête ?",
    "Qui est le plus likely à faire un pari coquin avec un ami ?",
    "Qui est le plus du genre à se réveiller à côté d’une personne inconnue ?",
    "Qui est le plus likely à essayer un nouveau type d’alcool fort ?",
    "Qui est le plus du genre à flirter ouvertement après quelques verres ?",
    "Qui est le plus likely à faire un strip-tease improvisé ?",
    "Qui est le plus du genre à faire un shot juste pour impressionner ?",
    "Qui est le plus likely à se retrouver sur scène à chanter sexy ?",
    "Qui est le plus du genre à goûter toutes les boissons d’une soirée ?",
    "Qui est le plus likely à avoir déjà eu une aventure coquine avec un ami ?",
    "Qui est le plus du genre à envoyer des messages coquins en groupe ?",
    "Qui est le plus likely à finir par confesser ses fantasmes ?",
    "Qui est le plus du genre à avoir déjà flirter dans un lieu public ?",
    "Qui est le plus likely à tester une drogue juste par curiosité ?",
    "Qui est le plus du genre à finir la soirée en dansant de façon sexy ?",
    "Qui est le plus likely à se réveiller avec un tatouage temporaire gênant ?",
    "Qui est le plus du genre à boire pour oublier un ex ?",
    "Qui est le plus likely à faire un strip-tease par défi ?",
    "Qui est le plus du genre à draguer quelqu’un qu’il ne devrait pas ?",
    "Qui est le plus likely à envoyer un message sexy à la mauvaise personne ?",
    "Qui est le plus du genre à boire pour prendre confiance avec quelqu’un ?",
    "Qui est le plus likely à essayer un cocktail très fort juste pour tester ?",
    "Qui est le plus du genre à organiser un jeu sexy en soirée ?",
    "Qui est le plus likely à finir la soirée en chantant des chansons osées ?",
    "Qui est le plus du genre à avoir déjà eu une aventure d’un soir avec un inconnu ?",
    "Qui est le plus likely à tester une drogue pour s’amuser ?",
    "Qui est le plus du genre à flirter après quelques verres sans gêne ?",
    "Qui est le plus likely à faire une blague salace dans un groupe ?",
    "Qui est le plus du genre à envoyer un sext en pleine soirée ?",
    "Qui est le plus likely à oublier où il a laissé son verre ?",
    "Qui est le plus du genre à avoir déjà fait un pari coquin avec un ami ?",
    "Qui est le plus likely à se retrouver dans un lit à plusieurs après une soirée ?",
    "Qui est le plus du genre à boire jusqu’à ne plus se souvenir de rien ?",
    "Qui est le plus likely à finir la soirée en dansant de façon suggestive ?",
    "Qui est le plus du genre à flirter subtilement avec quelqu’un en couple ?",
    "Qui est le plus likely à goûter toutes les boissons disponibles par curiosité ?",
    "Qui est le plus du genre à envoyer des messages coquins par erreur ?",
    "Qui est le plus likely à tenter un pari osé avec de l’alcool ou de la drogue ?",
    "Qui est le plus du genre à finir la soirée en chantant des chansons coquines ?",
    "Qui est le plus likely à tester un nouveau type de boisson alcoolisée très fort ?",
    "Qui est le plus du genre à flirter ouvertement après quelques shots ?",
    "Qui est le plus likely à finir par confesser un fantasme à quelqu’un ?",
    "Qui est le plus du genre à organiser une soirée très sexy et alcoolisée ?",
    "Qui est le plus likely à danser sur la table en plein milieu de la fête ?",
    "Qui est le plus du genre à envoyer un message sexy à son crush après quelques verres ?",
    "Qui est le plus likely à essayer une drogue juste par curiosité ?",
    "Qui est le plus du genre à finir la soirée complètement ivre mais heureux ?",
    "Qui est le plus likely à faire un strip-tease pour amuser le groupe ?",
    "Qui est le plus du genre à flirter avec une personne qu’il ne devrait pas ?",
    "Qui est le plus likely à envoyer un message sexy au mauvais destinataire ?",
    "Qui est le plus du genre à goûter tous les cocktails d’une soirée pour le fun ?",
    "Qui est le plus likely à finir par danser de manière sexy sur de la musique forte ?",
    "Qui est le plus du genre à avoir déjà eu une aventure coquine avec un inconnu ?",
    "Qui est le plus likely à tester un nouveau cocktail dangereux juste pour rigoler ?",
    "Qui est le plus du genre à envoyer un message coquin à tout le groupe ?",
    "Qui est le plus likely à confesser un fantasme lors d’une soirée arrosée ?",
    "Qui est le plus du genre à flirter dans un lieu public juste pour s’amuser ?",
    "Qui est le plus likely à finir la soirée complètement déchaîné après quelques verres ?",
    "Qui est le plus du genre à tester une drogue en soirée sans y penser ?",
    "Qui est le plus likely à envoyer un sext accidentel à la mauvaise personne ?",
    "Qui est le plus du genre à danser de façon sexy juste pour attirer l’attention ?",
    "Qui est le plus likely à finir la soirée en chantant des chansons osées avec le groupe ?",
    "Qui est le plus du genre à flirter ouvertement après quelques verres d’alcool ?",
    "Qui est le plus likely à se réveiller dans un lit inconnu après une fête ?",
    "Qui est le plus du genre à organiser un jeu sexy ou coquin pendant la soirée ?",
    "Qui est le plus likely à goûter tous les alcools disponibles pour tester ?",
    "Qui est le plus du genre à finir la soirée ivre mais heureux avec des amis ?",
    "Qui est le plus likely à faire un pari coquin avec de l’alcool ou de la drogue ?",
    "Qui est le plus du genre à flirter subtilement avec quelqu’un qu’il ne devrait pas ?",
    "Qui est le plus likely à envoyer un message sexy ou coquin sans réfléchir ?",
    "Qui est le plus du genre à danser sur la table après quelques verres ?",
    "Qui est le plus likely à tester un cocktail dangereux juste pour le fun ?",
    "Qui est le plus du genre à finir la soirée complètement déchaîné et coquin ?",
    "Qui est le plus likely à envoyer un sext accidentel à la mauvaise personne ?",
    "Qui est le plus du genre à flirter ouvertement dans un lieu public pour s’amuser ?",
    "Qui est le plus likely à finir la soirée en chantant des chansons coquines avec tout le monde ?",
    "Qui est le plus du genre à organiser une soirée sexy avec alcool et jeux ?",
    "Qui est le plus likely à tester un nouveau type de drogue juste pour l’expérience ?",
    "Qui est le plus du genre à finir ivre mais heureux avec des amis ?",
    "Qui est le plus likely à faire un strip-tease improvisé pour amuser le groupe ?",
    "Qui est le plus du genre à envoyer un message sexy à un crush après quelques verres ?",
    "Qui est le plus likely à flirter avec quelqu’un en couple pour le fun ?",
    "Qui est le plus du genre à goûter tous les cocktails disponibles juste par curiosité ?",
    "Qui est le plus likely à finir la soirée complètement déchaîné après quelques shots ?",
    "Qui est le plus du genre à envoyer des messages coquins par erreur ?",
    "Qui est le plus likely à confesser un fantasme en soirée après quelques verres ?",
    "Qui est le plus du genre à flirter subtilement avec un inconnu ?",
    "Qui est le plus likely à finir la soirée en chantant des chansons osées ?",
    "Qui est le plus du genre à tester un cocktail très fort juste pour rigoler ?",
    "Qui est le plus likely à envoyer un sext accidentel à son crush ?",
    "Qui est le plus du genre à finir la soirée complètement ivre et heureux ?",
    "Qui est le plus likely à organiser un jeu sexy ou coquin pendant la fête ?",
    "Qui est le plus du genre à flirter ouvertement après quelques verres d’alcool ?",
    "Qui est le plus susceptible de ghoster quelqu’un après un premier date ?",
    "Qui est le moins susceptible de dire non à un dernier verre ?",
    "Qui est le plus à même de pleurer devant un film Disney ?",
    "Qui est le moins à même de tenir un secret plus de 24h ?",
    "Qui est le plus susceptible de draguer en étant déjà en couple ?",
    "Qui est le moins susceptible de payer sa tournée ?",
    "Qui est le plus accro aux réseaux sociaux ?",
    "Qui est le moins à même de survivre sans son téléphone une journée ?",
    "Qui est le plus susceptible de mentir sur son âge ?",
    "Qui est le moins susceptible de finir son assiette ?",
    "Qui est le plus à même de faire une crise de jalousie ?",
    "Qui est le moins courageux face à une araignée ?",
    "Qui est le plus susceptible de tricher aux jeux de société ?",
    "Qui est le moins à même de se lever tôt un week-end ?",
    "Qui est le plus susceptible de raconter des potins ?",
    "Qui est le moins susceptible de dire la vérité quand on demande « ça va ? » ?",
    "Qui est le plus à même de se perdre dans sa propre ville ?",
    "Qui est le moins susceptible de refuser un défi stupide ?",
    "Qui est le plus susceptible de rougir en recevant un compliment ?",
    "Qui est le moins à même de garder son calme en embouteillage ?",
    "Qui est le plus susceptible de pleurer de rire pour rien ?",
    "Qui est le moins susceptible de partager sa nourriture ?",
    "Qui est le plus à même de faire des selfies partout ?",
    "Qui est le moins à même de respecter une vitesse limitée ?",
    "Qui est le plus susceptible de chanter faux sous la douche ?",
    "Qui est le moins susceptible de ranger sa chambre ?",
    "Qui est le plus à même de paniquer pour rien ?",
    "Qui est le moins à même de dire non à un dessert ?",
    "Qui est le plus susceptible de flirter avec le serveur/la serveuse ?",
    "Qui est le moins susceptible de finir un livre commencé ?",
    "Qui est le plus à même de faire des blagues nulles ?",
    "Qui est le moins à même de tenir une plante en vie ?",
    "Qui est le plus susceptible de parler tout seul ?",
    "Qui est le moins susceptible de répondre aux messages ?",
    "Qui est le plus à même de dépenser tout son salaire en une soirée ?",
    "Qui est le moins courageux pour aller aux toilettes dans le noir ?",
    "Qui est le plus susceptible de râler pour tout ?",
    "Qui est le moins à même de cuisiner sans recette ?",
    "Qui est le plus à même de se plaindre du froid en été ?",
    "Qui est le moins susceptible de dire merci au livreur ?",
    "Qui est le plus susceptible de faire des grimaces sur les photos ?",
    "Qui est le moins à même de supporter le silence ?",
    "Qui est le plus à même de danser comme personne ne regarde ?",
    "Qui est le moins susceptible de se souvenir des anniversaires ?",
    "Qui est le plus susceptible de manger des chips au petit-déjeuner ?",
    "Qui est le moins à même de faire du sport régulièrement ?",
    "Qui est le plus à même de raconter sa vie à un inconnu ?",
    "Qui est le moins susceptible de prêter de l’argent ?",
    "Qui est le plus susceptible de pleurer en regardant un pub ?",
    "Qui est le moins à même de tenir sa langue quand il est énervé ?",
    "Qui est le plus à même de commander la même chose au resto ?",
    "Qui est le moins susceptible de dire non à un shot ?",
    "Qui est le plus susceptible de se tromper de prénom en flirtant ?",
    "Qui est le moins à même de supporter les épices ?",
    "Qui est le plus à même de faire des listes pour tout ?",
    "Qui est le moins susceptible de ranger son téléphone en soirée ?",
    "Qui est le plus susceptible de se lever pour danser en premier ?",
    "Qui est le moins à même de finir une série sans spoiler ?",
    "Qui est le plus à même de parler dans son sommeil ?",
    "Qui est le moins susceptible de partager ses frites ?",
    "Qui est le plus susceptible de paniquer avant un rendez-vous ?",
    "Qui est le moins à même de respecter un budget ?",
    "Qui est le plus à même de faire des imitations foireuses ?",
    "Qui est le moins susceptible de dire non à un câlin ?",
    "Qui est le plus à même de râler contre la météo ?",
    "Qui est le moins à même de se maquiller/se raser correctement pressé ?",
    "Qui est le plus susceptible de chanter les paroles fausses ?",
    "Qui est le moins susceptible de refuser un pari ?",
    "Qui est le plus à même de pleurer devant un animal mignon ?",
    "Qui est le moins à même de tenir un régime plus de 3 jours ?",
    "Qui est le plus susceptible de faire des blagues racistes sans le vouloir ?",
    "Qui est le moins susceptible de dire la vérité sur son poids ?",
    "Qui est le plus à même de se plaindre d’avoir mal aux pieds ?",
    "Qui est le moins à même de supporter le bruit ?",
    "Qui est le plus susceptible de faire des photos ratées ?",
    "Qui est le moins susceptible de payer l’addition ?",
    "Qui est le plus à même de se lever en dernier ?",
    "Qui est le moins à même de supporter la chaleur ?",
    "Qui est le plus susceptible de raconter des histoires exagérées ?",
    "Qui est le moins susceptible de finir ses restes ?",
    "Qui est le plus à même de faire des crises de rire incontrôlables ?",
    "Qui est le moins à même de dire non à une sieste ?",
    "Qui est le plus susceptible de se faire arnaquer en voyage ?",
    "Qui est le moins susceptible de ranger après une soirée ?",
    "Qui est le plus à même de parler trop fort au téléphone ?",
    "Qui est le moins à même de supporter les enfants ?",
    "Qui est le plus susceptible de manger en cachette ?",
    "Qui est le moins susceptible de dire non à un dessert supplémentaire ?",
    "Qui est le plus à même de râler contre le service au resto ?",
    "Qui est le moins à même de tenir une conversation sérieuse ?",
    "Qui est le plus susceptible de se plaindre d’être fatigué ?",
    "Qui est le moins susceptible de partager son mot de passe Netflix ?",
    "Qui est le plus à même de faire des blagues potaches ?",
    "Qui est le moins à même de supporter les films d’horreur ?",
    "Qui est le plus susceptible de se tromper dans un toast ?",
    "Qui est le moins susceptible de dire non à un câlin de groupe ?",
    "Qui est le plus à même de paniquer pour une deadline ?",
    "Qui est le moins à même de supporter le désordre ?",
    "Qui est le plus susceptible de faire des danses ridicules ?",
    "Qui est le moins susceptible de refuser un gage ?",
    "Qui est le plus à même de pleurer en écoutant une chanson ?",
    "Qui est le moins à même de tenir sa résolution du nouvel an ?"
];