let words = [
    "Tu préfères ne plus jamais avoir internet ou ne plus jamais prendre l’avion ?",
    "Tu préfères être toujours en retard de 10 minutes ou toujours en avance de 20 minutes ?",
    "Tu préfères parler toutes les langues du monde ou parler avec les animaux ?",
    "Tu préfères ne jamais dormir ou ne jamais manger (sans conséquence sur ta santé) ?",
    "Tu préfères savoir lire dans les pensées ou pouvoir te téléporter ?",
    "Tu préfères avoir une mémoire parfaite ou pouvoir oublier ce que tu veux ?",
    "Tu préfères avoir une vie sans musique ou une vie sans films/séries ?",
    "Tu préfères vivre dans le futur ou revivre dans le passé ?",
    "Tu préfères devenir invisible ou voler ?",
    "Tu préfères toujours dire la vérité ou toujours mentir ?",
    "Tu préfères ne plus jamais utiliser ton téléphone ou ne plus jamais regarder la TV/Netflix ?",
    "Tu préfères avoir chaud tout le temps ou avoir froid tout le temps ?",
    "Tu préfères vivre sans réseaux sociaux ou vivre sans jeux vidéo ?",
    "Tu préfères manger uniquement sucré ou uniquement salé ?",
    "Tu préfères avoir une maison immense loin de tout ou un petit appartement en plein centre-ville ?",
    "Tu préfères perdre ton argent ou perdre tous tes souvenirs ?",
    "Tu préfères avoir une journée de 48h ou dormir seulement 2h par nuit sans jamais être fatigué ?",
    "Tu préfères être riche et malheureux ou pauvre et heureux ?",
    "Tu préfères avoir toujours la même chanson coincée dans la tête ou ne plus jamais pouvoir écouter de musique ?",
    "Tu préfères voyager partout gratuitement ou manger gratuitement partout ?",
    "Tu préfères avoir un super pouvoir inutile (comme changer la couleur de tes cheveux par pensée) ou pas de pouvoir du tout ?",
    "Tu préfères ne plus jamais avoir mal physiquement ou ne plus jamais avoir mal émotionnellement ?",
    "Tu préfères avoir un clone de toi ou un robot qui fait tout à ta place ?",
    "Tu préfères connaître ton futur ou oublier ton passé ?",
    "Tu préfères perdre ton sens du goût ou ton sens de l’ouïe ?",
    "Tu préfères vivre sans miroir ou sans appareil photo ?",
    "Tu préfères pouvoir parler avec ton animal de compagnie ou pouvoir parler avec ton moi du futur ?",
    "Tu préfères ne plus jamais avoir de pub YouTube ou ne plus jamais avoir de pub dans la rue ?",
    "Tu préfères avoir une mauvaise réputation mais être riche ou être fauché mais admiré de tous ?",
    "Tu préfères manger la même chose toute ta vie ou ne jamais manger deux fois la même chose ?",
    "Tu préfères ne jamais te perdre ou ne jamais tomber malade ?",
    "Tu préfères que tout ce que tu dis devienne vrai ou que tu puisses annuler une action passée chaque jour ?",
    "Tu préfères avoir une voiture de luxe mais jamais de permis, ou un vieux vélo mais toutes les routes libres pour toi ?",
    "Tu préfères dormir dans un lit super confortable mais froid, ou un lit dur mais chaud ?",
    "Tu préfères avoir des cheveux qui poussent instantanément ou des ongles qui ne poussent jamais ?",
    "Tu préfères pouvoir mettre pause au temps ou l’accélérer ?",
    "Tu préfères savoir quand tu vas mourir ou savoir comment tu vas mourir ?",
    "Tu préfères qu’on lise tes messages privés ou qu’on voit ton historique internet ?",
    "Tu préfères avoir un rire très bizarre ou ne jamais rire ?",
    "Tu préfères être le plus drôle ou le plus intelligent de ton groupe d’amis ?",
    "Tu préfères ne plus jamais ressentir la faim ou la soif ?",
    "Tu préfères ne jamais avoir de travail ou devoir travailler 7j/7 ?",
    "Tu préfères vivre sans musique ou vivre sans livres ?",
    "Tu préfères que ton téléphone n’ait plus jamais de batterie ou que ton Wi-Fi tombe en panne 1h par jour ?",
    "Tu préfères que tout soit gratuit dans un seul magasin de ton choix ou gagner 1000€ par mois à vie ?",
    "Tu préfères perdre ton sens de l’humour ou perdre ton charisme ?",
    "Tu préfères être bloqué une semaine dans un ascenseur ou une semaine dans une grotte ?",
    "Tu préfères avoir une voix trop forte ou une voix trop faible ?",
    "Tu préfères vivre dans un film d’action ou dans une comédie romantique ?",
    "Tu préfères que tout le monde t’oublie après 24h ou que personne ne t’oublie jamais ?",
    "Tu préfères être tout le temps chanceux au jeu ou tout le temps chanceux en amour ?",
    "Tu préfères manger une pizza à chaque repas ou ne jamais pouvoir en manger ?",
    "Tu préfères toujours transpirer énormément ou avoir toujours froid ?",
    "Tu préfères être célèbre mais haï, ou inconnu mais adoré de ton entourage ?",
    "Tu préfères être bloqué dans le temps ou voyager dans le futur sans retour ?",
    "Tu préfères vivre 200 ans mais seul ou 50 ans entouré d’amis et famille ?",
    "Tu préfères que tout le monde sache ce que tu penses ou ne jamais pouvoir parler ?",
    "Tu préfères qu’il pleuve toujours ou qu’il fasse toujours très chaud ?",
    "Tu préfères avoir toujours 10% de batterie ou toujours 10% d’essence ?",
    "Tu préfères manger uniquement des pâtes ou uniquement du riz toute ta vie ?",
    "Tu préfères ne jamais pouvoir t’asseoir ou ne jamais pouvoir courir ?",
    "Tu préfères dormir à chaque fois que tu t’ennuies ou rire à chaque fois que tu es stressé ?",
    "Tu préfères ne pas avoir de miroir ou ne pas avoir de téléphone ?",
    "Tu préfères que ton voisin soit ton meilleur ami ou une célébrité ?",
    "Tu préfères pouvoir voler mais lentement ou courir à 200 km/h ?",
    "Tu préfères avoir des super oreilles ou une super vue ?",
    "Tu préfères être capable de contrôler les rêves des autres ou leurs souvenirs ?",
    "Tu préfères avoir une maison flottante ou une maison sous terre ?",
    "Tu préfères te réveiller toujours en pleine forme ou ne jamais être fatigué ?",
    "Tu préfères être tout le temps dans un film d’horreur ou tout le temps dans un jeu vidéo ?",
    "Tu préfères parler toutes les langues mortes ou toutes les langues vivantes ?",
    "Tu préfères pouvoir voyager dans le temps mais pas contrôler la date, ou voyager dans l’espace mais pas contrôler la destination ?",
    "Tu préfères avoir un animal de compagnie dragon ou phénix ?",
    "Tu préfères vivre sans argent ou vivre sans amis ?",
    "Tu préfères qu’on sache toujours où tu es ou qu’on sache toujours ce que tu fais ?",
    "Tu préfères voir le futur de 10 minutes ou de 10 ans ?",
    "Tu préfères que tout soit écrit comme un livre ou que tout soit filmé comme un film ?",
    "Tu préfères dormir 20h par jour ou seulement 2h ?",
    "Tu préfères que tout ce que tu dessines devienne réel ou que tout ce que tu racontes devienne vrai ?",
    "Tu préfères ne plus jamais avoir faim ou ne plus jamais être fatigué ?",
    "Tu préfères vivre dans un monde sans chocolat ou sans fromage ?",
    "Tu préfères toujours porter un pyjama ou toujours porter un costume ?",
    "Tu préfères ne jamais avoir de problème de santé ou ne jamais avoir de problème d’argent ?",
    "Tu préfères avoir une maison en glace ou en feu (protégé évidemment) ?",
    "Tu préfères que ton rire soit un bruit bizarre ou que tu ne puisses jamais rire ?",
    "Tu préfères que chaque fois que tu parles une chanson démarre, ou chaque fois que tu marches des applaudissements retentissent ?",
    "Tu préfères être réveillé chaque matin par une sirène ou ne jamais savoir quand tu dois te réveiller ?",
    "Tu préfères avoir des bras très longs ou des jambes très courtes ?",
    "Tu préfères nager dans la lave (protégé) ou voler dans une tornade ?",
    "Tu préfères que tout soit en noir et blanc sauf une couleur ou que chaque jour une couleur disparaisse ?",
    "Tu préfères parler comme un robot ou marcher comme un pingouin ?",
    "Tu préfères avoir des cheveux fluorescents ou des yeux qui changent de couleur ?",
    "Tu préfères ne plus jamais pouvoir rire ou rire à chaque fois qu’on parle sérieusement ?",
    "Tu préfères vivre dans un monde sans internet ou sans électricité ?",
    "Tu préfères que tout le monde connaisse ton secret le plus honteux ou que tu connaisses celui de tout le monde ?",
    "Tu préfères avoir toujours du sable dans tes chaussures ou de l’eau dans tes poches ?",
    "Tu préfères ne jamais te doucher ou ne jamais te brosser les dents ?",
    "Tu préfères ne plus jamais voir la nuit ou ne plus jamais voir le jour ?",
    "Tu préfères avoir une moustache qui pousse en 1 minute ou des cheveux qui repoussent en 1 seconde ?",
    "Tu préfères avoir un pouvoir aléatoire chaque jour ou garder un seul pouvoir à vie ?",
    "Tu préfères être coincé dans un ascenseur avec 3 inconnus ou marcher seul dans un tunnel sombre ?",
    "Tu préfères que tout le monde se souvienne de ton anniversaire ou que personne ne s’en souvienne jamais ?",
    "Tu préfères pouvoir sauter très haut ou courir très vite ?",
    "Tu préfères parler comme un bébé ou marcher comme une grenouille ?",
    "Tu préfères que tout soit en ralenti ou tout en accéléré ?",
    "Tu préfères manger un insecte vivant ou boire un verre de lait périmé ?",
    "Tu préfères toujours parler en rimes ou toujours chanter tes phrases ?",
    "Tu préfères que ta vie soit un film comique ou un film dramatique ?",
    "Tu préfères pouvoir lire 1000 pages en 1h ou écrire 1000 mots en 1h ?",
    "Tu préfères que chaque fois que tu éternues il pleuve, ou que chaque fois que tu bâilles il y ait du tonnerre ?",
    "Tu préfères être connu dans un petit village ou inconnu dans une grande ville ?",
    "Tu préfères manger froid toute ta vie ou manger brûlant toute ta vie ?",
    "Tu préfères que ton téléphone sonne fort à chaque notif ou ne jamais avoir de notif sonore ?",
    "Tu préfères toujours tomber quand tu cours ou toujours tomber quand tu marches ?",
    "Tu préfères que ton ombre disparaisse ou que ton reflet disparaisse ?",
    "Tu préfères toujours avoir un chewing-gum collé sous ta chaussure ou toujours avoir de la boue sur ton pantalon ?",
    "Tu préfères avoir toujours faim ou toujours sommeil ?",
    "Tu préfères être bloqué dans un monde de jeux vidéo rétro ou dans un monde de dessins animés ?",
    "Tu préfères vivre dans une comédie musicale ou dans un film d’action ?",
    "Tu préfères avoir les dents qui brillent dans le noir ou les yeux qui font lampe torche ?",
    "Tu préfères ne jamais avoir froid en hiver ou ne jamais avoir chaud en été ?",
    "Tu préfères que ton prénom soit oublié par tout le monde ou qu’on t’appelle par un mauvais prénom toute ta vie ?",
    "Tu préfères avoir un animal qui parle ou un objet qui parle ?",
    "Tu préfères vivre dans un monde où tout flotte ou où tout colle ?",
    "Tu préfères que ton rire ressemble à une sirène ou à une voiture qui démarre ?",
    "Tu préfères manger des chips sans fin ou boire du soda sans fin ?",
    "Tu préfères que ton téléphone tombe toujours par terre ou que tes écouteurs s’emmêlent toujours ?",
    "Tu préfères ne jamais pouvoir fermer les yeux ou ne jamais pouvoir les ouvrir ?",
    "Tu préfères toujours avoir des chaussures trop petites ou des vêtements trop grands ?",
    "Tu préfères que chaque fois que tu parles une bulle de BD apparaisse au-dessus de ta tête ou que chaque fois que tu marches des sous-titres apparaissent ?",
    "Tu préfères embrasser ton pire ennemi ou embrasser ton ex devant tout le monde ?",
    "Tu préfères envoyer un nude à la mauvaise personne ou en recevoir un d’un inconnu ?",
    "Tu préfères être surpris par tes parents en plein acte ou surprendre tes parents ?",
    "Tu préfères coucher avec ton prof ou avec ton boss ?",
    "Tu préfères ne plus jamais avoir de relations sexuelles ou ne plus jamais embrasser quelqu’un ?",
    "Tu préfères être vu nu par toute ta classe ou voir toute ta classe nue ?",
    "Tu préfères que tout le monde connaisse ton historique de navigation ou tes conversations privées ?",
    "Tu préfères coucher sans sentiments ou avoir des sentiments sans jamais coucher ?",
    "Tu préfères avoir une sextape qui fuite ou une conversation gênante qui fuite ?",
    "Tu préfères être coincé·e une nuit entière avec ton ex ou avec la personne que tu détestes le plus ?",
    "Tu préfères embrasser un inconnu devant tes amis ou embrasser ton ex devant ta famille ?",
    "Tu préfères avoir toujours du désir mais pas de partenaire, ou avoir un partenaire sans désir ?",
    "Tu préfères perdre tous tes sextos ou perdre toutes tes photos de vacances ?",
    "Tu préfères coucher dans un endroit public ou dans un endroit sale ?",
    "Tu préfères que tes parents lisent tes sextos ou que tes grands-parents les lisent ?",
    "Tu préfères coucher avec un inconnu masqué ou ton/ta meilleur·e ami·e ?",
    "Tu préfères avoir une panne sexuelle ou faire semblant toute ta vie ?",
    "Tu préfères coucher avec quelqu’un de beaucoup plus vieux ou de beaucoup plus jeune (majeur bien sûr) ?",
    "Tu préfères ne jamais avoir d’orgasme ou donner toujours de faux orgasmes ?",
    "Tu préfères qu’on te filme pendant l’acte ou qu’on te regarde en direct ?",
    "Tu préfères avoir une relation d’un soir avec ton crush ou une relation longue sans sexe ?",
    "Tu préfères que tes sextos soient projetés en classe ou au boulot ?",
    "Tu préfères coucher avec la lumière allumée ou toujours dans le noir complet ?",
    "Tu préfères ne jamais pouvoir te masturber ou ne jamais pouvoir coucher ?",
    "Tu préfères faire l’amour dans une voiture ou dans des toilettes publiques ?",
    "Tu préfères coucher avec un inconnu bourré ou sobre mais gênant ?",
    "Tu préfères embrasser ton/ta meilleur·e ami·e ou ton pire ennemi ?",
    "Tu préfères que tes parents te surprennent en train de te masturber ou de coucher ?",
    "Tu préfères avoir une sextape sur internet ou une vidéo où tu chantes faux ?",
    "Tu préfères coucher avec deux inconnus en même temps ou ne jamais le faire ?",
    "Tu préfères avoir une relation sexuelle qui dure 5 secondes ou 5 heures ?",
    "Tu préfères coucher avec ton ex une dernière fois ou ne jamais recoucher de ta vie ?",
    "Tu préfères être infidèle une fois ou être cocu toute ta vie ?",
    "Tu préfères que tout le monde pense que tu es mauvais au lit ou que tout le monde sache que tu es excellent ?",
    "Tu préfères embrasser quelqu’un avec une haleine horrible ou embrasser quelqu’un qui bave énormément ?",
    "Tu préfères coucher dans un lit rempli de sable ou rempli de miettes de chips ?",
    "Tu préfères coucher avec quelqu’un qui parle trop ou qui ne dit jamais un mot ?",
    "Tu préfères coucher avec ton crush mais qu’il/elle te ghost après ou ne jamais essayer ?",
    "Tu préfères avoir une panne devant 1 personne ou devant 100 ?",
    "Tu préfères envoyer un sext à ton prof ou à ta mère ?",
    "Tu préfères embrasser quelqu’un après qu’il/elle ait vomi ou après qu’il/elle ait mangé de l’ail cru ?",
    "Tu préfères ne jamais avoir de préliminaires ou ne jamais avoir de pénétration ?",
    "Tu préfères coucher tous les jours sans plaisir ou une fois par an avec le meilleur plaisir de ta vie ?",
    "Tu préfères que ton/ta partenaire gémisse trop fort ou pas du tout ?",
    "Tu préfères coucher avec quelqu’un qui sent très mauvais ou qui ne se lave jamais les dents ?",
    "Tu préfères avoir une relation cachée avec ton prof ou publique avec ton pire crush ?",
    "Tu préfères avoir ton prénom tatoué sur ton/ta partenaire ou le sien tatoué sur toi ?",
    "Tu préfères coucher devant un miroir géant ou sous une caméra thermique ?",
    "Tu préfères coucher avec ton voisin ou avec ton/ta collègue ?",
    "Tu préfères avoir une réputation de chaud lapin sans raison ou être un génie au lit sans que personne ne le sache ?",
    "Tu préfères faire un strip-tease à ton/ta partenaire ou en public devant des inconnus ?",
    "Tu préfères te réveiller nu dans un lit inconnu ou te réveiller habillé mais menotté au lit ?",
    "Tu préfères avoir un orgasme en public ou avoir un fou rire en plein acte ?",
    "Tu préfères que tout le monde entende tes gémissements ou que tout le monde lise tes sextos ?",
    "Tu préfères coucher dans un lit trempé ou dans un lit rempli de poils d’animaux ?",
    "Tu préfères coucher avec quelqu’un qui parle de son ex en plein acte ou qui t’appelle par le mauvais prénom ?",
    "Tu préfères coucher en plein jour dehors ou en pleine nuit dans un cimetière ?",
    "Tu préfères embrasser quelqu’un avec un appareil dentaire plein de nourriture ou quelqu’un avec les dents jaunes ?",
    "Tu préfères coucher avec ton premier amour ou avec ton dernier crush ?",
    "Tu préfères avoir une relation d’un soir avec ton prof ou ton patron ?",
    "Tu préfères que ta sextape devienne virale ou qu’un fou rire gênant au lit devienne viral ?",
    "Tu préfères coucher une seule fois avec une célébrité ou toute ta vie avec un inconnu ?",
    "Tu préfères que ton/ta partenaire rie de toi nu ou qu’il/elle pleure après l’acte ?",
    "Tu préfères coucher avec un masque ou déguisé en personnage ridicule ?",
    "Tu préfères coucher avec quelqu’un qui raconte sa vie ou qui ne fait aucun bruit ?",
    "Tu préfères ne jamais pouvoir dire non ou que tout le monde dise toujours non ?",
    "Tu préfères faire l’amour sous la pluie ou dans le sable ?",
    "Tu préfères coucher dans une chambre avec miroir au plafond ou avec caméra ?",
    "Tu préfères que ta première fois soit filmée ou commentée par tes amis ?",
    "Tu préfères avoir un orgasme silencieux ou un orgasme qui réveille tout l’immeuble ?",
    "Tu préfères que ton/ta partenaire parle de son ex pendant l’acte ou qu’il/elle rigole de ton corps ?",
    "Tu préfères être interrompu·e par ton coloc ou par tes parents ?",
    "Tu préfères coucher avec ton ex en secret ou ne jamais coucher pendant un an ?",
    "Tu préfères coucher avec ton/ta crush mais qu’il/elle parle de son ex ou ne jamais coucher avec ?",
    "Tu préfères être nu devant toute ta famille ou devant toute ta classe ?",
    "Tu préfères avoir un orgasme à chaque fois que tu éternues ou ne jamais en avoir ?",
    "Tu préfères que ton/ta partenaire s’endorme après 2 minutes ou qu’il/elle dure 5 heures ?",
    "Tu préfères que ta sextape fuite à ta fac ou à ton travail ?",
    "Tu préfères coucher dans un avion ou dans un train ?",
    "Tu préfères embrasser un inconnu en public ou ton ex en secret ?",
    "Tu préfères que tout le monde pense que tu es puceau/pucelette ou que tout le monde pense que tu es addict au sexe ?",
    "Tu préfères ne jamais pouvoir embrasser ou ne jamais pouvoir caresser ?",
    "Tu préfères coucher dans un parc ou dans un ascenseur ?",
    "Tu préfères qu’on te surprenne en train de mater du porno ou en train de te masturber ?",
    "Tu préfères coucher avec ton crush ivre ou sobre mais maladroit·e ?",
    "Tu préfères que tes sextos soient projetés à ta famille ou à tes profs ?",
    "Tu préfères coucher avec quelqu’un qui pleure ou qui rigole pendant l’acte ?",
    "Tu préfères coucher dans un lit plein de miettes ou plein de sueur ?",
    "Tu préfères qu’on se moque de ton corps ou de ta performance ?",
    "Tu préfères coucher dans un jacuzzi public ou dans des toilettes de boîte ?",
    "Tu préfères embrasser ton/ta prof ou ton/ta boss devant tout le monde ?",
    "Tu préfères coucher avec quelqu’un qui sent mauvais ou qui fait du bruit bizarre ?",
    "Tu préfères que ton prénom soit crié par erreur ou que ton ex soit appelé ?",
    "Tu préfères coucher dans la voiture de tes parents ou dans leur lit ?",
    "Tu préfères avoir un orgasme ridicule ou aucun orgasme du tout ?",
    "Tu préfères coucher avec ton ex par dépit ou ne jamais coucher pendant 2 ans ?",
    "Tu préfères être aimé mais incompris, ou compris mais jamais aimé ?",
    "Tu préfères vivre heureux dans l’ignorance ou malheureux avec toute la vérité ?",
    "Tu préfères sauver une seule personne que tu aimes ou cent inconnus ?",
    "Tu préfères mourir jeune en ayant marqué l’histoire ou vivre vieux mais oublié ?",
    "Tu préfères pardonner facilement et souffrir ou ne jamais pardonner et être seul ?",
    "Tu préfères perdre tous tes souvenirs heureux ou garder uniquement tes souvenirs tristes ?",
    "Tu préfères être libre mais pauvre, ou riche mais prisonnier de ton travail ?",
    "Tu préfères être craint ou respecté ?",
    "Tu préfères vivre dans un monde sans art ou sans science ?",
    "Tu préfères suivre ton cœur ou ta raison ?",
    "Tu préfères être honnête et perdre des amis ou mentir pour les garder ?",
    "Tu préfères toujours faire passer les autres avant toi ou toujours passer avant les autres ?",
    "Tu préfères échouer en essayant ou réussir sans effort ?",
    "Tu préfères vivre une vie courte mais intense ou longue mais monotone ?",
    "Tu préfères ne jamais savoir si quelqu’un t’aime vraiment ou toujours douter de toi ?",
    "Tu préfères être heureux seul ou malheureux entouré ?",
    "Tu préfères que ton nom soit oublié ou qu’il soit détesté mais jamais effacé ?",
    "Tu préfères vivre dans un monde d’égalité parfaite mais sans liberté, ou un monde libre mais injuste ?",
    "Tu préfères aider une personne que tu connais ou dix inconnus ?",
    "Tu préfères être trahi par un ami ou par ta famille ?",
    "Tu préfères toujours dire ce que tu penses ou ne jamais pouvoir dire ce que tu penses ?",
    "Tu préfères avoir raison seul ou avoir tort avec tout le monde ?",
    "Tu préfères mourir pour une cause ou vivre pour toi-même ?",
    "Tu préfères voir le futur ou changer ton passé ?",
    "Tu préfères être jugé sur tes erreurs ou sur tes intentions ?",
    "Tu préfères vivre sans jamais aimer ou aimer mais ne jamais être aimé en retour ?",
    "Tu préfères être riche matériellement ou riche intérieurement ?",
    "Tu préfères que le monde soit gouverné par la logique ou par l’empathie ?",
    "Tu préfères tout oublier chaque nuit ou te souvenir de tout à jamais ?",
    "Tu préfères être l’ami fidèle de quelqu’un ou l’amour de sa vie mais éphémère ?",
    "Tu préfères être l’auteur d’un mensonge qui sauve ou de la vérité qui détruit ?",
    "Tu préfères renoncer à tes rêves pour tes proches ou poursuivre tes rêves en les perdant ?",
    "Tu préfères être toujours heureux mais superficiel ou toujours triste mais profond ?",
    "Tu préfères vivre dans un monde sans guerre ou un monde sans pauvreté ?",
    "Tu préfères être courageux et mourir jeune ou lâche et vivre longtemps ?",
    "Tu préfères ne jamais douter ou toujours douter ?",
    "Tu préfères vivre dans le silence éternel ou dans le bruit constant ?",
    "Tu préfères ne jamais commettre d’injustice ou ne jamais subir d’injustice ?",
    "Tu préfères être spectateur de ta vie ou acteur sans contrôle ?",
    "Tu préfères vivre pour laisser une trace ou juste pour profiter du moment ?",
    "Tu préfères aider les autres mais ne jamais t’aider toi-même, ou l’inverse ?",
    "Tu préfères croire en quelque chose de faux ou ne croire en rien ?",
    "Tu préfères vivre dans un monde totalement rationnel ou totalement spirituel ?",
    "Tu préfères avoir le pouvoir de sauver une vie par jour ou d’améliorer mille vies légèrement ?",
    "Tu préfères que les autres te voient comme tu es vraiment ou comme tu voudrais être vu ?",
    "Tu préfères sacrifier ton bonheur pour la paix mondiale ou sacrifier la paix mondiale pour ton bonheur ?",
    "Tu préfères être tolérant avec tous mais incompris, ou être compris mais intolérant ?",
    "Tu préfères vivre dans un monde sans mort ou dans un monde sans naissance ?",
    "Tu préfères mourir en héros ou vivre en lâche ?",
    "Tu préfères changer le destin d’une seule personne ou influencer légèrement toute l’humanité ?",
    "Tu préfères être riche de temps ou riche d’argent ?",
    "Tu préfères être toujours jugé par les autres ou ne jamais être vu ?",
    "Tu préfères savoir exactement combien de temps il te reste à vivre ou ne jamais savoir ?",
    "Tu préfères avoir une vie stable et vide ou instable mais pleine d’expériences ?",
    "Tu préfères perdre la capacité d’aimer ou la capacité de penser ?",
    "Tu préfères que ton bonheur dépende des autres ou que celui des autres dépende de toi ?",
    "Tu préfères vivre dans un mensonge confortable ou dans une vérité douloureuse ?",
    "Tu préfères être un génie incompris ou une personne simple aimée de tous ?",
    "Tu préfères avoir le pouvoir d’effacer la haine ou d’amplifier l’amour ?",
    "Tu préfères que la justice soit absolue ou que le pardon soit universel ?",
    "Tu préfères toujours être trop honnête ou trop hypocrite ?",
    "Tu préfères savoir tout sur le monde ou tout sur toi-même ?",
    "Tu préfères être spectateur de la beauté ou acteur du changement ?",
    "Tu préfères vivre dans un monde sans mensonges ou dans un monde sans vérités ?",
    "Tu préfères avoir la liberté totale mais pas de sécurité, ou une sécurité totale sans liberté ?",
    "Tu préfères vivre une vie simple et tranquille ou une vie extraordinaire mais compliquée ?",
    "Tu préfères être maître de ton destin ou esclave de tes passions ?",
    "Tu préfères qu’on se souvienne de toi pour ta bonté ou pour ton intelligence ?",
    "Tu préfères pardonner une trahison ou la venger ?",
    "Tu préfères savoir tout ce que pensent les gens de toi ou qu’ils sachent tout ce que tu penses ?",
    "Tu préfères mourir sans regrets ou vivre avec des remords ?",
    "Tu préfères sacrifier ton avenir pour ton passé ou ton passé pour ton avenir ?",
    "Tu préfères être guidé par la peur ou par l’amour ?",
    "Tu préfères sauver la vie d’un enfant ou celle d’un vieillard sage ?",
    "Tu préfères vivre en suivant les règles ou en créant les tiennes ?",
    "Tu préfères être libre seul ou prisonnier avec tous ?",
    "Tu préfères changer le monde mais ne jamais être reconnu ou être reconnu sans rien changer ?",
    "Tu préfères perdre ta dignité ou perdre tes proches ?",
    "Tu préfères être totalement sincère ou totalement mystérieux ?",
    "Tu préfères toujours choisir le bien commun au détriment de ton bonheur ou l’inverse ?",
    "Tu préfères être en paix mais insignifiant ou tourmenté mais important ?",
    "Tu préfères donner la vie ou sauver une vie ?",
    "Tu préfères être aimé pour ce que tu n’es pas ou détesté pour ce que tu es ?",
    "Tu préfères que le monde soit entièrement juste mais triste, ou injuste mais joyeux ?",
    "Tu préfères toujours sacrifier ou toujours recevoir ?",
    "Tu préfères vivre en cherchant le sens ou en profitant sans chercher ?",
    "Tu préfères ne jamais douter de toi ou ne jamais douter des autres ?",
    "Tu préfères avoir la sagesse sans le bonheur ou le bonheur sans la sagesse ?",
    "Tu préfères toujours dire la vérité qui blesse ou un mensonge qui rassure ?",
    "Tu préfères vivre pour toi ou vivre pour les autres ?",
    "Tu préfères souffrir en aimant ou ne jamais souffrir mais ne jamais aimer ?",
    "Tu préfères être un modèle moral mais pauvre, ou riche et immoral ?",
    "Tu préfères vivre une vie banale mais sans douleur ou une vie marquée par la souffrance et la grandeur ?",
    "Tu préfères changer une décision passée ou en garantir une future ?",
    "Tu préfères être fidèle à tes valeurs mais seul, ou compromis et entouré ?",
    "Tu préfères vivre avec la culpabilité ou avec l’oubli ?",
    "Tu préfères être admiré par beaucoup ou aimé profondément par un seul ?",
    "Tu préfères que l’humanité survive sans toi ou que toi tu survives sans l’humanité ?",
    "Tu préfères chercher éternellement des réponses ou ne jamais poser de questions ?",
    "Tu préfères être ivre mort devant tes parents ou sobre quand tous tes amis sont défoncés ?",
    "Tu préfères avoir une gueule de bois 7 jours de suite ou ne jamais plus pouvoir boire ?",
    "Tu préfères oublier toute ta soirée parce que tu as trop bu ou te souvenir de tout mais avoir fait la honte ?",
    "Tu préfères boire un verre de vodka pur ou fumer un joint seul devant tout le monde ?",
    "Tu préfères vomir dans un taxi ou vomir sur ton crush ?",
    "Tu préfères boire de l’alcool frelaté ou fumer un joint trempé dans de la bière ?",
    "Tu préfères boire un shooter inconnu ou goûter une drogue dont tu ignores les effets ?",
    "Tu préfères être toujours trop bourré ou jamais assez ?",
    "Tu préfères que tout le monde te voie nu bourré ou qu’on te filme en train de fumer ?",
    "Tu préfères boire avec tes parents ou avec tes profs ?",
    "Tu préfères finir la soirée à l’hôpital ou au poste de police ?",
    "Tu préfères avoir une gueule de bois pendant une semaine ou rester sobre toute ta vie ?",
    "Tu préfères dire tous tes secrets quand tu es bourré ou devenir violent quand tu es bourré ?",
    "Tu préfères embrasser ton ex bourré·e ou un inconnu défoncé ?",
    "Tu préfères qu’on poste une vidéo de toi en train de danser bourré ou de toi en train de rouler un joint ?",
    "Tu préfères ne jamais avoir d’effets en buvant ou toujours avoir une énorme gueule de bois ?",
    "Tu préfères boire un litre de tequila cul sec ou fumer 5 joints d’affilée ?",
    "Tu préfères oublier ton nom ou oublier ton adresse quand tu es bourré ?",
    "Tu préfères dormir dehors bourré·e ou dormir chez ton ex défoncé·e ?",
    "Tu préfères être toujours le premier KO en soirée ou toujours le dernier debout mais seul ?",
    "Tu préfères embrasser quelqu’un avec une haleine d’alcool ou avec une haleine de weed ?",
    "Tu préfères perdre un pari et devoir boire un mélange dégueu ou fumer quelque chose de louche ?",
    "Tu préfères être connu comme l’alcoolique du groupe ou comme le toxico du groupe ?",
    "Tu préfères qu’on t’offre une soirée open bar ou une soirée open joint ?",
    "Tu préfères tomber par terre ivre devant ton crush ou dire une énormité sous drogue devant lui/elle ?",
    "Tu préfères que tes parents trouvent ton stock d’alcool ou ton stock de drogue ?",
    "Tu préfères boire seul tous les jours ou fumer seul tous les jours ?",
    "Tu préfères être toujours trop sobre en soirée ou toujours trop défoncé ?",
    "Tu préfères que ton boss te voie bourré en boîte ou que ton prof te voie fumer ?",
    "Tu préfères embrasser un inconnu bourré ou partager un joint avec un inconnu ?",
    "Tu préfères avoir la mémoire effacée par l’alcool ou avoir des hallucinations par la drogue ?",
    "Tu préfères avoir une gueule de bois en plein examen ou être stone à un entretien d’embauche ?",
    "Tu préfères boire un verre piégé par tes potes ou rouler pour tout le monde avec du tabac moisi ?",
    "Tu préfères boire jusqu’à ne plus marcher ou fumer jusqu’à ne plus parler ?",
    "Tu préfères être bourré dès une gorgée ou résister à 10 litres sans effets ?",
    "Tu préfères finir une soirée au lit avec ton ex bourré·e ou avec un inconnu défoncé ?",
    "Tu préfères que tout le monde sache combien tu bois ou combien tu fumes ?",
    "Tu préfères avoir des photos compromettantes de toi bourré qui circulent ou une vidéo de toi en train de fumer ?",
    "Tu préfères que ton/ta partenaire soit tout le temps bourré·e ou tout le temps défoncé·e ?",
    "Tu préfères vomir en plein milieu de la piste de danse ou t’endormir en plein milieu du salon ?",
    "Tu préfères boire un verre de bière chaude ou fumer une cigarette trempée ?",
    "Tu préfères que ta première cuite soit avec tes parents ou avec tes profs ?",
    "Tu préfères boire un shot de chaque bouteille d’une soirée ou fumer tout ce qui passe ?",
    "Tu préfères être sobre à vie mais entouré ou bourré/défoncé à vie mais seul ?",
    "Tu préfères que ton crush te voie danser ivre ou planer sur place complètement stone ?",
    "Tu préfères perdre ton portefeuille en soirée arrosée ou perdre ton téléphone en étant défoncé ?",
    "Tu préfères être malade à cause de l’alcool ou parano à cause de la drogue ?",
    "Tu préfères qu’on te filme en train de chanter bourré au karaoké ou en train de divaguer sous drogue ?",
    "Tu préfères avoir toujours trop de verres offerts ou toujours trop de joints proposés ?",
    "Tu préfères survivre à une énorme cuite mémorable ou à un énorme trip mémorable ?",
    "Tu préfères faire un black-out total en soirée et te réveiller chez un inconnu ou planer tellement que tu oublies ton nom pendant des heures ?",
    "Tu préfères que tes amis te filment en train de danser comme un fou bourré ou en train de rire bêtement sous drogue ?",
    "Tu préfères avoir une tolérance zéro à l'alcool et être saoul après un verre ou résister à tout mais ne jamais planer ?",
    "Tu préfères que ton/ta crush te voit vomir après trop de verres ou te voit paniquer en bad trip ?",
    "Tu préfères boire de la bière tiède toute ta vie ou fumer du tabac sec et irritant ?",
    "Tu préfères être le seul sobre en soirée déjantée ou le seul défoncé en réunion sérieuse ?",
    "Tu préfères que tes parents découvrent tes bouteilles vides ou tes pochons vides ?",
    "Tu préfères avoir une haleine d'alcoolique ou des yeux rougis en permanence ?",
    "Tu préfères rater un rendez-vous important à cause d'une cuite ou d'un trip trop long ?",
    "Tu préfères que tout le monde sache tes anecdotes bourrés ou tes anecdotes défoncés ?",
    "Tu préfères boire un cocktail mystère ou fumer un joint mystère ?",
    "Tu préfères être allergique à l'alcool ou aux substances psychédéliques ?",
    "Tu préfères que ton boss te surprenne en train de boire au travail ou de fumer en pause ?",
    "Tu préfères avoir des nausées après l'alcool ou des crises de rire incontrôlables sous drogue ?",
    "Tu préfères finir une bouteille seul ou rouler un joint géant seul ?",
    "Tu préfères que ta photo de profil soit une de toi bourré ou stone ?",
    "Tu préfères oublier une nuit entière à cause de l'alcool ou avoir des flashbacks bizarres de drogue ?",
    "Tu préfères que tes voisins se plaignent de tes soirées alcoolisées ou de l'odeur de weed ?",
    "Tu préfères boire jusqu'à l'aube ou fumer jusqu'au petit matin ?",
    "Tu préfères que ton/ta partenaire te quitte à cause de l'alcool ou de la drogue ?",
    "Tu préfères avoir une dépendance à la bière ou au tabac roulé ?",
    "Tu préfères que tes enfants découvrent ton passé alcoolique ou drogué ?",
    "Tu préfères être bourré à un mariage ou défoncé à un enterrement ?",
    "Tu préfères que la police te contrôle saoul au volant ou stone au volant ?",
    "Tu préfères boire un verre par heure toute la journée ou fumer un joint par heure ?",
    "Tu préfères avoir des tremblements après l'alcool ou des sueurs froides après la drogue ?",
    "Tu préfères que ton compte bancaire soit vidé par des soirées alcool ou par des achats de drogue ?",
    "Tu préfères être connu comme l'ivrogne du quartier ou le stoner du quartier ?",
    "Tu préfères rater un vol à cause d'une cuite ou d'un bad trip ?",
    "Tu préfères que tes collègues te voient en after bourrés ou en after défoncés ?",
    "Tu préfères boire de l'alcool frelaté ou fumer de la mauvaise herbe ?",
    "Tu préfères avoir une cirrhose ou des poumons noircis ?",
    "Tu préfères que ton/ta ex diffuse des stories de toi bourré ou stone ?",
    "Tu préfères être saoul à Noël ou défoncé au Nouvel An ?",
    "Tu préfères que tes potes te charrient sur tes cuites ou sur tes trips ?",
    "Tu préfères boire seul devant la TV ou fumer seul sur le balcon ?",
    "Tu préfères avoir des regrets après l'alcool ou des angoisses après la drogue ?",
    "Tu préfères que ton médecin te sermonne sur l'alcool ou sur la drogue ?",
    "Tu préfères être bourré en visio ou stone en appel vocal ?",
    "Tu préfères que ton animal de compagnie mange ton stock d'alcool ou de drogue ?",
    "Tu préfères boire un shot de vinaigre ou fumer une cigarette de menthe poivrée ?",
    "Tu préfères que tes rêves soient alcoolisés ou hallucinogènes ?",
    "Tu préfères être le chauffeur sobre ou le passager défoncé ?",
    "Tu préfères que ton/ta crush te ghoste après une soirée alcool ou drogue ?",
    "Tu préfères avoir une tolérance infinie à l'alcool mais pas à la drogue ou l'inverse ?",
    "Tu préfères que tes vacances soient alcoolisées ou psychédéliques ?",
    "Tu préfères boire en silence ou fumer en silence ?",
    "Tu préfères que ton/ta boss te propose un verre ou un joint ?",
    "Tu préfères rater un concert à cause de l'alcool ou de la drogue ?",
    "Tu préfères que tes selfies soient bourrés ou stones ?",
    "Tu préfères avoir des amis alcoolos ou stoners ?",
    "Tu préfères que ton frigo soit rempli de bières ou de pochons ?",
    "Tu préfères être saoul à un pique-nique ou défoncé à un barbecue ?",
    "Tu préfères que tes textos soient envoyés bourrés ou stones ?",
    "Tu préfères boire de l'eau gazeuse comme alcool ou fumer de l'air comme drogue ?",
    "Tu préfères que ton/ta partenaire te surprenne en train de boire seul ou fumer seul ?",
    "Tu préfères avoir une overdose d'alcool ou de drogue douce ?",
    "Tu préfères que tes soirées finissent en coma éthylique ou en coma stone ?",
    "Tu préfères être bourré en randonnée ou défoncé en escalade ?",
    "Tu préfères que tes podcasts soient sur l'alcool ou la drogue ?",
    "Tu préfères boire un verre avec un ennemi ou fumer un joint avec lui ?",
    "Tu préfères que ton/ta crush te voit saoul en train de manger ou stone en train de fixer le mur ?",
    "Tu préfères avoir des cernes d'alcool ou de drogue ?",
    "Tu préfères que tes fêtes d'anniversaire soient alcoolisées ou droguées ?",
    "Tu préfères boire en travaillant ou fumer en étudiant ?",
    "Tu préfères que ton/ta ex te rappelle bourré ou stone ?",
    "Tu préfères avoir une vie sans alcool mais avec drogue ou l'inverse ?",
    "Tu préfères que tes voisins entendent tes rires bourrés ou tes divagations stones ?",
    "Tu préfères boire un cocktail sans alcool qui goûte l'alcool ou fumer un joint sans effet ?",
    "Tu préfères que ton/ta boss découvre tes bouteilles ou tes grinders ?",
    "Tu préfères être saoul à un festival ou défoncé à un concert ?",
    "Tu préfères que tes achats en ligne soient faits bourrés ou stones ?",
    "Tu préfères avoir des amis qui boivent trop ou qui fument trop ?",
    "Tu préfères que ton/ta crush te propose un verre ou un joint ?",
    "Tu préfères boire seul au bar ou fumer seul au parc ?",
    "Tu préfères que tes rêves éveillés soient alcoolisés ou hallucinés ?",
    "Tu préfères rater un train à cause d'une cuite ou d'un trip ?",
    "Tu préfères que tes collègues te surnomment 'l'ivrogne' ou 'le stoner' ?",
    "Tu préfères boire de la bière sans alcool ou fumer du CBD sans THC ?",
    "Tu préfères que ton/ta partenaire te quitte pour alcool ou drogue ?",
    "Tu préfères être bourré en avion ou défoncé en train ?",
    "Tu préfères que tes posts sur les réseaux soient bourrés ou stones ?",
    "Tu préfères avoir une dépendance visible à l'alcool ou cachée à la drogue ?",
    "Tu préfères que tes parents te voient saoul ou stone ?",
    "Tu préfères boire un verre avec un fantôme ou fumer un joint avec un alien ?",
    "Tu préfères que tes soirées se terminent par un taxi bourré ou un Uber stone ?",
    "Tu préfères avoir des nausées matinales d'alcool ou des paranoïas nocturnes de drogue ?",
    "Tu préfères que ton/ta crush te voit en pyjama bourré ou en jogging stone ?",
    "Tu préfères boire en famille ou fumer avec des inconnus ?",
    "Tu préfères que tes vidéos virales soient bourrées ou stones ?",
    "Tu préfères avoir une tolérance faible à l'alcool ou à la drogue ?",
    "Tu préfères que ton/ta boss te vire pour alcool ou drogue ?",
    "Tu préfères boire un shot avec un rival ou fumer un pétard avec un ennemi ?",
    "Tu préfères que tes regrets soient alcoolisés ou drogués ?",
    "Tu préfères être saoul à un rendez-vous galant ou stone à un premier date ?",
    "Tu préfères que tes amis te sauvent d'une cuite ou d'un bad trip ?",
    "Tu préfères boire seul en vacances ou fumer seul en voyage ?",
    "Tu préfères que tes tattoos soient faits bourrés ou stones ?",
    "Tu préfères avoir des amis alcoolos bruyants ou stoners silencieux ?",
    "Tu préfères que ton/ta crush te ghoste après un verre ou un joint ?",
    "Tu préfères boire un verre avec ton ex ou fumer avec son nouveau ?",
    "Tu préfères que tes soirées d'entreprise soient alcoolisées ou droguées ?",
    "Tu préfères rater un examen à cause de l'alcool ou de la drogue ?",
    "Tu préfères que tes collègues découvrent ton stock d'alcool ou de drogue au bureau ?",
    "Tu préfères boire en silence avec un inconnu ou fumer en discutant avec un ami ?",
    "Tu préfères que tes rêves soient perturbés par l'alcool ou par la drogue ?",
    "Tu préfères être bourré à un spectacle ou défoncé à un film ?",
    "Tu préfères que ton/ta partenaire te mente sur l'alcool ou la drogue ?",
    "Tu préfères boire un verre piégé ou fumer un joint trafiqué ?",
    "Tu préfères que tes fêtes foraines soient alcoolisées ou stones ?",
    "Tu préfères avoir des hallucinations alcooliques ou droguées ?",
    "Tu préfères que ton/ta crush te voit saoul en train de chanter ou stone en train de danser ?",
    "Tu préfères boire seul le soir ou fumer seul le matin ?",
    "Tu préfères que tes voisins se plaignent de tes cuites ou de tes sessions fumette ?",
    "Tu préfères rater un appel important à cause de l'alcool ou de la drogue ?",
    "Tu préfères que tes selfies de groupe soient bourrés ou stones ?",
    "Tu préfères avoir une vie sans cuites mais avec trips ou l'inverse ?",
    "Tu préfères que tes potes te filment saoul ou stone ?",
    "Tu préfères boire un cocktail avec un celebrity ou fumer un joint avec une star ?",
    "Tu préfères que tes anniversaires finissent bourrés ou stones ?",
    "Tu préfères être saoul en montagne ou défoncé à la mer ?",
    "Tu préfères que ton/ta boss te surprenne en train de boire ou fumer en télétravail ?",
    "Tu préfères boire un verre avec un politicien ou fumer avec un artiste ?",
    "Tu préfères que tes regrets du lendemain soient d'alcool ou de drogue ?",
    "Tu préfères être bourré à un parc d'attractions ou défoncé à un zoo ?",
    "Tu préfères que tes amis te jugent pour l'alcool ou la drogue ?",
    "Tu préfères boire seul en hiver ou fumer seul en été ?",
    "Tu préfères que tes voyages soient alcoolisés ou psychédéliques ?",
    "Tu préfères rater un bus à cause d'une cuite ou d'un trip ?",
    "Tu préfères que tes collègues te voient saoul à la cantine ou stone à la pause ?",
    "Tu préfères boire un shot avec un animal ou fumer un pétard avec un robot ?",
    "Tu préfères que tes soirées pyjama soient alcoolisées ou stones ?",
    "Tu préfères avoir des crises de rire alcooliques ou droguées ?",
    "Tu préfères que ton/ta crush te voit bourré en train de manger un kebab ou stone en train de fixer les étoiles ?",
    "Tu préfères boire en groupe silencieux ou fumer en solo bruyant ?",
    "Tu préfères que tes posts Instagram soient tagués bourrés ou stones ?",
    "Tu préfères avoir une tolérance extrême à l'alcool ou à la drogue ?",
    "Tu préfères que ton/ta partenaire te surprenne avec une bouteille ou un grinder ?",
    "Tu préfères boire un verre avec un superhéros ou fumer avec un villain ?",
    "Tu préfères que tes fêtes de fin d'année soient alcoolisées ou droguées ?",
    "Tu préfères être saoul en vélo ou défoncé en skate ?",
    "Tu préfères que tes amis te sauvent d'un coma éthylique ou d'un coma stone ?",
    "Tu préfères boire seul au restaurant ou fumer seul au cinéma ?",
    "Tu préfères que tes tatouages regrettés soient faits sous alcool ou drogue ?",
    "Tu préfères avoir des amis qui boivent modérément ou fument occasionnellement ?",
    "Tu préfères que ton/ta crush te propose un shot ou un pétard ?",
    "Tu préfères boire avec ton patron ou fumer avec ton prof ?",
    "Tu préfères que tes soirées karaoké finissent bourrées ou stones ?",
    "Tu préfères rater un rendez-vous médical à cause de l'alcool ou de la drogue ?",
    "Tu préfères que tes collègues découvrent tes verres cachés ou tes joints cachés ?",
    "Tu préfères boire en écoutant de la musique classique ou fumer en regardant un documentaire ?",
    "Tu préfères que tes rêves nocturnes soient influencés par l'alcool ou la drogue ?",
    "Tu préfères être bourré à un opéra ou défoncé à un ballet ?",
    "Tu préfères que ton/ta partenaire te mente sur ses cuites ou ses trips ?",
    "Tu préfères boire un cocktail empoisonné ou fumer un joint contaminé ?",
    "Tu préfères que tes fêtes d'Halloween soient alcoolisées ou psychédéliques ?",
    "Tu préfères avoir des visions alcooliques ou hallucinogènes ?",
    "Tu préfères que ton/ta crush te voit saoul en train de cuisiner ou stone en train de peindre ?",
    "Tu préfères boire seul le week-end ou fumer seul en semaine ?",
    "Tu préfères que tes voisins entendent tes chants bourrés ou tes rires stones ?"
];