const mots = {"chat": ["chien", "tigre", "lion"],
    "chien": ["chiot", "canin", "labrador"],
    "oiseau": ["moineau", "perroquet", "aigle"],
    "poisson": ["saumon", "truite", "thon"],
    "cheval": ["poney", "jument", "étalon"],
    "vache": ["taureau", "veau", "bovin"],
    "cochon": ["porcelet", "sanglier", "truie"],
    "lapin": ["lièvre", "lapereau", "cochon d'inde"],
    "serpent": ["vipère", "boa", "python"],
    "souris": ["rat", "hamster", "mulot"],
    "tigre": ["lion", "léopard", "panthère"],
    "éléphant": ["mammouth", "rhinocéros", "buffle"],
    "lion": ["tigresse", "lionceau", "guépard"],
    "ours": ["panda", "grizzly", "ours polaire"],
    "grenouille": ["crapaud", "rainette", "têtard"],
    "abeille": ["guêpe", "bourdon", "mouche"],
    "fourmi": ["termitte", "puceron", "coccinelle"],
    "papillon": ["morpho", "piéride", "flambé"],
    "arbre": ["chêne", "sapin", "bouleau"],
    "fleur": ["rose", "tulipe", "orchidée"],
    "plante": ["cactus", "bambou", "fougère"],
    "fruit": ["pomme", "banane", "orange"],
    "légume": ["carotte", "tomate", "concombre"],
    "noix": ["amande", "noisette", "cacahuète"],
    "épice": ["curry", "poivre", "paprika"],
    "viande": ["poulet", "boeuf", "porc"],
    "poisson cru": ["saumon", "thon", "maquereau"],
    "produit laitier": ["lait", "fromage", "yaourt"],
    "boisson": ["eau", "jus", "café"],
    "dessert": ["gâteau", "tarte", "glace"],
    "pain": ["baguette", "brioche", "croissant"],
    "riz": ["basmati", "japonica", "carnaroli"],
    "pâtes": ["spaghetti", "penne", "tagliatelle"],
    "pizza": ["margherita", "pepperoni", "reine"],
    "hamburger": ["cheeseburger", "veggie burger", "double"],
    "sandwich": ["club", "panini", "baguette"],
    "soupe": ["velouté", "bouillon", "minestrone"],
    "salade": ["cesar", "niçoise", "grecque"],
    "œuf": ["omelette", "œuf dur", "œuf poché"],
    "fromage": ["camembert", "roquefort", "emmental"],
    "beurre": ["margarine", "ghee", "beurre salé"],
    "chocolat": ["noir", "blanc", "au lait"],
    "sucre": ["cassonade", "roux", "glace"],
    "sel": ["fleur de sel", "gros sel", "sel fin"],
    "huile": ["olive", "tournesol", "colza"],
    "vinaigre": ["balsamique", "cidre", "vin"],
    "céréale": ["blé", "maïs", "avoine"],
    "yaourt": ["grec", "nature", "aux fruits"],
    "lait": ["entier", "demi-écrémé", "écrémé"],
    "jus de fruit": ["orange", "pomme", "ananas"],
    "thé": ["vert", "noir", "blanc"],
    "bière": ["blonde", "brune", "rousse"],
    "vin": ["rouge", "blanc", "rosé"],
    "cocktail": ["mojito", "pina colada", "martini"],
    "eau gazeuse": ["pétillante", "plate", "aromatisée"],
    "chocolat chaud": ["lait", "noisette", "cannelle"],
    "pain au chocolat": ["croissant", "chausson", "brioche"],
    "croissant": ["viennoiserie", "pain", "chausson"],
    "glace": ["sorbet", "crème glacée", "parfait"],
    "gâteau": ["éponge", "fondant", "moelleux"],
    "tarte": ["tatin", "aux fruits", "au citron"],
    "muffin": ["cupcake", "brownie", "madeleine"],
    "cookie": ["biscuit", "brownie", "sablé"],
    "fusée": ["satellite", "astronaute", "station"],
    "avion": ["hélicoptère", "jet", "drone"],
    "bateau": ["voilier", "canoë", "péniche"],
    "vélo": ["trottinette", "roller", "bmx"],
    "moto": ["scooter", "quad", "sidecar"],
    "voiture": ["camion", "bus", "moto"],
    "train": ["locomotive", "wagon", "rail"],
    "bus": ["minibus", "autocar", "tramway"],
    "armoire": ["commode", "étagère", "placard"],
    "lit": ["matelas", "oreiller", "couette"],
    "porte": ["fenêtre", "cloison", "portail"],
    "fenêtre": ["rideau", "vitre", "volet"],
    "lampe": ["ampoule", "lustre", "veilleuse"],
    "table": ["chaise", "bureau", "console"],
    "chaise": ["tabouret", "fauteuil", "canapé"],
    "ordinateur": ["PC", "Mac", "portable"],
    "téléphone": ["smartphone", "fixe", "portable"],
    "imprimante": ["scanner", "photocopieur", "fax"],
    "stylo": ["crayon", "marqueur", "plume"],
    "cahier": ["bloc", "agenda", "carnet"],
    "livre": ["roman", "journal", "magazine"],
    "papier": ["feuille", "carton", "papier journal"],
    "musique": ["chanson", "mélodie", "rythme"],
    "film": ["cinéma", "série", "documentaire"],
    "jeu": ["plateau", "cartes", "vidéo"],
    "sport": ["football", "basket", "tennis"],
    "ballon": ["foot", "basket", "volley"],
    "raquette": ["tennis", "badminton", "ping-pong"],
    "vêtement": ["chemise", "pantalon", "robe"],
    "chaussure": ["bottes", "sandales", "sneakers"],
    "chapeau": ["casquette", "béret", "bonnet"],
    "lunette": ["soleil", "vue", "goggles"],
    "montre": ["bracelet", "cadran", "chronomètre"],
    "bijou": ["collier", "bracelet", "bague"],
    "sac": ["cartable", "sac à dos", "pochette"],
    "nourriture": ["fruit", "légume", "viande"]};