const propositionsNormal = [
    "Quelqu'un annule à la dernière minute : excuse valable ou pas ?",
    "Partager un mot de passe Netflix : normal ou abus ?",
    "Manger dessert avant le repas : acceptable ou pas ?",
    "Il/elle répond aux messages 5 heures après : qui a raison ?",
    "Laisser la vaisselle dans l’évier une nuit : tolérable ou pas ?",
    "Mettre la musique fort dans les transports : qui a raison ?",
    "Ne pas rappeler après un premier date : ghosting justifié ou pas ?",
    "Prendre la dernière part de pizza sans demander : OK ou pas ?",
    "Regarder la série en avance sans l’autre : trahison ou pas ?",
    "Laisser les chaussettes par terre : qui a raison ?",
    "Envoyer un vocal de 3 minutes : pratique ou insupportable ?",
    "Manger dans le lit : hygiénique ou dégueu ?",
    "Ne pas fêter l’anniversaire de couple : grave ou pas grave ?",
    "Utiliser le téléphone aux toilettes : normal ou sale ?",
    "Oublier de dire merci après un cadeau : impoli ou pas ?",
    "Arriver 15 minutes en retard systématiquement : qui a raison ?",
    "Écouter la conversation des voisins : curieux ou indiscret ?",
    "Ne pas ranger ses affaires après une soirée : tolérable ou pas ?",
    "Poster une photo de couple sans demander : respectueux ou pas ?",
    "Manger les restes de l’autre dans le frigo : vol ou partage ?",
    "Ne pas aimer les animaux : anormal ou pas ?",
    "Dire 'je t’aime' en premier : courageux ou trop tôt ?",
    "Regarder le téléphone de son partenaire : confiance ou pas ?",
    "Ne pas aimer les câlins après le sexe : froid ou normal ?",
    "Laisser le panier de linge sale déborder : qui a raison ?",
    "Oublier de recharger le téléphone commun : négligent ou pas ?",
    "Mettre des glaçons dans le vin : blasphème ou astuce ?",
    "Ne pas répondre aux messages de groupe : associable ou pas ?",
    "Prendre une douche de 30 minutes : écolo ou pas ?",
    "Manger des chips au lit : acceptable ou interdit ?",
    "Ne pas offrir de cadeau à Noël : radin ou pas ?",
    "Dire qu’on est occupé alors qu’on scroll : mensonge ou pas ?",
    "Laisser les lumières allumées en partant : qui a raison ?",
    "Ne pas aimer danser : coincé ou normal ?",
    "Utiliser le shampoing de l’autre jusqu’au bout : partage ou abus ?",
    "Ne pas dire bonjour dans l’ascenseur : impoli ou pas ?",
    "Manger l’ail avant un date : irresponsable ou pas ?",
    "Ne pas ranger le chariot au supermarché : qui a raison ?",
    "Écrire 'lol' alors qu’on ne rit pas : hypocrite ou normal ?",
    "Ne pas aimer le fromage : bizarre ou pas ?",
    "Regarder des stories sans liker : voyeur ou discret ?",
    "Ne pas couper les étiquettes des vêtements : qui a raison ?",
    "Manger avec les mains : sauvage ou pratique ?",
    "Ne pas fêter la Saint-Valentin : romantique ou pas ?",
    "Laisser le capuchon du dentifrice ouvert : tolérable ou pas ?",
    "Envoyer des memes à 3h du mat : drôle ou relou ?",
    "Ne pas aimer le café : anormal ou pas ?",
    "Mettre trop de parfum : qui a raison ?",
    "Ne pas répondre aux 'ça va ?' par 'ça va' : original ou chiant ?",
    "Prendre des photos pendant un concert : vivre le moment ou pas ?",
    "Ne pas aimer les enfants : égoïste ou honnête ?",
    "Manger du chocolat au petit-déjeuner : gourmand ou pas ?",
    "Ne pas plier le linge tout de suite : paresseux ou pas ?",
    "Dire 'on se rappelle' sans le faire : poli ou menteur ?",
    "Utiliser le dernier rouleau de PQ sans le remplacer : qui a raison ?",
    "Ne pas aimer les fleurs en cadeau : ingrat ou pas ?",
    "Mettre le chauffage à 24°C : confort ou gâchis ?",
    "Ne pas liker les posts de son partenaire : distant ou pas ?",
    "Boire dans le carton de jus : dégueu ou pratique ?",
    "Ne pas ranger les chaussures à l’entrée : bordélique ou pas ?",
    "Envoyer plusieurs messages d’affilée : désespéré ou normal ?",
    "Ne pas aimer les surprises : rabat-joie ou pas ?",
    "Manger les frites de l’autre : partage ou vol ?",
    "Ne pas dire merci au serveur : impoli ou pas ?",
    "Laisser la télé allumée pour s’endormir : qui a raison ?",
    "Ne pas aimer les épices : difficile ou pas ?",
    "Utiliser le compte Spotify de l’autre : normal ou abus ?",
    "Ne pas ranger le lit le matin : qui a raison ?",
    "Manger du fromage qui pue : tolérable ou pas ?",
    "Ne pas répondre aux appels inconnus : parano ou prudent ?",
    "Prendre le bras accoudoir dans l’avion : qui a raison ?",
    "Ne pas aimer les hugs : froid ou normal ?",
    "Mettre du ketchup sur les pâtes : crime ou pas ?",
    "Ne pas offrir à boire quand on reçoit : radin ou pas ?",
    "Regarder un film sans sous-titres : qui a raison ?",
    "Ne pas aimer les selfies : narcissique ou pas ?",
    "Laisser les poils dans la douche : dégueu ou pas ?",
    "Envoyer des 'k' en réponse : sec ou normal ?",
    "Ne pas aimer voyager : casanier ou pas ?",
    "Manger la peau du poulet : délicieux ou dégueu ?",
    "Ne pas ranger les courses tout de suite : qui a raison ?",
    "Dire qu’on arrive dans 5 min alors qu’on est pas prêt : menteur ou pas ?",
    "Ne pas aimer les réseaux sociaux : vieux jeu ou pas ?",
    "Mettre du lait avant les céréales : hérétique ou pas ?",
    "Ne pas répondre aux messages vocaux : flemmard ou pas ?",
    "Prendre une place handicapé quand y’en a plus : qui a raison ?",
    "Ne pas aimer le vin : inculte ou pas ?",
    "Manger des bonbons au cinéma en cachette : malin ou pas ?",
    "Ne pas dire au revoir en partant : impoli ou pas ?",
    "Laisser le frigo ouvert : qui a raison ?",
    "Ne pas aimer les compliments : modeste ou faux cul ?",
    "Mettre du sel sur le melon : bizarre ou génie ?",
    "Ne pas ranger les écouteurs : bordélique ou pas ?",
    "Envoyer des screenshots de conversation : traître ou pas ?",
    "Ne pas aimer les pique-niques : chiant ou pas ?",
    "Manger des frites avec une fourchette : précieux ou normal ?",
    "Ne pas offrir de cadeau d’anniversaire : radin ou pas ?",
    "Regarder le match en mangeant des chips bruyamment : qui a raison ?",
    "Ne pas aimer les tatouages : vieux ou pas ?",
    "Mettre la clim à fond en été : confort ou égoïste ?",
    "Ne pas répondre aux 'tu fais quoi ?' : distant ou pas ?",
    "Laisser les miettes sur la table : tolérable ou pas ?",
    "Ne pas aimer les séries : asocial ou pas ?",
    "Manger du Nutella à la cuillère : normal ou addiction ?",
    "Ne pas ranger le vélo dans le couloir : qui a raison ?",
    "Dire 'je suis là dans 2 min' alors qu’on est encore en pyjama : menteur ou pas ?",
    "Ne pas aimer les photos de groupe : égoïste ou pas ?",
    "Mettre du sucre dans le vin : crime ou pas ?",
    "Ne pas liker les photos de vacances des amis : jaloux ou pas ?",
    "Laisser le chargeur branché toute la journée : qui a raison ?",
    "Ne pas aimer les bisous dans le cou : sensible ou pas ?",
    "Manger des oignons crus : courageux ou fou ?",
    "Ne pas répondre aux appels de maman : ingrat ou pas ?",
    "Prendre deux serviettes à l’hôtel : voleur ou pas ?",
    "Ne pas aimer les marchés de Noël : grincheux ou pas ?",
    "Mettre du fromage sur le poisson : blasphème ou pas ?",
    "Ne pas ranger les livres sur l’étagère : qui a raison ?",
    "Envoyer des 'seen' sans répondre : relou ou pas ?",
    "Ne pas aimer les animaux en photo : cœur de pierre ou pas ?",
    "Manger la pâte à crêpes crue : dangereux ou délicieux ?",
    "Ne pas dire merci après un compliment : malpoli ou pas ?",
    "Laisser les fenêtres ouvertes en hiver : qui a raison ?",
    "Ne pas aimer les escapes games : casanier ou pas ?",
    "Mettre du pineapple sur la pizza : acceptable ou pas ?",
    "Ne pas répondre aux messages pros le week-end : droit ou pas ?",
    "Prendre le dernier croissant sans demander : qui a raison ?",
    "Ne pas aimer les feux d’artifice : écolo ou rabat-joie ?",
    "Manger des chips en faisant du bruit : tolérable ou pas ?",
    "Ne pas ranger le linge sec tout de suite : flemmard ou pas ?",
    "Dire qu’on est malade pour éviter une soirée : menteur ou pas ?",
    "Ne pas aimer les concerts : asocial ou pas ?",
    "Mettre du beurre salé sur du pain sucré : génie ou pas ?",
    "Ne pas liker les posts politiques : neutre ou lâche ?",
    "Laisser le panier dans le parking : qui a raison ?",
    "Ne pas aimer les câlins en public : pudique ou froid ?",
    "Manger du fromage après le dessert : normal ou pas ?",
    "Ne pas répondre aux 'bonne nuit' : sec ou pas ?",
    "Prendre une photo avant de manger : influenceur ou pas ?",
    "Ne pas aimer les karaokés : coincé ou pas ?",
    "Mettre de la mayo sur les frites : belge ou français ?",
    "Ne pas ranger les affaires de sport : qui a raison ?",
    "Envoyer des cœurs à tout le monde : dragueur ou gentil ?",
    "Ne pas aimer les museums : inculte ou pas ?",
    "Manger des céréales au dîner : adulte ou pas ?",
    "Ne pas dire 'à tes souhaits' après un éternuement : impoli ou pas ?",
    "Laisser le téléphone en sonnerie en réunion : qui a raison ?",
    "Ne pas aimer les randonnées : paresseux ou pas ?",
    "Mettre du citron dans la bière : normal ou pas ?",
    "Ne pas répondre aux stories : distant ou pas ?",
    "Prendre deux places dans le métro : égoïste ou pas ?",
    "Ne pas aimer les surprises parties : associable ou pas ?",
    "Manger du pain avec du fromage fondu : raclette ou pas ?",
    "Ne pas ranger les couverts sales : qui a raison ?",
    "Dire 'je t’appelle' sans le faire : poli ou menteur ?",
    "Ne pas aimer les plages bondées : solitaire ou pas ?",
    "Mettre du sel sur la pastèque : bizarre ou délicieux ?",
    "Ne pas liker les bébés en photo : jaloux ou honnête ?",
    "Laisser les poils du chien partout : tolérable ou pas ?",
    "Ne pas répondre aux 'tu dors ?' à 2h : relou ou normal ?",
    "Prendre le dernier café sans refaire la cafetière : qui a raison ?",
    "Ne pas aimer les festivals : vieux ou pas ?",
    "Manger des escargots : courageux ou dégueu ?",
    "Ne pas dire merci au livreur : impoli ou pas ?"
];

const propositionsHot = [
    "Flirter avec un ami du couple : OK ou pas OK ?",
    "Garder le contact avec une ex : sain ou toxique ?",
    "Cacher des petits secrets au couple : normal ?",
    "Regarder du porno en couple : excitant ou trahison ?",
    "Envoyer des nudes à son ex : nostalgie ou infidélité ?",
    "Mentir sur son nombre de partenaires : qui a raison ?",
    "Aimer les likes d’un ex sur Insta : innocent ou suspect ?",
    "Faire un plan cul avec un collègue : risque ou plaisir ?",
    "Coucher dès le premier soir : facile ou moderne ?",
    "Regarder le téléphone du partenaire : confiance ou parano ?",
    "Fantasmer sur l’ami(e) de son mec/sa meuf : normal ou pas ?",
    "Dire 'je t’aime' juste pour coucher : manipulateur ou pas ?",
    "Refuser la sodomie : coincé(e) ou droit ?",
    "Aimer être attaché(e) au lit : kinky ou trop ?",
    "Mentir sur son âge sur Tinder : petit mensonge ou pas ?",
    "Faire l’amour avec la lumière allumée : intime ou gênant ?",
    "Garder des photos nues d’un ex : qui a raison ?",
    "Payer pour du sexe : loser ou pratique ?",
    "Avoir un crush sur le beau-frère/la belle-sœur : grave ou pas ?",
    "Simuler l’orgasme : gentil ou menteur ?",
    "Parler de ses ex au lit : excitant ou relou ?",
    "Refuser le sexe quand l’autre a envie : égoïste ou pas ?",
    "Aimer les sextos pendant la journée : hot ou trop ?",
    "Coucher avec quelqu’un en couple : salaud ou opportuniste ?",
    "Regarder du porno ensemble : piment ou pression ?",
    "Mentir sur ce qu’on aime au lit : qui a raison ?",
    "Avoir un friends with benefits en parallèle : tromperie ou pas ?",
    "Dire qu’on est vierge alors que non : honte ou stratégie ?",
    "Aimer les fessées : violent ou excitant ?",
    "Envoyer des nudes non sollicités : drague ou harcèlement ?",
    "Fantasmer sur un prof/un boss : tabou ou normal ?",
    "Refuser les câlins après le sexe : froid ou normal ?",
    "Garder un plan cul secret : trahison ou pas ?",
    "Aimer le dirty talk : vulgaire ou excitant ?",
    "Coucher avec l’ex de son meilleur ami : code violé ou pas ?",
    "Mentir sur son orientation sexuelle : qui a raison ?",
    "Avoir plusieurs partenaires en même temps : poly ou salaud ?",
    "Regarder les DM coquins sans répondre : innocent ou pas ?",
    "Faire du sexe en public : adrenalin ou exhibitionniste ?",
    "Refuser le préservatif en couple : confiance ou irresponsable ?",
    "Aimer les jeux de rôle au lit : bizarre ou fun ?",
    "Parler de ses fantasmes extrêmes : trop tôt ou honnête ?",
    "Coucher pour se venger : justifié ou immature ?",
    "Garder des messages coquins d’un ex : qui a raison ?",
    "Aimer être dominé(e) : soumission ou plaisir ?",
    "Envoyer des vocaux coquins : hot ou gênant ?",
    "Fantasmer sur un membre de la famille du partenaire : grave ou pas ?",
    "Simuler pour faire plaisir : attentionné ou faux ?",
    "Refuser le sexe oral : réciprocité ou pas ?",
    "Avoir un OnlyFans en couple : trahison ou business ?",
    "Mentir sur sa taille/particularité : complexe ou tromperie ?",
    "Aimer les trios : ouvert ou infidèle ?",
    "Regarder du porno en cachette : normal ou secret honteux ?",
    "Faire du sexting avec un inconnu : aventure ou danger ?",
    "Coucher avec quelqu’un beaucoup plus jeune/vieux : qui a raison ?",
    "Refuser de dire 'je t’aime' après le sexe : peur ou honnête ?",
    "Aimer les marques (suçons, griffures) : passion ou violence ?",
    "Garder contact avec un plan cul passé : respect ou espoir ?",
    "Parler salaire au premier date : vulgaire ou transparent ?",
    "Avoir des sex toys en couple : tabou ou normal ?",
    "Mentir sur son expérience sexuelle : qui a raison ?",
    "Fantasmer sur la meilleure amie du partenaire : trahison mentale ou pas ?",
    "Refuser le sexe pendant les règles : dégueu ou respect ?",
    "Aimer le sexe brutal : violent ou passionné ?",
    "Envoyer des nudes à un collègue : risque ou flirt ?",
    "Coucher après une rupture pour oublier : rebond ou erreur ?",
    "Regarder les ex sur les réseaux : nostalgie ou malsain ?",
    "Aimer être filmé(e) au lit : excitant ou dangereux ?",
    "Mentir sur son statut relationnel : joueur ou manipulateur ?",
    "Refuser le mariage mais vouloir des enfants : cohérent ou pas ?",
    "Avoir un sugar daddy/mommy : pratique ou prostitution ?",
    "Parler de ses kinks dès le début : trop ou honnête ?",
    "Simuler l’intérêt sexuel pour garder quelqu’un : qui a raison ?",
    "Faire du sexe sans sentiments : froid ou libéré ?",
    "Garder des capotes dans le portefeuille : prévoyant ou dragueur ?",
    "Aimer les sextos avec des inconnus : trahison ou fantasme ?",
    "Coucher avec quelqu’un bourré : consentement ou pas ?",
    "Refuser de coucher sans être en couple : prude ou valeurs ?",
    "Avoir des rêves érotiques sur un ami : coupable ou pas ?",
    "Mentir sur son plaisir au lit : protecteur ou faux ?",
    "Fantasmer sur des célébrités en couple : normal ou immature ?",
    "Regarder du porno lesbien en étant hétéro : curieux ou bi refoulé ?",
    "Aimer le sexe en extérieur : aventurier ou exhibitionniste ?",
    "Envoyer des photos osées sans le visage : prudent ou pas ?",
    "Coucher pour un pari : connerie ou fun ?",
    "Refuser le sexe matinal : flemmard ou pas son truc ?",
    "Garder des souvenirs intimes d’ex : sentimental ou malsain ?",
    "Aimer les compliments crus : vulgaire ou direct ?",
    "Faire semblant d’aimer les mêmes kinks : qui a raison ?",
    "Parler de ses ex au lit pour exciter : hot ou relou ?",
    "Avoir un crush secret en étant en couple : infidélité émotionnelle ou pas ?",
    "Refuser les positions demandées : fermé ou limites ?",
    "Mentir sur son orientation pour tester : manipulateur ou pas ?",
    "Aimer le sexe sans baiser : détaché ou pratique ?",
    "Regarder les profils Tinder en couple : curiosité ou trahison ?",
    "Faire du phone sex : intime ou désespéré ?",
    "Coucher avec l’ex pendant une pause : tromperie ou pas ?",
    "Refuser de dire son fantasme le plus sombre : honte ou prudent ?",
    "Aimer être regardé(e) pendant l’acte : voyeur ou excitant ?",
    "Envoyer des 'tu me manques' à un ex : nostalgie ou manipulation ?",
    "Simuler pour terminer plus vite : égoïste ou pratique ?",
    "Avoir des sex friends en voyage : aventure ou infidélité ?",
    "Mentir sur son corps (photos retouchées) : tromperie ou pas ?",
    "Fantasmer sur le/la partenaire de son ami : grave ou pas ?",
    "Refuser le sexe quand l’autre est malade : attention ou rejet ?",
    "Aimer les mots crus au lit : vulgaire ou passionné ?",
    "Garder des vidéos intimes : confiance ou risque ?",
    "Parler de ses conquêtes passées : vantard ou transparent ?",
    "Coucher sans attachement : mature ou incapable d’aimer ?",
    "Regarder du porno en pensant à quelqu’un d’autre : trahison ou pas ?",
    "Aimer les surprises coquines : fun ou intrusion ?",
    "Envoyer des nudes expirants : prudent ou tease ?",
    "Faire l’amour bruyamment chez les parents : qui a raison ?",
    "Refuser les préliminaires longs : pressé ou pas patient ?",
    "Mentir sur son plaisir pour booster l’autre : gentil ou faux ?",
    "Avoir un piercing intime en secret : surprise ou mensonge ?",
    "Fantasmer sur un inconnu croisé : normal ou obsédé ?",
    "Regarder les recherches porno de son partenaire : parano ou curieux ?",
    "Aimer le sexe rapide : efficace ou paresseux ?",
    "Coucher après 3 verres : regret ou fun ?",
    "Refuser de dormir nu : pudique ou coincé ?",
    "Garder un journal de ses conquêtes : nostalgie ou glauque ?",
    "Parler de taille au premier date : vulgaire ou important ?",
    "Aimer les câlins post-sexe plus que l’acte : romantique ou bizarre ?",
    "Envoyer des 'je pense à toi' coquins au boulot : hot ou risqué ?",
    "Simuler l’orgasme pour éviter les questions : qui a raison ?",
    "Faire du sexe pour se réconcilier : solution ou pansement ?",
    "Refuser le sexe en vacances : gâchis ou fatigue ?",
    "Mentir sur ses expériences extrêmes : honte ou pas ?",
    "Avoir des fantasmes non réalisés : frustré ou normal ?",
    "Regarder du porno en couple pour apprendre : éducatif ou pas ?",
    "Aimer être pris(e) par surprise : excitant ou limite ?",
    "Coucher avec quelqu’un qui ressemble à son ex : rebond ou pas ?",
    "Refuser les jouets en couple : fermé ou jaloux ?",
    "Garder des sous-vêtements d’un ex : fétichiste ou sentimental ?",
    "Parler de ses insécurités au lit : vulnérable ou tue-l’ambiance ?",
    "Aimer le slow sex : profond ou ennuyeux ?",
    "Envoyer des nudes à un crush en couple : salaud ou pas ?",
    "Faire semblant d’être plus expérimenté(e) : qui a raison ?",
    "Regarder les ex sur LinkedIn : pro ou stalker ?",
    "Aimer le sexe sans contact visuel : détaché ou intense ?",
    "Coucher pour tester la compatibilité : logique ou superficiel ?",
    "Refuser de dire ce qu’on aime vraiment : timide ou frustrant ?",
    "Mentir sur son fantasme le plus tabou : protection ou pas ?",
    "Avoir des rêves humides sur un collègue : coupable ou pas ?",
    "Parler de ses limites sexuelles tôt : mature ou rabat-joie ?",
    "Aimer le sexe tous les jours : accro ou normal ?",
    "Envoyer des messages coquins à 8h du mat : matin coquin ou trop ?",
    "Simuler pour ne pas blesser : compassion ou mensonge ?",
    "Faire du sexe virtuel en couple séparé : fidélité ou pas ?",
    "Refuser le sexe pendant une dispute : punition ou pas prêt ?",
    "Garder des captures d’écran coquines : souvenir ou risque ?",
    "Aimer les compliments sur le corps seulement : superficiel ou pas ?",
    "Coucher après un enterrement : manque de respect ou besoin ?",
    "Mentir sur son orientation passée : qui a raison ?",
    "Fantasmer sur des scénarios non consentis dans la tête : normal ou pas ?",
    "Regarder du contenu érotique ensemble : piment ou comparaison ?",
    "Aimer être appelé(e) des noms au lit : dégradant ou excitant ?",
    "Envoyer des 'reviens' à un ex toxique : faible ou espoir ?",
    "Refuser le sexe sans amour : romantique ou prude ?",
    "Parler de ses peurs sexuelles : intime ou lourd ?"
];