
const motEspion = "Espion"; // mot de l'espion
const lieux = [
    "Plage",
    "Forêt",
    "Bureau",
    "École",
    "Hôpital",
    "Restaurant",
    "Avion",
    "Cinéma",
    "Musée",
    "Château",
    "Bibliothèque",
    "Parc",
    "Supermarché",
    "Gare",
    "Aéroport",
    "Port",
    "Montagne",
    "Désert",
    "Volcan",
    "Grotte",
    "Île",
    "Ville",
    "Village",
    "Ferme",
    "Usine",
    "Laboratoire",
    "Théâtre",
    "Salle de concert",
    "Stade",
    "Piscine",
    "Gym",
    "Salon de coiffure",
    "Bar",
    "Café",
    "Boulangerie",
    "Pâtisserie",
    "Boucherie",
    "Poissonnerie",
    "Marché",
    "Tribunal",
    "Prison",
    "Caserne de pompiers",
    "Commissariat de police",
    "Ambassade",
    "Mairie",
    "Banque",
    "Hôtel",
    "Auberge de jeunesse",
    "Camping",
    "Appartement",
    "Maison",
    "Loft",
    "Chalet",
    "Cabane",
    "Bateau",
    "Sous-marin",
    "Bus",
    "Train",
    "Métro",
    "Tramway",
    "Taxi",
    "Voiture",
    "Moto",
    "Vélo",
    "Scooter",
    "Skatepark",
    "Patinoire",
    "Bowling",
    "Galerie d'art",
    "Antiquaire",
    "Magasin de vêtements",
    "Librairie",
    "Fleuriste",
    "Bijouterie",
    "Horlogerie",
    "Quai",
    "Phare",
    "Observatoire",
    "Planetarium",
    "Zoo",
    "Jardin botanique",
    "Serre",
    "Verger",
    "Vigne",
    "Champs",
    "Marais",
    "Étang",
    "Lac",
    "Rivière",
    "Canal",
    "Cascade",
    "Glacier",
    "Toundra",
    "Jungle",
    "Savane",
    "Steppe",
    "Canyon",
    "Falaise",
    "Colline",
    "Vallée",
    "Plateau",
    "Geyser",
    "Source chaude",
    "Fjord",
    "Atoll",
    "Lagon",
    "Récif corallien",
    "Épave",
    "Sous l'eau",
    "Dans les airs",
    "Espace",
    "Station spatiale",
    "Vaisseau spatial",
    "Planète étrangère",
    "Astéroïde",
    "Comète",
    "Nuage",
    "Arche",
    "Pont",
    "Tunnel",
    "Égouts",
    "Catacombes",
    "Mine",
    "Carrière",
    "Écluse",
    "Barrage",
    "Centrale électrique",
    "Raffinerie",
    "Dépôt",
    "Entrepôt",
    "Parking",
    "Garage",
    "Chantier de construction",
    "Scène de crime",
    "Rue",
    "Allée",
    "Place",
    "Boulevard",
    "Avenue",
    "Route",
    "Autoroute",
    "Carrefour",
    "Rond-point",
    "Passerelle",
    "Souterrain",
    "Parc d'attractions",
    "Fête foraine",
    "Cirque",
    "Studio de cinéma",
    "Studio d'enregistrement",
    "Plateau de télévision",
    "Cabaret",
    "Discothèque",
    "Salon de thé",
    "Maison de retraite",
    "Crèche",
    "Jardin d'enfants",
    "Université",
    "Campus",
    "Amphithéâtre",
    "Auditorium",
    "Gymnase",
    "Vestiaire",
    "Douche",
    "Toilettes publiques",
    "Salle d'attente",
    "Couloir",
    "Escalier",
    "Ascenseur",
    "Sous-sol",
    "Grenier",
    "Toit",
    "Balcon",
    "Terrasse",
    "Patio",
    "Jardin",
    "Cour",
    "Porche",
    "Véranda",
    "Cellier",
    "Buanderie",
    "Cuisine",
    "Salon",
    "Salle à manger",
    "Chambre",
    "Salle de bain",
    "Bureau à domicile",
    "Atelier",
    "Garage automobile",
    "Dépôt-vente",
    "Brocante",
    "Vide-grenier",
    "Puce",
    "Kiosque",
    "Fontaine",
    "Monument",
    "Statue",
    "Obélisque",
    "Arche de triomphe",
    "Colisée",
    "Pyramide",
    "Sphinx",
    "Temple",
    "Église",
    "Cathédrale",
    "Mosquée",
    "Synagogue",
    "Pagode",
    "Stupa",
    "Monastère",
    "Couvent",
    "Ermitage",
    "Sanctuaire",
    "Autel",
    "Crypte",
    "Cimetière",
    "Mausolée",
    "Panthéon",
    "Mémorial",
    "Camp de réfugiés",
    "Frontière",
    "Douane",
    "Poste-frontière",
    "Zone démilitarisée",
    "Zone de guerre",
    "Champ de bataille",
    "Bunker",
    "Abri anti-atomique",
    "Base militaire",
    "Quartier général",
    "Ambassade secrète",
    "Repaire de bandits",
    "Cachette",
    "Refuge",
    "Donjon",
    "Tour",
    "Rempart",
    "Douve",
    "Pont-levis",
    "Cour intérieure",
    "Souterrain secret",
    "Passage dérobé",
    "Salle du trésor",
    "Armurerie",
    "Scriptorium",
    "Salle des cartes",
    "Salon de jeux",
    "Salle de billard",
    "Salle de sport",
    "Sauna",
    "Hammam",
    "Spa",
    "Centre de bien-être",
    "Clinique",
    "Pharmacie",
    "Cabinet médical",
    "Cabinet dentaire",
    "Vétérinaire",
    "Chenil",
    "Refuge animalier",
    "Élevage",
    "Ranch",
    "Écurie",
    "Haras",
    "Paddock",
    "Arène",
    "Hippodrome",
    "Circuit automobile",
    "Piste de course",
    "Piste d'atterrissage",
    "Héliport",
    "Base de lancement",
    "Pas de tir",
    "Champ de tir",
    "Stand de tir",
    "Centre de commandement",
    "Salle de contrôle",
    "Poste de garde",
    "Guérite",
    "Cabine téléphonique",
    "Arrêt de bus",
    "Station de métro",
    "Borne-taxi",
    "Station-service",
    "Lavage auto",
    "Point de recharge électrique",
    "Aire de repos",
    "Aire de pique-nique",
    "Observatoire météorologique",
    "Station sismique",
    "Phare météo",
    "Bouée météorologique",
    "Sonde sous-marine",
    "Satellite",
    "Telescopes (terrestre)",
    "Radiotélescope",
    "Centre de recherche",
    "Laboratoire secret",
    "Base souterraine",
    "Dôme sous-marin",
    "Cité sous-marine",
    "Colonie spatiale",
    "Vaisseau-mère",
    "Champ d'astéroïdes",
    "Nébuleuse",
    "Trou noir",
    "Galaxie",
    "Univers parallèle",
    "Dimension alternative",
    "Rêve",
    "Cauchemar",
    "Illusion",
    "Mirage",
    "Monde virtuel",
    "Simulation",
    "Hologramme",
    "Fantôme",
    "Esprit",
    "Âme",
    "Au-delà",
    "Enfer",
    "Paradis",
    "Purgatoire",
    "Valhalla",
    "Olympes",
    "Asgard",
    "Shambala",
    "Atlantis",
    "El Dorado",
    "Cité perdue",
    "Ruines",
    "Village abandonné",
    "Ville fantôme",
    "Fortin",
    "Relais de poste",
    "Auberge",
    "Relais routier",
    "Gare routière",
    "Terminal",
    "Hangar",
    "Docks",
    "Frigo (chambre froide)",
    "Grenier (pour le grain)",
    "Cave à vin",
    "Brasserie",
    "Distillerie",
    "Fromagerie",
    "Bouchon (restaurant typique)",
    "Guinguette",
    "Paillote",
    "Food truck",
    "Kebab",
    "Pizzeria",
    "Sushi bar",
    "Crêperie",
    "Glacier (magasin)",
    "Chais",
    "Moulin",
    "Scierie",
    "Forge",
    "Fonderie",
    "Tannerie",
    "Filature",
    "Tissage",
    "Imprimerie",
    "Papeterie",
    "Atelier de poterie",
    "Atelier de sculpture",
    "Atelier de peinture",
    "Studio photo",
    "Studio de danse",
    "Salle de répétition",
    "Backstage",
    "Loge",
    "Fosse d'orchestre",
    "Régie",
    "Projecteur",
    "Grille de scène",
    "Plateau (de tournage)",
    "Coulisses",
    "Tapis rouge",
    "Podium",
    "Tribune",
    "Banc des remplaçants",
    "Vestiaires (sportifs)",
    "Anneau de boxe",
    "Cage de MMA",
    "Ring de lutte",
    "Tatami",
    "Piscine olympique",
    "Bassin d'apprentissage",
    "Plongeoir",
    "Toboggan aquatique",
    "Jacuzzi",
    "Bains à remous",
    "Salle de massage",
    "Cabine UV",
    "Salon de manucure",
    "Salon de tatouage",
    "Piercing studio",
    "Bureau de tabac",
    "Presse (magasin)",
    "Loto (point de vente)",
    "Poste (bureau de poste)",
    "Recyclerie",
    "Déchetterie",
    "Usine de traitement des eaux",
    "Centrale d'épuration",
    "Incinérateur",
    "Centre de tri",
    "Site d'enfouissement",
    "Champs éoliens",
    "Panneaux solaires (ferme)",
    "Géothermie (centrale)",
    "Marémotrice (centrale)",
    "Centrale nucléaire",
    "Barrage hydroélectrique",
    "Écluse de Panama",
    "Phare d'Alexandrie (ruines/reconstitution)",
    "Colosse de Rhodes (ruines/reconstitution)",
    "Jardin suspendus de Babylone (ruines/reconstitution)",
    "Mur de Chine",
    "Grande Muraille de Chine",
    "Taj Mahal",
    "Petra",
    "Machu Picchu",
    "Chichen Itza",
    "Stonehenge",
    "Moaï (Île de Pâques)",
    "Acropole d'Athènes",
    "Parthénon",
    "Basilique Saint-Pierre",
    "Chapelle Sixtine",
    "Tour Eiffel",
    "Statue de la Liberté",
    "Big Ben",
    "Opéra de Sydney",
    "Christ Rédempteur",
    "Golden Gate Bridge",
    "Burj Khalifa",
    "Tour de Pise",
    "Cité du Vatican",
    "La Mecque",
    "Jérusalem",
    "Rome antique",
    "Pompéi",
    "Herculanum",
    "Timgad",
    "Volubilis",
    "Leptis Magna",
    "Palmyre",
    "Persepolis",
    "Angkor Wat",
    "Bagan",
    "Borobudur",
    "Lalibela",
    "Dendera",
    "Abou Simbel",
    "Vallée des Rois",
    "Pyramides de Gizeh",
    "Musée du Louvre",
    "British Museum",
    "Metropolitan Museum of Art",
    "Rijksmuseum",
    "Prado",
    "Galerie des Offices",
    "Hermitage",
    "Musée d'Orsay",
    "Centre Pompidou",
    "Guggenheim (Bilbao/New York)",
    "La Joconde (devant la)",
    "Le David (devant la)",
    "La Cène (devant la)",
    "Les Tournesols (devant les)",
    "Le Cri (devant le)",
    "La Nuit étoilée (devant la)",
    "Parc national de Yellowstone",
    "Grand Canyon",
    "Yosemite",
    "Sequoia National Park",
    "Fiordland (Nouvelle-Zélande)",
    "Great Barrier Reef",
    "Amazonie",
    "Sahara",
    "Antarctique",
    "Arctique",
    "Himalaya",
    "Mont Everest",
    "K2",
    "Mont Blanc",
    "Fuji-san",
    "Kilimandjaro",
    "Cratère du Ngorongoro",
    "Serengeti",
    "Okavango",
    "Lac Baïkal",
    "Mer Morte",
    "Nil",
    "Amazone (fleuve)",
    "Danube",
    "Dans une chaussette orpheline géante",
    "Sous le canapé d'un paresseux",
    "Au fond de la poche d'un kangourou distrait",
    "Sur le dos d'une limace de course",
    "Dans le clavier d'un ordinateur ancien",
    "À l'intérieur d'une bulle de savon géante",
    "Derrière le rideau d'une scène vide",
    "Dans un chapeau de magicien sans lapin",
    "Au milieu d'un champ de licornes péteuses",
    "Sous la langue d'un géant endormi",
    "Dans une machine à laver en pleine essorage",
    "Sur le dernier poil d'une moustache de pharaon",
    "À l'intérieur d'un rêve oublié",
    "Dans la valise d'un clown triste",
    "Sur une plume tombée d'un ange maladroit",
    "Au cœur d'un sandwich cosmique",
    "Dans la tirelire d'un écureuil radin",
    "Sous le menton d'une gargouille rieuse",
    "Entre deux pages d'un livre jamais lu",
    "Sur la dernière miette d'un gâteau maudit",
    "Dans l'oreille d'un détective privé sourd",
    "Au milieu d'une danse de chaussettes sales",
    "Sous un parapluie troué un jour de déluge",
    "Dans le sillage d'un bateau fantôme",
    "Sur le bouton 'mute' de l'univers",
    "À l'intérieur d'un flocon de neige unique",
    "Dans l'œil d'une aiguille cosmique",
    "Au fond d'un tiroir à secrets qui grince",
    "Sur le pétale d'une fleur carnivore végétarienne",
    "Dans la mémoire tampon d'un robot nostalgique",
    "Sous la table d'une conférence de chaussettes",
    "Au pays des objets perdus et retrouvés",
    "Dans un nuage de pensées confuses",
    "Sur une étoile filante en panne d'essence",
    "À l'intérieur d'une blague pas drôle",
    "Dans la corne d'un narval mélomane",
    "Sous le coussin d'un sofa qui respire",
    "Au fond d'une tasse de café oubliée",
    "Dans le trou d'une chaussette porte-bonheur",
    "Sur l'ombre d'un caméléon invisible",
    "À l'intérieur d'un chuchotement lointain",
    "Dans les coulisses d'un spectacle de marionnettes récalcitrantes",
    "Sous le chapeau d'un gnome jardinier pressé",
    "Au milieu d'une conversation de perroquets philosophes",
    "Sur le fil d'un rasoir affûté par l'ennui",
    "Dans un sablier dont le temps est inversé",
    "Au cœur d'une énigme sans réponse",
    "Sous une perruque de juge chauve",
    "Dans la poche d'un pantalon qui rétrécit",
    "Sur un trampoline de gelée géante",
    "À l'intérieur d'une mélodie qui n'a pas de fin",
    "Dans le sac à main d'une fée excentrique",
    "Sous l'escalier qui ne mène nulle part",
    "Au fond d'un puits à souhaits mal compris",
    "Sur la page blanche d'un écrivain en panne",
    "Dans le frigo d'un vampire végétalien",
    "À l'intérieur d'une capsule temporelle ouverte",
    "Sous les sourcils d'un savant fou qui rit",
    "Dans le labyrinthe d'une miette de pain",
    "Sur la pointe d'un iceberg flottant dans le thé",
    "Au cœur d'un trou de serrure qui observe",
    "Dans le sifflement du vent entre les dents d'un squelette",
    "Sous une statue de jardin qui cligne des yeux",
    "Au fond d'une boîte de Pandore vide",
    "Sur le papier peint d'une chambre hantée par l'ennui",
    "Dans les poils d'un mammouth laineux allergique",
    "À l'intérieur d'un miroir qui ne reflète rien",
    "Sous le clavier d'un piano qui joue tout seul",
    "Dans le ventre d'une horloge qui ronfle",
    "Sur un nuage en forme de mouton râleur",
    "Au cœur d'une tempête de confettis cosmiques",
    "Dans le tiroir secret d'une commode bavarde",
    "Sous l'écorce d'un arbre qui raconte des blagues",
    "Au fond d'une théière remplie d'idées folles",
    "Sur les lunettes d'un hibou qui a perdu son livre",
    "Dans le pansement d'un robot blessé",
    "À l'intérieur d'une boussole qui indique le passé",
    "Sous la gomme d'un crayon magicien",
    "Dans le souffle d'un dragon enrhumé",
    "Sur un tapis volant pris dans les embouteillages",
    "Au cœur d'une forêt de champignons lumineux",
    "Dans la moustache d'un chef cuisinier invisible",
    "Sous le trottoir d'une ville sans nom",
    "Au fond d'une machine à remonter le temps rouillée",
    "Sur la queue d'un cerf-volant rebelle",
    "Dans la bulle de pensée d'un escargot pressé",
    "À l'intérieur d'une chaussette de Noël en juillet",
    "Sous le collier d'un chien qui parle latin",
    "Dans le jardin d'un sculpteur de nuages",
    "Sur un fil à linge tendu entre deux étoiles",
    "Au cœur d'un labyrinthe de spaghettis",
    "Dans les pages d'un grimoire de recettes oubliées",
    "Sous le couvercle d'une boîte à musique cassée",
    "Au fond d'un tiroir à jouets qui s'ennuient",
    "Sur l'oreiller d'un fantôme insomniaque",
    "Dans les plis d'une carte au trésor illisible",
    "À l'intérieur d'une boule de cristal brouillée",
    "Sous le chapeau d'un nain de jardin fugueur",
    "Dans le souffle d'un sifflet sans trou",
    "Sur la dernière goutte d'une potion magique périmée",
    "Au cœur d'une tempête de neige artificielle",
    "Dans les serres d'un griffon distrait",
    "Sous le pont d'un navire sans gouvernail",
    "Au fond d'une piscine remplie de gelée",
    "Sur la feuille d'automne d'un arbre qui pleure",
    "Dans le panthéon des dieux oubliés de la vaisselle",
    "À l'intérieur d'un dé à coudre géant",
    "Sous le nez d'un sphinx qui a le hoquet",
    "Dans le journal intime d'un chat philosophe",
    "Sur le bord d'un trou noir qui bâille",
    "Au cœur d'un champignon atomique",
    "Dans le nid d'un oiseau qui chante faux",
    "Sous la tapisserie d'un château hanté par la poussière",
    "Au fond d'un tiroir à souvenirs effacés",
    "Sur la balançoire d'un parc désert",
    "Dans le ventre d'un doudou qui ronfle",
    "À l'intérieur d'une bulle de rêve volée",
    "Sous l'oreiller d'un géant qui fait des cauchemars",
    "Dans le sable d'une plage sans mer",
    "Sur le poil d'une chenille transformée en papillon rockeur",
    "Au cœur d'un trou de lapin qui danse",
    "Dans les archives d'un bureau des objets trouvés du futur",
    "Sous la coiffe d'une sirène qui fait du stand-up",
    "Au fond d'un égout parfumé",
    "Sur la corne d'un rhinocéros qui patine",
    "Dans le nuage de vapeur d'une machine à café cosmique",
    "À l'intérieur d'un pot de miel intelligent",
    "Sous le bec d'un perroquet qui récite des poèmes",
    "Dans la manche d'une veste invisible",
    "Sur le nez d'un clown qui ne rit jamais",
    "Au cœur d'un rayon de soleil qui a froid",
    "Dans l'estomac d'une baleine qui aime les sushis",
    "Sous le chapeau melon d'un gentleman démoniaque",
    "Au fond d'un bar à milkshakes intergalactique",
    "Sur le miroir d'une voiture qui roule à reculons",
    "Dans les cheveux d'une sorcière en pleine coiffure",
    "À l'intérieur d'une cacahuète parlante",
    "Sous la feuille de salade d'un sandwich végétal",
    "Dans le grenier des peurs enfantines",
    "Sur le rayon d'une roue de bicyclette volante",
    "Au cœur d'une tempête de plumes",
    "Dans la poche d'un pantalon qui est toujours propre",
    "Sous la neige d'un pays chaud",
    "Au fond d'un verre d'eau qui est toujours à moitié plein",
    "Sur la langue d'un serpent qui parle toutes les langues",
    "Dans les étoiles d'un ciel sans lune",
    "À l'intérieur d'un œuf de dragon qui n'éclot pas",
    "Sous l'aile d'une chauve-souris qui a peur du noir",
    "Dans le ventre d'une montagne qui chante",
    "Sur le fil d'un rasoir électrique à poils longs",
    "Au cœur d'une forêt de cactus parlants",
    "Dans la barbe d'un Père Noël en vacances",
    "Sous la jupe d'une danseuse de claquettes géante",
    "Au fond d'une bouteille à la mer qui contient un message du futur",
    "Sur le nez d'un chien qui sent la tarte aux pommes",
    "Dans la mémoire d'un poisson rouge amnésique",
    "À l'intérieur d'une coquille d'escargot qui vibre",
    "Sous le pied d'un troll qui ne paie pas ses impôts",
    "Dans le chapeau d'un magicien qui a perdu sa baguette",
    "Sur la lèvre d'un volcan endormi mais bavard",
    "Au cœur d'un flan qui tremble de peur",
    "Dans les rêves d'une plante carnivore",
    "Sous la terre d'un jardin hanté par les carottes",
    "Au fond d'un sac à dos d'aventurier débutant",
    "Sur le dos d'une tortue qui fait la course",
    "Dans la poche d'un pantalon à carreaux qui s'agite",
    "À l'intérieur d'une machine à café qui prépare du thé",
    "Sous le casque d'un chevalier qui a peur des souris",
    "Dans le tiroir à chaussettes d'un homme politique honnête",
    "Sur l'écume d'une vague qui chuchote des secrets",
    "Au cœur d'une fontaine à chocolat qui ne coule jamais",
    "Dans la barbe d'un lutin grincheux",
    "Sous l'ongle d'un géant manucuré",
    "Au fond d'un bocal à poissons rouges avec un réseau wifi",
    "Sur la dernière goutte d'une bière de licorne",
    "Dans l'œil d'un cyclone en pleine sieste",
    "À l'intérieur d'une machine à remonter le temps qui avance",
    "Sous la couronne d'un roi qui a peur du noir",
    "Dans le ventre d'un nuage en forme d'éléphant rose",
    "Sur le filament d'une ampoule qui a une idée brillante",
    "Au cœur d'une tempête de pétales de rose en acier",
    "Dans la poche d'un gilet pare-balles en gaufre",
    "Sous le lit d'un monstre qui lit des histoires pour enfants",
    "Au fond d'une boîte de céréales avec un prix Nobel",
    "Sur la dent d'un vampire qui a un régime végétalien",
    "Dans l'esprit d'un robot qui rêve de moutons électriques",
    "À l'intérieur d'un pot de fleurs qui chante de l'opéra",
    "Sous le chapeau d'un détective qui enquête sur sa propre disparition",
    "Dans le souffle d'un dragon qui crache des bulles de savon",
    "Sur le rebord d'une tasse de café qui contient l'univers",
    "Au cœur d'un labyrinthe de confitures",
    "Dans les plumes d'un dodo qui a appris à voler",
    "Sous la langue d'un caméléon qui perd ses couleurs",
    "Au fond d'un puits de lumière sans fond",
    "Sur la dernière feuille d'un calendrier perpétuel",
    "Dans le ventre d'une chaussette porte-bonheur qui a faim",
    "À l'intérieur d'un nuage de coton candy cosmique",
    "Sous l'ombre d'un arbre qui bouge",
    "Dans le rire d'un enfant qui n'a jamais grandi",
    "Sur le point final d'une histoire infinie"
];


// ----- RÉCUPÉRATION DES JOUEURS -----
const listJoueurs = JSON.parse(localStorage.getItem('joueurs')) || [];
const nbJoueurs = listJoueurs.length;
let joueursMots = []; // contiendra les mots attribués à chaque joueur

// ----- DISTRIBUTION DES MOTS -----
function distribuerMots() {
    // Choisir un lieu au hasard
    const lieuChoisi = lieux[Math.floor(Math.random() * lieux.length)];

    // Crée un tableau rempli avec le lieu choisi
    joueursMots = Array(nbJoueurs).fill(lieuChoisi);

    // Sélectionne un espion (ou deux si beaucoup de joueurs)
    const nbEspions = nbJoueurs <= 7 ? 1 : 2;
    const indicesEspions = [...Array(nbJoueurs).keys()]
        .sort(() => Math.random() - 0.5)
        .slice(0, nbEspions);

    // L'espion reçoit uniquement le mot "Espion"
    indicesEspions.forEach(i => {
        joueursMots[i] = motEspion;
    });

    // Sauvegarde les données
    localStorage.setItem("lieuChoisi", lieuChoisi);
    localStorage.setItem("joueurs", JSON.stringify(listJoueurs));
    localStorage.setItem("joueursMots", JSON.stringify(joueursMots));

    console.log("Lieu choisi :", lieuChoisi);
    console.log("Distribution des mots :", joueursMots);
}

// ----- AFFICHAGE DES MOTS AUX JOUEURS -----
let current = 0;
const joueurDiv = document.getElementById("joueur");
const motDiv = document.getElementById("mot");
const btnVoir = document.getElementById("voirMot");
const btnSuivant = document.getElementById("suivant");

function afficherJoueur() {
    joueurDiv.textContent = listJoueurs[current] || "Joueur inconnu";
    motDiv.textContent = "";
    btnVoir.style.display = "inline-block";
    btnSuivant.style.display = "none";
}

btnVoir.addEventListener("click", () => {
    const mot = joueursMots[current];
    motDiv.textContent = mot === motEspion
        ? "Vous êtes l'espion !"
        : `Le mot est : ${mot}`;
    btnVoir.style.display = "none";
    btnSuivant.style.display = "inline-block";
});

btnSuivant.addEventListener("click", () => {
    current++;
    if (current < nbJoueurs) {
        afficherJoueur();
    } else {
        joueurDiv.textContent = "Tous les joueurs ont vu leur mot.";
        motDiv.textContent = "";
        btnVoir.style.display = "none";
        btnSuivant.style.display = "none";
        startChrono();
    }
});

// ----- CHRONOMÈTRE -----
let tempsRestant = 90; // 3 minutes = 180 secondes
let timerInterval;
const chronoDiv = document.getElementById("chrono");

function startChrono() {
    clearInterval(timerInterval);

    timerInterval = setInterval(() => {
        const minutes = Math.floor(tempsRestant / 60);
        const secondes = tempsRestant % 60;
        chronoDiv.textContent = `${minutes}:${secondes < 10 ? "0" : ""}${secondes}`;

        if (tempsRestant <= 0) {
            clearInterval(timerInterval);
            chronoDiv.textContent = "Temps écoulé !";
            window.location.assign('spy3.html');
        }

        tempsRestant--;
    }, 1000);

}


// ----- LANCEMENT DU JEU -----
distribuerMots();
afficherJoueur();
