const propositionsNormal = [
"Classe les 8 pires animaux de compagnie",
"Classe les 6 super-pouvoirs les plus utiles",
"Classe tes boissons préférées",
"Classe les animaux les plus mignons",
"Classe les 7 instruments de musique les plus utiles",
"Classe tes odeurs préférés",
"Classe ce qui est le pire : manger épicé / sucré / salé / amer",
"Classe les films d'horreur du plus effrayant au moins",
"Classe les 7 meilleurs excuses bidon",
"Classe les memes du plus mignon au moins mignon",
"Classe les chansons pour une playlist chill",
"Classe les 3 pires fêtes",
"Classe tes citations motivantes préférés",
"Classe les 6 couleurs les plus utiles",
"Classe les 6 légumes les plus romantique",
"Classe ces odeurs par ordre de préférence",
"Classe les 4 émotions les plus utiles",
"Classe du plus drôle au moins plus drôle : être en retard / oublier un prénom / dire 'toi aussi' quand on te souhaite bon appétit",
"Classe tes villes à visiter préférés",
"Classe les 7 légumes les plus utiles",
"Classe les destinations de voyage idéales",
"Classe les 3 sons relaxants les plus utiles",
"Classe les 5 fêtes les plus utiles",
"Classe les 6 villes à visiter les plus utile",
"Classe les 3 snacks les plus relaxant",
"Classe les 3 légumes les plus utiles",
"Classe ces langues à apprendre par ordre de préférence",
"Classe du plus cool au moins plus cool : perdre son téléphone / oublier son anniversaire / rater un examen",
"Classe ces chanteurs par ordre de préférence",
"Classe tes pizzas toppings préférés",
"Classe du pire au moins pire : pleurer en public / roter fort / trébucher devant tout le monde",
"Classe les 3 chanteurs les plus cool",
"Classe les 3 meilleurs jeux vidéo",
"Classe les 6 meilleurs animaux de compagnie",
"Classe les 5 films les plus utiles",
"Classe les 8 auteurs préférés les plus mignon",
"Classe les super-héros les plus puissants",
"Classe les villes à visiter du plus relaxant au moins relaxant",
"Classe les 5 fruits les plus romantique",
"Classe les langues à apprendre du plus utile au moins utile",
"Classe les 6 chaînes YouTube les plus cool",
"Classe les 8 meilleurs émotions",
"Classe les 5 pires desserts",
"Classe les 6 livres les plus relaxant",
"Classe les 3 meilleurs fêtes",
"Classe du plus utile au moins plus utile : pleurer en public / roter fort / trébucher devant tout le monde",
"Classe du plus drôle au moins plus drôle : manger épicé / sucré / salé / amer",
"Classe les 4 meilleurs émotions",
"Classe tes phobies préférés",
"Classe les 10 pires memes",
"Classe les 8 meilleurs sons relaxants",
"Classe les villes à visiter du plus utile au moins utile",
"Classe ces saisons par ordre de préférence",
"Classe les 7 animaux de compagnie les plus romantique",
"Classe les 6 pires habitudes du matin",
"Classe les 5 saisons les plus romantique",
"Classe les 5 pires films",
"Classe les 6 pires jeux vidéo",
"Classe du pire au moins pire : manger épicé / sucré / salé / amer",
"Classe ce qui est le pire : être en retard / oublier un prénom / dire 'toi aussi' quand on te souhaite bon appétit",
"Classe les 3 auteurs préférés les plus drôle",
"Classe les 6 pires auteurs préférés",
"Classe les 4 couleurs les plus cool",
"Classe les séries Netflix du plus utile au moins utile",
"Classe les 8 films les plus utiles",
"Classe les 4 pires sports",
"Classe les 5 pires super-pouvoirs",
"Classe ce qui est le pire : pleurer en public / roter fort / trébucher devant tout le monde",
"Classe ce qui est le pire : perdre son téléphone / oublier son anniversaire / rater un examen",
"Classe tes playlists Spotify préférés",
"Classe les 10 pires pizzas toppings",
"Classe les 10 auteurs préférés les plus romantique",
"Classe les super-pouvoirs du plus relaxant au moins relaxant",
"Classe les 4 meilleurs applis",
"Classe du meilleur au moins meilleur : être en retard / oublier un prénom / dire 'toi aussi' quand on te souhaite bon appétit",
"Classe les 10 pires odeurs",
"Classe du plus drôle au moins plus drôle : pleurer en public / roter fort / trébucher devant tout le monde",
"Classe ces émotions par ordre de préférence",
"Classe les citations motivantes du plus relaxant au moins relaxant",
"Classe les 3 meilleurs sons relaxants",
"Classe du plus utile au moins plus utile : être en retard / oublier un prénom / dire 'toi aussi' quand on te souhaite bon appétit",
"Classe tes fêtes préférés",
"Classe du pire au moins pire : être en retard / oublier un prénom / dire 'toi aussi' quand on te souhaite bon appétit",
"Classe les 8 auteurs préférés les plus cool",
"Classe les playlists Spotify du plus mignon au moins mignon",
"Classe tes auteurs préférés préférés",
"Classe les films du plus mignon au moins mignon",
"Classe les 6 meilleurs applis",
"Classe les 6 super-pouvoirs les plus romantique",
"Classe les 3 sports les plus délicieux",
"Classe du plus cool au moins plus cool : manger épicé / sucré / salé / amer",
"Classe les 8 pires pizzas toppings",
"Classe les 7 pires livres",
"Classe les instruments de musique du plus drôle au moins drôle",
"Classe les 10 applis les plus utile",
"Classe les citations motivantes du plus délicieux au moins délicieux",
"Classe les 8 sons relaxants les plus utiles",
"Classe du plus utile au moins plus utile : manger épicé / sucré / salé / amer",
"Classe les 10 meilleurs genres musicaux",
"Classe les villes à visiter du plus effrayant au moins effrayant",
"Classe les 7 genres musicaux les plus utile",
"Classe tes genres musicaux préférés",
"Classe les 3 sports les plus cool",
"Classe les 4 pires excuses bidon",
"Classe les 5 memes les plus utiles",
"Classe les 7 langues à apprendre les plus effrayant",
"Classe tes sons relaxants préférés",
"Classe tes animaux de compagnie préférés",
"Classe les 6 odeurs les plus mignon",
"Classe les 5 pires genres musicaux",
"Classe tes excuses bidon préférés",
"Classe ces boissons chaudes par ordre de préférence",
"Classe les 3 pires chanteurs",
"Classe ces excuses bidon par ordre de préférence",
"Classe ces desserts par ordre de préférence",
"Classe ces chaînes YouTube par ordre de préférence",
"Classe les 5 pizzas toppings les plus relaxant",
"Classe ces couleurs par ordre de préférence",
"Classe les 5 pires sons relaxants",
"Classe ces jeux vidéo par ordre de préférence",
"Classe les 4 séries Netflix les plus utiles",
"Classe ces super-pouvoirs par ordre de préférence",
"Classe du plus utile au moins plus utile : perdre son téléphone / oublier son anniversaire / rater un examen",
"Classe les 3 memes les plus utiles",
"Classe les fruits du plus relaxant au moins relaxant",
"Classe les 8 meilleurs livres",
"Classe ces habitudes du matin par ordre de préférence",
"Classe les 5 meilleurs snacks",
"Classe tes memes préférés",
"Classe les 7 boissons chaudes les plus utiles",
"Classe ces films par ordre de préférence",
"Classe les 10 pires légumes",
"Classe les 6 pires langues à apprendre",
"Classe les 4 pires films",
"Classe les 7 pires playlists Spotify",
"Classe les 3 memes les plus utile",
"Classe les 8 memes les plus utile",
"Classe ces fêtes par ordre de préférence",
"Classe les 3 sports les plus utiles",
"Classe les 5 meilleurs chanteurs",
"Classe les 10 pires citations motivantes",
"Classe les 7 sports les plus délicieux",
"Classe les 5 meilleurs super-pouvoirs",
"Classe les 3 meilleurs fruits",
"Classe les 5 pires chaînes YouTube",
"Classe les 3 genres musicaux les plus utiles",
"Classe les 5 meilleurs saisons",
"Classe ces villes à visiter par ordre de préférence",
"Classe les 7 meilleurs langues à apprendre",
"Classe les habitudes du matin du plus relaxant au moins relaxant",
"Classe ces fruits par ordre de préférence",
"Classe les 3 meilleurs citations motivantes",
"Classe les 6 meilleurs super-pouvoirs",
"Classe les 3 pizzas toppings les plus utiles",
"Classe les 10 émotions les plus utiles",
"Classe les 7 pires chanteurs",
"Classe les 7 citations motivantes les plus cool",
"Classe tes desserts préférés",
"Classe ces livres par ordre de préférence",
"Classe les habitudes du matin du plus délicieux au moins délicieux",
"Classe les 5 livres les plus utiles",
"Classe les 7 sons relaxants les plus utiles",
"Classe les 3 meilleurs memes",
"Classe les 5 boissons chaudes les plus utiles",
"Classe les 5 pires langues à apprendre",
"Classe les 10 langues à apprendre les plus utiles",
"Classe les légumes du plus délicieux au moins délicieux",
"Classe les 7 memes les plus relaxant",
"Classe les memes du plus cool au moins cool",
"Classe les 8 meilleurs boissons chaudes",
"Classe du meilleur au moins meilleur : perdre son téléphone / oublier son anniversaire / rater un examen",
"Classe les 5 meilleurs desserts",
"Classe les snacks du plus effrayant au moins effrayant",
"Classe les pizzas toppings du plus cool au moins cool",
"Classe tes saisons préférés",
"Classe les 8 pires séries Netflix",
"Classe du plus drôle au moins plus drôle : perdre son téléphone / oublier son anniversaire / rater un examen",
"Classe les saisons du plus cool au moins cool",
"Classe les fruits du plus utile au moins utile",
"Classe du plus cool au moins plus cool : pleurer en public / roter fort / trébucher devant tout le monde",
"Classe les applis du plus mignon au moins mignon",
"Classe les sports du plus mignon au moins mignon",
"Classe les 10 meilleurs citations motivantes",
"Classe tes langues à apprendre préférés",
"Classe les saisons du plus mignon au moins mignon",
"Classe les 4 memes les plus utiles",
"Classe les odeurs du plus drôle au moins drôle",
"Classe tes snacks préférés",
"Classe les 8 pires playlists Spotify",
"Classe les 3 citations motivantes les plus romantique",
"Classe les 4 séries Netflix les plus drôle",
"Classe les 6 excuses bidon les plus mignon",
"Classe tes sports préférés",
"Classe les 7 films les plus utiles",
"Classe les 6 fêtes les plus utiles",
"Classe les excuses bidon du plus mignon au moins mignon",
"Classe les 4 habitudes du matin les plus effrayant",
"Classe les 4 pires légumes",
"Classe ces phobies par ordre de préférence",
"Classe tes séries Netflix préférés"];

const propositionsHot = [
"Classe les zones érogènes du plus sensible au moins",
"Classe les tenues les plus provocantes",
"Classe les 3 positions sexuelles les plus excitant",
"Classe les messages coquins du plus soft au plus direct",
"Classe les jouets adultes préférés",
"Classe les 10 fantasmes les plus excitants",
"Classe du plus excitant au moins : mordre trop fort / griffer / laisser des marques",
"Classe les 8 meilleurs zones du corps pour pimenter",
"Classe les 7 meilleurs goûts pour pimenter",
"Classe les 6 trucs les plus hot à faire à deux",
"Classe du plus plaisant au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les compliments les plus chauds",
"Classe les 7 trucs les plus hot à faire à deux",
"Classe les 3 parties du corps les plus excitants",
"Classe tes accessoires BDSM préférés au lit",
"Classe les 8 meilleurs tenues lingerie pour pimenter",
"Classe les 8 phrases à dire au lit les plus excitants",
"Classe les 8 meilleurs fétishes pour pimenter",
"Classe les 8 positions sexuelles les plus kinky",
"Classe les 3 jouets les plus excitants",
"Classe du plus excitant au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 10 meilleurs techniques orales pour pimenter",
"Classe tes fantasmes préférés au lit",
"Classe ce qui est le pire au lit : parler sale / rester silencieux / gémir trop fort",
"Classe les textures les plus sexy",
"Classe les 6 positions sexuelles les plus excitant",
"Classe ce qui est le pire au lit : mordre trop fort / griffer / laisser des marques",
"Classe les 4 positions sexuelles les plus chaud",
"Classe tes fantasmes préférés",
"Classe tes techniques orales préférés au lit",
"Classe ce qui est le pire au lit : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe tes positions préférés au lit",
"Classe les scénarios roleplay les plus excitants",
"Classe tes préliminaires préférés au lit",
"Classe du plus sensuel au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 5 zones du corps les plus excitants",
"Classe les 3 trucs les plus hot à faire à deux",
"Classe les 5 trucs les plus hot à faire à deux",
"Classe du plus kinky au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 5 positions sexuelles les plus tabou",
"Classe les 5 roleplays les plus excitants",
"Classe du plus sensuel au moins : mordre trop fort / griffer / laisser des marques",
"Classe les odeurs corporelles les plus sexy",
"Classe les 3 meilleurs fantasmes pour pimenter",
"Classe tes scénarios préférés au lit",
"Classe les fétishes les plus sexy",
"Classe les 4 trucs les plus hot à faire à deux",
"Classe les 7 meilleurs techniques orales pour pimenter",
"Classe les 7 goûts les plus excitants",
"Classe les 6 fantasmes les plus excitants",
"Classe tes parties du corps préférés au lit",
"Classe les 5 meilleurs textures pour pimenter",
"Classe les 6 meilleurs zones du corps pour pimenter",
"Classe les 8 trucs les plus hot à faire à deux",
"Classe tes zones du corps préférés au lit",
"Classe les 7 tenues lingerie les plus excitants",
"Classe les roleplays les plus sexy",
"Classe les parties du corps les plus sexy",
"Classe les 7 positions sexuelles les plus plaisant",
"Classe du plus excitant au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 10 trucs les plus hot à faire à deux",
"Classe du plus chaud au moins : mordre trop fort / griffer / laisser des marques",
"Classe les 5 positions sexuelles les plus chaud",
"Classe les 8 positions sexuelles les plus orgasmique",
"Classe les sons pendant l'acte les plus sexy",
"Classe du plus orgasmique au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 10 positions sexuelles les plus tabou",
"Classe les tenues lingerie les plus sexy",
"Classe les 3 meilleurs préliminaires pour pimenter",
"Classe tes phrases à dire au lit préférés au lit",
"Classe les positions les plus sexy",
"Classe les 4 positions sexuelles les plus sensuel",
"Classe les 5 positions sexuelles les plus plaisant",
"Classe les 4 meilleurs jouets pour pimenter",
"Classe les 10 meilleurs jouets pour pimenter",
"Classe tes fétishes préférés au lit",
"Classe les 3 positions sexuelles les plus sensuel",
"Classe les 8 positions sexuelles les plus tabou",
"Classe du plus chaud au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 4 meilleurs goûts pour pimenter",
"Classe les 8 fantasmes les plus excitants",
"Classe les 7 messages coquins les plus excitants",
"Classe les 8 préliminaires les plus excitants",
"Classe les 8 zones du corps les plus excitants",
"Classe les 3 positions sexuelles les plus intense",
"Classe les 5 positions sexuelles les plus sensuel",
"Classe les 5 jouets les plus excitants",
"Classe les techniques orales les plus sexy",
"Classe les 6 positions sexuelles les plus intense",
"Classe du plus kinky au moins : mordre trop fort / griffer / laisser des marques",
"Classe tes sons pendant l'acte préférés au lit",
"Classe les 3 positions sexuelles les plus tabou",
"Classe les 8 meilleurs phrases à dire au lit pour pimenter",
"Classe tes messages coquins préférés au lit",
"Classe les phrases à dire au lit les plus sexy",
"Classe du plus plaisant au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 8 messages coquins les plus excitants",
"Classe les 8 meilleurs textures pour pimenter",
"Classe les 4 positions sexuelles les plus tabou",
"Classe les 6 positions sexuelles les plus orgasmique",
"Classe les 7 fétishes les plus excitants",
"Classe les 10 meilleurs textures pour pimenter",
"Classe les 5 parties du corps les plus excitants",
"Classe les 3 meilleurs messages coquins pour pimenter",
"Classe les 3 accessoires BDSM les plus excitants",
"Classe les 7 positions sexuelles les plus excitant",
"Classe les 8 positions sexuelles les plus chaud",
"Classe les 5 meilleurs odeurs corporelles pour pimenter",
"Classe tes odeurs corporelles préférés au lit",
"Classe les préliminaires les plus sexy",
"Classe les 7 positions sexuelles les plus chaud",
"Classe les 3 meilleurs roleplays pour pimenter",
"Classe les 4 odeurs corporelles les plus excitants",
"Classe les 5 meilleurs parties du corps pour pimenter",
"Classe du plus plaisant au moins : mordre trop fort / griffer / laisser des marques",
"Classe les 5 préliminaires les plus excitants",
"Classe les 3 meilleurs accessoires BDSM pour pimenter",
"Classe les 5 positions les plus excitants",
"Classe les 10 positions sexuelles les plus chaud",
"Classe les 10 positions sexuelles les plus plaisant",
"Classe les fantasmes les plus sexy",
"Classe les 6 meilleurs roleplays pour pimenter",
"Classe les 8 positions sexuelles les plus sensuel",
"Classe les 7 meilleurs roleplays pour pimenter",
"Classe les 5 meilleurs zones du corps pour pimenter",
"Classe les 3 meilleurs fétishes pour pimenter",
"Classe les 10 meilleurs tenues lingerie pour pimenter",
"Classe les 10 odeurs corporelles les plus excitants",
"Classe les 4 positions sexuelles les plus intense",
"Classe les 3 positions sexuelles les plus chaud",
"Classe les 8 sons pendant l'acte les plus excitants",
"Classe les 5 meilleurs roleplays pour pimenter",
"Classe du plus sensuel au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 8 meilleurs scénarios pour pimenter",
"Classe les 3 scénarios les plus excitants",
"Classe les goûts les plus sexy",
"Classe les 5 positions sexuelles les plus intense",
"Classe les 7 positions sexuelles les plus intense",
"Classe les 3 fétishes les plus excitants",
"Classe les 5 meilleurs préliminaires pour pimenter",
"Classe les accessoires BDSM les plus sexy",
"Classe tes tenues lingerie préférés au lit",
"Classe les 10 meilleurs phrases à dire au lit pour pimenter",
"Classe les 6 meilleurs techniques orales pour pimenter",
"Classe les 3 meilleurs positions pour pimenter",
"Classe les messages coquins les plus sexy",
"Classe les 7 meilleurs zones du corps pour pimenter",
"Classe les 6 textures les plus excitants",
"Classe les 8 accessoires BDSM les plus excitants",
"Classe les 4 positions les plus excitants",
"Classe les 6 meilleurs préliminaires pour pimenter",
"Classe les 5 positions sexuelles les plus kinky",
"Classe les 8 positions sexuelles les plus excitant",
"Classe les 3 zones du corps les plus excitants",
"Classe du plus kinky au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 4 roleplays les plus excitants",
"Classe du plus tabou au moins : mordre trop fort / griffer / laisser des marques",
"Classe les 5 meilleurs messages coquins pour pimenter",
"Classe les zones du corps les plus sexy",
"Classe du plus tabou au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 7 jouets les plus excitants",
"Classe les 10 meilleurs accessoires BDSM pour pimenter",
"Classe les 5 meilleurs accessoires BDSM pour pimenter",
"Classe les scénarios les plus sexy",
"Classe les 8 roleplays les plus excitants",
"Classe les 4 fétishes les plus excitants",
"Classe les 5 meilleurs fantasmes pour pimenter",
"Classe les jouets les plus sexy",
"Classe les 6 positions sexuelles les plus chaud",
"Classe les 5 odeurs corporelles les plus excitants",
"Classe les 5 meilleurs phrases à dire au lit pour pimenter",
"Classe du plus orgasmique au moins : mordre trop fort / griffer / laisser des marques",
"Classe tes textures préférés au lit",
"Classe du plus intense au moins : être trop bruyant / finir trop vite / ne pas finir du tout",
"Classe les 10 positions sexuelles les plus kinky",
"Classe les 4 textures les plus excitants",
"Classe les 5 sons pendant l'acte les plus excitants",
"Classe les 4 positions sexuelles les plus excitant",
"Classe les 5 positions sexuelles les plus orgasmique",
"Classe les 5 tenues lingerie les plus excitants",
"Classe les 4 meilleurs préliminaires pour pimenter",
"Classe les 10 meilleurs fantasmes pour pimenter",
"Classe les 7 meilleurs parties du corps pour pimenter",
"Classe les 4 sons pendant l'acte les plus excitants",
"Classe les 8 meilleurs fantasmes pour pimenter",
"Classe du plus intense au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 10 meilleurs zones du corps pour pimenter",
"Classe les 8 meilleurs positions pour pimenter",
"Classe les 3 positions sexuelles les plus orgasmique",
"Classe les 3 meilleurs scénarios pour pimenter",
"Classe les 4 techniques orales les plus excitants",
"Classe du plus orgasmique au moins : parler sale / rester silencieux / gémir trop fort",
"Classe les 4 meilleurs accessoires BDSM pour pimenter",
"Classe les 8 parties du corps les plus excitants",
"Classe du plus intense au moins : mordre trop fort / griffer / laisser des marques",
"Classe les 6 meilleurs scénarios pour pimenter",
"Classe les 8 meilleurs sons pendant l'acte pour pimenter",
"Classe les 6 techniques orales les plus excitants",
"Classe les 7 meilleurs phrases à dire au lit pour pimenter",
"Classe les 4 meilleurs techniques orales pour pimenter"];